### ISSUE TITLE
awx backup with external postgres possibility 

### ISSUE THREAD

**Issue by JSGUYOT** [ansible/tower-operator#1000]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hello, 

I need use an internal postgres image with awx backup (i have not web connexion ...)
Actually, they are no possibility to put internal image (image from internal registry) on awx-backup configuration.

my actual solution is to tag internal image with external name, but is not clean ...

thank's in advance :)

Regards,

**Comment by kurokobo** [comment]
Have you tried specifying `postgres_image` and `postgres_image_version` in the spec for your AWXBackup resources?
It's not documented in the README.md for backup and restore roles, but works for me.

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  ...
spec:
  deployment_name: awx
  ...
  postgres_image: registry.example.com/postgres     👈👈👈
  postgres_image_version: "12.11.0"     👈👈👈
```

**Comment by JSGUYOT** [comment]
Hello, 

It's not work for me : 

```yaml
apiVersion: awx.ansible.com/v1beta1                                            
kind: AWXRestore                                                               
metadata:                                                                      
  name: restore-awx                                                            
  namespace: awx                                                               
spec:                                                                          
  deployment_name: awx                                                         
  backup_pvc: awx-backup-claim                                                 
  backup_pvc_namespace: awx                                                    
  backup_dir: '/data/awx/backup/tower-openshift-backup-2022-07-28-06:50:09'    
  postgres_image: xxxxxxx/awx/library/postgres                        
  postgres_image_version: "14.4"     
```                                          
                                                             
Result of restore 

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  39s                default-scheduler  Successfully assigned awx/restore-awx-db-management to dal-b-025409
  Normal   Pulling    24s (x2 over 39s)  kubelet            Pulling image "postgres:12"
  Warning  Failed     24s (x2 over 39s)  kubelet            Failed to pull image "postgres:12": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/postgres:12": failed to resolve reference "docker.io/library/postgres:12": failed to do request: Head "https://registry-1.docker.io/v2/library/postgres/manifests/12": dial tcp: lookup registry-1.docker.io on 195.200.1.4:53: no such host
  Warning  Failed     24s (x2 over 39s)  kubelet            Error: ErrImagePull
  Normal   BackOff    9s (x2 over 38s)   kubelet            Back-off pulling image "postgres:12"
  Warning  Failed     9s (x2 over 38s)   kubelet            Error: ImagePullBackOff
```


It's OK for awx deployment, but not for backup ... 

Regards,

**Comment by kurokobo** [comment]
Hmm, what version of operator are you using?

**Comment by JSGUYOT** [comment]
Hello @kurokobo, 

It's finally OK, the deployment was still always on old deployment, 
awx-oprator took its time to take into account the new variables.

Sometimes giving things time by getting a good night's sleep is good :)

Thank's 

Regards,
