### ISSUE TITLE
ansible awx saml integration with azure

### ISSUE THREAD

**Issue by CatchKarthik** [ansible/tower-operator#1009]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Trying to configure Azure SAML for Ansible AWX.  Followed all the steps mentioned in the below document

https://access.redhat.com/solutions/3889291

When I click on the SAML Azure icon, it gives the below error 

**AADSTS50011: The reply URL 'http://ansible.example.io/sso/complete/saml/' specified in the request does not match the reply URLs configured for the application 'https://ansible.example.io'. Make sure the reply URL sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/urlMismatchError to learn more about how to fix this.**

The reply URL in Azure is set to the SAML Assertion Consumer Service (ACS) URL which is 
https://ansible.example.io/sso/complete/saml/. The entity ID in Azure is set to the Entity id configured in AWX which is https://ansible.example.io

I see that when it connects to SSO, the URL is http and not https (as shown in the error). The ACS URL however is https in AWX. Not sure if that is causing the problem.

### AWX Operator version

0.24.0

### AWX version

21.3.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.21

### Modifications

no

### Steps to reproduce

Configure Ansible AWX SAML settings based on the below URL

https://access.redhat.com/solutions/3889291

Try accessing Azure SAML

### Expected results

Ansible AWX should work with SSO configure and should be able to login

### Actual results

SSO not working and is giving the below error

**AADSTS50011: The reply URL 'http://ansible.example.io/sso/complete/saml/' specified in the request does not match the reply URLs configured for the application 'https://ansible.example.io'. Make sure the reply URL sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/urlMismatchError to learn more about how to fix this.**

**Comment by akus062381** [comment]
Hello @CatchKarthik, this appears to be less of a bug report or feature request and more of a configuration issue. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

We will close this for now. If you feel this is an error, please let us know via the mailing list and we can reopen it. Thank you!
