### ISSUE TITLE
Question - Values file passing in runasuser to containers and apparmor profile for OPA Gatekeeper

### ISSUE THREAD

**Issue by dslater-ak** [ansible/tower-operator#1014]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

My org has a fairly ridged security posture and requires us to comply with the gatekeeper settings they have in place. Normally this would mean getting runasuser: uid runasgroup: guid passed in as well as the apparmor runtime profile. 

I have looked thru and see I can pass in a couple of the requirements (containers must have limits) but that seems to be about it. 

Is there a provision to pass in 'runasuser', etc?

**Comment by akus062381** [comment]
Hi @dslater-ak, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
