### ISSUE TITLE
Connect awx 21.2 to postgres 9.6.9 external database

### ISSUE THREAD

**Issue by albericyao** [ansible/tower-operator#1019]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi all,

I  have to connect my awx installation to an external database (in postgres v9.6.9).

I can properly install the operator (0.23.0) and awx component. But the awx application containers cannot connect to that external database without showing any error (and stay in wait-for-migrations state).
<img width="363" alt="wait-for-migration" src="https://user-images.githubusercontent.com/29493207/184263588-85319bb1-4bbb-4d5d-8f26-f13991402dfe.PNG">

I also tried to migrate my old installation data (awx v15.0.0 with postgres 9.6.9) to my new installation (awx v21 with postgres 12) unsuccessfully (without error too).

is it possible to connect my installation to my external postgres database (9.6.9) ?
Or how can I migrate this data correctly ?

### AWX Operator version

0.23.0

### AWX version

21.2

### Kubernetes platform

openshift

### Kubernetes/Platform version

4.6

### Modifications

no

### Steps to reproduce

-Install Postgres 9.6.9
-Install awx 15.0.0 and connect it to your Postgres 9 database
-Install awx operator 0.23.0 with configuration for that Postgres 9.6.9 as external database 

### Expected results

awx 21.2 is completely  installed and available

### Actual results

stuck on waiting for migration message during awx components starting

**Comment by akus062381** [comment]
@rooftopcellist can you take a look at this when you have a chance please?

**Comment by chuegel** [comment]
We have the the same issue with awx operator 0.27.0 and postgres 10
```bash
TASK [installer : Check if there are any super users defined.] *****************\r\ntask path: /opt/ansible/roles/installer/tasks/initialize_django.yml:2\nfatal: [localhost]: FAILED! => {\"changed\": true, \"rc\": 1, \"return_code\": 1, \"stderr\": \"Postgres version 12 is required\\n\", \"stderr_lines\": [\"Postgres version 12 is required\"], \"stdout\": \"\", \"stdout_lines\": []}\r\n...ignoring\n\r\nTASK [installer : Create super user via Django if it doesn't exist.] ***********\r\ntask path: /opt/ansible/roles/installer/tasks/initialize_django.yml:16\nfatal: [localhost]: FAILED! => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\"
```
Did I miss the requirements for an external postgres db?

**Comment by albericyao** [comment]
@chuegel It seems that Postgres 12 is required. I tried with it and made a restore of my old database, it works this way.

**Comment by hreidar** [comment]
Hi, I'm trying out AWX for the first time, I also see this "super user defined" error and everything seems to be stuck. I'm doing a fresh install using operator 0.28.0 and an external Postgres 10.3. Do I need to upgrade Postgres to version 12 for this to work?

**Comment by chuegel** [comment]
@hreidar yes, according to the error message:
```
Postgres version 12 is required
```
Wonder which AWX postgres feature is needed to justify the hard requirement for posgres 12
https://www.postgresql.org/about/featurematrix/

**Comment by hreidar** [comment]
Thanks, @chuegel , I did not find this error until I stumbled up on another issue (#510) and found the following command:
```kubectl -n awx exec -ti deploy/awx -c awx-web -- awx-manage check```
which shows this.

Yes, strange that this is not mentioned in the install docs, this Postgres version requirement that is.

**Comment by akus062381** [comment]
@albericyao it appears that this issue has been resolved, so we are going to close it. If you would like, please feel free to open a PR to improve our docs! Thank you for your contribution!

**Comment by rooftopcellist** [comment]
@chuegel @hreidar we can only guarantee what we test.  We test the default Postgres version used for managed databases with a given version of awx.  The default Postgres version with awx-operator 0.30.0 is Postgres 13.  You can find this default for a given version by looking here: 
* https://github.com/ansible/awx-operator/blob/0fc145b6aa5b76e4afdb913c0e384da4f16d8290/roles/installer/defaults/main.yml#L138

I expect that newer versions of Postgres (13,14,15, etc.) will work with the current awx-operator and awx versions if configured as an external database.  

If your database is managed by the awx-operator (default if you don't specify a `postgres_configuration_secret`), then you should not override the default version as this may cause issues when awx-operator tries to upgrade your postgresql pod.

**Comment by rooftopcellist** [comment]
I added a doc PR to help clarify this.
* https://github.com/ansible/awx-operator/pull/1103
