### ISSUE TITLE
Unable to update from AWX 21.3 to 21.4, operator 0.25 to 0.26, Postgres 13 Pending

### ISSUE THREAD

**Issue by gianmarco-mameli** [ansible/tower-operator#1020]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### AWX Operator version

0.26.0

### AWX version

21.3

### Kubernetes platform

minikube

### Kubernetes/Platform version

1.24.0

### Modifications

no

### Steps to reproduce

Try to upgrade awx to 21.4 using 0.26.0 operator

git clone https://github.com/ansible/awx-operator.git
cd awx-operator/
git checkout 0.26.0
sed 's/kubectl/minikube kubectl --/g' -i Makefile
make deploy

### Expected results

upgrade of awx from 21.3 to 21.4

### Actual results

The deployment fails, the pod awx-postgres-13-0 remains in pending status for pvc

root@xxxxxxxx:~# kubectl -n awx describe pod awx-postgres-13-0
Name:           awx-postgres-13-0
Namespace:      awx
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/component=database
                app.kubernetes.io/instance=postgres-13-awx
                app.kubernetes.io/managed-by=awx-operator
                app.kubernetes.io/name=postgres-13
                app.kubernetes.io/part-of=awx
                controller-revision-hash=awx-postgres-13-54fc4988f
                statefulset.kubernetes.io/pod-name=awx-postgres-13-0
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/awx-postgres-13
Containers:
  postgres:
    Image:      postgres:13
    Port:       5432/TCP
    Host Port:  0/TCP
    Args:
      -c
      max_connections=1000
    Requests:
      cpu:     10m
      memory:  64Mi
    Environment:
      POSTGRESQL_DATABASE:        <set to the key 'database' in secret 'awx-postgres-configuration'>  Optional: false
      POSTGRESQL_USER:            <set to the key 'username' in secret 'awx-postgres-configuration'>  Optional: false
      POSTGRESQL_PASSWORD:        <set to the key 'password' in secret 'awx-postgres-configuration'>  Optional: false
      POSTGRES_DB:                <set to the key 'database' in secret 'awx-postgres-configuration'>  Optional: false
      POSTGRES_USER:              <set to the key 'username' in secret 'awx-postgres-configuration'>  Optional: false
      POSTGRES_PASSWORD:          <set to the key 'password' in secret 'awx-postgres-configuration'>  Optional: false
      PGDATA:                     /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS:       --auth-host=scram-sha-256
      POSTGRES_HOST_AUTH_METHOD:  scram-sha-256
    Mounts:
      /var/lib/postgresql/data from postgres-13 (rw,path="data")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gphwt (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  postgres-13:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  postgres-13-awx-postgres-13-0
    ReadOnly:   false
  kube-api-access-gphwt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  3s (x4 over 113s)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.

### Operator Logs

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Wait for Database to initialize if managed DB] ***************
task path: /opt/ansible/roles/installer/tasks/database_configuration.yml:206

-------------------------------------------------------------------------------
{"level":"info","ts":1660308833.8173711,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1660308839.3941922,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1660308844.9963953,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1660308850.587044,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1660308856.171865,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1660308861.8076298,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1660308867.4222105,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1660308873.0174794,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1660308878.596774,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1660308884.1892304,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}
{"level":"info","ts":1660308889.7719114,"logger":"proxy","msg":"cache miss: /v1, Kind=PodList err-Index with name field:status.phase does not exist"}

**Comment by kurokobo** [comment]
During the upgrade process, PSQL 13 is additionally deployed by 0.26.0 next to PSQL 12 that created with 0.25.0. 
Therefore, one additional PV with the class specified via `postgres_storage_class` is temporarily required for PSQL13 in addition to the one for PSQL 12.

If you had specified the class of PV for PSQL 12 manually, then you should have a pre-created PV for PSQL 13 with the same class, or the storage provisioner for the class must be configured correctly.

You can check the status via following commands;

```bash
kubectl get pv
kubectl -n awx get pvc
kubectl -n awx describe pvc postgres-13-awx-postgres-13-0
```

**Comment by gianmarco-mameli** [comment]
Hi @kurokobo, yes the pv is manually defined like this

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgres-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: awx-postgres-volume
  hostPath:
    path: /srv/postgres

and in awx.yml specs

...
postgres_storage_class: awx-postgres-volume
...

accordingly to your instructions I need to create another pv, in the same host_path or different?
example

---
apiVersion: v1
kind: PersistentVolume
metadata:
  **name: awx-postgres-13-volume**
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: awx-postgres-volume
  hostPath:
    **path: /srv/postgres13**

**Comment by kurokobo** [comment]
@gianmarco-mameli 
Thanks for updating, so you should create another pv with _different_ hostPath, before performing upgrade.
Once the upgrade completed, your AWX is working with PSQL 13 that uses `/srv/postgres13`, so you can delete old pv `awx-postgres-volume` and old directory `/srv/postgres` that are no longer used by AWX.

**Comment by gianmarco-mameli** [comment]
It worked! thanks for your support
