### ISSUE TITLE
Not able to launch AWX instance/pods on hostNetwork

### ISSUE THREAD

**Issue by meankit007** [ansible/tower-operator#1023]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

My internal github is behind a VPN/firewall and it don't allow traffic from pod CIDRs, it only handles traffic/listen from node CIDRs.
So because of which i am not able to sync my github/scm project in awx:
From the awx Job:
Failed to connect to XXXXXXXX.com port 443: Connection timed out

So i want to install AWX instance/pods in my hostNetwork. 

I am trying to install AWX instance using helm, by upgrading my awx-operator:

-  Install awx-operator:
   ==> **helm install -n awx my-awx-operator awx-operator/awx-operator**

-  Upgarding the awx-operator to install AWX instance:
   ==> cat awx-operator/new-value.yaml
AWX:
  enabled: true
  name: awx-demo
  namespace: awx
  spec:
    **hostNetwork: true**
    service_type: nodeport
    ingress_type: ingress
    ingress_annotations: |
      [kubernetes.io/ingress.class](http://kubernetes.io/ingress.class): gce-internal
   ==> **helm upgrade -n awx my-awx-operator awx-operator/awx-operator -f awx-operator/new-value.yaml**
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(AWX.spec): unknown field "hostNetwork" in com.ansible.awx.v1beta1.AWX.spec

ENV: I am trying above deployment in GCP-GKE private cluster.

helm list -n awx
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
my-awx-operator awx             2               2022-08-17 16:57:07.428193364 +0000 UTC deployed        awx-operator-0.25.0     0.25.0

### AWX Operator version

0.25.0

### AWX version

latest

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

v1.23.2

### Modifications

no

### Steps to reproduce

1)clone the awx-operator repo:
2) follow helm install on existing cluster:
https://github.com/ansible/awx-operator#helm-install-on-existing-cluster
helm install -n awx my-awx-operator awx-operator/awx-operator
3) Prepare a value for awx instance:
cat awx-operator/new-value.yaml
AWX:
  enabled: true
  name: awx-demo
  namespace: awx
  spec:
    hostNetwork: true
    service_type: nodeport
    ingress_type: ingress
    ingress_annotations: |
      [kubernetes.io/ingress.class](http://kubernetes.io/ingress.class): gce-internal
4) Upgrade the awx-operator to deploy awx instance/pods
  helm upgrade -n awx my-awx-operator awx-operator/awx-operator -f awx-operator/new-value.yaml

### Expected results

AWX instance/pods should be launched in hostNetwork/node network successfully. Pods should have ip from the node CIDRs

### Actual results

Not able to launch a AWX instance in host network:

Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(AWX.spec): unknown field "hostNetwork" in com.ansible.awx.v1beta1.AWX.spec

**Comment by fosterseth** [comment]
@meankit007 did you resolve this yet? You may get more traction on this by creating a new post in the mailing list https://groups.google.com/u/1/g/awx-project

**Comment by meankit007** [comment]
As my internal github doesn't allow any traffic from pods ip range, so i setup ip masquerading GKE. With IP masquerading, GKE changes the packet's source address from the Pod IP to the underlying node's IP address. Masquerading a packet's source is useful when a recipient is configured to receive packets only from the cluster's node IP addresses. So it is no more a blocker for me, but the issue still exist for someone who specifically want to launch AWX instance in host Network.

**Comment by akus062381** [comment]
Hi @meankit007!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
