### ISSUE TITLE
Upgrade fails due to hard coded cluster.local reference

### ISSUE THREAD

**Issue by mateuszdrab** [ansible/tower-operator#1031]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

My AWX instance fails to upgrade with the following error: 
```
could not translate host name awx-postgres.awx.svc.cluster.local
```
I figured quickly that this is due to `cluster.local` not being the domain name of my cluster.

There seems to be a reference somewhere in the playbook or config which hard codes it, but I've not been able to find it.

I think it would be better to omit `cluster.local` and attempt to resolve `awx-postgres.awx.svc` instead - where awx is the namespace

### AWX Operator version

0.27.0

### AWX version

0.21.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

k3s 1.22.9

### Modifications

no

### Steps to reproduce

- had an existing setup created by AWX 0.21.0 operator
- upgraded AWX operator from 0.21.0 to 0.27.0

### Expected results

- upgrade proceeds successfully

### Actual results

- upgrade fails to upgrade postgres from 12 to 13 due to dns resolution error
- 

### Operator Logs

TASK [installer : Stream backup from pg_dump to the new postgresql container] ***
task path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:89
fatal: [localhost]: FAILED! => {\"changed\": true, \"failed_when_result\": true, \"rc\": 1, \"return_code\": 1, \"stderr\": \"pg_dump: error: connection to database \\\"awx\\\" failed: could not translate host name \\\"awx-postgres.awx.svc.cluster.local\\\" to address: Name or service not known\
pg_restore: error: input file is too short (read 0, expected 5)\
\", \"stderr_lines\": [\"pg_dump: error: connection to database \\\"awx\\\" failed: could not translate host name \\\"awx-postgres.awx.svc.cluster.local\\\" to address: Name or service not known\", \"pg_restore: error: input file is too short (read 0, expected 5)\"], \"stdout\": \"\", \"stdout_lines\": []}

**Comment by mateuszdrab** [comment]
Resolved by modifying `/opt/ansible/roles/installer/tasks/upgrade_postgres.yml` in the container and removing the `.cluster.local` reference allowing DNS search domains to append the correct suffix.

Happy to PR this change as it should not break existing setups - cluster.local is one of the automatically appended search domains in Kubernetes.

**Comment by fosterseth** [comment]
@mateuszdrab Hi, a PR would be welcomed for this, feel free to @ me in the PR once opened and I'll take a look

**Comment by mateuszdrab** [comment]
@fosterseth PR created
