### ISSUE TITLE
AWX Deployment Fails with 0.27.0

### ISSUE THREAD

**Issue by CastawayEGR** [ansible/tower-operator#1036]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I have written an ansible playbook to deploy the AWX operator on k3s on GCP. In attempting a new deployment it fails with a templating error. 

The deployment of AWX is what fails, postgres and the controller-manager succeed. The PVC for AWX stays in a pending state due to the deployment failing to rollout. 

### AWX Operator version

0.27.0

### AWX version

2.9.27

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

v1.24.3+k3s1

### Modifications

no

### Steps to reproduce

1. Deploy latest version of k3s.
2. Make deploy using the 0.27.0 release of AWX Operator.
3. Create and apply PVC and AWX Kind.
4. Wait for failure of roll-out.

### Expected results

AWX is deployed and fully functional. 

### Actual results

AWX container fails rollout with the error below. 

### Additional information

Rolling back to AWX Operator version 0.26.0 succeeds in deployment.

### Operator Logs

[awx-deployment-error-0.27.0.log](https://github.com/ansible/awx-operator/files/9424744/awx-deployment-error-0.27.0.log)

**Comment by CastawayEGR** [comment]
Complete log attached here. 

[awx-operator-0.27.0-full.log](https://github.com/ansible/awx-operator/files/9424775/awx-operator-0.27.0-full.log)

**Comment by kurokobo** [comment]
@CastawayEGR 

> do_indent() got an unexpected keyword argument 'indentfirst'"}

This issue seems dup of #1032 and is already fixed in the upstream devel branch. We should just wait for the next release or use 0.26.0 instead as a workaround.

**Comment by CastawayEGR** [comment]
My mistake, I should have noticed that duplicate but saw upgrade in the title and didn't know if it was related or not. Thanks @kurokobo for pointing me in the right direction!
