### ISSUE TITLE
fail to deploy operator 0.28.0 because of wrong yaml format

### ISSUE THREAD

**Issue by adpavlov** [ansible/tower-operator#1037]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

awx-operator 0.28.0 deployment failing with the following error:

`{"changed": true, "cmd": "make deploy\n", "delta": "0:00:00.440185", "end": "2022-08-25 23:56:03.529811", "msg": "non-zero return code", "rc": 2, "start": "2022-08-25 23:56:03.089626", "stderr": "Error: accumulating resources: accumulation err='accumulating resources from '../manager': '/home/devops/ansible/roles/awx/files/awx-operator-0.28.0/config/manager' must resolve to a file': recursed accumulation of path '/home/devops/ansible/roles/awx/files/awx-operator-0.28.0/config/manager': accumulating resources: accumulating resources from 'manager.yaml': MalformedYAMLError: yaml: line 29: did not find expected key in File: manager.yaml\nerror: no objects passed to apply\nmake: *** [deploy] Error 1", "stderr_lines": ["Error: accumulating resources: accumulation err='accumulating resources from '../manager': '/home/devops/ansible/roles/awx/files/awx-operator-0.28.0/config/manager' must resolve to a file': recursed accumulation of path '/home/devops/ansible/roles/awx/files/awx-operator-0.28.0/config/manager': accumulating resources: accumulating resources from 'manager.yaml': MalformedYAMLError: yaml: line 29: did not find expected key in File: manager.yaml", "error: no objects passed to apply", "make: *** [deploy] Error 1"], "stdout": "", "stdout_lines": []}`

### AWX Operator version

0.28.0

### AWX version

21.5.0

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

k3s

### Modifications

no

### Steps to reproduce

make deploy

### Expected results

all resources configured

### Actual results

deploy failed because of MalformedYAMLError 

### Additional information

Seems like issue with spacing. Attaching file that passing validation and allowed to deploy awx-operator
[manager.txt](https://github.com/ansible/awx-operator/files/9428478/manager.txt)

**Comment by adpavlov** [comment]
adding @rooftopcellist as it was his commit

**Comment by kurokobo** [comment]
@adpavlov 
This can't be reproduced on my side. Everything works as expected.

```bash
$ git clone https://github.com/ansible/awx-operator.git
$ cd awx-operator
$ git checkout 0.28.0
$ export NAMESPACE=awx
$ make deploy
namespace/awx created
customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com created
customresourcedefinition.apiextensions.k8s.io/awxrestores.awx.ansible.com created
customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com created
serviceaccount/awx-operator-controller-manager created
role.rbac.authorization.k8s.io/awx-operator-awx-manager-role created
role.rbac.authorization.k8s.io/awx-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/awx-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/awx-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/awx-operator-awx-manager-rolebinding created
rolebinding.rbac.authorization.k8s.io/awx-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/awx-operator-proxy-rolebinding created
configmap/awx-operator-awx-manager-config created
service/awx-operator-controller-manager-metrics-service created
deployment.apps/awx-operator-controller-manager created
```

I am guessing from the message you provided that you are running `make deploy` from a playbook or a role?
If so, I think it's an issue of your playbook or role, and not an AWX Operator issue.

**Comment by adpavlov** [comment]
Indeed, I found the cause. I'm inserting `- name: DEFAULT_AWX_VERSION` value in `env:` section, but since spacing changed my lineinfile corrupted manager.yaml
