### ISSUE TITLE
Fail to install second AWX with different namespace and the same awx-operator

### ISSUE THREAD

**Issue by qoovsxp** [ansible/tower-operator#1039]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### AWX Operator version

0.28

### AWX version

21.5

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

EKS Kubernetes 1.20

### Modifications

no

### Steps to reproduce

Step1.Install awx operator by helm ,and deploy first AWX by yaml

Step2.fixed yaml for second AWX with different namespace then deploy the second AWX by yaml.

### Expected results

The second AWX will finish with different namespace.

### Actual results

It's stuck with some cluster role errors in install logs.

### Additional information

![image](https://user-images.githubusercontent.com/22346526/187172567-26d10584-42de-4253-ae4e-7d4d02a2d9ec.png)

### Operator Logs

Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "awx-operator-metrics-reader" in namespace "" exists and cannot be imported into the current release:
 invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "test-awx-operator": current value is "staging-awx-operator"; annotation validation error: 
key "meta.helm.sh/release-namespace" must equal "staging-awx2": current value is "staging-awx"

**Comment by jcomito** [comment]
You need to install the operator again into the second namespace.

"Starting with awx-operator 0.14.0, AWX can only be deployed in the namespace that the operator exists in. This is called a namespace-scoped operator." https://github.com/ansible/awx-operator#cluster-scope-to-namespace-scope-considerations

**Comment by praniq** [comment]
Have the same issue. Looks like it's not possible to deploy multiple awx-operators in different namespaces. 

The issue here is that multiple awx-operator helm releases try to manage the same ClusterRole "awx-operator-metrics-reader". And Helm doesn't allow multiple releases to manage the same resource. During a release install Helm checks "meta.helm.sh/release-name" and "meta.helm.sh/release-namespace" annotations and sees that it's managed by another release and fails with error:

```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "awx-operator-metrics-reader" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "AAA": current value is "BBB"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "CCC": current value is "DDD"
```

**Comment by bewing** [comment]
The issue are the `awx-operator-metrics-reader` and `awx-operator-proxy-role` defined in `awx-operator/config/rbac/auth_proxy*` being cluster resources.

Does kube-rbac-proxy require a ClusterRole?
Can we wrap deployment of these templates in a values check so we can suppress them after the first controller has been deployed to a namespace?

**Comment by pat-s** [comment]
I also just fell over this. Applies also to clusterrolebinding `awx-operator-proxy-rolebinding`.

**Comment by chillTschill** [comment]
We are experiencing the same issue with the helm chart. 

Regarding the proposed solution by @bewing , I think this might not work for the proxy ClusterRole, as we need to map the serviceAccounts in the clusterrolebinding as well.

What would you think about adding the `HelmRelease.Name` as a prefix to the global spaced resources?
Please let me know your opinion about that - I would be happy to provide a PR.

**Comment by akus062381** [comment]
Hi @qoovsxp,

Do any of these community member suggestions help in your situation?

**Comment by qoovsxp** [comment]
Hi @akus062381 ,

I have a workaround solution for that.

You need fix release name and namespace in cluster role and cluster role binding to second awx first.
![image](https://user-images.githubusercontent.com/22346526/207485704-c317b56f-a6de-4f5a-a9d5-2f7d622fe736.png)
![image](https://user-images.githubusercontent.com/22346526/207485879-37e4e892-71d2-412a-bb54-6d085ebed76e.png)
![image](https://user-images.githubusercontent.com/22346526/207486006-daecd770-aa78-44db-9088-882260719e17.png)

![image](https://user-images.githubusercontent.com/22346526/207486277-889bdb9b-d725-4b79-9053-a9644c098c5f.png)

![image](https://user-images.githubusercontent.com/22346526/207486401-bf7e33ed-c08b-4827-9875-a92fe6260e32.png)

Then you can deploy the secound awx operator and awx.

**Comment by ThomasSteinbach** [comment]
# Workaround

When installing the AWX operator, following transformer within the kustomization will add a suffix to all namespace resources.

**kustomization.yaml**

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

transformers:
  - suffix-cluster-resources.yaml
```

**suffix-cluster-resources.yaml**

```yaml
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: customPrefixer
suffix: "-dev"  # change as desired
fieldSpecs:
  - kind: ClusterRole
    path: metadata/name
  - kind: ClusterRoleBinding
    path: metadata/name
```

**Comment by jigarpa1** [comment]
> 

Can you please let me know where to find those files?
