### ISSUE TITLE
Jobs getting suck

### ISSUE THREAD

**Issue by joaogl** [ansible/tower-operator#105]
Hello,

Using this operator I'm getting an issue which I can't really figure out what is going on...
Initially I created this: https://github.com/ansible/awx/issues/9364 but now I'm no longer sure that the issue is on awx side or on this operator side :/

Did anyone see this or can think of anything that could cause this issue?

THanks

**Comment by tchellomello** [comment]
@joaogl  it seems the ansible/awx#9364 was been closed as dups for ansible/awx#9401 which has been fixed by `awx 17.0.0`. Please try it using the latest `awx-operator` version and let us know if you have any issues.

@Spredzy @shanemcd it seems we are good to close this one.
