### ISSUE TITLE
documentation <tag> URL in Kustomizer.yal fails with path error

### ISSUE THREAD

**Issue by twobombs** [ansible/tower-operator#1058]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

https://github.com/ansible/awx-operator#basic-install contains a kustomizer.yaml example that gives a path error when filled

<img width="863" alt="Screenshot 2022-09-22 at 11 27 42" src="https://user-images.githubusercontent.com/12692227/191711161-f14e3bd5-b999-4b5e-acd6-ab87e94fdb2e.png">

<img width="802" alt="Screenshot 2022-09-22 at 11 37 44" src="https://user-images.githubusercontent.com/12692227/191713453-ec475fb9-0fed-4954-8f73-206fc9fbb11e.png">

`kustomize build . | kubectl apply -f -
Error: accumulating resources: accumulation err='accumulating resources from 'github.com/ansible/awx-operator/tree/0.29.0/config/default': evalsymlink failure on '/root/github.com/ansible/awx-operator/tree/0.29.0/config/default' : lstat /root/github.com: no such file or directory': git cmd = '/snap/kustomize/34/usr/bin/git init': exit status 127
error: no objects passed to apply`

### AWX Operator version

0.29.0

### AWX version

-

### Kubernetes platform

minikube

### Kubernetes/Platform version

minikube version: v1.27.0 

### Modifications

no

### Steps to reproduce

https://github.com/ansible/awx-operator#basic-install contains a kustomizer.yaml example that gives a path error when filled in 

<img width="863" alt="Screenshot 2022-09-22 at 11 27 42" src="https://user-images.githubusercontent.com/12692227/191711161-f14e3bd5-b999-4b5e-acd6-ab87e94fdb2e.png">

### Expected results

succesfull deployment

### Actual results

`kustomize build . | kubectl apply -f -
Error: accumulating resources: accumulation err='accumulating resources from 'github.com/ansible/awx-operator/tree/0.29.0/config/default': evalsymlink failure on '/root/github.com/ansible/awx-operator/tree/0.29.0/config/default' : lstat /root/github.com: no such file or directory': git cmd = '/snap/kustomize/34/usr/bin/git init': exit status 127
error: no objects passed to apply`

### Additional information

this is run on an Ubuntu 18.04 linode instance as root
kustomize was installed using snap

**Comment by kurokobo** [comment]
> kustomize was installed using snap

Dups of #919. The `kustomize` from snap causes this issue.

Refer my comment on https://github.com/ansible/awx-operator/issues/919#issuecomment-1184510748 and try pure `kustomize` by downloading binary directly. Refer: https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/

`github.com/ansible/awx-operator/config/default?ref=<tag>` is for API call, so getting 404 if you access this URL from your browser is expected behavior.

**Comment by twobombs** [comment]
tnx - closed
