### ISSUE TITLE
Migration data from AWX 17.1.0 to AWX 21.2.0

### ISSUE THREAD

**Issue by RootKaizer** [ansible/tower-operator#1060]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi AWX team, I have problems when trying to migrate the database Postgres from AWX 17 to AWX 21.2

I follow the guide "https://github.com/ansible/awx-operator/blob/devel/docs/migration.md".

I checked the Issues about migration topic, all Issues close when your team answer, please read the guide. I seek videos about this migration but I don found anything on my network.

could your team make an explication video step by step?

### AWX Operator version

0.23.0

### AWX version

21.2.0

### Kubernetes platform

minikube

### Kubernetes/Platform version

1.23

### Modifications

no

### Steps to reproduce

1) get secret key from inventory AWX17
vi **<AWX17_installer_folder>**/installer/inventory
#######################
pg_username=**<pg_username>**
pg_password=**<pg_password>**
pg_database=**<pg_database>**
secret_Key:**<value_secret_key_awx>**
#######################

2. open networ postgres from AWX17
vi **<home_user>**/.awx/awxcompose/docker-compose.yml
#######################
  postgres:
    image: postgres:12
    container_name: awx_postgres
    ports:
      - **"5432:5432"**
.......
#######################

3. reboot AWX17 service
docker stop awx_task awx_web awx_postgres awx_redis
docker-compose -f **<home_user>**/.awx/awxcompose/docker-compose.yml up -d

4. create secret playbook on AWX21.2.0 folder
cd **<AWX17_installer_folder>**
vi secret.yaml
#######################
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-secret-key
  namespace: awx
stringData:
  secret_key: **<value_secret_key_awx>**
type: Opaque
#######################

5. create postgres-awx17.yaml
#######################
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: <ip_awx17_server>
  port: 5432
  database: **<pg_database>**
  username: **<pg_username>**
  password: **<pg_password>**
type: Opaque
#######################

6. update awx-demo.yaml file
#######################
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  # default nodeport_port is 30080
  nodeport_port: 30080
  **old_postgres_configuration_secret: awx-postgres-configuration
  secret_key_secret: awx-secret-key**
#######################

7. check kustomization.yaml
#######################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=0.23.0
# add resource awx-21.2.0-prod
  - awx-demo.yaml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.23.0

# Specify a custom namespace in which to install AWX
namespace: awx
#######################

8. reboot service AWX21.2.0
sudo systemctl stop minikube.service
sudo systemctl start minikube.service

9. check my AWX 21.2.0 website
**My data isn't migrate, i only have started data**

### Expected results

I expected to get data AWX17 on the website AWX 21.2.0

### Actual results

website AWX21.2.0 only has started data and it don't have data from AWX 17

### Operator Logs

escued=0    ignored=0   \r\n\n","job":"5363105567607275310","name":"awx-demo","namespace":"awx","error":"exit status 2"}

----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx-demo/awx) -----

PLAY RECAP *********************************************************************
localhost                  : ok=44   changed=0    unreachable=0    failed=1    skipped=32   rescued=0    ignored=0

----------
{"level":"error","ts":1663953196.1770906,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Reconciler error","name":"awx-demo","namespace":"awx","error":"event runner on failed","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214"}

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Patching labels to AWX kind] *********************************
task path: /opt/ansible/roles/installer/tasks/main.yml:2

-------------------------------------------------------------------------------
{"level":"info","ts":1663953197.520823,"logger":"logging_event_handler","msg":"[playbook task start]","name":"awx-demo","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"5647864405804212632","EventData.Name":"installer : Patching labels to AWX kind"}
{"level":"info","ts":1663953198.539386,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/awx.ansible.com/v1beta1/namespaces/awx/awxs/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"awx.ansible.com","APIVersion":"v1beta1","Namespace":"awx","Resource":"awxs","Subresource":"","Name":"awx-demo","Parts":["awxs","awx-demo"]}}
{"level":"info","ts":1663953198.6801004,"logger":"logging_event_handler","msg":"[playbook task start]","name":"awx-demo","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"5647864405804212632","EventData.Name":"installer : Include secret key configuration tasks"}

**Comment by PaulVerhoeven1** [comment]
This is the only thing i found: https://www.reddit.com/r/ansible/comments/mvcsyw/comment/gvbi7jx/?utm_source=share&utm_medium=web2x&context=3

**Comment by fosterseth** [comment]
@RootKaizer You may checkout our AWX mailing list [here](https://groups.google.com/u/1/g/awx-project), there are a good number of discussions around upgrading from older AWX instances.

Feel free to open a topic there
