### ISSUE TITLE
Add options in CRD for setting labels on pods

### ISSUE THREAD

**Issue by bpedersen2** [ansible/tower-operator#1081]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

For using awx deployed with the awx operator in combination with istio I would like to be able to set the istio-injection labels (https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy) on a per-pod basis.
Reason: Setting autoinjection on the namespace causes  a startup error for the ee pod:
`Error creating pod: expected 1 container in pod but there were 2`  as  the istio-porxy sidecar is present.

**Comment by fosterseth** [comment]
@rooftopcellist is that > 1 container error a restriction on our end?

**Comment by bpedersen2** [comment]
The error is  thrown  from the recptor: https://github.com/ansible/receptor/blob/a65ef6c80ac68c133d2c3d7ccd341758b0185dcc/pkg/workceptor/kubernetes.go#L243

**Comment by rooftopcellist** [comment]
@bpedersen2 If I understand correctly, this was implemented in https://github.com/ansible/awx-operator/pull/1160

Please comment here if that is not the case and I will re-open the issue.  

You may also be interested in this other PR which allows for configuring a sidecar:
* https://github.com/ansible/awx-operator/pull/1236

**Comment by bpedersen2** [comment]
Seems a workable way to do it. ( the real problem is in the receptor code,but that  should be a separate ticket). Fine with closing this .

**Comment by bpedersen2** [comment]
will be fully fixed by https://github.com/ansible/receptor/pull/717
