### ISSUE TITLE
Ability to use external postgres database

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#11]
In some use cases, Id like to only run Tower/AWX inside the cluster, but rely on an external set of postgres databases that I'm already operating. As part of the operator, I'd like to be able to point to this database instead of spinning one up in the cluster.

**Comment by matburt** [comment]
This is supported now and the details are outlined in the CRD

https://github.com/ansible/awx-operator/blob/devel/deploy/crds/awx_v1beta1_crd.yaml#L32

**Comment by jcomito** [comment]
Can I be a bother and get some more specifics on how to set this up during installation? Do I just add those parameters to my my-awx.yml file and apply it?

**Comment by matburt** [comment]
You can find the instructions alongside the CRD's external database setting: https://github.com/ansible/awx-operator/blob/devel/deploy/crds/awx_v1beta1_crd.yaml#L32

Set this  value to true in your CR and then create a secret containing the required information.
