### ISSUE TITLE
Missing extra_nginx_include config in CRD

### ISSUE THREAD

**Issue by autofald** [ansible/tower-operator#1112]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When trying to add extra parameters in the nginx.conf (max_body_size), I found out that there is already the jinja variable _extra_nginx_include_ in the configMap.

Unfortunately, I can't use it because the config is missing in the CRD.

### AWX Operator version

1.0.0

### AWX version

21.8.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

K3S

### Modifications

no

### Steps to reproduce

Add extra_nginx_include configuration in AWX-operator specs :
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  extra_nginx_include: /nginx/extra-ngninx.conf
```

### Expected results

The content of the configuration extra_nginx_include configuration is used during the templating of the configMap :
https://github.com/ansible/awx-operator/blob/1cf466def2fe226f592711161983c0fa114909ac/roles/installer/templates/configmaps/config.yaml.j2#L215-L217

### Actual results

ValidationError(AWX.spec): unknown field "extra_nginx_include" in com.ansible.awx.v1beta1.AWX.spec

**Comment by Zokormazo** [comment]
If we include `include /etc/nginx/conf.d/*.conf` to our nginx.conf, you could do that without new fields in the cr, might be a better approach.

Using a [custom volume mount](https://github.com/ansible/awx-operator#custom-volume-and-volume-mount-options) you can mount extra files in /etc/nginx/conf.d of web container from a `ConfigMap`, we probably just miss the bits to actually read them

Thous @rooftopcellist  ?

**Comment by AymericP35** [comment]
Would appreciate such a feature as I’m also seeking a way to put extra conf to nginx !

**Comment by rooftopcellist** [comment]
I thing that approach is the most extensible, but might be a bit difficult at first for a user somewhat new to k8s.  

I put up a draft PR here for that approach so we can talk about it:
* https://github.com/ansible/awx-operator/pull/1145

I wonder if a more opinionated approach might be better for the end user.  What I have in mind is allowing the user to specify a configmap via the spec, and the awx-operator takes care of making a volume and volumeMount for it. I don't think we really have a precedent for that approach yet though, so it might be more confusing (users may already be familiar with the extra_volumes pattern) cc @Zokormazo

**Comment by rooftopcellist** [comment]
This is now possible in the devel branch with the merge of https://github.com/ansible/awx-operator/pull/1145

cc @jagrutibelani
