### ISSUE TITLE
Do not use latest image tag in release version

### ISSUE THREAD

**Issue by weironz** [ansible/tower-operator#1118]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

can you let `quay.io/ansible/awx-ee:latest`  as one Specific default version, thanks.

it will be good for offline install.

```
root@node1:~# kubectl -n awx get pods -o yaml |grep image:
      image: docker.io/redis:7
      image: quay.io/ansible/awx:21.8.0
      image: quay.io/ansible/awx:21.8.0
      image: quay.io/ansible/awx-ee:latest
      image: quay.io/ansible/awx-ee:latest
      image: quay.io/ansible/awx-ee:latest
      image: quay.io/ansible/awx-ee:latest
      image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
      image: quay.io/ansible/awx-operator:1.0.0
```

**Comment by weironz** [comment]
In addition, I want to find the default awx image tag used by the operator, but the entire repo does not find `quay.io/ansible/awx:21.8.0`

![image](https://user-images.githubusercontent.com/33590311/201369498-c9ba469c-950b-40b1-9752-caa835313b9a.png)

**Comment by djyasin** [comment]
Hello, please use the following command to grab the latest image:
docker run --entrypoint=“”  quay.io/ansible/awx-operator:1.0.0 bash -c “env | grep DEFAULT_AWX_VERSION”
DEFAULT_AWX_VERSION=21.8.0
