### ISSUE TITLE
got an unexpected keyword argument 'suppress_env_files'

### ISSUE THREAD

**Issue by weironz** [ansible/tower-operator#1120]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/__main__.py", line 861, in main
    res = run(**run_options)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 257, in run
    r.run()
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/streaming.py", line 128, in run
    r = ansible_runner.interface.run(**self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 256, in run
    r = init_runner(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 118, in init_runner
    rc = RunnerConfig(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/config/runner.py", line 78, in __init__
    super(RunnerConfig, self).__init__(private_data_dir, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'suppress_env_files'

  This can be caused if the version of ansible-runner in your execution environment is out of date.
```

### AWX Operator version

1.0.0

### AWX version

21.8.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.25.3

### Modifications

no

### Steps to reproduce
1、 install awx
```
helm upgrade -i awx awx-operator/awx-operator -n awx --create-namespace --set AWX.enabled=true,AWX.spec.service_type=NodePort
```
2、run default job

### Expected results

run job success

### Actual results

run job failed

**Comment by djyasin** [comment]
Hi @willzhang!

We would like to gather some information from you. Please let us know what execution environment you are running.

**Comment by Xiol** [comment]
I'm getting this same issue using the default `quay.io/ansible/awx-ee:latest` EE. I have also tried it with the Control Plane EE and a custom EE, and all report the same error.

**Comment by akus062381** [comment]
Hi @willzhang,

Our suggestion is to rebuild your image using the latest AWX EE. 
Please compare the image sha with what is on the AWX EE Quay website:
https://quay.io/repository/ansible/awx-ee?tab=tags

**Comment by akus062381** [comment]
@Xiol,

can you please make sure that your pull policy is set to get the latest version of the EE? If you had an older version of awx-ee:latest with an old ansible-runner and haven't downloaded a new version recently you may see this issue.

**Comment by Xiol** [comment]
The pull policy was set to Always to no effect.

In the end I had to restart the deployment to get it to work. I'm not sure of the root cause - there was little in the logs that I could see.
