### ISSUE TITLE
Previous helm chart versions not available

### ISSUE THREAD

**Issue by Alex011274** [ansible/tower-operator#1136]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello,
I faced the same problem as in the issue https://github.com/ansible/awx-operator/issues/1053
It was fixed in https://github.com/ansible/awx-operator/pull/1087, but now it has broken again. 
This seems to be the cause of the problem: https://github.com/ansible/awx-operator/commit/262f34c171670a4332639360a457e3d6b9054d50

Could you please fix it?

### AWX Operator version

0.30.0

### AWX version

21.7.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

Doesn't depend on kubernetes version

### Modifications

yes

### Steps to reproduce

```
$ helm search repo awx-operator -l
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                      
awx-operator/awx-operator	1.1.0        	1.1.0      	A Helm chart for the AWX Operator
```

### Expected results

all previous versions should be available with the `helm search` command.

### Actual results

```
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                      
awx-operator/awx-operator	1.1.0        	1.1.0      	A Helm chart for the AWX Operator
```

**Comment by djyasin** [comment]
Hello @Alex011274, 
Thank you for bringing this to our attention. We will investigate this further and get back to you!

**Comment by miles-w-3** [comment]
Index.yaml indeed only has the lastest chart link - https://github.com/ansible/awx-operator/blob/gh-pages/index.yaml

@janorn and @rooftopcellist, I don’t think the changes from this commit are being propagated to index.yaml
https://github.com/ansible/awx-operator/pull/1065

**Comment by miles-w-3** [comment]
I believe the helm-index target defined [here](https://github.com/ansible/awx-operator/blob/f35bd7cf831468c647d0db52fe9f20991315e467/Makefile#L362) has to be called during the promote pipeline [here](https://github.com/ansible/awx-operator/blob/f35bd7cf831468c647d0db52fe9f20991315e467/ansible/helm-release.yml#L19)

**Comment by skattaa** [comment]
facing the same problem .. with each newer version , I can't see the older ones !

**Comment by miles-w-3** [comment]
yep, the make target that copies all previous tags into the index.yaml file is not being run

**Comment by kristofre** [comment]
Confirming that the issue still exists with the current release. This is hurting any automation use case with fixed versions.
