### ISSUE TITLE
Upgrade from 0.28 to 1.0.0 fails due to missing contstraint.

### ISSUE THREAD

**Issue by HGS9761** [ansible/tower-operator#1143]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

An upgrade from 0.28 to 1.0.0. fails due to what seems to be a missing constraint.

```
2022-12-02 09:51:47.075 CET [52137] ERROR:  there is no unique constraint matching given keys for referenced table "main_workflowjobnode"
2022-12-02 09:51:47.075 CET [52137] STATEMENT:  ALTER TABLE "main_workflowjobnode_labels" ADD CONSTRAINT "main_workflowjobnode_workflowjobnode_id_14f419e1_fk_main_work" FOREIGN KEY ("workflowjobnode_id") REFERENCES "main_workflowjobnode" ("id") DEFERRABLE INITIALLY DEFERRED
```

I am using k3s

### AWX Operator version

1.0.0

### AWX version

21.5.0

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

k3s-selinux-1.2-2.el8.noarch

### Modifications

no

### Steps to reproduce

Upgrade working installation from version 0.28.0 to 1.0.0

### Expected results

That everything worked correctly

### Actual results

The environment was no longer available

### Operator Logs

[postgres.log](https://github.com/ansible/awx-operator/files/10139962/postgres.log)

**Comment by rooftopcellist** [comment]
@HGS9761 This is an issue with the database migrations, not the operator itself.  Could you please open an issue in the github.com/ansible/awx repo?

**Comment by HGS9761** [comment]
Hi Christian,

Thanks for closing it.
I noticed that it does not reproduce always.

It seems to be related to awx process that stay when k3s is stopped


***@***.*** ~]# systemctl stop k3s
***@***.*** ~]# ps -ef|grep awx
1001        5292    4949  0 13:32 ?        00:00:00 /tini --
/usr/local/bin/ansible-operator run --watches-file=./watches.yaml
--reconcile-period=0s --health-probe-bind-address=:6789
--metrics-bind-address=127.0.0.1:8080 --leader-elect
--leader-election-id=awx-operator
1001        5444    5292  0 13:32 ?        00:00:00
/usr/local/bin/ansible-operator run --watches-file=./watches.yaml
--reconcile-period=0s --health-probe-bind-address=:6789
--metrics-bind-address=127.0.0.1:8080 --leader-elect
--leader-election-id=awx-operator
hans-pe+    6252    5943  0 13:33 ?        00:00:00 dumb-init --
/usr/bin/launch_awx.sh
hans-pe+    6265    6252  0 13:33 ?        00:00:00 bash
/usr/bin/launch_awx.sh
hans-pe+    6311    5943  0 13:33 ?        00:00:00 dumb-init --
/usr/bin/launch_awx_task.sh
hans-pe+    6336    6311  0 13:33 ?        00:00:00 bash
/usr/bin/launch_awx_task.sh
hans-pe+    6589    6290  0 13:33 ?        00:00:00 /usr/bin/coreutils
--coreutils-prog-shebang=timeout /usr/bin/timeout 60 /bin/bash -c
awx-manage check
hans-pe+    6590    6356  0 13:33 ?        00:00:00 /usr/bin/coreutils
--coreutils-prog-shebang=timeout /usr/bin/timeout 60 /bin/bash -c
awx-manage check
hans-pe+    6591    6589  7 13:33 ?        00:00:00
/var/lib/awx/venv/awx/bin/python3.9 /usr/bin/awx-manage check
hans-pe+    6592    6590  7 13:33 ?        00:00:00
/var/lib/awx/venv/awx/bin/python3.9 /usr/bin/awx-manage check



Op ma 5 dec. 2022 om 22:02 schreef Christian Adams ***@***.***
