### ISSUE TITLE
[web/task split] web deployment needs receptor certs for execution node install bundle to work

### ISSUE THREAD

**Issue by relrod** [ansible/tower-operator#1155]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Currently (as of 20bd5041eb6d027cacda4477d80d58b30eee9022 on the `web-task-split` branch), it is impossible to download an install bundle to set up a new remote execution node.

![image](https://user-images.githubusercontent.com/43930/207591904-3846fce2-29dc-4d58-b0ac-ccd719e396a2.png)

### AWX Operator version

web-task-split branch

### AWX version

wsrelay branch

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

kind

### Modifications

yes

### Steps to reproduce

- Get an environment set up using `web-task-split` branch from here and `wsrelay` branch from awx
- Log in and add a new execution instance 
- Try to download the installer bundle

### Expected results

The install bundle should get generated and downloaded

### Actual results

Traceback in image above.

**Comment by TheRealHaoLiu** [comment]
the CA cert should be located in a secret which is shareable between deployments 

https://github.com/ansible/awx-operator/blob/9bf896e37c1551922001f0a15035f8cd9c4b4bef/roles/installer/templates/deployments/deployment.yaml.j2#L65-L69

https://github.com/ansible/awx-operator/blob/9bf896e37c1551922001f0a15035f8cd9c4b4bef/roles/installer/templates/deployments/deployment.yaml.j2#L436-L438

**Comment by TheRealHaoLiu** [comment]
Make sure we test this my adding a remote execution node

**Comment by djyasin** [comment]
Steps to reproduce UPDATE:
Get an environment set up using `web-task-split` branch from here and `web-task-split` branch from awx. Disregard earlier step of using `wsrelay` as we have moved past that now.
