### ISSUE TITLE
Clear documentation on Logging  Forwarding to External logging service like log stash

### ISSUE THREAD

**Issue by rakesh561** [ansible/tower-operator#1164]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Team I have been trying to understand how we can forward logs from awx to external resources like Logstash etc.
It would be great wat needs to be done at deployment level like do we need to add any configuration in awx deployment in k8s and also example like once we update logging settings in awx UI demo example of how you can visualize/detect logs in elastic search or log stash and create a dummy index etc.Ansible tower documentation but it doesn't look that great.

**Comment by fosterseth** [comment]
hi! thanks for opening an issue. We are tracking this issue here https://github.com/ansible/awx-operator/issues/1086, so we'll go ahead and close this issue. Please take a look at that other issue and add comments/thoughts there.
