### ISSUE TITLE
RFE: Add custom LDAP auth using custom "*.pem" file during installation on OCP

### ISSUE THREAD

**Issue by agilleyrh** [ansible/tower-operator#117]
Original issue: https://github.com/ansible/tower-packaging/issues/1052

ISSUE TYPE
Enhancement - provide the option to add a custom LDAP AUTH configuration using a custom PEM file during installation, if desired or required by security policies.
SUMMARY
This solution requires two new custom files, and modifications to two existing files:
New files
roles/kubernetes/templates/EXAMPLE.pem.j2
roles/kubernetes/templates/ldap.py.j2
Existing files
roles/kubernetes/templates/deployment.yml.j2
roles/kubernetes/templates/secret.yml.j2

DETAILS
The EXAMPLE.pem file would contain all the custom certificates that are required by the user.

The ldap.py.j2 file would contain the AUTH_LDAP_GOLBAL_OPTIONS directive and pull the cert information from the custom PEM file:

AUTH_LDAP_GLOBAL_OPTIONS = { ldap.OPT_X_TLS_REQUIRE_CERT: True, ldap.OPT_X_TLS_CACERTFILE: "/etc/openldap/certs/EXAMPLE.pem" }
This code would be added to the deployment.yml.j2 file:

(in the "volumeMounts:" section of the "{{ kubernetes_deployment_name }}-web" container)

```
{% if custom_ldap_auth is true %}
    - name: "{{ kubernetes_deployment_name }}-application-credentials"
      mountPath: "/etc/openldap/certs/EXAMPLE.pem
      subPath: EXAMPLE.pem
      readOnly: true
    - name: "{{ kubernetes_deployment_name }}-application-credentials"
      mountPath: "/etc/tower/conf.d/ldap.py"
      subPath: ldap.py
      readOnly: true
{% endif %}
```

(listed with the secrets in the "{{ kubernetes_deployment_name }}-application-credentials" volume)

```
{% if custom_ldap_auth is true %}
    - key: EXAMPLE_pem
      path: 'EXAMPLE.pem'
    - key: ldap_py
      path: 'ldap.py'
{% endif %}
```

The ldap.py variable can be defaulted to false in roles/kubernetes/defaults/main.yml, then changed to "true" to use a custom LDAP auth.

This code would be added to the "data" section of the secret.yml.j2 file:

```
ldap_py: "{{ lookup('template', 'ldap.py.j2') | b64encode }}"
EXAMPLE_pem: "{{ lookup('template', 'EXAMPLE.pem.j2') | b64encode }}"
```

NOTE: The YAML code has been tested during installations, but the Jinja2 conditional tests have not.

**Comment by ghost** [comment]
+1.. Having custom ldap trust certificates really needs to be a feature
