### ISSUE TITLE
Avoid creating service account in default namespace

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#12]
Currently the service account for the operator is created in the `default` namespace by default. This should be corrected so that it is created/deployed into the same namespace that the operator is deployed to.

**Comment by matburt** [comment]
Well, right now we deploy *everything* related to the operator in the default namespace... I'd love to not be strictly opinionated about this but for some reason the role binding *does* have to be in a namespace:

https://github.com/ansible/awx-operator/blob/devel/deploy/role_binding.yaml#L9

I'm not entirely sure how to resolve this. This whole operator needs to be updated for the new SDK so that might be a good opportunity to try to address this.

**Comment by tylerauerbeck** [comment]
Agreed. I think some of this will be able to be handled with some of those changes/ OLM in the future.

For those that don't necessarily want to rely on OLM though, I had written a kustomize implementation that would allow folks to use the repo as a remote base and specify the namespace there. PR from old repo here: https://github.com/geerlingguy/tower-operator/pull/41/files

**Comment by mamercad** [comment]
I've had success putting everything under its own namespace (`awx` in my case):

```
❯ kubectl -n awx get clusterrole/awx-operator
NAME           CREATED AT
awx-operator   2020-12-29T15:46:34Z

❯ kubectl -n awx get clusterrolebinding/awx-operator
NAME           ROLE                       AGE
awx-operator   ClusterRole/awx-operator   15m

❯ awx ping
{
     "ha": false,
     "version": "15.0.0",
     "active_node": "awx-b68d85457-wx5m4",
     "install_uuid": "2e130d3c-b37e-4104-8a83-1cb1100d4fa3",
     "instances": [
          {
               "node": "awx-b68d85457-wx5m4",
               "uuid": "00000000-0000-0000-0000-000000000000",
               "heartbeat": "2020-12-29T16:01:37.535957Z",
               "capacity": 59,
               "version": "15.0.0"
          }
     ],
     "instance_groups": [
          {
               "name": "tower",
               "capacity": 59,
               "instances": [
                    "awx-b68d85457-wx5m4"
               ]
          }
     ]
}
```

**Comment by metabsd** [comment]
@mamercad Can you share the yaml file please :)

**Comment by mamercad** [comment]
Sure, this is what I've been WIP'ing this morning, caveat emptor: https://github.com/mamercad/do-awx-ops/blob/dev/ansible/roles/kubernetes/tasks/awx-operator.yml

**Comment by metabsd** [comment]
So in short you change default namespace with a variable. You also enforce the namespace.

**Comment by metabsd** [comment]
To be able to use kubectl the file will be like this one. `https://raw.githubusercontent.com/metabsd/awx-operator/devel/deploy/awx-operator.yaml`

I choose `tower-awx` as the namespace.

**Comment by mamercad** [comment]
Right, I manually pulled things from that manifest into my role (with the addition of my namespace directives).

**Comment by ghost** [comment]
This file only shows default as namespace.  
https://raw.githubusercontent.com/metabsd/awx-operator/devel/deploy/awx-operator.yaml

**Comment by wenottingham** [comment]
@sdmattheww You can change/override that `default` to the namespace you want to use. We do use `default` out of the box as that's a namespace that will generally exist, but you can override it as you see fit.
