### ISSUE TITLE
Error when trying to create backup using backup role and external postgres database 

### ISSUE THREAD

**Issue by Andrew920** [ansible/tower-operator#1221]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When trying to create a backup using the backup role on an external postgres database that is version 14 this error occurs: 

TASK [Write pg_dump to backup on PVC] ********************************
fatal: [localhost]: FAILED! => {"changed": true, "failed_when_result": true, "rc": 1, "return_code": 1, "stderr": "pg_dump: error: server version: 14.6; pg_dump version: 13.9 (Debian 13.9-1.pgdg110+1)\npg_dump: error: aborting because of server version mismatch\n", "stderr_lines": ["pg_dump: error: server version: 14.6; pg_dump version: 13.9 (Debian 13.9-1.pgdg110+1)", "pg_dump: error: aborting because of server version mismatch"], "stdout": "", "stdout_lines": []}

### AWX Operator version

1.1.4

### AWX version

21.11.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.24.8

### Modifications

no

### Steps to reproduce

Use external postgres database that is version 14 or newer and apply backup-awx.yaml:
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awxbackup-2023-02-06
  namespace: awx
spec:
  deployment_name: awx

The operator will show error: 
pg_dump: error: server version: 14.6; pg_dump version: 13.9

### Expected results

Backup is created.

### Actual results

The operator will create a new pod and then show error:

TASK [Write pg_dump to backup on PVC] ********************************
fatal: [localhost]: FAILED! => {"changed": true, "failed_when_result": true, "rc": 1, "return_code": 1, "stderr": "pg_dump: error: server version: 14.6; pg_dump version: 13.9 (Debian 13.9-1.pgdg110+1)\npg_dump: error: aborting because of server version mismatch\n", "stderr_lines": ["pg_dump: error: server version: 14.6; pg_dump version: 13.9 (Debian 13.9-1.pgdg110+1)", "pg_dump: error: aborting because of server version mismatch"], "stdout": "", "stdout_lines": []}

The pod will then get terminated and then this will repeat.

**Comment by fosterseth** [comment]
Hi,

we officially support postgres 13, as indicated here
https://github.com/ansible/awx-operator/blob/devel/roles/installer/defaults/main.yml#L140

and in the official docs

https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/red_hat_ansible_automation_platform_planning_guide/platform-system-requirements#red_hat_ansible_automation_platform_system_requirements

It is recommended to stay with 13 until we official support higher versions.

**Comment by Andrew920** [comment]
Thanks for the explanation, will downgrade my external database to version 13.
