### ISSUE TITLE
Helm index not update when release was created.

### ISSUE THREAD

**Issue by janorn** [ansible/tower-operator#1246]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Lates release in helm index is still 1.1.4.
https://github.com/ansible/awx-operator/blob/56afcae193ddacebdb0b8fb2ea04f4d33a3eb447/index.yaml#L4-L13

### AWX Operator version

n/a

### AWX version

n/a

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

n/a

### Modifications

no

### Steps to reproduce

-

### Expected results

Latest release in index.yaml

### Actual results

No update of index.yaml

**Comment by janorn** [comment]
Did the commit fail? @rooftopcellist

**Comment by janorn** [comment]
Can't see any obvious errors from the release action.
https://github.com/ansible/awx-operator/actions/runs/4166664596/jobs/7211282683

**Comment by JSN-1** [comment]
I am also not able to find 1.2.0.

1.1.4 is still the latest using awx-operator repo.

```
helm repo update awx-operator   
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "awx-operator" chart repository
Update Complete. ⎈Happy Helming!⎈

helm search repo awx-operator -l
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                      
awx-operator/awx-operator	1.1.4        	1.1.4      	A Helm chart for the AWX Operator
awx-operator/awx-operator	1.1.3        	1.1.3      	A Helm chart for the AWX Operator
awx-operator/awx-operator	1.1.2        	1.1.2      	A Helm chart for the AWX Operator
awx-operator/awx-operator	1.1.1        	1.1.1      	A Helm chart for the AWX Operator
awx-operator/awx-operator	1.1.0        	1.1.0      	A Helm chart for the AWX Operator
awx-operator/awx-operator	1.0.0        	1.0.0      	A Helm chart for the AWX Operator
...
etc
```

what i did to install 1.20 where to install it local from [latest release](https://github.com/ansible/awx-operator/releases/download/1.2.0/awx-operator-1.2.0.tgz)
