### ISSUE TITLE
Helm repo does not deploy operator correctly

### ISSUE THREAD

**Issue by saxx0n** [ansible/tower-operator#1271]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Deploying the helm chart for version 1.3.0 results in the system trying to pull a non-existant quay.io image.

The exact error message my k8s cluster returns is:

Failed to pull image "quay.io/ansible:1.3.0": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/ansible:1.3.0": failed to resolve reference "quay.io/ansible:1.3.0": quay.io/ansible:1.3.0: not found

### AWX Operator version

1.3.0

### AWX version

N/A

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.24.9+k3s1 

### Modifications

no

### Steps to reproduce

This deployment is being done with terraform, with the following config:

resource "helm_release" "awx-operator" {
    name       = "awx-operator"
    namespace  = "awx"
    repository = "https://ansible.github.io/awx-operator/"
    chart      = "awx-operator"
    version    = "1.3.0"
}

### Expected results

AWX Operator 1.3.0 being deployed

### Actual results

Kubernetes fails to find the correct container, referenceing ansible:1.3.0 as opposed to ansible-operator: 1.3.0:

Failed to pull image "quay.io/ansible:1.3.0": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/ansible:1.3.0": failed to resolve reference "quay.io/ansible:1.3.0": quay.io/ansible:1.3.0: not found

**Comment by danielmorillas** [comment]
Same here deploying manually the helm chart:

```
  Normal   Pulling    5s (x4 over 92s)   kubelet            Pulling image "quay.io/ansible:1.3.0"
  Warning  Failed     5s (x4 over 92s)   kubelet            Failed to pull image "quay.io/ansible:1.3.0": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/ansible:1.3.0": failed to resolve reference "quay.io/ansible:1.3.0": quay.io/ansible:1.3.0: not found
  Warning  Failed     5s (x4 over 92s)   kubelet            Error: ErrImagePull
```
  
I pulled the chart and I see that in templates/deployment-awx-operator-controller-manager.yaml in line 57 I see:
`image: quay.io/ansible:1.3.0`
and should not this be?
`image: quay.io/ansible/awx-operator:1.3.0`

Checking manually the above change, I only got deployed the awx-operator pod:

```
root@dmorillas-dev:~/dmorillas# kubectl get pods -n dev-ops-playground
NAME                                              READY   STATUS    RESTARTS   AGE
awx-operator-controller-manager-95bf94584-jkrmq   2/2     Running   0          4m51s

root@dmorillas-dev:~/dmorillas# kubectl logs awx-operator-controller-manager-95bf94584-jkrmq -n dev-ops-playground
{"level":"info","ts":1678177233.0589921,"logger":"cmd","msg":"Version","Go Version":"go1.18.9","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.26.0","commit":"cbeec475e4612e19f1047ff7014342afe93f60d2"}
{"level":"info","ts":1678177233.0593867,"logger":"cmd","msg":"Watching single namespace.","Namespace":"dev-ops-playground"}
{"level":"info","ts":1678177233.6645968,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":"127.0.0.1:8080"}
{"level":"info","ts":1678177233.665902,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_AWX_AWX_ANSIBLE_COM","default":2}
{"level":"info","ts":1678177233.6659656,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_AWXBACKUP_AWX_ANSIBLE_COM","default":2}
{"level":"info","ts":1678177233.6660295,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_AWXRESTORE_AWX_ANSIBLE_COM","default":2}
{"level":"info","ts":1678177233.6661146,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"awx.ansible.com","Options.Version":"v1beta1","Options.Kind":"AWX"}
{"level":"info","ts":1678177233.666369,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"awx.ansible.com","Options.Version":"v1beta1","Options.Kind":"AWXBackup"}
{"level":"info","ts":1678177233.6664438,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"awx.ansible.com","Options.Version":"v1beta1","Options.Kind":"AWXRestore"}
{"level":"info","ts":1678177233.6678216,"logger":"apiserver","msg":"Starting to serve metrics listener","Address":"localhost:5050"}
{"level":"info","ts":1678177233.6678095,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"info","ts":1678177233.668398,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"127.0.0.1:8080"}
I0307 08:20:33.668502       7 leaderelection.go:248] attempting to acquire leader lease dev-ops-playground/awx-operator...
{"level":"info","ts":1678177233.6690283,"msg":"Starting server","kind":"health probe","addr":"[::]:6789"}
I0307 08:20:33.686675       7 leaderelection.go:258] successfully acquired lease dev-ops-playground/awx-operator
{"level":"info","ts":1678177233.6875007,"msg":"Starting EventSource","controller":"awx-controller","source":"kind source: *unstructured.Unstructured"}
{"level":"info","ts":1678177233.6876004,"msg":"Starting Controller","controller":"awx-controller"}
{"level":"info","ts":1678177233.6890693,"msg":"Starting EventSource","controller":"awxrestore-controller","source":"kind source: *unstructured.Unstructured"}
{"level":"info","ts":1678177233.6891258,"msg":"Starting Controller","controller":"awxrestore-controller"}
{"level":"info","ts":1678177233.6901183,"msg":"Starting EventSource","controller":"awxbackup-controller","source":"kind source: *unstructured.Unstructured"}
{"level":"info","ts":1678177233.690176,"msg":"Starting Controller","controller":"awxbackup-controller"}
{"level":"info","ts":1678177233.789513,"msg":"Starting workers","controller":"awx-controller","worker count":4}
{"level":"info","ts":1678177233.7906618,"msg":"Starting workers","controller":"awxbackup-controller","worker count":4}
{"level":"info","ts":1678177233.7907026,"msg":"Starting workers","controller":"awxrestore-controller","worker count":4}


```

Any thoughts about it ?

**Comment by ksquires** [comment]
I noticed this, too.  The issue is in `awx-operator/templates/deployment-awx-operator-controller-manager.yaml` line 57

```
48           env:
 49             - name: ANSIBLE_GATHERING
 50               value: explicit
 51             - name: ANSIBLE_DEBUG_LOGS
 52               value: "false"
 53             - name: WATCH_NAMESPACE
 54               valueFrom:
 55                 fieldRef:
 56                   fieldPath: metadata.namespace
 57           image: quay.io/ansible:1.3.0 <--- this guy
```

**Comment by andriktr** [comment]
"+ 1" 
Changing it to `quay.io/ansible/awx-operator:1.3.0` fixes issue. 
Wondering why this hardcoded in template and not passed from `values.yaml`

**Comment by ksquires** [comment]
> "+ 1" Changing it to `quay.io/ansible/awx-operator:1.3.0` fixes issue. Wondering why this hardcoded in template and not passed from `values.yaml`

In all fairness, I took that code snipped from the tar.gz available in the releases.  I'm not sure where that image name is set/built in the source code as I haven't dug into it.

**Comment by danielmorillas** [comment]
> "+ 1" Changing it to `quay.io/ansible/awx-operator:1.3.0` fixes issue. Wondering why this hardcoded in template and not passed from `values.yaml`

Could you deploy awx using that image version?
I couldn't deploy it. Just only appears awx-operator pod and in the logs I see what I added in my previous message.

Just tested in different dev clusters and same issue.

**Comment by andriktr** [comment]
I will do deployment,but tomorrow. I strongly believe that your particular issue is not related to this one. This issue look like only typo in the awx-operator deployment template where awx-operator image path is wrong. IMO it's only used for operator deploymet itself. 
From your provided logs its not clear but maybe operator don't see any awx resources which defines params for your awx. So it simply does nothing.
Are you deploying from scratch or updating existing version? 
If u deploying from scratch try pull earlier chart versions.

**Comment by ftasbasi** [comment]
+1
Failed to pull image "quay.io/ansible:1.3.0"

**Comment by tanganellilore** [comment]
Probably, issue is related to this PR:
https://github.com/ansible/awx-operator/pull/1270

Release was published manually and i see a "wrong" `-e operator_image=quay.io/ansible` that should be `-e operator_image=quay.io/ansible/awx-operator`.

@rooftopcellist Can you republish 1.3.0?

**Comment by ksquires** [comment]
maybe I'm jumping the gun, but I saw 1.3.0 release was republished yesterday but the .tar.gz file for it still contains the malformed image name

from the tar.gz file:
`templates/deployment-awx-operator-controller-manager.yaml:          image: quay.io/ansible:1.3.0`

**Comment by ftasbasi** [comment]
> maybe I'm jumping the gun, but I saw 1.3.0 release was republished yesterday but the .tar.gz file for it still contains the malformed image name
> 
> from the tar.gz file: `templates/deployment-awx-operator-controller-manager.yaml: image: quay.io/ansible:1.3.0`

+1

**Comment by rooftopcellist** [comment]
Hi Folks, there was an issue with the release, when I ran the automation locally after the release to push the helm chart tar.gz I think the CHART_REPO variable must not have been set correctly.  

I can echo/confirm the findings of others above:
```
$ wget https://github.com/ansible/awx-operator/releases/download/1.3.0/awx-operator-1.3.0.tgz
$ tar xf awx-operator-1.3.0.tgz

$ cat awx-operator/templates/deployment-awx-operator-controller-manager.yaml | grep "image: quay"
          image: quay.io/ansible:1.3.0
```

I'll get this fixed up this afternoon.

**Comment by JSN-1** [comment]
seems like the tarball is missing or url is incorrect ?

helm upgrade --install -n awx --create-namespace my-awx-operator awx-operator/awx-operator --version 1.3.0
Release "my-awx-operator" does not exist. Installing it now.
Error: failed to fetch https://github.com/ansible/awx-operator/releases/download/awx-operator-1.3.0.tgz : 404 Not Found

**Comment by rooftopcellist** [comment]
Try uninstalling the helm repo, reinstalling it, then running helm repo update.

That works for me when testing locally

**Comment by saxx0n** [comment]
After your rebuild it now pulls the correct operator and deploys the correct version of AWX.  Thanks.

**Comment by rooftopcellist** [comment]
Thanks for testing it out and reporting back @saxx0n !

FYI, if anyone is still running in to this, you may need to uninstall the helm repo, reinstalling it, then running helm repo update:

```
helm uninstall my-awx-operator
helm repo remove awx-operator
helm repo add awx-operator https://ansible.github.io/awx-operator/
helm repo update
helm search repo awx-operator -l

# And if desired, install 1.3.0
helm install my-awx-operator awx-operator/awx-operator -n awx --create-namespace -f my-values.yml --version 1.3.0
```

cc @JSN-1
