### ISSUE TITLE
Egress IP

### ISSUE THREAD

**Issue by srekkas** [ansible/tower-operator#1273]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Ansible needs to connect to servers to SSH over 22 port. Most servers or networks have firewalls with whitelist ACLs.
Can AWX get egress static IP, so it can be added to whitelists?

**Comment by saxx0n** [comment]
We solved this by deploying antrea-cni. Let us set the egress to a fixed IP.

**Comment by djyasin** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information on ways to connect with us.

**Comment by srekkas** [comment]
Thanks. I got one answer. I will try if needed mailling list..

**Comment by edge-compute** [comment]
What was the fix for this? Having the same issue.

**Comment by srekkas** [comment]
> What was the fix for this? Having the same issue.

Same as above, using Antrea CNI.

**Comment by edge-compute** [comment]
@srekkas what is Antrea CNI for $200. (Jeopardy Question). Did you follow any documentation with implementing Antrea CNI? Thanks for your fast reply man lol.

**Comment by srekkas** [comment]
> @srekkas what is Antrea CNI for $200. (Jeopardy Question). Did you follow any documentation with implementing Antrea CNI? Thanks for your fast reply man lol.

What i used was free. You can use any CNI with egress ip function. Maybe yours existing CNI have same function. Because if you want tu use Antrea, you have to unonstall existing CNI first ...
Tomorow i can send some notes if you want.
