### ISSUE TITLE
Simplify Ingress Logic

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#129]
I believe for a majority of OpenShift 4.X releases, you can use an ingress object to generate a corresponding Route. So in theory, we should be able to simplify the current logic in place and then  only have to maintain a single template for creating ingress (vs. the current Route v. Ingress templates and logic that are in place now).

I guess the only question here is there a targeted version of K8S/OCP that this operator looks to target? As that would be the only note that we may want to put in place before making this change

**Comment by shanemcd** [comment]
I know that we're _not_ supporting OCP 3.x with this Operator, but don't know how far back we want to support 4.x. What's the oldest version that has this functionality?

**Comment by tylerauerbeck** [comment]
Let me dig up the docs. But from a few quick chats it's been available from some of the later 3.X releases.

**Comment by tylerauerbeck** [comment]
@shanemcd Here's the docs as far back as OCP 3.11: https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#architecture-routes-support-for-ingress . Would be happy to pull together a quick PR for this if interested.

**Comment by tchellomello** [comment]
I'm closing this one since we got https://github.com/ansible/awx-operator/pull/330 merged
