### ISSUE TITLE
Update Operator-SDK version

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#130]
Currently using v0.19.4. Currently users/maintainers need to have an old version of operator-sdk in order to follow the build instructions here (`operator-sdk build...`) as this was removed in the 1.X version of operator-sdk.

**Comment by shanemcd** [comment]
We won't be able to do this until we drop OCP 4.6 support.

**Comment by tylerauerbeck** [comment]
What's the dependence on 4.6?

**Comment by shanemcd** [comment]
This is being done in https://github.com/ansible/awx-operator/pull/569

**Comment by shanemcd** [comment]
Closing - #569 has been released in 0.14.0.
