### ISSUE TITLE
Upgrades now require manually running awx-manage migrate in terminal

### ISSUE THREAD

**Issue by trippinnik** [ansible/tower-operator#1317]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

as of last few upgrades I now need to terminal to awx-web container and execute `awx-manage migrate`

in the logs you can see waiting migrations and counters then ERROR Migrations not applied. 

### AWX Operator version

1.4.0

### AWX version

21.14.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.24

### Modifications

yes

### Steps to reproduce

update chart to use 1.4.0 from 1.3.0, deploy and wait. then ERROR

### Expected results

update chart to latest and success

### Actual results

ERROR, requires manual intervention

**Comment by fosterseth** [comment]
@trippinnik do you think this is an issue specific to helm?

**Comment by djyasin** [comment]
We are going to close this issue due to inactivity. If you are still encountering difficulty, please open a new issue and mention this one within it.

**Comment by trippinnik** [comment]
Idk what it has to do with... it's just always required. Wasn't required
before.

I think many people post issue related in awx group when new version come
out complaining web interface doesn't come up but containers created
