### ISSUE TITLE
Helm Chart index contains wrong url for version 2.0.0

### ISSUE THREAD

**Issue by GeroL** [ansible/tower-operator#1325]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The Index file [awx-operator helm chart index](https://ansible.github.io/awx-operator/index.yaml) contains an error for the newest 2.0.0 version. The release tag is missing the url

### AWX Operator version

2.0.0

### AWX version

22.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

Any

### Modifications

no

### Steps to reproduce

Try to install via Helm

### Expected results

An operator install in Kubernetes

### Actual results

helm dependency build` failed exit status 1: Error: could not download https://github.com/ansible/awx-operator/releases/download/awx-operator-2.0.0.tgz: failed to fetch https://github.com/ansible/awx-operator/releases/download/awx-operator-2.0.0.tgz : 404 Not Found

### Additional information

If you check https://ansible.github.io/awx-operator/index.yaml
you quickly will notice that the tag 2.0.0 is missing after between "download" and "awx-operator-2.0.0.tgz"

**Comment by fosterseth** [comment]
@TheRealHaoLiu did you fix this by chance?

**Comment by GeroL** [comment]
Seems fixed now

**Comment by djyasin** [comment]
@GeroL we are so happy to hear that this has been resolved for you! We are going to go ahead and close out this issue now. Should you encounter any additional difficulty please feel free to open a new issue. Thank you for your time!
