### ISSUE TITLE
Set ipv6_disabled value to true in https://github.com/ansible/awx-operator/blob/devel/config/crd/bases/awx.ansible.com_awxs.yaml

### ISSUE THREAD

**Issue by rakesh561** [ansible/tower-operator#1330]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Set ipv6_disabled value to true in https://github.com/ansible/awx-operator/blob/devel/config/crd/bases/awx.ansible.com_awxs.yaml.
I ran into this scenario where i had two instance with 0.19.0 operator i have upgraded them to 1.1.3 set the ipv6_disabled:true in my setting upgrade went fine no issues until after few days i went a head and created instance with 0.19.0 then the instance which got upgraded started crashing and reporting ngnix error.After full length research wat i found is that ipv6_disabled: true flag gets overwritten or removed  to false causing the existing instances which are upgraded to redeploy with new config map that contains ngnix trying to listen on ipv6 for this issue wat i did was i have modified ipv6_disabled: true in config/crd/bases/awx.ansible.com_awxs.yaml then ran make deploy that way ipv6_disabled: true is getting set during operator deployment and config map is created with ngnix listening on ipv4 instead of ipv6.Also if you look at present user base not many teams run ngnix awx on ipv6 so this will be much better way then setting default to ipv6.If this sounds good i will go head and modify crd of ipv6_disabled to true in config/crd/bases/awx.ansible.com_awxs.yaml.

### AWX Operator version

21.10.2

### AWX version

1.1.3

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.19

### Modifications

no

### Steps to reproduce

Create awx in two different namespaces with two different operator versions especially one which has ipv6 and then create operator instance which doesnt have ipv6 using make deploy restart the awx deployment in namespace which has ipv6 flag you will see awx-web container going down.

### Expected results

AWX-web container will report ngnix issue

### Actual results

Ngnix not supported family

### Additional information

N/A

### Operator Logs

N/A

**Comment by fosterseth** [comment]
@rooftopcellist is this the expected behavior?

**Comment by rakesh561** [comment]
@rooftopcellist @fosterseth  sorry to tag you guys directly any thoughts? It would not be bad idea to make ipv6_disabled by default we could update documentation and also in tag release mentioning about the changes
