### ISSUE TITLE
Operator 2.0.0 - Inconsistent templating to tolerations between task and web causes deployment failure

### ISSUE THREAD

**Issue by MrBones757** [ansible/tower-operator#1337]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Deploying an AWX instance with Tolerations defined (either tolerations or task_tolerations/web_tolerations) causes the operator to render an invalid Deployment Payload.

### AWX Operator version

2.0.0

### AWX version

22.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.23.x

### Modifications

no

### Steps to reproduce

Deploy an AWX instance in defining:

task_tolerations: |
    -   effect: <effect>
        key: <key>
        operator: <Operator>

web_tolerations: |
    -   effect: <effect>
        key: <key>
        operator: <Operator>
        
Will cause the web pod to deploy successfully and the task pod to fail.

### Expected results

AWX Deployment to success, and both task and web pods to be created

### Actual results

web pod is created, task pod never creates. Errors can be found in Operator Logs.

### Additional information

This seems to be caused by a difference in the web and task toleration renderings in the templates:

Task Uses to_nice_yaml and indent
https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/deployments/task.yaml.j2#L386
https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/deployments/task.yaml.j2#L389

Web uses only indent (original behaviour from previous versions)
https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/deployments/web.yaml.j2#L270
https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/deployments/web.yaml.j2#L273

I suspect the task definition needs to be made the same as web to resolve this issue, since the input from the operator is a multiline yaml string.

### Operator Logs

failed: [localhost] (item=task) => {"ansible_loop_var": "item", "changed": false, "item": "task", "msg": "Failed to apply object: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Deployment in version \\\\\\\\"v1\\\\\\\\" cannot be handled as a Deployment: json: cannot unmarshal string into Go struct field PodSpec.spec.template.spec.tolerations of type []v1.Toleration","reason":"BadRequest","code":400}\\\
'", "reason": "Bad Request"}

**Comment by RaceFPV** [comment]
Bumping with the exact same issue, awx never 'starts' as the operator errors out due to unmarshal string into go errors. For me the web doesn't even start up due to the same error as above. The way we worked around this in our helm charts is to add `{{- tpl (`tolerations') }} instead of to_nice, at least for other projects

**Comment by thedoubl3j** [comment]
@RaceFPV @MrBones757 I think we have `to_nice_yaml` laying around from some bug fixesduring development. I will attempt to repro but wanted to see if you all saw similar issues with the other parameters if you are using any of them. I will test the others and see how the templates come out but my immediate thought is to tear them all out.

**Comment by MrBones757** [comment]
@thedoubl3j I had a look though the templates and couldn't see anything obvious, so i assume this is the only occurrence, i also checked between web and task and this was the only real formatting diff i found, though, I did not have an extensive look at non-deployment resources so i may be wrong here.

**Comment by thedoubl3j** [comment]
@MrBones757 Gotcha, I will look at the diff between the deployments when they are rendered after messing with a few things and report back. should have a PR up today

**Comment by thedoubl3j** [comment]
@MrBones757 confirmed it was only tolerations that was having issues. tested affinity and it built valid yaml 
```
      affinity:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                -   matchExpressions:
                    -   key: app.kubernetes.io/name
                        operator: In
                        values:
                        - awx-task
```

will have the PR up shortly to remove to_nice_yaml from task deployment tolerations

**Comment by MrBones757** [comment]
Thanks for the updates! Will wait for the next release and have another crack at the upgrade.

**Comment by RaceFPV** [comment]
I was able to get this running by removing both tolerations AND volume mounts, just as a FYI
