### ISSUE TITLE
Failed to connect via ssh to RHEL6/CentOS 6 hosts. Complains "failed to connect to host via SSH. No matching host key found"

### ISSUE THREAD

**Issue by kkalyanp85** [ansible/tower-operator#1338]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi, 
I recently setup AWX tower using Kubernetes operator. I am running Operator version 1.4. I face the following error while trying to run any playbook on rhel6/centos 6 hosts. I get the following error "Failed to connect to the host via ssh: Unable to negotiate with <ip address> port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss", "unreachable": true}

The same playbooks work on RHEL7/RHEL8, Ubuntu 20.04, 22.04 etc. By default Host key checking is disabled on AWX so how come host key checking is happening for RHEL6/Centos6 hosts alone?? I have tried creating inventory file on GITHUB, importing it as a source in AWX inventory and passed variables to disable strict host checking yet AWX ignores it and continues to error out for RHEL 6 hosts only. 

Kindly look into this as it occurs to me that this is surely a bug. If this were a generic problem, even RHEL7 & RHEL8 hosts should have been impacted as well. PFA the screenshot for your reference
<img width="743" alt="Screenshot_1" src="https://user-images.githubusercontent.com/125262544/230331998-817bdb4b-1bc0-483f-8a2a-ec20919446db.png">

### AWX Operator version

1.4.0

### AWX version

21.14

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.26.3

### Modifications

no

### Steps to reproduce

Add a RHEL6 or CentOS 6 test node and try running a simple ping test playbook using machine credentials with privilege escalation enabled

### Expected results

Ideally ping test should be successful with following result,
**ok: [ip_address] => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "ping": "pong"}**

<img width="648" alt="Screenshot_2" src="https://user-images.githubusercontent.com/125262544/230332273-3a9bb3ef-d0ee-414b-848a-1990322b37b2.png">

### Actual results

 I get the following error "Failed to connect to the host via ssh: Unable to negotiate with <ip address> port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss", "unreachable": true}

This happens when running any playbook on AWX Tower especially against hosts which are RHEL 6 or CentOS 6
<img width="743" alt="Screenshot_1" src="https://user-images.githubusercontent.com/125262544/230331868-34f4f3c0-5463-41c6-98e8-f40e85d3bae8.png">

**Comment by relrod** [comment]
Hi :)

> Kindly look into this as it occurs to me that this is surely a bug.

But, it's not ;)

And especially, it's not an awx-operator bug. If anything, you could make an argument for it being an awx-ee bug. But I argue it's not that, either :).

Our upstream execution environment image is based on CentOS Stream 9. In EL9, SHA-1 is not enabled by default. And in `awx-ee` it is a conscious decision to not override this, as SHA-1 is considered legacy. 

You can solve this in a few ways:

- You can switch to an execution environment that was built before we switched to Stream 9.
- You can re-generate the RHEL 6 host key with ECDSA instead of the legacy sha1-rsa
- You can create a custom EE that adds the legacy SHA1 on top of the default crypto policy (see the `update-crypto-policies` command)
- You can switch the systems to use the "LEGACY" policy.

I hope this helps. If you need more support on this matter, please reach out to the community on the AWX mailing list or the AWX matrix chat.

**Comment by peacengell** [comment]
Hello,

Hope this helps

I solved mine using this awx-ee version

quay.io/ansible/awx-ee:21.11.0

Thank you

**Comment by todayislegday** [comment]
> Hi :)
> 
> > Kindly look into this as it occurs to me that this is surely a bug.
> 
> But, it's not ;)
> 
> And especially, it's not an awx-operator bug. If anything, you could make an argument for it being an awx-ee bug. But I argue it's not that, either :).
> 
> Our upstream execution environment image is based on CentOS Stream 9. In EL9, SHA-1 is not enabled by default. And in `awx-ee` it is a conscious decision to not override this, as SHA-1 is considered legacy.
> 
> You can solve this in a few ways:
> 
> * You can switch to an execution environment that was built before we switched to Stream 9.
> * You can re-generate the RHEL 6 host key with ECDSA instead of the legacy sha1-rsa
> * You can create a custom EE that adds the legacy SHA1 on top of the default crypto policy (see the `update-crypto-policies` command)
> * You can switch the systems to use the "LEGACY" policy.
> 
> I hope this helps. If you need more support on this matter, please reach out to the community on the AWX mailing list or the AWX matrix chat.

Hello,  I solved it too !!! using this awx-ee version  'quay.io/ansible/awx-ee:21.11.0' THX
