### ISSUE TITLE
Molecule Tests

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#134]
Is anybody else having issues running the molecule tests? When trying to run them against the devel branch, I seem to get stuck on waiting for the CR to get created (which looks to be because the operator pod gets stuck in a crashloopbackoff because the liveness probe is failing). Trying to figure out if this is a user issue or if others are seeing this as well.

**Comment by tylerauerbeck** [comment]
Hmm. Not quite sure exactly the issue here, but looks like it has something to do with ubuntu 18.04 -> ubuntu 20.04 (was running into this while testing something out in github actions and they recently just finished flipping ubuntu-latest between those two versions)

**Comment by shanemcd** [comment]
You might be encountering https://github.com/bsycorp/kind/issues/44

**Comment by tchellomello** [comment]
Closing this as tests are passing on devel.
