### ISSUE TITLE
Create mkdocs scaffolding to build the docs locally

### ISSUE THREAD

**Issue by samccann** [ansible/tower-operator#1359]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Based on[ MkDocs](https://www.mkdocs.org/getting-started/), create the scaffolding required to build the docs locally.

Use https://github.com/ansible/ansible-navigator/blob/main/mkdocs.yml as an example of how to do this.

NOTE - we may not need everything in that example but it's a good working project to learn from

**Comment by samccann** [comment]
@BhattacharjeeSutapa will take this task on. Sorry, I don't have the ability to 'assign' people to issues here.

**Comment by BhattacharjeeSutapa** [comment]
Hi @samccann , I have created a new branch and tested out my work there. 
I am able to run the site locally with `mkdocs serve`  but I am getting the following error: 

```
WARNING  -  A relative path to 'index.md' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  Documentation file 'build_awx_image.md' contains a link to '../INSTALL.md' which is not found in the documentation files.
WARNING  -  Documentation file 'release_process.md' contains a link to '../.github/triage_replies.md' which is not found in the documentation files.

```

Do you happen to know or point me to a direction where I can get this sorted? I will push my work in the branch I created.

EDIT

* I cannot push to the repository because of an access problem.

```
$ git push origin mkdocs-scaffolding 
ERROR: Permission to ansible/awx.git denied to BhattacharjeeSutapa.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

EDIT x2

Forget the push error, I should have forked it.

**Comment by oraNod** [comment]
@BhattacharjeeSutapa Hi, just to be sure it doesn't get lost but I created PR for your branch here: https://github.com/BhattacharjeeSutapa/awx-operator/pull/1
