### ISSUE TITLE
Split Readme up into multiple files

### ISSUE THREAD

**Issue by samccann** [ansible/tower-operator#1360]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

In preparation for creating a docsite, split up the existing readme into multiple smaller files in the /docs folder.

- [x] draft out a proposal for how to split the file up. Use a comment in this github issue to describe the proposed set of new files.
- [x] Once the writers agree, move that information into the agreed list of files.
- [x] Leave everything from Contributing section to the end of the README file in the README file.
- [x] Leave everything BEFORE the Table of contents in the README file.
- [ ] Add the new files to the mkdocs.yml and test the docs build

**Comment by samccann** [comment]
@desmondsanctity will start this by creating a proposal on how to breakdown the readme file.

**Comment by DesmondSanctity** [comment]
# Docs Breakdown for AWX Operator

## Introduction

This table below is aimed at breaking down the ReadME documentation for Ansible AWX Operator and structure it in the way it can be moved to the Read The Docs module.

From the ReadMe file, the documentation can be classified into six distinct segments which are:


- Introduction/Getting Started
- Installation
- User Guide
- Upgrade
- Uninstall
- Contributors Guide

Using these listed segments, we can do a proper breakdown of all the topics in the ReadMe and place each one in the segment they fall into. This table is open to any form of refactoring or modifications.

| Segments           | Topics                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Introduction       | - [Purpose](https://github.com/ansible/awx-operator#purpose)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Installation       | - [Creating a minikube cluster for testing](https://github.com/ansible/awx-operator#creating-a-minikube-cluster-for-testing)<br>- [Basic Install](https://github.com/ansible/awx-operator#basic-install)<br>- [Helm Install on existing cluster](https://github.com/ansible/awx-operator#helm-install-on-existing-cluster)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| User Guide     | - [Admin user account configuration](https://github.com/ansible/awx-operator#admin-user-account-configuration)<br>- [Network and TLS Configuration](https://github.com/ansible/awx-operator#network-and-tls-configuration)<br>    * [Service Type](https://github.com/ansible/awx-operator#service-type)<br>    * [Ingress Type](https://github.com/ansible/awx-operator#ingress-type)<br>- [Database Configuration](https://github.com/ansible/awx-operator#database-configuration)<br>    * [External PostgreSQL Service](https://github.com/ansible/awx-operator#external-postgresql-service)<br>    * [Migrating data from an old AWX instance](https://github.com/ansible/awx-operator#migrating-data-from-an-old-awx-instance)<br>    * [Managed PostgreSQL Service](https://github.com/ansible/awx-operator#managed-postgresql-service)<br>- [Advanced Configuration](https://github.com/ansible/awx-operator#advanced-configuration)<br>    * [Deploying a specific version of AWX](https://github.com/ansible/awx-operator#deploying-a-specific-version-of-awx)<br>    * [Redis container capabilities](https://github.com/ansible/awx-operator#redis-container-capabilities)<br>    * [Privileged Tasks](https://github.com/ansible/awx-operator#privileged-tasks)<br>    * [Containers Resource Requirements](https://github.com/ansible/awx-operator#containers-resource-requirements)<br>    * [Priority Classes](https://github.com/ansible/awx-operator#priority-classes)<br>    * [Assigning AWX pods to specific nodes](https://github.com/ansible/awx-operator#assigning-awx-pods-to-specific-nodes)<br>    * [Trusting a Custom Certificate Authority](https://github.com/ansible/awx-operator#trusting-a-custom-certificate-authority)<br>    * [Enabling LDAP Integration at AWX bootstrap](https://github.com/ansible/awx-operator#enabling-ldap-integration-at-awx-bootstrap)<br>    * [Persisting Projects Directory](https://github.com/ansible/awx-operator#persisting-projects-directory)<br>    * [Custom Volume and Volume Mount Options](https://github.com/ansible/awx-operator#custom-volume-and-volume-mount-options)<br>    * [Default execution environments from private registries](https://github.com/ansible/awx-operator#default-execution-environments-from-private-registries)<br>        * * [Control plane ee from private registry](https://github.com/ansible/awx-operator#control-plane-ee-from-private-registry)<br>    * [Exporting Environment Variables to Containers](https://github.com/ansible/awx-operator#exporting-environment-variables-to-containers)<br>    * [CSRF Cookie Secure Setting](https://github.com/ansible/awx-operator#csrf-cookie-secure-setting)<br>    * [Session Cookie Secure Setting](https://github.com/ansible/awx-operator#session-cookie-secure-setting)<br>    * [Extra Settings](https://github.com/ansible/awx-operator#extra-settings)<br>    * [Configure no_log](https://github.com/ansible/awx-operator#no-log)<br>    * [Auto Upgrade](https://github.com/ansible/awx-operator#auto-upgrade)<br>        ** [Upgrade of instances without auto upgrade](https://github.com/ansible/awx-operator#upgrade-of-instances-without-auto-upgrade)<br>    * [Service Account](https://github.com/ansible/awx-operator#service-account)<br>    * [Labeling operator managed objects](https://github.com/ansible/awx-operator#labeling-operator-managed-objects)<br>    * [Pods termination grace period](https://github.com/ansible/awx-operator#pods-termination-grace-period)<br>    * [Disable IPV6](https://github.com/ansible/awx-operator#disable-ipv6)<br>    * [Add Execution Nodes](https://github.com/ansible/awx-operator#adding-execution-nodes)<br>        ** [Custom Receptor CA](https://github.com/ansible/awx-operator#custom-receptor-ca)<br>    * [Debugging](https://github.com/ansible/awx-operator/blob/devel/docs/debugging.md)<br>    * [Migration](https://github.com/ansible/awx-operator/blob/devel/docs/migration.md) |
| Upgrade            | - [Upgrading](https://github.com/ansible/awx-operator#upgrading)<br>    * [Backup](https://github.com/ansible/awx-operator#backup)<br>    * [v0.14.0](https://github.com/ansible/awx-operator#v0140)<br>        ** [Cluster-scope to Namespace-scope considerations](https://github.com/ansible/awx-operator#cluster-scope-to-namespace-scope-considerations)<br>        ** [Project is now based on v1.x of the operator-sdk project](https://github.com/ansible/awx-operator#project-is-now-based-on-v1x-of-the-operator-sdk-project)<br>        ** [Steps to upgrade](https://github.com/ansible/awx-operator#steps-to-upgrade)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| Uninstall          | - [Uninstall](https://github.com/ansible/awx-operator#uninstall)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| Contributors Guide | - [Contributing](https://github.com/ansible/awx-operator#contributing)<br>- [Release Process](https://github.com/ansible/awx-operator#release-process)<br>- [Author](https://github.com/ansible/awx-operator#author)<br>- [Code of Conduct](https://github.com/ansible/awx-operator#code-of-conduct)<br>- [Get Involved](https://github.com/ansible/awx-operator#get-involved)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |


Note: I could not get the multi-level bullet point list to work in the table so I used single asterisk `*` for one level down and double asterisk `**` for two level down.

**Comment by DesmondSanctity** [comment]
> # Docs Breakdown for AWX Operator
> ## Introduction
> This table below is aimed at breaking down the ReadME documentation for Ansible AWX Operator and structure it in the way it can be moved to the Read The Docs module.
> 
> From the ReadMe file, the documentation can be classified into six distinct segments which are:
> 
> * Introduction/Getting Started
> * Installation
> * Configurations
> * Upgrade
> * Uninstall
> * Contributions Guides
> 
> Using these listed segments, we can do a proper breakdown of all the topics in the ReadMe and place each one in the segment they fall into. This table is open to any form of refactoring or modifications.
> 
> Segments	Topics
> Introduction	- [Purpose](https://github.com/ansible/awx-operator#purpose)
> Installation	- [Creating a minikube cluster for testing](https://github.com/ansible/awx-operator#creating-a-minikube-cluster-for-testing)
> - [Basic Install](https://github.com/ansible/awx-operator#basic-install)
> - [Helm Install on existing cluster](https://github.com/ansible/awx-operator#helm-install-on-existing-cluster)
> Configurations	- [Admin user account configuration](https://github.com/ansible/awx-operator#admin-user-account-configuration)
> - [Network and TLS Configuration](https://github.com/ansible/awx-operator#network-and-tls-configuration)
> * [Service Type](https://github.com/ansible/awx-operator#service-type)
> * [Ingress Type](https://github.com/ansible/awx-operator#ingress-type)
> - [Database Configuration](https://github.com/ansible/awx-operator#database-configuration)
> * [External PostgreSQL Service](https://github.com/ansible/awx-operator#external-postgresql-service)
> * [Migrating data from an old AWX instance](https://github.com/ansible/awx-operator#migrating-data-from-an-old-awx-instance)
> * [Managed PostgreSQL Service](https://github.com/ansible/awx-operator#managed-postgresql-service)
> - [Advanced Configuration](https://github.com/ansible/awx-operator#advanced-configuration)
> * [Deploying a specific version of AWX](https://github.com/ansible/awx-operator#deploying-a-specific-version-of-awx)
> - [Redis container capabilities](https://github.com/ansible/awx-operator#redis-container-capabilities)
> * [Privileged Tasks](https://github.com/ansible/awx-operator#privileged-tasks)
> * [Containers Resource Requirements](https://github.com/ansible/awx-operator#containers-resource-requirements)
> * [Priority Classes](https://github.com/ansible/awx-operator#priority-classes)
> * [Assigning AWX pods to specific nodes](https://github.com/ansible/awx-operator#assigning-awx-pods-to-specific-nodes)
> * [Trusting a Custom Certificate Authority](https://github.com/ansible/awx-operator#trusting-a-custom-certificate-authority)
> * [Enabling LDAP Integration at AWX bootstrap](https://github.com/ansible/awx-operator#enabling-ldap-integration-at-awx-bootstrap)
> * [Persisting Projects Directory](https://github.com/ansible/awx-operator#persisting-projects-directory)
> * [Custom Volume and Volume Mount Options](https://github.com/ansible/awx-operator#custom-volume-and-volume-mount-options)
> * [Default execution environments from private registries](https://github.com/ansible/awx-operator#default-execution-environments-from-private-registries)
> * * [Control plane ee from private registry](https://github.com/ansible/awx-operator#control-plane-ee-from-private-registry)
> * [Exporting Environment Variables to Containers](https://github.com/ansible/awx-operator#exporting-environment-variables-to-containers)
> * [CSRF Cookie Secure Setting](https://github.com/ansible/awx-operator#csrf-cookie-secure-setting)
> * [Session Cookie Secure Setting](https://github.com/ansible/awx-operator#session-cookie-secure-setting)
> * [Extra Settings](https://github.com/ansible/awx-operator#extra-settings)
> * [Configure no_log](https://github.com/ansible/awx-operator#no-log)
> * [Auto Upgrade](https://github.com/ansible/awx-operator#auto-upgrade)
> ** [Upgrade of instances without auto upgrade](https://github.com/ansible/awx-operator#upgrade-of-instances-without-auto-upgrade)
> * [Service Account](https://github.com/ansible/awx-operator#service-account)
> * [Labeling operator managed objects](https://github.com/ansible/awx-operator#labeling-operator-managed-objects)
> * [Pods termination grace period](https://github.com/ansible/awx-operator#pods-termination-grace-period)
> * [Disable IPV6](https://github.com/ansible/awx-operator#disable-ipv6)
> * [Add Execution Nodes](https://github.com/ansible/awx-operator#adding-execution-nodes)
> ** [Custom Receptor CA](https://github.com/ansible/awx-operator#custom-receptor-ca)
> Upgrade	- [Upgrading](https://github.com/ansible/awx-operator#upgrading)
> * [Backup](https://github.com/ansible/awx-operator#backup)
> * [v0.14.0](https://github.com/ansible/awx-operator#v0140)
> ** [Cluster-scope to Namespace-scope considerations](https://github.com/ansible/awx-operator#cluster-scope-to-namespace-scope-considerations)
> ** [Project is now based on v1.x of the operator-sdk project](https://github.com/ansible/awx-operator#project-is-now-based-on-v1x-of-the-operator-sdk-project)
> ** [Steps to upgrade](https://github.com/ansible/awx-operator#steps-to-upgrade)
> Uninstall	- [Uninstall](https://github.com/ansible/awx-operator#uninstall)
> Contibutions Guide	- [Contributing](https://github.com/ansible/awx-operator#contributing)
> - [Release Process](https://github.com/ansible/awx-operator#release-process)
> - [Author](https://github.com/ansible/awx-operator#author)
> - [Code of Conduct](https://github.com/ansible/awx-operator#code-of-conduct)
> - [Get Involved](https://github.com/ansible/awx-operator#get-involved)
> Note: I could not get the multi-level bullet point list to work in the table so I used single asterisk `*` for one level down and double askterisk `**` for two level down.

@samccann kindly review and drop feedbacks. Thanks

**Comment by DesmondSanctity** [comment]
@samccann I have prepared the breakdown. Please do review and drop feedbacks. Thanks

**Comment by samccann** [comment]
Looks like a good breakdown @DesmondSanctity . I couple of comments:
- change Configurations to User Guide
- Change Contributions Guide to Contributors Guide

Also can you look at the existing /docs folder? I noticed it has two files that need to be added to the table/proposed structure.  Thanks!

**Comment by DesmondSanctity** [comment]
Alright I'll check and effect possible changes

**Comment by DesmondSanctity** [comment]
> Looks like a good breakdown @DesmondSanctity . I couple of comments:
> 
> * change Configurations to User Guide
> * Change Contributions Guide to Contributors Guide
> 
> Also can you look at the existing /docs folder? I noticed it has two files that need to be added to the table/proposed structure. Thanks!

@samccann These suggestions are now updated in the table. Thanks

**Comment by rooftopcellist** [comment]
The migration guide might warrant another section.  It might make sense to have backup and restore as separate guides/sections as well, then link to those from the upgrade guide.  

I could be swayed either way on that, that is refactoring we could easily change after the first iteration.

**Comment by samccann** [comment]
@DesmondSanctity - looking good. I'd suggest creating that PR to match this outline. We can make adjustments when we see it all in action so to speak. Thanks!

**Comment by DesmondSanctity** [comment]
> @DesmondSanctity - looking good. I'd suggest creating that PR to match this outline. We can make adjustments when we see it all in action so to speak. Thanks!

@samccann  I have attached the PR as suggested.

**Comment by samccann** [comment]
Thanks @DesmondSanctity - I'll be off work for the next few weeks so there will be a delay on getting back to this. Sorry about that but thanks for the PR!

**Comment by DesmondSanctity** [comment]
> Thanks @DesmondSanctity - I'll be off work for the next few weeks so there will be a delay on getting back to this. Sorry about that but thanks for the PR! 

It's totally fine. Have a nice week ahead!

**Comment by rooftopcellist** [comment]
I'll merge the docs proposal PR so we have that as a guide as we break out each part of the README.md to different linked files.  I assume that will be in a follow-up PR (s).

**Comment by rooftopcellist** [comment]
This got auto-closed when the linked PR merged.  We still want this issue open to track the other items in the checklist afaik.  So I re-opened the issue.

**Comment by samccann** [comment]
Hi folks - coming back to this. Now that we have a defined outline, the next steps are to create all those individual md files to match the proposed outline. @DesmondSanctity are you up for that next step?

My recommendation on how to proceed:
1 - use one PR per 'segment' in the table above. 
2 - name the .md after the segment name (introduction.md  for example)
3. In the PR, remove the topics from the README file to the new .md file in the /docs folder
4. Update the mkdocs details (coming soon) to add the new file and test the mkdocs locally.

I'm working on getting https://github.com/ansible/awx-operator/pull/1363/ tested locally and then merged. That is required before step 4 above.

**Comment by DesmondSanctity** [comment]
> Hi folks - coming back to this. Now that we have a defined outline, the next steps are to create all those individual md files to match the proposed outline. @DesmondSanctity are you up for that next step?
> 
> My recommendation on how to proceed:
> 1 - use one PR per 'segment' in the table above. 
> 2 - name the .md after the segment name (introduction.md  for example)
> 3. In the PR, remove the topics from the README file to the new .md file in the /docs folder
> 4. Update the mkdocs details (coming soon) to add the new file and test the mkdocs locally.
> 
> I'm working on getting https://github.com/ansible/awx-operator/pull/1363/ tested locally and then merged. That is required before step 4 above.
> 
> 

Yes I'm ready. So we should wait till the MKDocs is ready or we can start 1-3?

**Comment by samccann** [comment]
go ahead and start 1-3 please and thanks!

**Comment by samccann** [comment]
@DesmondSanctity - the mkdocs scaffolding PR just got merged. How's it going with splitting up the readme into separate files? We can do this one section per PR if that helps so multiple people can help out here.

**Comment by DesmondSanctity** [comment]
> @DesmondSanctity - the mkdocs scaffolding PR just got merged. How's it going with splitting up the readme into separate files? We can do this one section per PR if that helps so multiple people can help out here.

@samccann  Hello! I will send this information to the discord and see if others will be available to work on it together. I am trying to get some work off my table and begin working on the docs by Friday. Tell me if that works. Thanks

**Comment by samccann** [comment]
Sounds good to me. We can get volunteers from there for sure but we want to coordinate the work in the open here in the issue so others outside of discord have a chance to help too.

**Comment by DesmondSanctity** [comment]
@samccann I have started working on moving the docs. I also sent a message to the discord community, hopefully others will join to make it faster.

**Comment by LuluNwenyi** [comment]
Hi @DesmondSanctity I would like to contribute to this.

**Comment by DesmondSanctity** [comment]
> Hi @DesmondSanctity I would like to contribute to this.
> 

Hello @LuluNwenyi , glad you want to contribute. Of you followed the conversation here, we've gone from breaking down the ReadMe files to sections and currently moving them to the docs folder.

My recommendation on how to proceed:
1 - use one PR per 'segment' in the table above.
2 - name the .md after the segment name (introduction.md for example). Also create a folder with the segment name and all the md files for that segment will be in that folder. (Check my PRs for guidance).
3. In the PR, remove the topics from the README file to the new .md file in the /docs folder.

I also see you're in the discord community. If you need clarification, message me and we can do a small meeting to put you through.

**Comment by LuluNwenyi** [comment]
HI @DesmondSanctity, I've gotten started on this, and I have a question. Would each subtopic under a topic have its own .md file? For instance, **advanced configuration**...

**Comment by DesmondSanctity** [comment]
Hello @LuluNwenyi

So firstly, you should follow the breakdown above and not the one on the Table of Content in the ReadMe file.

Secondly, Topics with other subtopics within them can stay in one .md files. For Advanced Configuration, we can create a folder named advanced-configuration and add the subtopics as different .md files since it has many subtopics and will be long for a one paged documentation.

Network and TLS Configuration & Database Configuration can stay in one file.

**Comment by DesmondSanctity** [comment]
> Hi folks - coming back to this. Now that we have a defined outline, the next steps are to create all those individual md files to match the proposed outline. @DesmondSanctity are you up for that next step?
> 
> My recommendation on how to proceed: 1 - use one PR per 'segment' in the table above. 2 - name the .md after the segment name (introduction.md for example) 3. In the PR, remove the topics from the README file to the new .md file in the /docs folder 4. Update the mkdocs details (coming soon) to add the new file and test the mkdocs locally.
> 
> I'm working on getting #1363 tested locally and then merged. That is required before step 4 above.

@samccann I and @LuluNwenyi have moved the docs to their respective files in the `docs` folder. You can also view the PRs as referenced and tell us what you think.
