### ISSUE TITLE
White page instead of main page: "You need to enable JavaScript to run this app."

### ISSUE THREAD

**Issue by johanneskastl** [ansible/tower-operator#1361]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I can finally reach the AWX page (see #1336), but all I get is a white page that contains some Javascript). The page source contains a warning that Javascript should be enabled. Which is already is...

```
<!doctype html><html lang="en"><head><script nonce="39beifsJBugBdC/O5E/porlYXNm298hEZTbPHBR8TnM=" type="text/javascript">window.NONCE_ID="39beifsJBugBdC/O5E/porlYXNm298hEZTbPHBR8TnM="</script><meta http-equiv="Content-Security-Policy" content="default-src 'self'; connect-src 'self' ws: wss:; style-src 'self' 'unsafe-inline'; script-src 'self' 'nonce-39beifsJBugBdC/O5E/porlYXNm298hEZTbPHBR8TnM=' *.pendo.io; img-src 'self' *.pendo.io data:; worker-src 'self' blob: ;"/><link rel="shortcut icon" href="[/static/media/favicon.ico](view-source:https://<redacted>/static/media/favicon.ico)"/><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="AWX"/><script defer="defer" src="[./static/js/main.dcd934c7.js](view-source:https://<redacted>/static/js/main.dcd934c7.js)"></script><link href="[./static/css/main.e706ca3d.css](view-source:https://<redacted>/static/css/main.e706ca3d.css)" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><style nonce="39beifsJBugBdC/O5E/porlYXNm298hEZTbPHBR8TnM=">.app{height:100%}</style><div id="app" class="app"></div></body></html>
```

### AWX Operator version

2.0.0

### AWX version

22.0.0

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

v1.26.3+k3s1

### Modifications

no

### Steps to reproduce

1.  Install awx-operator using helm
2.  Create CRD for AWX
3.  Wait until pods are "running"
4.  Try to connect

### Expected results

A working main page showing the login.

### Actual results

White page, only some javascript things in the page's source.

The web container's logs only show successful connections:

```
10.0.0.140 - - [17/Apr/2023:06:49:42 +0000] "GET / HTTP/1.1" 200 1044 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" "10.0.0.78"
[pid: 36|app: 0|req: 2/6] 10.0.0.140 () {62 vars in 970 bytes} [Mon Apr 17 06:49:42 2023] GET / => generated 1044 bytes in 52 msecs (HTTP/1.1 200) 7 headers in 269 bytes (1 switches on core 0)
10.0.0.140 - - [17/Apr/2023:06:49:42 +0000] "GET /static/css/main.e706ca3d.css HTTP/1.1" 200 1043127 "https://<redacted>/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" "10.0.0.78"
10.0.0.140 - - [17/Apr/2023:06:49:42 +0000] "GET /static/js/main.dcd934c7.js HTTP/1.1" 200 3453824 "https://<redacted>/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" "10.0.0.78"
10.0.0.140 - - [17/Apr/2023:06:49:43 +0000] "GET /static/media/default.strings.json HTTP/1.1" 200 53 "https://<redacted>/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" "10.0.0.78"
10.0.0.140 - - [17/Apr/2023:06:49:43 +0000] "GET /static/media/favicon.ico HTTP/1.1" 200 4286 "https://<redacted>/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" "10.0.0.78"
```

**Comment by johanneskastl** [comment]
I already tried some of the workarounds from https://github.com/ansible/awx-operator/issues/474, but none helped...

**Comment by AlePini** [comment]
If your browser language is set to something different than English, it's probably related to https://github.com/ansible/awx/issues/13756

Should be fixed for next release, for now just append `?lang=en` at the end of the AWX url

**Comment by johanneskastl** [comment]
> `?lang=en`

Thanks, that did the trick.
