### ISSUE TITLE
Add ability to specify Tower license as part of deployment

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#14]
Right now, the operator spins up Tower but still has a manual process to supply an appropriate license. It would be great to be able to be able to declaratively supply the license via the existing CR or additional CR's with this operator.

This could then be a good model for other awx/tower components to be supplied declaratively as part of your deployment (inventories, credentials, etc.)

**Comment by shanemcd** [comment]
This will come with a downstream operator sometime next year. Not going to track this upstream.
