### ISSUE TITLE
Is PostgreSQL v14 supported?

### ISSUE THREAD

**Issue by samweisgamdschie** [ansible/tower-operator#1404]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hi!

We searched for information about Support of awx and awx-operator for PostgreSQL v14.*, but did not found anything, except https://github.com/keycloak/keycloak/issues/10767 and https://github.com/ansible/awx-operator/commit/fde4a47a1404ac3f63d5ff60f306c14f4eb5f27c

I am talking about an external DB (not managed by awx-operator), which we configure with `postgres_configuration_secret`.

Many thanks in advance

**Comment by djyasin** [comment]
Hello @samweisgamdschie,
At this time that is not supported. Someone in the community may have some tips about this, so we would suggest asking about this on our mailing list. See https://github.com/ansible/awx/#get-involved for information regarding that. 

Thank you for your time!
