### ISSUE TITLE
awx-task and awx-web pod restarting continuously

### ISSUE THREAD

**Issue by vshete93** [ansible/tower-operator#1431]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I see below pods running after installing with awx-operator. But awx-task and awx-web are restarting every 10 min or so.

```
kubectl -n awx get pod
NAME                                                       READY   STATUS    RESTARTS         AGE
awx-operator-controller-manager-xx    2/2           Running       0                4h7m
awx-postgres-13-0                                  1/1        Running             0                3h1m
awx-task-xxx                                            4/4     Running        20 (9m55s ago)   136m
awx-web-xxx                                            3/3     Running   28 (5m32s ago)   178m
```

### AWX Operator version

2.0.1

### AWX version

22.2.0

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

EKS

### Modifications

yes

### Steps to reproduce

installing awx-operator and awx tower in EKS environment on the internal network. I am using awx-ee and awx images from internal registry with permissions modified to 0644 for /etc/passwd and /etc/group files. There is no workaround for this as thats the standard.

### Expected results

awx-task and awx-web pods running without any restarts

### Actual results

1. For **awx-task** pod **redis** and **awx-ee** containers are in running state. However containers (**init**-using awx-ee image is in **Terminated** state), **awx-task** and **awx-rsyslog** shows below errors
```

/usr/bin/launch_awx_task.sh: line 4: /etc/passwd: Permission denied
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1 of 30
[wait-for-migrations] Waiting 0.5 seconds before next attempt
[wait-for-migrations] Attempt 2 of 30
[wait-for-migrations] Waiting 1 seconds before next attempt
[wait-for-migrations] Attempt 3 of 30
[wait-for-migrations] Waiting 2 seconds before next attempt
```

```
/usr/bin/launch_awx_rsyslog.sh: line 4: /etc/passwd: Permission denied
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1 of 30
[wait-for-migrations] Waiting 0.5 seconds before next attempt
[wait-for-migrations] Attempt 2 of 30
[wait-for-migrations] Waiting 1 seconds before next attempt
[wait-for-migrations] Attempt 3 of 30
[wait-for-migrations] Waiting 2 seconds before next attempt
```

2. For **awx-web** pod redis container is in running state. However containers **awx-web** and **awx-rsyslog** containers are in similar state as above.

**Comment by vshete93** [comment]
found this for the older version: https://github.com/ansible/awx/issues/7545. But doenst seem to be the case for the version I am using.

**Comment by fosterseth** [comment]
can you provide the yml spec file that you used to deploy awx?

**Comment by vshete93** [comment]
thanks @fosterseth for your reply. Please find my spec file attached.
[AWX_spec_file.yaml.zip](https://github.com/ansible/awx-operator/files/11576313/AWX_spec_file.yaml.zip)

**Comment by fosterseth** [comment]
I see this error
`/usr/bin/launch_awx_task.sh: line 4: /etc/passwd: Permission denied`

are you using the official awx image or did you build a custom one?

the dockerfile to build the official image has this line to modify the permissions of /etc/passwd

https://github.com/fosterseth/awx/blob/ee7b3470da25058cef69af329dc06c7a65e75edb/tools/ansible/roles/dockerfile/templates/Dockerfile.j2#L257

it should look like this
```
(awx) ls -la /etc/passwd
-rw-rw-r--. 1 root root 40 May 26 04:09 /etc/passwd
```

**Comment by vshete93** [comment]
@fosterseth thanks for your reply. I am building my own image. But all I had to change is permissions to 0644 for `/etc/passwd` and `/etc/group `files. This is because of an internal network requirement to publish images to internal registry. Is above must to get this to work? or any other option to make it work?

**Comment by vshete93** [comment]
Also would like to understand why does awx needs access to those files with 755 permissions?

**Comment by fosterseth** [comment]
> Also would like to understand why does awx needs access to those files with 755 permissions?

I don't think the dockerfile is setting those to 755 (they don't have execute flag enabled)

/etc/passwd needs 0664 (group write permissions) due to this launch script https://github.com/fosterseth/awx/blob/b128f05a37bf165f6b5dbe08a9123ca3ded50b18/tools/ansible/roles/dockerfile/files/launch_awx_task.sh#L4

so I don't think 0644 would work

**Comment by vshete93** [comment]
Looks like opening up the permissions to allow root to execute things works. So this ticket can be closed.

**Comment by phanimullapudi** [comment]
> ### Please confirm the following
> * [x]  I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
> * [x]  I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
> * [x]  I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.
> 
> ### Bug Summary
> I see below pods running after installing with awx-operator. But awx-task and awx-web are restarting every 10 min or so.
> 
> ```
> kubectl -n awx get pod
> NAME                                                       READY   STATUS    RESTARTS         AGE
> awx-operator-controller-manager-xx    2/2           Running       0                4h7m
> awx-postgres-13-0                                  1/1        Running             0                3h1m
> awx-task-xxx                                            4/4     Running        20 (9m55s ago)   136m
> awx-web-xxx                                            3/3     Running   28 (5m32s ago)   178m
> ```
> 
> ### AWX Operator version
> 2.0.1
> 
> ### AWX version
> 22.2.0
> 
> ### Kubernetes platform
> other (please specify in additional information)
> 
> ### Kubernetes/Platform version
> EKS
> 
> ### Modifications
> yes
> 
> ### Steps to reproduce
> installing awx-operator and awx tower in EKS environment on the internal network. I am using awx-ee and awx images from internal registry with permissions modified to 0644 for /etc/passwd and /etc/group files. There is no workaround for this as thats the standard.
> 
> ### Expected results
> awx-task and awx-web pods running without any restarts
> 
> ### Actual results
> 1. For **awx-task** pod **redis** and **awx-ee** containers are in running state. However containers (**init**-using awx-ee image is in **Terminated** state), **awx-task** and **awx-rsyslog** shows below errors
> 
> ```
> 
> /usr/bin/launch_awx_task.sh: line 4: /etc/passwd: Permission denied
> [wait-for-migrations] Waiting for database migrations...
> [wait-for-migrations] Attempt 1 of 30
> [wait-for-migrations] Waiting 0.5 seconds before next attempt
> [wait-for-migrations] Attempt 2 of 30
> [wait-for-migrations] Waiting 1 seconds before next attempt
> [wait-for-migrations] Attempt 3 of 30
> [wait-for-migrations] Waiting 2 seconds before next attempt
> ```
> 
> ```
> /usr/bin/launch_awx_rsyslog.sh: line 4: /etc/passwd: Permission denied
> [wait-for-migrations] Waiting for database migrations...
> [wait-for-migrations] Attempt 1 of 30
> [wait-for-migrations] Waiting 0.5 seconds before next attempt
> [wait-for-migrations] Attempt 2 of 30
> [wait-for-migrations] Waiting 1 seconds before next attempt
> [wait-for-migrations] Attempt 3 of 30
> [wait-for-migrations] Waiting 2 seconds before next attempt
> ```
> 
> 2. For **awx-web** pod redis container is in running state. However containers **awx-web** and **awx-rsyslog** containers are in similar state as above.
> 
> ### Additional information
> _No response_
> 
> ### Operator Logs
> _No response_

Did you tried to upgrade the AWX image directly on AWX kind ? This generally happens if the AWX Operator and AWX kind are not in sync.

We should never be updating the image in AWX Kind directly. The AWX operator is responsible on spinning up the AWX with relevant version is set as default for the operator version.
