### ISSUE TITLE
fatal: unable to access Gitlab error:0A000152:SSL routines::unsafe legacy renegotiation disabled

### ISSUE THREAD

**Issue by ddelafuentelks** [ansible/tower-operator#1447]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

After fresh installation of AWX 22.3 we are getting problems to connect with out GitLab. We are getting the error --> fatal: unable to access 'https://devops.ddc.es/gitlab/gruposistemas/inventarios-pobres-ansible.git/': error:0A000152:SSL routines::unsafe legacy renegotiation disabled"

### AWX Operator version

2.2.1

### AWX version

22.3.0

### Kubernetes platform

minikube

### Kubernetes/Platform version

minikube version: v1.30.1

### Modifications

no

### Steps to reproduce

awx.yaml file I deployed with:
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-ddc
spec:
  service_type: nodeport
  nodeport_port: 30510

### Expected results

Connect with Gitlab

### Actual results

giving error. After configure credential and Gitlab project when launch a sync we are getting this error:
fatal: unable to access 'https://devops.ddc.es/gitlab/gruposistemas/inventarios-pobres-ansible.git/': error:0A000152:SSL routines::unsafe legacy renegotiation disabled

**Comment by fosterseth** [comment]
are you using  https or ssh to do the project update. That is, is your credential setting username/password or the scm private key? do you get the same errors in either case?
 
you may try building a custom EE to run this playbook sync in (by default it will awx-ee:latest). And in that custom EE you may need to configure the openssl to allow connections to legacy servers. See how it is done here https://stackoverflow.com/questions/75763525/curl-35-error0a000152ssl-routinesunsafe-legacy-renegotiation-disabled

once you have that image built, push to a public registry, and use this image in your Project's EE

let us know if that works for you

before doing all that -- are you able to do "git clone" operations on this same gitlab url locally (via https, not ssh)?

**Comment by ddelafuentelks** [comment]
I have tested both with user/password and with scm private key, and get the same result.

Sorry, but I can't change the openssl.cnf file in the container. I understand that I have to change the openssl.cnf of the awx-web pod, right?


[awxuser@plawxdevops01 ~]$ kubectl-iexec awx-ddc /bin/bash
Namespace: awx | Pod: ✔ awx-ddc-web-796b8c4fc6-msj8j
Container: ✔ awx-ddc-web
bash-5.1$ openssl version
OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
bash-5.1$ find . -name "openssl.cnf"
./etc/pki/tls/openssl.cnf
./etc/ssl/openssl.cnf
bash-5.1$ ls -l ./etc/ssl/openssl.cnf
lrwxrwxrwx. 1 root root 24 Aug 25  2022 ./etc/ssl/openssl.cnf -> /etc/pki/tls/openssl.cnf

How can I change to root (or login as root) inside the pod??

**Comment by ddelafuentelks** [comment]
Finnaly, It's working. Our network team have modified some parameters from our Netscaler proxy.
