### ISSUE TITLE
Allow ability to set securityContext in Postgres StatefulSet.

### ISSUE THREAD

**Issue by AlbinKroon** [ansible/tower-operator#1451]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

As of now it is not possible to set/change the securityContext of the Postgres StatefulSet. This means the pod won't start when having configured the Pod Security Admission Controller to enforce restricted mode in all namespaces.

<img width="1056" alt="Screenshot 2023-06-16 at 16 27 09" src="https://github.com/ansible/awx-operator/assets/33911033/27c0c66b-9c08-4100-bd7a-5683697ba869">

Please consider adding the ability to set the securityContext in `roles/installer/templates/statefulsets/postgres.yaml.j2` under `.spec.template.spec`.

**Comment by rooftopcellist** [comment]
This has been address by:
* https://github.com/ansible/awx-operator/pull/1517
