### ISSUE TITLE
Overview API groups permissions cluster rolebinding for serviceaccount 

### ISSUE THREAD

**Issue by dpaardenkooper** [ansible/tower-operator#1452]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Dear all,

We are working with AKS Kubernetes platform on a shared AKS environment. Each team is divided with its own Namespace and service account. Is it possible to retrieve a list of permissions on "API group" level that is required to install AWX tower which is deployed in an already existing namespace?

The deployment itself via Helm is giving this error message to us:
2023-06-20T12:49:27.8210686Z     * customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:<sa>:<namespace>" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope: Azure does not have opinion for this user.

**Comment by TheRealHaoLiu** [comment]
Hi @dpaardenkooper, currently it is not possible to install awx-operator as a namespace admin. 

Installing AWX operator will require a bunch of cluster scoped permission 

(creating CRD, creating clusterrole clusterrolebinding etc)
