### ISSUE TITLE
init container in awx-task pod not coming up

### ISSUE THREAD

**Issue by vshete93** [ansible/tower-operator#1453]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I have been using following configurations in my CRD file to spinup init container. However it doenst come up instead directly goes into `terminated` state.

```
  init_container_image: quay-io/ansible/awx-ee:22.2.0
  init_container_image_version: latest
  init_projects_container_image: quay.io/centos/centos:stream9
```

### AWX Operator version

2.0.1

### AWX version

22.2.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

EKS

### Modifications

yes

### Steps to reproduce

as explained in summary

### Expected results

init container starts up normally

### Actual results

init container in `Terminated` state

**Comment by djyasin** [comment]
Hello @vshete93, we would like to get a little bit more information from you. Could you please provide us with the logs for the task pod and the init container?

**Comment by vshete93** [comment]
@djyasin thanks for your reply. Container level logs for `init` container doesn't show anything. Following are logs for init container only inside the task pod. Other containers inside task pod is up and running.

`kubectl -n awx describe pod awx-task`
```
Init Containers:
    init:
      Container ID:  containerd://xyz
      Image:         internal_url_registry_link/awx_ee:22.2.0
      Image ID:      internal_url_registry_link/awx_ee:22.2.0@sha256:xyz
      Port:          <none>
      Host Port:     <none>
      Command:
        /bin/sh
        -c
        hostname=$MY_POD_NAME
        receptor --cert-makereq bits=2048 commonname=$hostname dnsname=$hostname nodeid=$hostname outreq=/etc/receptor/tls/receptor.req outkey=/etc/receptor/tls/receptor.key
        receptor --cert-signreq req=/etc/receptor/tls/receptor.req cacert=/etc/receptor/tls/ca/receptor-ca.crt cakey=/etc/receptor/tls/ca/receptor-ca.key outcert=/etc/receptor/tls/receptor.crt verify=yes
        
      State:          Terminated
        Reason:       Completed
        Exit Code:    0
        Started:      Tue, 20 Jun 2023 17:24:07 -0700
        Finished:     Tue, 20 Jun 2023 17:24:08 -0700
      Ready:          True
      Restart Count:  0
      Limits:
        cpu:     2
        memory:  2Gi
      Requests:
        cpu:     250m
        memory:  1Gi
      Environment:
        MY_POD_NAME:  awx-task-58d9db84f9-r2vhs (v1:metadata.name)
      Mounts:
        /etc/receptor/tls/ from awx-receptor-tls (rw)
        /etc/receptor/tls/ca/receptor-ca.crt from awx-receptor-ca (ro,path="tls.crt")
        /etc/receptor/tls/ca/receptor-ca.key from awx-receptor-ca (ro,path="tls.key")
        /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-x8rzx (ro)
```

**Comment by vshete93** [comment]
It looks like init containers are just required for initializing task and web pod. And in my case its doing that so this is good to close.
