### ISSUE TITLE
awx-operator.clusterserviceversion.yaml still references 0.6.0

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#147]
After the recent release to 0.7.0, I noticed that 0.6.0 is still being referenced in `./deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml`. Should this be updated as well?

**Comment by shanemcd** [comment]
That _should_ get fixed the next time we regenerate the olm-catalog directory... cc @Spredzy

**Comment by Spredzy** [comment]
That got fixed yesterday with https://github.com/ansible/awx-operator/commit/76092c366e77cbeb7b15191d6f62935ed1fad4be

Specific line: https://github.com/ansible/awx-operator/commit/76092c366e77cbeb7b15191d6f62935ed1fad4be#diff-07c80681d716a98ea263b011447ec8106142ebca5e52b68cdde239cdfb9bc97aR364
