### ISSUE TITLE
Allow for configurable image pull policy on the management pods for backup/restore

### ISSUE THREAD

**Issue by sirjaren** [ansible/tower-operator#1472]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Currently, the `management-pod.yml.j2` template for both the backup and restore roles hardcode the image pull policy to `Always`.

This should be configurable (or least removed) to default to `IfNotPresent`.
In lieu of an image registry, I have to modify the roles today and rebuild the AWX Operator image.

Thanks!

https://github.com/ansible/awx-operator/blob/devel/roles/backup/templates/management-pod.yml.j2
https://github.com/ansible/awx-operator/blob/devel/roles/restore/templates/management-pod.yml.j2

**Comment by rooftopcellist** [comment]
@sirjaren this feature was added by this PR thanks to @rakesh561!

* https://github.com/ansible/awx-operator/pull/1473
