### ISSUE TITLE
Add option to specify additional environment for EE container

### ISSUE THREAD

**Issue by balonik** [ansible/tower-operator#148]
Currently I can specify additional Environment for `awx-web` and `awx-task` containers using the `tower_task_extra_env` and `tower_web_extra_env` properties.
I would like to specify additional env also for the `awx-ee` container.
This is useful for example if I need to specify `https_proxy` variables.

**Comment by Spredzy** [comment]
@balonik do you mind giving the above PR a whirl ?

**Comment by balonik** [comment]
@Spredzy looks fine. worked for me

**Comment by jbradberry** [comment]
What's the actual status on this?  Following the links, I see one PR that is closed and two more that are merged.

**Comment by Spredzy** [comment]
Sorry yes this one is now closed. #406  and #407 addressed it.
