### ISSUE TITLE
Enabling debugging in 'Settings' in the AWX web UI causes webservice to break

### ISSUE THREAD

**Issue by jsprhssng** [ansible/tower-operator#1485]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Enabling debugging in 'Settings' in the AWX web UI causes webservice to break

UI crashed and doesnt get to login screen after enabling the setting. Shows; Server Error
A server error has occurred.

awx-web log writes;

`2023-07-05 17:38:48,380 ERROR    [32432794aa9d4d098ec0d6a7e2fdd987] django.request Internal Server Error: /
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/middleware.py", line 58, in process_response
    response['X-API-Profile-File'] = self.prof.stop()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 129, in stop
    res = self.output_results()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 90, in output_results
    super().output_results()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 22, in output_results
    os.makedirs(self.dest)
  File "/usr/lib64/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib64/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/log/tower'
`

### AWX version

2.3.0

### Select the relevant components

- [X] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Operating system

Ubuntu 22.04

### Steps to reproduce

Fresh install on rancher/k3s

1. Fresh install on rancher/k3s
2. Login to awx
3. Enable "Debug Web Requests" in Settings/Troubleshooting

### Expected results

Debugging web request python timing enabled

### Actual results

AWX web stops working, cannot login/no login screen.

Server Error
A server error has occurred.

### Additional information

Enabling this setting in the latest version of operator and awx gives the above error every time.

![image](https://github.com/ansible/awx/assets/56963367/c4676382-ed20-4fa1-bfc5-285daddc82df)

**Comment by fosterseth** [comment]
maybe one solution is to just create this dir with the right permissions in the image itself, somewhere around here

https://github.com/fosterseth/awx/blob/e47d30974ce1f71d1ad2d6bd0f3d81bf1f70fad6/tools/ansible/roles/dockerfile/templates/Dockerfile.j2#L241

**Comment by williamtwomey** [comment]
+1 same issue here on 2.4.0 after enabling debug via the web UI

`PermissionError: [Errno 13] Permission denied: '/var/log/tower'
2023-10-06 12:59:25,687 ERROR    [a4949506dc184a73b436aaeca1e1d3d7] django.request Internal Server Error: /
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/middleware.py", line 58, in process_response
    response['X-API-Profile-File'] = self.prof.stop()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 129, in stop
    res = self.output_results()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 90, in output_results
    super().output_results()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 22, in output_results
    os.makedirs(self.dest)
  File "/usr/lib64/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib64/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
`

If anyone finds themselves in this situation and wants to back out, just have to delete this from the conf_setting table

```
delete from conf_setting where key=AWX_REQUEST_PROFILE;
```

**Comment by druesendieb** [comment]
Ran into the same issue as well today. 
Manually adding an empty dir for the k8s web deployment for `/var/log/` allowed us to deactivate the feature again.

**Comment by gsg-git** [comment]
I have the same issue with 23.6.0 - i luckily could undo it via snapshot.

**Comment by kumarkaji** [comment]
> +1 same issue here on 2.4.0 after enabling debug via the web UI
> 
> `PermissionError: [Errno 13] Permission denied: '/var/log/tower' 2023-10-06 12:59:25,687 ERROR [a4949506dc184a73b436aaeca1e1d3d7] django.request Internal Server Error: / Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner response = get_response(request) File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__ response = self.process_response(request, response) File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/middleware.py", line 58, in process_response response['X-API-Profile-File'] = self.prof.stop() File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 129, in stop res = self.output_results() File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 90, in output_results super().output_results() File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 22, in output_results os.makedirs(self.dest) File "/usr/lib64/python3.9/os.py", line 215, in makedirs makedirs(head, exist_ok=exist_ok) File "/usr/lib64/python3.9/os.py", line 225, in makedirs mkdir(name, mode) `
> 
> If anyone finds themselves in this situation and wants to back out, just have to delete this from the conf_setting table
> 
> ```
> delete from conf_setting where key=AWX_REQUEST_PROFILE;
> ```

I was able to use this to fix my broken UI. Just had to revise the query to the below as opposed to the above.
delete from conf_setting where key = 'AWX_REQUEST_PROFILE';

Thank you,
Kumar.

**Comment by kurokobo** [comment]
If we do not want to manipulate the DB directly, there is a workaround that mounting `emptyDir` to `/var/log/tower`:

```yaml
spec:
  ...
  extra_volumes: |
    - name: awx-web-debug
      emptyDir: {}
  web_extra_volume_mounts: |
    - name: awx-web-debug
      mountPath: "/var/log/tower"
```

**Comment by yyosha** [comment]
> If we do not want to manipulate the DB directly, there is a workaround that mounting `emptyDir` to `/var/log/tower`:
> 
> ```yaml
> spec:
>   ...
>   extra_volumes: |
>     - name: awx-web-debug
>       emptyDir: {}
>   web_extra_volume_mounts: |
>     - name: awx-web-debug
>       mountPath: "/var/log/tower"
> ```

@kurokobo,

Running on EKS with SC & PV on EFS (EFS is pre-provisioned).

I added it in my AWX yaml for my custom configurations.

Works like a charm!

Thanks!

**Comment by nlaphine** [comment]
> +1 same issue here on 2.4.0 after enabling debug via the web UI
> 
> `PermissionError: [Errno 13] Permission denied: '/var/log/tower' 2023-10-06 12:59:25,687 ERROR [a4949506dc184a73b436aaeca1e1d3d7] django.request Internal Server Error: / Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner response = get_response(request) File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__ response = self.process_response(request, response) File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/middleware.py", line 58, in process_response response['X-API-Profile-File'] = self.prof.stop() File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 129, in stop res = self.output_results() File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 90, in output_results super().output_results() File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/utils/profiling.py", line 22, in output_results os.makedirs(self.dest) File "/usr/lib64/python3.9/os.py", line 215, in makedirs makedirs(head, exist_ok=exist_ok) File "/usr/lib64/python3.9/os.py", line 225, in makedirs mkdir(name, mode) `
> 
> If anyone finds themselves in this situation and wants to back out, just have to delete this from the conf_setting table
> 
> ```
> delete from conf_setting where key=AWX_REQUEST_PROFILE;
> ```

Does someone know what the updated table would be ?
`postgres=# delete from conf_setting where key = 'AWX_REQUEST_PROFILE';
ERROR:  relation "conf_setting" does not exist
LINE 1: delete from conf_setting where key = 'AWX_REQUEST_PROFILE';`

or were there commands in front of that, that everyone thought was obvious (sysadmins aren't DBAs)

thanks
Peter
