### ISSUE TITLE
Missing inventory script tab

### ISSUE THREAD

**Issue by Slim-Rush** [ansible/tower-operator#149]
AWX version: 17.0.1
AWX install method: docker on i,

I have recently installed the AWX through the docker-compose method. In version 17.0.1 the functionality of dynamic inventory is unavailable. In the left pane, the inventory script is missing.

Is this expected? If so, any plan to release this in the near future?linux

**Comment by billett83** [comment]
@daichenge Please could raise AWX image issues on the AWX github repo https://github.com/ansible/awx - This repo is for the awx-operator

**Comment by Spredzy** [comment]
As @billett83 raised, this repo is for the `awx-operator` only. Please refer to https://github.com/ansible/awx for any question regardding the `docker-compose` installation method.
