### ISSUE TITLE
Create a contributors guide

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#15]
Would be good to have a contributors guide so that folks could understand what kind of guidelines there are for getting involved here.

**Comment by kedark3** [comment]
There already exists a https://github.com/ansible/awx-operator#development section maybe that's a good start. But sure, I'd love to see a contributors guide as well. In addition to that, if there are any items on the ROADMAP, any enhancements that are desired/planned where external contributors can help, would be awesome addition to the README.
