### ISSUE TITLE
Instalation crash on awx-web and awx-task start

### ISSUE THREAD

**Issue by gertz22** [ansible/tower-operator#1503]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello, I was trying update my old awx 0.15.0 to latest with steps in documentation and it was failing on deploy. After that I chose to do clean install and its still failing 

kubectl -n awx get pods -l "app.kubernetes.io/managed-by=awx-operator"
```
NAME                        READY   STATUS                  RESTARTS         AGE
awx-postgres-13-0           1/1     Running                 0                29m
awx-web-565fbfb879-qhsp5    1/3     CrashLoopBackOff        18 (4m19s ago)   26m
awx-task-57fd466894-sj8cd   0/4     Init:CrashLoopBackOff   10 (29s ago)     28m
```
I followed this manual:
https://computingforgeeks.com/how-to-install-ansible-awx-on-debian-buster/

### AWX Operator version

2.4.0

### AWX version

install in progress

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

kubectl go1.20.5

### Modifications

no

### Steps to reproduce

I followed this manual:
https://computingforgeeks.com/how-to-install-ansible-awx-on-debian-buster/

### Expected results

working deploy and runnign all pods

### Actual results

pods crashing

### Operator Logs

```
 *********************************************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:203\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nfailed: [localhost] (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nfatal: [localhost]: FAILED! => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=55   changed=0    unreachable=0    failed=1    skipped=64   rescued=0    ignored=0   \r\n\n","job":"865409372696361617","name":"awx","namespace":"awx","error":"exit status 2","stacktrace":"github.com/operator-framework/operator-sdk/internal/ansible/runner.(*runner).Run.func1\n\t/workspace/internal/ansible/runner/runner.go:269"}
----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx/awx) -----


PLAY RECAP *********************************************************************
localhost                  : ok=55   changed=0    unreachable=0    failed=1    skipped=64   rescued=0    ignored=0   


----------
{"level":"error","ts":"2023-07-27T14:20:24Z","msg":"Reconciler error","controller":"awx-controller","object":{"name":"awx","namespace":"awx"},"namespace":"awx","name":"awx","reconcileID":"d4ee40a0-e11c-425e-8712-f5d982fc266d","error":"event runner on failed","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}


```

**Comment by gertz22** [comment]
at version 2.5.0 its same Apply resorces failed

**Comment by fosterseth** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by Taylor-Hogan** [comment]
I am getting the same errors on a fresh install of centos 8 and rocky 8. Using build 2.5.0. 

Any help would be appreciated.

**Comment by gertz22** [comment]
> I am getting the same errors on a fresh install of centos 8 and rocky 8. Using build 2.5.0.
> 
> Any help would be appreciated.

Your system running in VM? 

Any way I finally found solution and it doesnt fork for me because VM had not support for x86-v64-v2+aes  I set proxmox CPU to x86-v64-v2+aes and add CPU support for aes.

**Comment by Taylor-Hogan** [comment]
Yes it is in a proxmox server VM. 
I'll try those specs and report back.

Thanks for following up.
