### ISSUE TITLE
AWX Operator 2.4.0 New Deploy Never Completes (django.db.utils.OperationalError: connection is bad)

### ISSUE THREAD

**Issue by kgoddarddev** [ansible/tower-operator#1506]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Current Version of Kubernetes Running on Ubuntu 22.04
`Client Version: v1.27.4
  Kustomize Version: v5.0.1
  Server Version: v1.27.0
 Node-Local-DNS installed
`

AWX Operator 2.4.0 (Make Deploy)

`---
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx
      spec:
        service_type: nodeport
        nodeport_port: 30080
`

In the logs:

`-------------------------- Ansible Task StdOut -------------------------------

 TASK [Check if there are any super users defined.] ******************************** 
fatal: [localhost]: FAILED! => {"changed": true, "rc": 1, "return_code": 1, "stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 289, in ensure_connection\n    self.connect()\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 270, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py\", line 269, in get_new_connection\n    connection = self.Database.connect(**conn_params)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg/connection.py\", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: Name or service not known\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/bin/awx-manage\", line 8, in <module>\n    sys.exit(manage())\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py\", line 184, in manage\n    if (connection.pg_version // 10000) < 12:\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/connection.py\", line 15, in __getattr__\n    return getattr(self._connections[self._alias], item)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/functional.py\", line 57, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py\", line 437, in pg_version\n    with self.temporary_connection():\n  File \"/usr/lib64/python3.9/contextlib.py\", line 119, in __enter__\n    return next(self.gen)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 705, in temporary_connection\n    with self.cursor() as cursor:\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 330, in cursor\n    return self._cursor()\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 306, in _cursor\n    self.ensure_connection()\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 289, in ensure_connection\n    self.connect()\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 289, in ensure_connection\n    self.connect()\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 270, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py\", line 269, in get_new_connection\n    connection = self.Database.connect(**conn_params)\n  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg/connection.py\", line 728, in connect\n    raise ex.with_traceback(None)\ndjango.db.utils.OperationalError: connection is bad: Name or service not known\n", "stderr_lines": ["Traceback (most recent call last):", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 289, in ensure_connection", "    self.connect()", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner", "    return func(*args, **kwargs)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 270, in connect", "    self.connection = self.get_new_connection(conn_params)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner", "    return func(*args, **kwargs)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py\", line 269, in get_new_connection", "    connection = self.Database.connect(**conn_params)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg/connection.py\", line 728, in connect", "    raise ex.with_traceback(None)", "psycopg.OperationalError: connection is bad: Name or service not known", "", "The above exception was the direct cause of the following exception:", "", "Traceback (most recent call last):", "  File \"/usr/bin/awx-manage\", line 8, in <module>", "    sys.exit(manage())", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py\", line 184, in manage", "    if (connection.pg_version // 10000) < 12:", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/connection.py\", line 15, in __getattr__", "    return getattr(self._connections[self._alias], item)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/functional.py\", line 57, in __get__", "    res = instance.__dict__[self.name] = self.func(instance)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py\", line 437, in pg_version", "    with self.temporary_connection():", "  File \"/usr/lib64/python3.9/contextlib.py\", line 119, in __enter__", "    return next(self.gen)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 705, in temporary_connection", "    with self.cursor() as cursor:", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner", "    return func(*args, **kwargs)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 330, in cursor", "    return self._cursor()", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 306, in _cursor", "    self.ensure_connection()", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner", "    return func(*args, **kwargs)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 289, in ensure_connection", "    self.connect()", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/utils.py\", line 91, in __exit__", "    raise dj_exc_value.with_traceback(traceback) from exc_value", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 289, in ensure_connection", "    self.connect()", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner", "    return func(*args, **kwargs)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py\", line 270, in connect", "    self.connection = self.get_new_connection(conn_params)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner", "    return func(*args, **kwargs)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py\", line 269, in get_new_connection", "    connection = self.Database.connect(**conn_params)", "  File \"/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg/connection.py\", line 728, in connect", "    raise ex.with_traceback(None)", "django.db.utils.OperationalError: connection is bad: Name or service not known"], "stdout": "", "stdout_lines": []}
...ignoring
`

### AWX Operator version

2.4.0

### AWX version

latest

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.27.4

### Modifications

no

### Steps to reproduce

make deploy

kubectl -f awx.yaml

`---
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx
      spec:
        service_type: nodeport
        nodeport_port: 30080
`

### Expected results

Running AWX 

### Actual results

Task never complete

**Comment by kgoddarddev** [comment]
Well... I am going to post what fixed it for me.   This should be added to at least some FAQ.
I am on Ubuntu 22.04

my kustomization.yaml


`apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - awx.yaml
  - awx-local-storage.yaml
  - awx-pv.yaml
  - awx-pvc.yaml
 
`
1. Disabled firewall sudo ufw disable 
2. Reboot your nodes
3. Fix password in POSTGRES SQL node
   steps:
    1.  Get secret:   k get secret ansible-awx-postgres-configuration -o yaml
    2. echo "--------------------------------------="|base64 --decode  where --- are you put the result of the password from the 
       yaml output
    4.  Login to your postgressql pod: kubectl exec -it ansible-awx-postgres-13-0 -- /bin/bash
    5. Login to psql:   psql --user awx
    6. Update password: ALTER USER awx WITH PASSWORD 'dTqISygR0IHGXxxDjVUtA2hQZIkxt9VF';    Note: this is the pass from 
        the echo output
    7. If the admin password provided in the secrets does not work use this to create a super user

    k exec -n awx -it $(k get pods -n awx -l app.kubernetes.io/component=awx -o name) -c awx-task -- awx-



Hope this helps someone.

**Comment by wongnickel** [comment]
I have the same symptom in a fresh install in RHEL8.
even tried for the latest version 22.7.0
any suggestion?
the last command you put seems chopped at the end "awx-"
I did try to put everything in one worker node, but same failure.
try the following command on awx-task, got the same connection error too

kubectl exec -n awx-dev -it pod/awx-task-7bf8cf9795-xcf7w -c awx-task -- awx-manage showmigrations
.
.
django.db.utils.OperationalError: connection is bad: Name or service not known

Please comment

Nick

**Comment by dev1983** [comment]
also facing same error, any solution?

**Comment by wongnickel** [comment]
for my case, the issue is on Kubernetes set up
initially I have

pod-network-cidr=192.168.10.0/16

that cause the error
once I rebuild the cluster with

pod-network-cidr=192.168.0.0/16

the install was working just fine

Hope it helps

Nickel

**Comment by dev1983** [comment]
Thanks

But for me above error was for DB connection, web was not able to connect
to db.
So I changed the dab password according to web and it worked fine.

- Dev

**Comment by yoonmin1030** [comment]
I had the same issue, but resolved to restart coredns.
kubectl -n kube-system delete pod -l k8s-app=kube-dns

it seems all the configuration all okay. but awx-task didn't get  db connection and the same logs "django.db.utils.OperationalError: connection is bad: Name or service not known"

after coredns restarting, awx-task container got running.  => a few minutes, task pod got error status. Restarting coredns is not the solution, thou.
