### ISSUE TITLE
Handling HTTP loadbalancer

### ISSUE THREAD

**Issue by gdelanoe** [ansible/tower-operator#151]
Hello,

At job, we plan to deploy awx using awx-operator. Everything works great except one thing : we want to deploy awx using an HTTP loadbalancer. I tried to find in the documentation the way to do that but it's look like it's not implemented.

I use this YML code to describe the AWX CR : 
```---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: ${K8S_AWX_NAMESPACE}
spec:
  tower_hostname: ${INTERNAL_AWX_HOST}
  tower_admin_user: admin
  tower_admin_email: XXXX 
  tower_admin_password_secret: ${AWX_ADMIN_PASSWORD}
  tower_broadcast_websocket_secret: awx-broadcast-websocket
  tower_postgres_configuration_secret: awx-postgres-configuration
  tower_ingress_type: LoadBalancer
  tower_loadbalancer_annotations: "networking.gke.io/load-balancer-type: Internal"
  tower_loadbalancer_protocol: http
```

This configuration led me to this error in the awx-operator pods : 
```{
  "ansible_loop_var": "item",
  "changed": false,
  "error": 422,
  "item":
  "tower_service",
  "msg": "Failed to apply object: b'{
    "kind":"Status",
    "apiVersion":"v1",
    "metadata":{},
    "status":"Failure",
    "message":"Service "awx-service" is invalid: spec.ports: Required value",
    "reason":"Invalid",
    "details":{
      "name":"awx-service",
      "kind":"Service",
      "causes":
        [
          {
          "reason":"FieldValueRequired",
          "message":"Required value",
          "field":"spec.ports"
          }
        ]
      }
  }
}
```

Looking in "awx-operator/roles/installer/templates/tower_service.yaml.j2" I found that the loadbalancer with HTTP case is not implemented.

Do I missed something ? Is there a way to do it using the default variable ?

If it's not possible, I will make a PR to develop this feature :)

**Comment by billett83** [comment]
Have you tried adding:

`tower_loadbalancer_port: 80`

This should be the default is not specified.

**Comment by Spredzy** [comment]
The problem is here https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_service.yaml.j2#L15-L32, it gets into no `if` statement (based on OP configuration)  leading to this section to be empty

@billett83 we missed this use case when analyzing the original PR. Do you mind providing a fix ?

**Comment by billett83** [comment]
I have reviewed the awx-operator/roles/installer/templates/tower_service.yaml.j2 file and see the following

`spec:
  ports:
{% if tower_ingress_type | lower != 'loadbalancer' and tower_loadbalancer_protocol | lower != 'https' %}
    - port: 80
      protocol: TCP
      targetPort: 8052
      name: http
{% endif %}`

The conditional statement is incorrect. I will fix this shortly with PR

**Comment by gdelanoe** [comment]
Thank you a lot @billett83 and @Spredzy for your quick answers !
Waiting for the PR.
