### ISSUE TITLE
Project does not pull "Source Control Credential" properly with git accesscode

### ISSUE THREAD

**Issue by doyoungim999** [ansible/tower-operator#1510]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

"Select Source Control Credential"  does not show the credentials which I created. 
How can I setup Git  "Personal Access Tokens" in Project ? 

### AWX Operator version

 AWX 22.5.0

### AWX version

 AWX 22.5.0

### Kubernetes platform

minikube

### Kubernetes/Platform version

minikube version: v1.31.1

### Modifications

no

### Steps to reproduce

Projects-> Edit Details --> Source Control Credential --> nothing 
"No Source Control Credential Found" 

Do you support github source access with "Personal access Tokens"? 

### Expected results

I should see the credentials which I registered with "Personal access tokens " of github. 

### Actual results

nothing

**Comment by doyoungim999** [comment]
![image](https://github.com/ansible/awx-operator/assets/6082088/f3ea98ad-63c1-4827-93fb-73e9a53cb5e2)

**Comment by doyoungim999** [comment]
I found how to. I will close it.

**Comment by ProfessorCha0s** [comment]
Maybe share how you found it?

**Comment by thesNu** [comment]
> I found how to. I will close it.

need help, how to find where is creds?

**Comment by thesNu** [comment]
> Maybe share how you found it?

You need create 	Source Control  credential.  Use a token instead of a password

**Comment by krunal4baps** [comment]
Did you use, user name entry or no? I tried this many many times but still failing

**Comment by Egarone** [comment]
Hi @krunal4baps !
Man, I was same problem and doubts like you... Follow the steps: 

In github, you can create a 'deploy key' for a repository.
This key will only be valid for that repository.
First, create a key pair.
In github, navigate to your repository's homepage and click on Settings.
Click on 'Deploy keys' and then click 'Add deploy key'.
Give it a name and paste the public key and save it.
In AWX, create a 'Source Control' credential type.
Give it a name and paste the private key into the box (and also the passphrase if you used one) and save it.
In your project definition, set the Source Code Credential to the credential you just created and save it.

**Comment by krunal4baps** [comment]
Really appreciate the time you took to reply!
