### ISSUE TITLE
Broken link README.md

### ISSUE THREAD

**Issue by metabsd** [ansible/tower-operator#1521]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I decide to read the doc another time to update my knowledge of the project.

I found there is a broken link: https://github.com/ansible/awx-operator/blob/devel/docs/installation/installation.md

![image](https://github.com/ansible/awx-operator/assets/7953470/924f00e2-4274-4197-bab5-985b3e5c7ef1)

### AWX Operator version

devel

### AWX version

devel

### Kubernetes platform

openshift

### Kubernetes/Platform version

4.12

### Modifications

no

### Steps to reproduce

Trying to read the documentation.

### Expected results

The link to be working

### Actual results

Broken link

**Comment by fosterseth** [comment]
@rooftopcellist

@metabsd found a broken link

**Comment by rooftopcellist** [comment]
Fixed by https://github.com/ansible/awx-operator/pull/1523/files

Thanks for the issue!
