### ISSUE TITLE
Awx UI. For uploading files to operator node

### ISSUE THREAD

**Issue by nx2804** [ansible/tower-operator#1527]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hi Team

Iam looking for the solution to upload files through UI in awx , can this feature be enabled please

Thanks 
Nachammai

**Comment by fosterseth** [comment]
which files are you wishing to upload? can you please update the post body with more details?

**Comment by nx2804** [comment]
Hi

I have awx-operator which is running on my machine

I wanted to upload files tar files from awx ui to my machine under certain
path without logging into the server

Is their any feasibility for this?

**Comment by nachammaichidambaram** [comment]
any update on this please

**Comment by fosterseth** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by fosterseth** [comment]
There is no way to upload files through the UI/API
