### ISSUE TITLE
awx-operator basic-install.md - get admin password

### ISSUE THREAD

**Issue by hagrace4** [ansible/tower-operator#1529]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

To retrieve the admin password the documentation suggested to use:

`$ kubectl get secret awx-demo-admin-password -o jsonpath="{.data.password}" | base64 --decode `

This command did not work for me and returned:
`Error from server (NotFound): secrets "awx-demo-admin-password" not found`

However, I was able to successfully retrieve my admin password fo the WebUI using:
`kubectl get secrets --namespace=awx awx-demo-admin-password  -ojsonpath='{.data.password}' | base64 -d
`

Hope this may help anyone else coming to the same problem as I have.

### AWX Operator version

v2.5.1

### AWX version

v22.7.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.27.4+k3s1

### Modifications

no

### Steps to reproduce

Follow the basic-install.md at https://github.com/ansible/awx-operator/blob/devel/docs/installation/basic-install.md

### Expected results

Admin password would be returned

### Actual results

This command did not work for me and returned:
`Error from server (NotFound): secrets "awx-demo-admin-password" not found`

**Comment by kurokobo** [comment]
@hagrace4 
As described in `basic-install.md`, invoking `set-context` before `get secrets` would solve your problem (`-n awx` is equivalent to `--namespace=awx`).

> So we don't have to keep repeating -n awx, let's set the current namespace for kubectl:
> 
> ```bash
> $ kubectl config set-context --current --namespace=awx
> ```

**Comment by djyasin** [comment]
Marking as resolved.
