### ISSUE TITLE
AWX - Expose Service with NodePort

### ISSUE THREAD

**Issue by leandrocarpenter** [ansible/tower-operator#1533]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

**Failed to expose AWX services.**

Sharing with you a solution I found to expose the AWX frontend.
I followed the entire procedure in the documentation - https://github.com/ansible/awx-operator/blob/devel/docs/installation/basic-install.md , and I had a lot of trouble exposing the service, so for those who are passing due to the same difficulty, after carrying out the entire documentation process, a suggestion is to use the following command so that the front is available outside the cluster.

`kubectl port-forward svc/awx-service --address 0.0.0.0 <nodeport>:80 &> /dev/null &`

### AWX Operator version

2.5.1

### AWX version

2.5.1

### Kubernetes platform

minikube

### Kubernetes/Platform version

v1.27.3

### Modifications

no

### Steps to reproduce

follow documentation https://github.com/ansible/awx-operator/blob/devel/docs/installation/basic-install.md

### Expected results

Open the front outside the cluster

### Actual results

Can't open front outside the cluster

**Comment by fosterseth** [comment]
Thanks for highlighting the usage of port-forward, it is a nice too when working with k8s

The service should already be exposed via the nodeport. You can run the following to get the service, and port-forward shouldn't be required.

`minikube service -n awx awx-demo-service --url`

more info here https://github.com/ansible/awx-operator/blob/devel/docs/installation/basic-install.md

**Comment by Sortitio** [comment]
> Thanks for highlighting the usage of port-forward, it is a nice too when working with k8s
> 
> The service should already be exposed via the nodeport. You can run the following to get the service, and port-forward shouldn't be required.
> 
> `minikube service -n awx awx-demo-service --url`
> 
> more info here https://github.com/ansible/awx-operator/blob/devel/docs/installation/basic-install.md

Hello, a bit new here and learning rocky 9.4/kubernetes/ansible. 

I was wondering if there's a kubectl command equivalent to get the URL or if the URL would simply be the hostname:nodeport# ? 

Another question was I set this up with kubernetes 1.30, would it be much simpler to use minikube if all I want/need is the awx GUI?
