### ISSUE TITLE
awx-web to use https using NodePort and SSL

### ISSUE THREAD

**Issue by hairishhanda** [ansible/tower-operator#1559]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Document Refrence - https://github.com/ansible/awx-operator/blob/devel/docs/user-guide/network-and-tls-configuration.md

There is not option to enable SSL for while using NodePort.

**Comment by fosterseth** [comment]
@rooftopcellist is there a limitation for TLS with nodeport?

**Comment by fosterseth** [comment]
closing in favor of this issue https://github.com/ansible/awx-operator/issues/1563
