### ISSUE TITLE
[backup] precreate_partition_hours is not modifiable

### ISSUE THREAD

**Issue by kurokobo** [ansible/tower-operator#1570]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Reated to https://github.com/ansible/awx-operator/pull/1443

Newly added spec `precreate_partition_hours` for `awxbackup` can't be modified due to misconfigured type `string`.

- Passing `"0"` (string) causes task failure since `int` and `string` is not comparable in task
- Passing `0` (integer) is rejected since this value have to be `string`

Simply, `precreate_partition_hours` should be defined as `integer` instead of `string`.

### AWX Operator version

2.6.0

### AWX version

N/A

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

k3s version v1.27.6+k3s1 (bd04941a)

### Modifications

no

### Steps to reproduce

1. Deploy AWX with managed database
2. Create AWXBackup with following spec

   ```yaml
   ---
   apiVersion: awx.ansible.com/v1beta1
   kind: AWXBackup
   metadata:
     name: awxbackup-2023-09-29
     namespace: awx
   spec:
     deployment_name: awx
     precreate_partition_hours: "0"
   ```

### Expected results

Backup data is generated in newly created PVC.

### Actual results

Backup role failed with following error.

```bash
TASK [Precreate database partitions] ******************************** 
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'precreate_partition_hours > 0' failed. The error was: Unexpected templating type error occurred on ({% if precreate_partition_hours > 0 %} True {% else %} False {% endif %}): '>' not supported between instances of 'string' and 'int'\n\nThe error appears to be in '/opt/ansible/roles/backup/tasks/postgres.yml': line 110, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Precreate database partitions\n  ^ here\n"}
```

### Additional information

Passing `precreate_partition_hours: 0` (interger) instead of `"0"` (string) is not accepted since `precreate_partition_hours` is defined as `string` type.

```bash
$ kubectl apply -f awxbackup.yaml 
The AWXBackup "awxbackup-2023-09-29" is invalid: spec.precreate_partition_hours: Invalid value: "integer": spec.precreate_partition_hours in body must be of type string: "integer"
```

https://github.com/ansible/awx-operator/blob/8518e0d1c7b60c76f339f47ba8ed666ce80117c4/config/crd/bases/awx.ansible.com_awxbackups.yaml#L93-L95

**Comment by kurokobo** [comment]
@jessicamack 
Hi, please let me know if you have any reason that you use `string` type for this parameter.

**Comment by jessicamack** [comment]
@kurokobo Hello, no that was a mistake on my part. `integer` is the correct type.
