### ISSUE TITLE
Auto upload operator to operator hub upon new release 

### ISSUE THREAD

**Issue by aheath1992** [ansible/tower-operator#1579]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

A pipeline to auto upload the awx-operator to operator hub upon new releases to avoid forgetting to update the operator.

**Comment by fosterseth** [comment]
@aheath1992 thanks for creating this issue, we do need to get this part of our release workflows

**Comment by aheath1992** [comment]
@TheRealHaoLiu Anything I can do to help with this? I opened the Feature Request, but I am new to the project.

**Comment by TheRealHaoLiu** [comment]
@aheath1992 here's what i done so far 
- https://github.com/ansible/awx-operator/pull/1600 when running `make bundle` auto install operator-sdk if needed
- https://github.com/ansible/awx-operator/pull/1598 stage and publish catalog and bundle images

what i need to do next is to create modify the bundle (with version and replace information) and create PR against operator-hub repos

**Comment by TheRealHaoLiu** [comment]
got the last part done
