### ISSUE TITLE
awx-operator restore is stuck on pg_restore step

### ISSUE THREAD

**Issue by romankuzmik** [ansible/tower-operator#1587]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

AWXRestore from CR is failing on "Restore database dump to the new postgresql container" step while executing `pg_restore --clean --if-exists ...`

### AWX Operator version

2.7.0

### AWX version

23.3.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.24.9

### Modifications

no

### Steps to reproduce

1. Install AWX via operator with default/empty database
2. Perform backup create AWXBackup manifest
3. Perform restore creating AWXRestore manifest pointing to CR created in step 2
4. Observe an issue

### Expected results

pg_restore to complete

### Actual results

restore process is failing on awx-operator/roles/restore/tasks/postgres.yml "Restore database dump to the new postgresql container" step

### Operator Logs

```
pg_restore: error: could not execute query: ERROR:  cannot drop inherited constraint \\\"main_adhoccommandevent_20231005_21_pkey\\\" of relation \\\"main_adhoccommandevent_20231005_21\\\"\", \"Command was: ALTER TABLE IF EXISTS ONLY public.main_adhoccommandevent_20231005_21 DROP CONSTRAINT IF EXISTS main_adhoccommandevent_20231005_21_pkey;\",
```
and many more of the similar pg_restore errors

**Comment by metabsd** [comment]
I think I have the same problem trying to migrate from postgresql12 to 13. I see an error about trying to stream the backup to the new postgresql instance. I try again tomorrow to provide more detail.

**Comment by kurokobo** [comment]
@romankuzmik 
Have you performed following steps before restoration?

> *Before Restoring from a backup*, be sure to:
>   - delete the old existing AWX CR
>   - delete the persistent volume claim (PVC) for the database from the old deployment, which has a name like `postgres-13-<deployment-name>-postgres-13-0`
> 
> https://github.com/ansible/awx-operator/tree/devel/roles/restore#requirements

If you plan to reuse old PV/PVC for newly restored DB, removing containing data in PV before restoration is also recommended.

**Comment by romankuzmik** [comment]
wondering why would we want to got so extreme in this requirements. deleting main CR and then removing PV with database data. usually these are managed by Continuous Delivery, where reconcilers apply desired state to k8s cluster. manually deleting managed resources is not desirable or sometimes even not possible. for instance if k8s is managed by FluxCD, then deleted CR will be immediately restored by CD.

it would be significantly easier to remove these requirements and instead drop database as part of the restore process.
For example to add:
```
echo "DROP DATABASE $POSTGRESQL_DATABASE WITH (FORCE);" | psql --dbname=postgres --username=$POSTGRESQL_USER
echo "CREATE DATABASE $POSTGRESQL_DATABASE WITH OWNER = $POSTGRESQL_USER;" | psql --dbname=postgres --username=$POSTGRESQL_USER
```
to "Restore database dump to the new postgresql container" step in awx-operator/roles/restore/tasks/postgres.yml

**Comment by fosterseth** [comment]
@rooftopcellist @TheRealHaoLiu can elaborate on the requirements for deleting AWX CR and the PVC before restoring?
