### ISSUE TITLE
AWX/Tower Clustering

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#16]
It would be nice to be able to run a clustered set of AWX / Towers as part of this operator as mentioned here: https://docs.ansible.com/ansible-tower/latest/html/administration/clustering.html.

**Comment by matburt** [comment]
You can actually do that by adjusting the replica count in your CR

https://github.com/ansible/awx-operator/blob/devel/roles/awx/templates/tower.yaml.j2#L22

Which we should, admittedly, document better if it's not already in the README or example CR.

**Comment by satellite-no** [comment]
@matburt was this ever documented? The link provide no longer works :(.  

I am actually looking to see if its possible to setup a hop instance to interact with other environments that do not directly have SSH access.  But these topics are sort or adjacent lol.
