### ISSUE TITLE
enable https in awx

### ISSUE THREAD

**Issue by alvis9515** [ansible/tower-operator#1622]
### Please confirm the following

- [ ] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [ ] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [ ] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hello team, I have installed awx with k3s, but now I want to enable https in awx, would I like to know what steps to follow for said execution?

In awx 2.6

Regards;

**Comment by kurokobo** [comment]
F.Y.I. This is the place to track bugs and RFEs so any usage questions should be asked on the forum 😃 
Seems you've create new topic on forum, so this issue should be closed: https://forum.ansible.com/t/how-to-enable-https-in-awx/2213
