### ISSUE TITLE
Cannot change the name to my Ansible Host (controlplane)

### ISSUE THREAD

**Issue by gtupini** [ansible/tower-operator#1632]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello,
My issue is that I deploy the cluster in an EC2 instance named "ansible" and everything goes fine, 
but when i change the hostname of the instance for testing purposes to "ansible-test" for example, the cluster automatically creates 2 control planes and doesn't deploy the pods, especially postgres. 
Maybe the problem is postgres and in consequence the other pods don't get deployed because of it.
I believe that this looks like an issue of state or reconciliation loop or state, but cannot find the place where the cluster expects the control plane to be named "ansible" and not "ansible-test". 
Can you help me?

### AWX Operator version

2.5.2

### AWX version

23.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

GitVersion:"v1.25.6+k3s1"

### Modifications

no

### Steps to reproduce

Install AWX-operator on Kubernetes.
Change hostname of the instance.

### Expected results

Postgres gets successfully deployed 

### Actual results

Postgres doesn't work

**Comment by fosterseth** [comment]
can you provide your awx spec file?

**Comment by gtupini** [comment]
![Screenshot 2023-11-20 at 11 16 32](https://github.com/ansible/awx-operator/assets/147523118/2a436d3a-cb4f-4998-86e3-2a341c2a7060)
Hello! thanks for getting back to me, is this file above ok? let me know

**Comment by kurokobo** [comment]
Maybe the node with the old hostname has been left in the cluster in `NotReady` state, and the PSQL pod is still tied to the old node.

StatefulSet strictly guarantees the number of pods, so even if a node is `NotReady`, k8s will not recreate the pod on another node.

Check the output from the following commands.

```bash
kubectl get node
kubectl -n awx get pod -o wide
```

It would be better to delete the old node after changing the hostname or fix the node name (`--node-name`) before changing the hostname.

**Comment by gtupini** [comment]
Thanks! We saw the nodeName resource in the yaml of our pods managed by the deployments thanks to your suggestion.
I believe this was the problem, thank you for your kind attention.
