### ISSUE TITLE
my awxrestore never ended (loop)

### ISSUE THREAD

**Issue by bskou57** [ansible/tower-operator#1649]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello All

I run awx restore via pod awxrestore but loop indefinitely

Seems that restore is fined but awxrestore pod never finish and always restart

Can you please advise '

Thanks for oyur support

### AWX Operator version

2.8.0

### AWX version

23.5.0

### Kubernetes platform

minikube

### Kubernetes/Platform version

v1.27.7+k3s2

### Modifications

no

### Steps to reproduce

I backup my current installation (awx 22.4.0 operator 2.7.0 succeefully

[root@ awx-on-k3s]# kubectl get awxbackup -n awx
NAME                   AGE
awxbackup-2023-27-11   20h
awxbackup-2023-26-11   33h
[root@ awx-on-k3s]# kubectl get awxrestore -n awx
NAME                    AGE
awxrestore-2023-27-11   17h
[root@

### Expected results

login successfully to https web interface but restore restart in loop

[root@kubectl get pods -n awx
NAME                                               READY   STATUS      RESTARTS      AGE
awx-postgres-13-0                                  1/1     Running     1 (16h ago)   17h
awx-operator-controller-manager-6c55dc66bd-4tdt8   2/2     Running     3 (16h ago)   3d10h
automation-job-8812-lz24r                          0/1     Completed   0             10h
awxrestore-2023-27-11-db-management                1/1     Running     0             116s
awx-web-d99945f44-xp295                            3/3     Running     0             57s
awx-task-7996c5b8d6-zz4r5                          4/4     Running     1 (33s ago)   64s

### Actual results

restore seems ok but
login successfully to https web interface but restore restart in loop

[root@kubectl get pods -n awx
NAME                                               READY   STATUS      RESTARTS      AGE
awx-postgres-13-0                                  1/1     Running     1 (16h ago)   17h
awx-operator-controller-manager-6c55dc66bd-4tdt8   2/2     Running     3 (16h ago)   3d10h
automation-job-8812-lz24r                          0/1     Completed   0             10h
awxrestore-2023-27-11-db-management                1/1     Running     0             116s
awx-web-d99945f44-xp295                            3/3     Running     0             57s
awx-task-7996c5b8d6-zz4r5                          4/4     Running     1 (33s ago)   64s

**Comment by jessicamack** [comment]
Hello, please provide the operator logs.

**Comment by rooftopcellist** [comment]
@bskou57 It sounds like you may have been hitting the issue fixed by this PR:
* https://github.com/ansible/awx-operator/pull/1652

Could you try again with the latest operator devel image?
* quay.io/ansible/awx-operator:devel

**Comment by bskou57** [comment]
Hello

works fine with latest awx operator

You can close the case

Thanks for your help

**Comment by rooftopcellist** [comment]
Thanks for the feedback, I'm glad it is working now with the recent changes!
