### ISSUE TITLE
how can I stop deployment ?

### ISSUE THREAD

**Issue by bskou57** [ansible/tower-operator#1650]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hi All

I just deployed application via kubectl apply -f  but loop

How can I stop deployment?

Thanks for your support

**Comment by jessicamack** [comment]
Hello, this question is not specific to the AWX project. Please check the kubernetes documentation https://kubernetes.io/docs/home/.

**Comment by rooftopcellist** [comment]
@bskou57 
Sidenote, to uninstall, you can run:

```
make undeploy
```

or to stop a specific deployment:

```
kubectl scale deployment <deployment-name> --replicas 0
```

More details in the k8s docs linked above
