### ISSUE TITLE
AWX restore never completes unless I clear out all job data and repeat backup and restore process

### ISSUE THREAD

**Issue by mcen1** [ansible/tower-operator#1653]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello.

I have a backup and restore that occurs nightly; each night, system A does an AWX backup as an awxbackup kubernetes object. This backup is transferred to system B, where it gets restored as an awxrestore object in kubernetes. This process works fine until some set of circumstances make it so the backup's equivalent restore object retries endlessly. If I go in to system A, run the AWX cleanup jobs (I am speaking of the management jobs inherent to AWX named Cleanup Activity Stream and Cleanup Job Details), then initiate the process again, this tends to fix whatever the problem is.

We don't have thousands upon thousands of jobs, I checked and tower.db is only 52.3 megabytes in my currently failing restore point, so I'm unsure what is wrong here. I would think it has something to do with data inside the postgresql db from the restore, but I'm not really seeing anything in the logs that helps me understand what's going wrong.

My apologies if this is something obvious or if I'm looking in the wrong place.

### AWX Operator version

2.3.0

### AWX version

22.4.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.22.17

### Modifications

no

### Steps to reproduce

I don't know if this is reproducible since I would assume other people would have witnessed it, but my process is as follows:
1. AWX job runs on system A on a nightly basis
2. System A awx job creates an awxbackup object in k8s
3. System A copies awxbackup object to System B
4. System B creates an awxrestore object based off System A's restore
5. Something about the restore makes AWX retry it indefinitely. Only workaround seems to be to clean up the job histories on System A and repeat the process.

### Expected results

I would expect the restore object to succeed, and indeed it does about 90% of the time (100% on lower environments) but it seems like something in the job history data makes it retry indefinitely.

### Actual results

AWX retries the restore indefinitely.

### Operator Logs

[operator-pod-log.txt](https://github.com/ansible/awx-operator/files/13528397/operator-pod-log.txt)

**Comment by rooftopcellist** [comment]
@mcen1 I believe this is happening because of a race condition between the restore role and the installer role of the new AWX instance both trying to access the DB at the same time.

It sounds like you may have been hitting the issue fixed by this PR:
* https://github.com/ansible/awx-operator/pull/1652

Could you try again with the latest operator devel image and let me know if that fixes your issue?
* quay.io/ansible/awx-operator:devel

**Comment by mcen1** [comment]
Seems like it might be related. It'll take a look time for us to be able to get to testing, so if the issue persists on that version, I'll re-open with new logs. Thanks!
