### ISSUE TITLE
how can I add https service to my running awx instance

### ISSUE THREAD

**Issue by bskou57** [ansible/tower-operator#1657]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hi

How can I add https service (with certificate) to my running awx instance ?

Thanks for your help

**Comment by fosterseth** [comment]
Hi! thanks for your question

you can ask user guide types of questions on the new ansible forum

https://forum.ansible.com/tags/c/help/6/none/awx

Github is for tracking bugs/features, so closing this issue for now
