### ISSUE TITLE
Cannot change "project base path"  in "awx-operator"  to my local OS directory /opt/awx/projects

### ISSUE THREAD

**Issue by ScorpionKing34** [ansible/tower-operator#1663]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I follow this tutorial 'https://computingforgeeks.com/how-to-install-ansible-awx-on-debian-buster/?expand_article=1' to install the new AWX on Debian, but I am unable to mount my local  '/opt/awx/projects' on the k3s Kubernetes. I also tried it on Ubuntu with tutorial 'https://computingforgeeks.com/how-to-install-ansible-awx-on-ubuntu-linux/'.

Both shows only '/var/lib/projects' in the web ui under new project:
![afbeelding](https://github.com/ansible/awx-operator/assets/39624641/e05f25e4-ced4-483a-943a-a13d71b86ad5)

### AWX Operator version

2.7.2

### AWX version

unknown

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.27.7 & Kustomize 5.2.1

### Modifications

no

### Steps to reproduce

I follow this tutorial 'https://computingforgeeks.com/how-to-install-ansible-awx-on-debian-buster/?expand_article=1'

Also tried with the following option under extra_volumes no luck.
    hostPath:
    path: /opt/awx/projects
    type: Directory
    name: os-mount

### Expected results

Selections of project folder Project_A or Project_B that contains basic inventory file.

### Actual results

But still I got the following:
![afbeelding](https://github.com/ansible/awx-operator/assets/39624641/dbd1045c-79da-4fa7-ab58-866a8dead136)

**Comment by kurokobo** [comment]
If you are finding the solution, could you please close this issue and open new topic on the Get Help category on the forum: https://forum.ansible.com/

F.Y.I., the Issues page here is the place for devs to track bugs and RFEs, not the place to ask usage questions.

**Comment by ScorpionKing34** [comment]
I did that already and for my this is a bug, because there are no tutorials or installation found to solve this issue. Side question: Why can AWX operator not directly installed on the OS without kubernetes or docker?

I hope that someone here can help me?

**Comment by fosterseth** [comment]
@ScorpionKing34 awx operator must be used on K8S cluster

**Comment by robo8619** [comment]
I see that this was closed but im not seeing a solution for the issue. 
Im having a similar issue with my install. The project base path /var/lib/awx/projects is not usable. 
Im finding many tutorials on installing kubernetes and awx but not much on the after install setup. 

![image](https://github.com/user-attachments/assets/c6978c90-235d-4ffe-a3c6-37064c195898)

**Comment by ScorpionKing34** [comment]
Sorry for a very late response, but do to other activities I did and do not have the time to test ansible.
