### ISSUE TITLE
[DOCS] "Adding Execution Nodes" should not be under "Disable IPV6"

### ISSUE THREAD

**Issue by kurokobo** [ansible/tower-operator#1672]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The documentation "Adding Execution Nodes" is under "Disable IPv6" section. This is completely different topic from IPv6-thing.

https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/advanced-configuration/disable-ipv6.html

### AWX Operator version

latest

### AWX version

N/A

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

N/A

### Modifications

no

### Steps to reproduce

See the docs: https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/advanced-configuration/disable-ipv6.html

### Expected results

"Adding Execution Nodes" should be placed as an independent page.

### Actual results

"Adding Execution Nodes" is placed under "Disable IPV6"

### Additional information

I don't know where "Adding Execution Nodes" should be placed, but it would be better to place it as an independent page under "Advanced Configuration" or "User Guide".

**Comment by jessicamack** [comment]
Hello @kurokobo, thank you for catching this. You're right and an independent page under "Advanced Configuration" is fine.

**Comment by tvo318** [comment]
See also PR https://github.com/ansible/awx-operator/pull/1684
