### ISSUE TITLE
[CI] Add check for building docs

### ISSUE THREAD

**Issue by tvo318** [ansible/tower-operator#1685]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

We need CI to post docs PRs up on RTD for preview. That would help for sure to verify things are working.
See the one made for AWX docs: https://github.com/ansible/awx/pull/14406

**Comment by oraNod** [comment]
@tvo318 As part of this I would like to suggest that we add either tox or nox as a virtual session manager. How could we bring this to the team for discussion?

AWX uses tox and it has many benefits, including the plus of being consistent across projects. At the same time nox is a solid option that uses a Python file, which could be preferable to the INI format of tox.
