### ISSUE TITLE
[DOCS] Use "stable" version as default version

### ISSUE THREAD

**Issue by kurokobo** [ansible/tower-operator#1692]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

The current documentation has two versions; `latest` and `stable`, and ["default version"](https://docs.readthedocs.io/en/stable/glossary.html#term-default-version) is configured as `latest`.

This means:

- [`latest` follows upstream `devel` branch, and `stable` follows the latest tagged release](https://docs.readthedocs.io/en/stable/versions.html)
- ["default version"](https://docs.readthedocs.io/en/stable/glossary.html#term-default-version) is used to the redirection from `/`, currently `/` redirects to the `latest` (`/en/latest/`)

Since the `latest` follows upstream `devel` branch, it may contain unreleased feature. This can cause users to not be able to use Operator as documented and be confusing to users, such as the issue https://github.com/ansible/awx-operator/issues/1691.

My suggestions are:

- [x] Update the link on the `README.md` to point `https://awx-operator.readthedocs.io/` (means `/`) or `https://awx-operator.readthedocs.io/en/stable/` instead of `latest`: Done by #1693 
- [x] Configure "default version" to `stable` (this can via `Admin` > `Advanced Settings` on the project page on the Read the Docs)

**Comment by kurokobo** [comment]
Thanks for merging #1693, this issue is 50% done.

If admins agree with my proposal, could you please perform the following task?

> Configure "default version" to `stable` (this can via `Admin` > `Advanced Settings` on the project page on the Read the Docs)

**Comment by oraNod** [comment]
@kurokobo Hi, apologies for the bit of delay here as I've been traveling. I switched the default version in readthedocs to the stable build and verified the changes. `awx-operator/en/stable/` should be the default now and currently corresponds to the 2.11 tag. Please take a look and confirm.

@thedoubl3j and @fosterseth On a related note, should I add either of you or anyone else as a maintainer in readthedocs so I'm not a bottleneck for these sorts of changes?

Thanks!

**Comment by kurokobo** [comment]
@oraNod
Hi, I'm sure you had a great travel😃 Thanks for working on this!
Confirmed that the link in README.md redirects `stable` version of the docs, so will close this issue. Thanks!

**Comment by rooftopcellist** [comment]
@kurokobo I think that since we have such a fast release cadence, and to reduce confusion about which users should be looking at, we could just keep the single `latest` docs stream.  That way it will also remain consistent with the other repos.

**Comment by oraNod** [comment]
@kurokobo Yes, I guess this was partly my mistake as well. Hopefully I didn't give you a wrong impression by enabling the stable version. You had made some valid points but it was something that I should have discussed more thoroughly with the wider team first. My apologies for any confusion and thanks again!

**Comment by kurokobo** [comment]
@rooftopcellist  @oraNod Thanks for pointing that out, I want to respect your team's decision so there is completely no problem to revert the changes!
