### ISSUE TITLE
[DOCS] Read the Docs failed to build latest docs

### ISSUE THREAD

**Issue by kurokobo** [ansible/tower-operator#1718]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

See the latest state: <https://readthedocs.org/projects/awx-operator/builds/>

- https://readthedocs.org/projects/awx-operator/builds/23458335/ (`stable` build)
- https://readthedocs.org/projects/awx-operator/builds/23457574/ (`latest` build)

The new docs for AWXMeshIngress (#1706) does not shown in the live docs page (both `stable` and `latest`):

- https://ansible.readthedocs.io/projects/awx-operator/en/latest/
- https://ansible.readthedocs.io/projects/awx-operator/en/stable/

### AWX Operator version

2.12.1

### AWX version

23.8.1

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

N/A

### Modifications

no

### Steps to reproduce

See the page: https://ansible.readthedocs.io/projects/awx-operator/en/latest/

### Expected results

There is a new doc for AWXMeshIngress

### Actual results

No doc for AWXMeshIngress

**Comment by kurokobo** [comment]
@TheRealHaoLiu 
F.Y.I.

**Comment by fosterseth** [comment]
should be fixed now, thank you
