### ISSUE TITLE
fail to deploy awx - Error from server (BadRequest): a container name must be specified for pod 

### ISSUE THREAD

**Issue by guntis-liepins** [ansible/tower-operator#178]
First time attempt to deploy simple AWX instance with awx operator

    ---
    apiVersion: awx.ansible.com/v1beta1
    kind: AWX
    metadata:
      name: awx
      namespace: awx
    spec:
      deployment_type: awx
      tower_ingress_type: Ingress
      tower_hostname: awx.test.org
      tower_ingress_tls_secret: awx-tls
      tower_admin_user: admin
      tower_admin_email: admin@test.org
      tower_admin_password_secret: awx-admin-password
     

Deployment fails, container stays in pending state:

    [z@alpha awx]$ kubectl get all -n awx
    NAME                       READY   STATUS    RESTARTS   AGE
    pod/awx-768cc86749-4r8pw   0/4     Pending   0          18m
    pod/awx-postgres-0         1/1     Running   0          19m    
    NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
    service/awx-postgres   ClusterIP   None             <none>        5432/TCP       19m
    service/awx-service    NodePort    172.19.100.180   <none>        80:30956/TCP   18m    
    NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
    deployment.apps/awx   0/1     1            0           18m    
    NAME                             DESIRED   CURRENT   READY   AGE
    replicaset.apps/awx-768cc86749   1         1         0       18m
    NAME                            READY   AGE
    statefulset.apps/awx-postgres   1/1     19m

Ingress is created

    [z@alpha awx]$ kubectl get ing -n awx
    NAME          HOSTS          ADDRESS        PORTS     AGE
    awx-ingress   awx.test.org   10.99.86.100   80, 443   20m

Looking into logs i see following error:

    [z@alpha awx]$ kubectl logs -n awx awx-768cc86749-4r8pw
    Error from server (BadRequest): a container name must be specified for pod awx-768cc86749-4r8pw, choose one of: 
    [redis awx-web awx-task awx-ee]

Version:
awx-operator.yml , commit 550756c 
Kubernetes version: Nutanix Karbon, Server Version: v1.17.13

**Comment by shanemcd** [comment]
As you can see, it says `choose one of: [redis awx-web awx-task awx-ee]`

So you'll need to do something like:

```
$ kubectl logs -n awx awx-768cc86749-4r8pw -c awx-task
```

**Comment by guntis-liepins** [comment]
[z@alpha awx]$ kubectl logs -n awx awx-768cc86749-4r8pw
    Error from server (BadRequest): a container name must be specified for pod awx-768cc86749-4r8pw, choose one of:  
    [redis awx-web awx-task awx-ee]
    [guntis@alpha awx]$ kubectl logs -n awx awx-768cc86749-4r8pw -c redis
    [guntis@alpha awx]$ kubectl logs -n awx awx-768cc86749-4r8pw -c awx-web
    [guntis@alpha awx]$ kubectl logs -n awx awx-768cc86749-4r8pw -c awx-task
    [guntis@alpha awx]$ kubectl logs -n awx awx-768cc86749-4r8pw -c awx-ee

this return nothing
