### ISSUE TITLE
Install a specific version of awx

### ISSUE THREAD

**Issue by MrAmbiG** [ansible/tower-operator#179]
We need to install a specific version of awx  since all of our existing code depends and works with that version of awx but there is no way of mentioning the version of awx with the operator.

**Comment by ryanpetrello** [comment]
@MrAmbiG,

AWX 18.0.0 is the first version that reliably works with this operator.

If you want to install an older version of AWX, follow version-specific instructions:

https://github.com/ansible/awx/blob/17.1.0/INSTALL.md#installing-awx

**Comment by MrAmbiG** [comment]
@ryanpetrello That is what i had to do, is there any future plans to support older versions? Would you also please have an option in the awx config to mention a version (supported versions ) so that when this operator+awx grows, users will have an option to choose from.
