### ISSUE TITLE
Support for external PostgreSQL cluster client-side High Availability

### ISSUE THREAD

**Issue by AymericP35** [ansible/tower-operator#1792]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Add ability to deploy an AWX instance with an external PostgreSQL cluster using client-side High Availability mode.

According to the [PostgreSQL documentation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-TARGET-SESSION-ATTRS), when using client-side High Availability, you must change the `target_session_attrs` default value `any` to `read-write` in order to select the primary postgreSQL server.

To allow such behavior, I suggest the following :

- Adjusting the Jinja template [credentials.py.j2](https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/settings/credentials.py.j2) to allow target_session_attrs option ;
- Add `awx_postgres_target_session_attrs` var in [database_configuration.yml](https://github.com/ansible/awx-operator/blob/devel/roles/installer/tasks/database_configuration.yml) ;
- Update [database-configuration.md](https://github.com/ansible/awx-operator/blob/devel/docs/user-guide/database-configuration.md) documentation.

**Comment by moonrail** [comment]
fyi, a non-configurable default approach was proposed in 2022 and actually approved, but never merged: #928

I've just now retested if AWX 24 can run with readonly PostgreSQL-Instances and the answer is: No, it cannot.
There is no benefit to not setting `target_session_attrs` to `read-write`. And there is no harm in doing so.
