### ISSUE TITLE
Container Error after restart

### ISSUE THREAD

**Issue by Uzzi** [ansible/tower-operator#181]
**ENVIRONMENT**

    AWX version: 18.0.0
    AWX install method: minikube, awx-operator
    Operating System: Debian Buster

I've to restart VM, than I've restarted minikube by  minikube start --driver=none --addons=ingress
awx-postgres-0                 0/1     CreateContainerConfigError

In  minikube kubectl logs -- -f awx-postgres-0:
`failed to try resolving symlinks in path "/var/log/pods/default_awx-postgres-0_2b3e5eb7-9649-429d-970c-efe20caa9c38/postgres/1.log": lstat /var/log/pods/default_awx-postgres-0_2b3e5eb7-9649-429d-970c-efe20caa9c38/postgres/1.log:`

How can I fix it?

**Comment by shanemcd** [comment]
This doesn't look like a problem with our operator. This is an issue tracker, not a tech support hotline 😄
