### ISSUE TITLE
Container image quay.io/ansible/awx:24.2.0 not found

### ISSUE THREAD

**Issue by florianbeer** [ansible/tower-operator#1817]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

This morning (CET) I installed the new awx-operator release to get rid of the websocket bug that has been bugging us.
Unfortunately it seems that the AWX image has not been uploaded to quay.io yet, so all my new pods are now stuck in ImagePullBackOff.

According to quay.io the last image upload was two weeks ago:
<img width="1774" alt="Screenshot 2024-04-10 at 08 48 33" src="https://github.com/ansible/awx-operator/assets/800047/b9b37a45-ee18-4247-a20f-ed829257b053">

### AWX Operator version

2.15.0

### AWX version

24.2.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.26.4

### Modifications

no

### Steps to reproduce

```
helm repo update
helm upgrade -n awx awx-operator awx-operator/awx-operator -f values.yml
```

### Expected results

New version of AWX starting up

### Actual results

ImagePullBackOff because container image is not available at registry

**Comment by florianbeer** [comment]
Seems to be related to this issue: https://github.com/ansible/awx/issues/15088

**Comment by kurokobo** [comment]
Publishing `awx-operator` image is triggered on ansible/awx repo instead of this repo.
Related to: https://github.com/ansible/awx/issues/15088

**Comment by florianbeer** [comment]
New image was successfully pushed.
