### ISSUE TITLE
awx-migration pod stuck in Completed

### ISSUE THREAD

**Issue by r1200gsdave** [ansible/tower-operator#1835]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I have just upgraded from 2.12.0 to 2.14.0 and there are two migration pods that are stuck in Completed status.

### AWX Operator version

2.14.0

### AWX version

AWX 24.1.0

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

EKS

### Modifications

no

### Steps to reproduce

Upgrade with 
kubectl apply -k .

### Expected results

kubectl  get pods -n awx
NAME                                               READY   STATUS      RESTARTS   AGE
awx-migration-23.8.0-g4jbr                         0/1     Completed   0          8m49s
awx-migration-24.1.0-c9j7j                         0/1     Completed   0          7m23s
awx-operator-controller-manager-6458cd4798-p5v7l   2/2     Running     0          10m
awx-task-775dc8f697-gkbnr                          4/4     Running     0          9m
awx-web-85d89959bf-kj2nn                           3/3     Running     0          9m2s

### Actual results

Everything seems functional.

### Additional information

kubectl logs awx-migration-23.8.0-g4jbr -n awx
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, dab_resource_registry, main, oauth2_provider, sessions, sites, social_django, sso
Running migrations:
  Applying dab_resource_registry.0001_initial... OK
  Applying dab_resource_registry.0002_remove_resource_id... OK
  Applying dab_resource_registry.0003_alter_resource_object_id... OK
  Applying main.0190_alter_inventorysource_source_and_more... OK
  
kubectl logs awx-migration-24.1.0-c9j7j -n awx
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, dab_resource_registry, main, oauth2_provider, sessions, sites, social_django, sso
Running migrations:
  No migrations to apply.

### Operator Logs

[awx-test-operator.logs.txt](https://github.com/ansible/awx-operator/files/15045216/awx-test-operator.logs.txt)

**Comment by r1200gsdave** [comment]
I just confirmed that the pods are still there.  Can I safely delete them?
 kubectl get pods -n awx
NAME                                               READY   STATUS      RESTARTS   AGE
awx-migration-23.8.0-g4jbr                         0/1     Completed   0          3d18h
awx-migration-24.1.0-c9j7j                         0/1     Completed   0          3d18h
awx-operator-controller-manager-6458cd4798-p5v7l   2/2     Running     0          3d18h
awx-task-775dc8f697-gkbnr                          4/4     Running     0          3d18h
awx-web-85d89959bf-kj2nn                           3/3     Running     0          3d18h

**Comment by tchellomello** [comment]
I would say they are not stuck but Completed instead. 

And yes, you can remove it

**Comment by r1200gsdave** [comment]
Thanks for confirming.
