### ISSUE TITLE
unable to start task container on awx v24.3.1

### ISSUE THREAD

**Issue by vivekshete9** [ansible/tower-operator#1850]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I updated awx-operator and awx images to latest version. But with this new deployment awx-task pod is unable to move pass init state. Container inside task pod -init-database container is running but init-receptor is stuck in waiting state

### AWX Operator version

2.16.1

### AWX version

24.3.1

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.28.7

### Modifications

yes

### Steps to reproduce

Upgrade to latest versions of awx operator and awx 

### Expected results

all pods and container spins up properly

### Actual results

awx-task pos stuck in init state

**Comment by vivekshete9** [comment]
```
awx-operator-controller-manager-5fdsfdsfbb-9645l   2/2     Running    0             60m
awx-postgres-15-0                           1/1     Running    0             33m
awx-task                   0/4     Init:0/2   0             55m
awx-web                    3/3     Running    2 (33m ago)   55m
```

And the migration keeps continuing even though its a fresh installation 

```
kubectl logs awx-task -c init-database -n awx
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1
[wait-for-migrations] Waiting 0.5 seconds before next attempt
[wait-for-migrations] Attempt 2
[wait-for-migrations] Waiting 1 seconds before next attempt
[wait-for-migrations] Attempt 3
[wait-for-migrations] Waiting 2 seconds before next attempt
[wait-for-migrations] Attempt 4
[wait-for-migrations] Waiting 4 seconds before next attempt
[wait-for-migrations] Attempt 5
[wait-for-migrations] Waiting 8 seconds before next attempt
[wait-for-migrations] Attempt 6
[wait-for-migrations] Waiting 16 seconds before next attempt
[wait-for-migrations] Attempt 7
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 8
[wait-for-migrations] Waiting 30 seconds before next attempt
```

**Comment by vivekshete9** [comment]
also those 2 init containers were not part of previous deployments. Looks like they got added to new versions.

**Comment by vivekshete9** [comment]
running below command on awx-web pod helped to spin up task pod correctly. However I am not able to use `awx-admin-password` secrets to login to the tower UI.

`awx-manage migrate --noinput`

**Comment by YaronL16** [comment]
@vivekshete9 It's suggested to first create a secret then set it as the admin-password-secret when installing the operator.

But if you just want to sign in you can use `awx-manage changepassword admin` on the awx-web pod

**Comment by vivekshete9** [comment]
Running below command on web pod helped

`kubectl exec pod/<awx_pod_name> --container awx-web -it awx-manage createsuperuser`

**Comment by fgardelli** [comment]
thanks @vivekshete9 for the hints, do you know how I can run the "awx-manage migrate" to fix the task pod stuck, but without losing all the exsisting configurations?
