### ISSUE TITLE
CrashLoopBackoff awx-operator-controller-manager - failed to wait for awxmeshingress-controller caches to sync

### ISSUE THREAD

**Issue by kurthv** [ansible/tower-operator#1851]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The awx-operator-controller-manager pod is constantly restarting, because of a CrashLoopBackoff.
In the operator logs I find the following error: "failed to wait for awxmeshingress-controller caches to sync".

### AWX Operator version

2.12.1

### AWX version

23.8.1

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.24.1 

### Modifications

no

### Steps to reproduce

Upgrade AWX Operator to v2.12.1

### Expected results

The awx-operator-controller-manager pod should run without constant restarts.

### Actual results

I can observe the following steps in an endless loop:
- awx-operator-controller-manager pod starts
- after 2-3 minutes it ends in CrashLoopBackoff state
- Back-off restarting failed container

### Operator Logs

awx-manager --------------------------- Ansible Task StdOut -------------------------------
awx-manager 
awx-manager TASK [installer : Remove ownerReferences reference] ****************************
awx-manager task path: /opt/ansible/roles/installer/tasks/cleanup.yml:12
awx-manager 
awx-manager -------------------------------------------------------------------------------
awx-manager {"level":"error","ts":"2024-05-03T12:53:42Z","logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"AWXMeshIngress.awx.ansible.com","error":"no matches for kind \"AWXMeshIngress\" in version \"awx.ansible.com/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:143\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:662\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:596\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:547\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:136"}
awx-manager {"level":"info","ts":"2024-05-03T12:53:42Z","logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/api/v1/namespaces/awx/secrets/awx-install-admin-password","Verb":"get","APIPrefix":"api","APIGroup":"","APIVersion":"v1","Namespace":"awx","Resource":"secrets","Subresource":"","Name":"awx-install-admin-password","Parts":["secrets","awx-install-admin-password"]}}
awx-manager 
awx-manager --------------------------- Ansible Task StdOut -------------------------------
awx-manager 
awx-manager  TASK [Remove ownerReferences reference] ******************************** 
awx-manager ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
awx-manager 
awx-manager -------------------------------------------------------------------------------
awx-manager {"level":"info","ts":"2024-05-03T12:53:43Z","logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/api/v1/namespaces/awx/secrets/awx-install-secret-key","Verb":"get","APIPrefix":"api","APIGroup":"","APIVersion":"v1","Namespace":"awx","Resource":"secrets","Subresource":"","Name":"awx-install-secret-key","Parts":["secrets","awx-install-secret-key"]}}
awx-manager 
awx-manager --------------------------- Ansible Task StdOut -------------------------------
awx-manager 
awx-manager  TASK [Remove ownerReferences reference] ******************************** 
awx-manager ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
awx-manager 
awx-manager -------------------------------------------------------------------------------
awx-manager {"level":"info","ts":"2024-05-03T12:53:44Z","logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/api/v1/namespaces/awx/secrets/awx-install-postgres-configuration","Verb":"get","APIPrefix":"api","APIGroup":"","APIVersion":"v1","Namespace":"awx","Resource":"secrets","Subresource":"","Name":"awx-install-postgres-configuration","Parts":["secrets","awx-install-postgres-configuration"]}}
awx-manager 
awx-manager --------------------------- Ansible Task StdOut -------------------------------
awx-manager 
awx-manager  TASK [Remove ownerReferences reference] ******************************** 
awx-manager ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
awx-manager 
awx-manager -------------------------------------------------------------------------------
awx-manager {"level":"info","ts":"2024-05-03T12:53:44Z","logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/api/v1/namespaces/awx/secrets/awx-install-broadcast-websocket","Verb":"get","APIPrefix":"api","APIGroup":"","APIVersion":"v1","Namespace":"awx","Resource":"secrets","Subresource":"","Name":"awx-install-broadcast-websocket","Parts":["secrets","awx-install-broadcast-websocket"]}}
awx-manager 
awx-manager --------------------------- Ansible Task StdOut -------------------------------
awx-manager 
awx-manager  TASK [Remove ownerReferences reference] ******************************** 
awx-manager ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
awx-manager 
awx-manager -------------------------------------------------------------------------------
awx-manager {"level":"info","ts":"2024-05-03T12:53:45Z","logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/api/v1/namespaces/awx/secrets/awx-install-receptor-ca","Verb":"get","APIPrefix":"api","APIGroup":"","APIVersion":"v1","Namespace":"awx","Resource":"secrets","Subresource":"","Name":"awx-install-receptor-ca","Parts":["secrets","awx-install-receptor-ca"]}}
awx-manager 
awx-manager --------------------------- Ansible Task StdOut -------------------------------
awx-manager 
awx-manager  TASK [Remove ownerReferences reference] ******************************** 
awx-manager ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
awx-manager 
awx-manager -------------------------------------------------------------------------------
awx-manager {"level":"info","ts":"2024-05-03T12:53:46Z","logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/api/v1/namespaces/awx/secrets/awx-install-receptor-work-signing","Verb":"get","APIPrefix":"api","APIGroup":"","APIVersion":"v1","Namespace":"awx","Resource":"secrets","Subresource":"","Name":"awx-install-receptor-work-signing","Parts":["secrets","awx-install-receptor-work-signing"]}}
awx-manager 
awx-manager --------------------------- Ansible Task StdOut -------------------------------
awx-manager 
awx-manager  TASK [Remove ownerReferences reference] ******************************** 
awx-manager ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
awx-manager 
awx-manager -------------------------------------------------------------------------------
awx-manager 
awx-manager --------------------------- Ansible Task StdOut -------------------------------
awx-manager 
awx-manager TASK [installer : Start installation if auto_upgrade is false and deployment is missing] ***
awx-manager task path: /opt/ansible/roles/installer/tasks/main.yml:31
awx-manager 
awx-manager -------------------------------------------------------------------------------
awx-manager {"level":"info","ts":"2024-05-03T12:53:46Z","logger":"logging_event_handler","msg":"[playbook task start]","name":"awx-install","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"1547027750300556243","EventData.Name":"installer : Start installation if auto_upgrade is false and deployment is missing"}
awx-manager {"level":"info","ts":"2024-05-03T12:53:46Z","logger":"runner","msg":"Ansible-runner exited successfully","job":"1547027750300556243","name":"awx-install","namespace":"awx"}
awx-manager 
awx-manager ----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx-install/awx) -----
awx-manager 
awx-manager 
awx-manager PLAY RECAP *********************************************************************
awx-manager localhost                  : ok=89   changed=1    unreachable=0    failed=0    skipped=78   rescued=0    ignored=1   
awx-manager 
awx-manager ----------
awx-manager {"level":"error","ts":"2024-05-03T12:53:52Z","logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"AWXMeshIngress.awx.ansible.com","error":"no matches for kind \"AWXMeshIngress\" in version \"awx.ansible.com/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:143\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:662\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:596\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:547\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:136"}
awx-manager {"level":"error","ts":"2024-05-03T12:54:02Z","logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"AWXMeshIngress.awx.ansible.com","error":"no matches for kind \"AWXMeshIngress\" in version \"awx.ansible.com/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:143\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:662\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:596\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:547\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:136"}
awx-manager {"level":"error","ts":"2024-05-03T12:54:12Z","logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"AWXMeshIngress.awx.ansible.com","error":"no matches for kind \"AWXMeshIngress\" in version \"awx.ansible.com/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:143\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:662\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:596\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:547\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:136"}
awx-manager {"level":"error","ts":"2024-05-03T12:54:22Z","msg":"Could not wait for Cache to sync","controller":"awxmeshingress-controller","error":"failed to wait for awxmeshingress-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:211\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:242\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/manager/runnable_group.go:219"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"Stopping and waiting for non leader election runnables"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"Stopping and waiting for leader election runnables"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"Shutdown signal received, waiting for all workers to finish","controller":"awxbackup-controller"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"All workers finished","controller":"awxbackup-controller"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"Shutdown signal received, waiting for all workers to finish","controller":"awxrestore-controller"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"All workers finished","controller":"awxrestore-controller"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"Shutdown signal received, waiting for all workers to finish","controller":"awx-controller"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"All workers finished","controller":"awx-controller"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"Stopping and waiting for caches"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"Stopping and waiting for webhooks"}
awx-manager {"level":"info","ts":"2024-05-03T12:54:22Z","msg":"Wait completed, proceeding to shutdown the manager"}
awx-manager {"level":"error","ts":"2024-05-03T12:54:22Z","logger":"cmd","msg":"Proxy or operator exited with error.","Namespace":"awx","error":"failed to wait for awxmeshingress-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"github.com/operator-framework/ansible-operator-plugins/internal/cmd/ansible-operator/run.run\n\tansible-operator-plugins/internal/cmd/ansible-operator/run/cmd.go:287\ngithub.com/operator-framework/ansible-operator-plugins/internal/cmd/ansible-operator/run.NewCmd.func1\n\tansible-operator-plugins/internal/cmd/ansible-operator/run/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\tansible-operator-plugins/cmd/ansible-operator/main.go:40\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/proc.go:250"}
Stream closed EOF for awx/awx-operator-controller-manager-576465d655-bhl84 (awx-manager)

**Comment by kurokobo** [comment]
Dup of: https://github.com/ansible/awx-operator/issues/1701

Please apply CRD changes: https://github.com/ansible/awx-operator/tree/devel/.helm/starter#caveats-on-upgrading-existing-installation

**Comment by kurthv** [comment]
@kurokobo Thank you very much!

I used the following command:
kubectl apply --server-side --force-conflicts -k github.com/ansible/awx-operator/config/crd?ref="2.12.1"

No restarts in the last 15 minutes :-)

**Comment by kurokobo** [comment]
@kurthv 
Hi, thanks for updating, glad that worked 😃 
Could you please close this issue if the issue has been solved? Thanks!
