### ISSUE TITLE
Postgres persistent volume reclaiming

### ISSUE THREAD

**Issue by PieterPaulussen** [ansible/tower-operator#1860]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

I've been experimenting with the AWX operator and deploying it to a cluster.

After tossing around some values and re-configuring the cluster, I had to remove my deployment and re-initialise it. However, I came to the conclusion that the postgres persistent volume did not get reclaimed by the new postgres pod when running a managed deployment.

Should the postgres volume not always be retained and reclaimed after a redeployment of the same chart? Or at least design the deployment in such a way that you cannot lose data by default?

FYI: The postgres persistent volumes reclaim policy is 'delete' not 'retain'.

**Comment by thedoubl3j** [comment]
This is a behavior that can be configured on the storage class for your kubernetes. The current workflow is if the pvc is deleted, the pv will also be deleted.

We currently don't configure that policy and nor do we have plans too currently.
