### ISSUE TITLE
Feature Wants: kubectel delete -k . should only delete all the awx resources, but not the entire namespace 

### ISSUE THREAD

**Issue by wangzhihaocom** [ansible/tower-operator#1864]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Currently., when I deploy the awx in the existing namespace, I use kustomization.yaml
kubectl apply -k . command ,

but when I want to delete all the resources, I use kubectl delete -k .

It will terminate all the resources, as well as the entire existing namespace( including our other existing pod in the namespace), which is not good.

Is there a better to just delete all the awx resource but not to delete the entire namespace?

This is my kustomization.yaml
```kind: Kustomization
namespace: devops

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=<host>
      - port=<port>
      - database=<db>
      - username=<user>
      - password=<password>
      - type=unmanaged
      - sslmode=prefer

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=admin

resources:
  - github.com/ansible/awx-operator/config/default?ref=2.16.1
  - awx.yaml

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.16.1

**Comment by TheRealHaoLiu** [comment]
> @rooftopcellist I am using this command to delete the AWX resources, the resources got deleted but I got some error at the end . so that my gitlab CICD job failed. Is this command correct?

> kubectl kustomize . | sed '/kind: Namespace/,+5d' | kubectl delete -f - 
```
customresourcedefinition.apiextensions.k8s.io "awxbackups.awx.ansible.com" deleted > customresourcedefinition.apiextensions.k8s.io "awxmeshingresses.awx.ansible.com" deleted > customresourcedefinition.apiextensions.k8s.io "awxrestores.awx.ansible.com" deleted customresourcedefinition.apiextensions.k8s.io "awxs.awx.ansible.com" deleted serviceaccount "awx-operator-controller-manager" deleted role.rbac.authorization.k8s.io "awx-operator-awx-manager-role" deleted role.rbac.authorization.k8s.io "awx-operator-leader-election-role" deleted clusterrole.rbac.authorization.k8s.io "awx-operator-metrics-reader" deleted clusterrole.rbac.authorization.k8s.io "awx-operator-proxy-role" deleted rolebinding.rbac.authorization.k8s.io "awx-operator-awx-manager-rolebinding" deleted rolebinding.rbac.authorization.k8s.io "awx-operator-leader-election-rolebinding" deleted clusterrolebinding.rbac.authorization.k8s.io "awx-operator-proxy-rolebinding" deleted configmap "awx-operator-awx-manager-config" deleted secret "awx-admin-password" deleted secret "awx-postgres-configuration" deleted service "awx-operator-controller-manager-metrics-service" deleted deployment.apps "awx-operator-controller-manager" deleted ingress.networking.k8s.io "awx" deleted Error from server (NotFound): error when deleting "STDIN": the server could not find the requested resource (delete awxs.awx.ansible.com awx)
```

here's the last thing you posted on #ansible/awx#15173

so basically there's a "order of operation" that need to happen when deleting 

we need to delete awx customresource before deleting the operator and crds (or else the deployments gets orphaned and nothing is left to clean it up)

i do not think `kubectl delete -k` will be do able u might be able to script around it something like

```bash
namespace=`cat kustomization.yaml | grep namespace | awk -F ' ' '{print $2}'`
kubectl delete awx --all -n ${namespace} # delete all awx instance in the namespace 
kubectl kustomize . | sed '/kind: Namespace/,+5d' | kubectl delete -f - # proceed to delete the operator
```

note this will retain the postgres PVC so if u want that gone u also need to explicitly delete that 


this is not a feature we looking to support in the project if you have any further question we can start a discussion thread on the forum.ansible.com

**Comment by kevrrnet** [comment]
This is still an issue/bug, it just delete my entire namespace, very bad , please fix.

**Comment by honza801** [comment]
Hi, we have run into the same issue. Deleting the awx results in deleting the whole namespace. Please fix.

**Comment by honza801** [comment]
I have digged little bit deeper into the issue and probably found the main problem/solution.

Do not advise users to put awx-operator and aws resource in the same kustomization in the documentation
```
...
resources:
  - github.com/ansible/awx-operator/config/default?ref=<tag>
  # Add this extra line:
  - awx-demo.yml # This should be definitely avoided
...
```
https://ansible.readthedocs.io/projects/awx-operator/en/latest/installation/basic-install.html

Instead new kustomization should be created for awx resources.

I can do a PR if interested.

Jan
