### ISSUE TITLE
Update AWX Operator 2.18 to 2.19:   'web_manage_replicas' is undefined

### ISSUE THREAD

**Issue by laboef1900** [ansible/tower-operator#1907]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When I upgrade AWX Operator with Helm then the upgrade procedure fails with the error: the task includes an option with an undefined variable. The error was: 'web_manage_replicas' is undefined. 'web_manage_replicas' is undefined. 'web_manage_replicas' is undefined

I found this in the documentation and tried to set the replicas option. But I'm not sure if I did it right also not sure if I missed something to configure or if it's a bug. 
(https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/advanced-configuration/scaling-the-web-and-task-pods-independently.html)

### AWX Operator version

2.18

### AWX version

24.5

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.28.2

### Modifications

no

### Steps to reproduce

**Upgrade from Operator 2.18 to 2.19**
helm upgrade awx-operator awx-operator/awx-operator -n awx  -f awx.yml

**My awx.yml**
```
AWZ
  enabled: true
  name: awx
  spec:
    admin_user: admin
    ingress_type: ingress
    ingress_hosts:
      - hostname: awx.domain.com
        tls_secret: awx-tls-secret
    ldap_cacert_secret: pki-custom-certs
    replicas: 1
```

### Expected results

Successfully upgrade to 2.19 as you did from 2.17 to 2.18

### Actual results

Failed deploymend

### Operator Logs

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Apply deployment resources] **********************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:248

-------------------------------------------------------------------------------
{"level":"error","ts":"2024-06-25T08:05:53Z","logger":"logging_event_handler","msg":"","name":"awx","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"runner_on_failed","job":"6632158980437416248","EventData.Task":"Apply deployment resources","EventData.TaskArgs":"","EventData.FailedTaskPath":"/opt/ansible/roles/installer/tasks/resources_configuration.yml:248","error":"[playbook task failed]","stacktrace":"github.com/operator-framework/ansible-operator-plugins/internal/ansible/events.loggingEventHandler.Handle\n\tansible-operator-plugins/internal/ansible/events/log_events.go:111"}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [Apply deployment resources] ********************************
fatal: [localhost]: FAILED! => {"msg": "**The task includes an option with an undefined variable. The error was: 'web_manage_replicas' is undefined. 'web_manage_replicas' is undefined. 'web_manage_replicas' is undefined.** 'web_manage_replicas' is undefined\n\nThe error appears to be in '/opt/ansible/roles/installer/tasks/resources_configuration.yml': line 248, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Apply deployment resources\n  ^ here\n"}

**Comment by Blunk** [comment]
I ran into the same issue and it seems to be related to CRD changes which by design do not get automatically updated. 

I had to execute
`kubectl apply --server-side -k "github.com/ansible/awx-operator/config/crd?ref=2.19.0"`
to fix it.

**Comment by laboef1900** [comment]
Thank you for the hint. I will try it later this week.

> I ran into the same issue and it seems to be related to CRD changes which by design do not get automatically updated.
> 
> I had to execute `kubectl apply --server-side -k "github.com/ansible/awx-operator/config/crd?ref=2.19.0"` to fix it.

**Comment by laboef1900** [comment]
I was able to fix the installation by updating the CRD. I also had to add the --force-conflicts flag.

**Comment by laboef1900** [comment]
I was able to fix the installation by updating the CRD. I also had to add the --force-conflicts flag.

**Comment by valkiriaaquatica** [comment]
Hey, same problem installing last awx-operator on kubernetes cluster with Helm. 
I did what @Blunk  said and delete and recreat the deploy and works fine also a problem with crd!

Thanks!

**Comment by RummsMurmel** [comment]
> I was able to fix the installation by updating the CRD. I also had to add the --force-conflicts flag.

Same here. 

Thank you @Blunk  and @laboef1900  !

**Comment by quadeare** [comment]
Same here.

`kubectl apply --server-side -f crds/ --force-conflicts`

Thank you ;)

**Comment by bpmb82** [comment]
I have this same issue on a new deployment, running ```kubectl apply --server-side --force-conflicts -k "github.com/ansible/awx-operator/config/crd?ref=2.19.1"``` does not resolve the issue either, I tried running it before and after deploying the operator, no dice..

This suddenly came up, I installed this roughly 2-3 weeks ago on another system and had no such issue, why is this happening? I don't see any code changes since that time either? I'm using ansible to install everything and nothing has changed there either..

**Comment by dberardo-com** [comment]
how to fix this when upgrading in a manual way ? i mean i have just changed the image version of the awxoperator ... what should i do to fix this error ?
