### ISSUE TITLE
quay.io complains about unpatched security flaws in the awx-operator images

### ISSUE THREAD

**Issue by lemmy04** [ansible/tower-operator#191]
one of the bigger features of the quay.io registry is the built in vulnerabilty scan which checks container images for unpatched flaws.

As of today, april 8 2021, it complains about 2 high, 25 medium, and 5 low vulnerabilities in the awx-operator image.

What can be done to fix this?

![grafik](https://user-images.githubusercontent.com/664127/113998486-66d9e780-9859-11eb-9584-5fa3d4006b36.png)

**Comment by shanemcd** [comment]
These are present in the `quay.io/operator-framework/ansible-operator` base image. You may want to ping that team and see if they can address this.

**Comment by lemmy04** [comment]
they are present in **old** versions of the base image... devel has no vulnerabilities, latest has one. Maybe the awx operator should be based on one of those?
