### ISSUE TITLE
Support for annotations on automation jobs

### ISSUE THREAD

**Issue by pmcenery-bl** [ansible/tower-operator#1916]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

I cant quite see whether or not its possible to add annotations to automation jobs. This would be a useful feature similar to #1624

**Comment by pmcenery-bl** [comment]
For anyone else who comes across this, you can edit the pod spec in instance groups here:

![image](https://github.com/ansible/awx-operator/assets/94845973/428a72aa-50d5-40e5-81dc-9d282344cabc)

**Comment by kevrrnet** [comment]
configure it on GUI is not a solution to configure automation-job pods spec.
@pmcenery-bl
