### ISSUE TITLE
helm install awx-operator postgres-15-0 pod is CrashLoopBackOff

### ISSUE THREAD

**Issue by Kevinwoolworth** [ansible/tower-operator#1930]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

environment AKS cluster, Server Version: v1.27.7

command: 
```
helm upgrade --install awx-operator awx-operator/awx-operator --namespace awx -f values.yaml
```
values.yaml
```
AWX:
  # enable use of awx-deploy template
  enabled: true
```

AWX Operator installed with Helm Chart version 2.19.1

### AWX Operator version

2.19.1

### AWX version

awx-operator-2.19.1	2.19.1

AWX
This version of the operator was release with AWX [v24.6.1](https://github.com/ansible/awx/releases/tag/24.6.1)

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.27.7

### Modifications

no

### Steps to reproduce

simple install awx operator via helm install, the pod is crash, error. 

```
NAME                                              READY   STATUS             RESTARTS      AGE
awx-demo-postgres-15-0                            0/1     CrashLoopBackOff   6 (73s ago)   7m30s
awx-demo-task-5597f9c785-722vs                    0/4     Init:0/2           0             26s
awx-demo-web-78678b4b79-6c5vt                     3/3     Running            0             28s
awx-operator-controller-manager-f7b8f4cd7-fzhzp   2/2     Running            0             8m43s
awx-postgres-15-0                                 0/1     CrashLoopBackOff   6 (94s ago)   7m30s
```
inspect logs from pod, and doesn't have any meaningful log to suggest the root cause. 

and doc https://ansible.readthedocs.io/projects/awx-operator/en/latest/installation/helm-install-on-existing-cluster.html is confusing, it install the operator , however, as user, i would like to see how to get awx up and running with helm install. 
I don't see this in the doc. please fix. 

helm values: 
```
USER-SUPPLIED VALUES:
AWX:
  enabled: true
```

### Expected results

awx is up and running, use can access its portal. 
pod should running as expected. 

### Actual results

```
NAME                                              READY   STATUS             RESTARTS      AGE
awx-demo-postgres-15-0                            0/1     CrashLoopBackOff   6 (73s ago)   7m30s
awx-demo-task-5597f9c785-722vs                    0/4     Init:0/2           0             26s
awx-demo-web-78678b4b79-6c5vt                     3/3     Running            0             28s
awx-operator-controller-manager-f7b8f4cd7-fzhzp   2/2     Running            0             8m43s
awx-postgres-15-0                                 0/1     CrashLoopBackOff   6 (94s ago)   7m30s
```

postgres-15 pod is crashloopbackoff

**Comment by mmondin** [comment]
Same issue here

**Comment by howardjones** [comment]
Same for me on Azure AKS with 

    mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied

Annoyingly, even with an external pg database (created with crunchydata operator) and the postgres_configuration_secret set, it doesn't actually produce any awx-web or awx-task pods. The last thing in the operator logs is a massive long ansible error which seems to be complaining about web_manage_replicas. web_manage_replicas is not valid configuration according to my kubernetes cluster.

**Comment by mmondin** [comment]
I have managed to find a workaround, even though it is not ideal for my setup.

I have deployed AWX on ArgoCD. Once Argo deploys everything, I need to go manually to the AWX object's manifest and add the following line:

```
spec:
...
  postgres_data_volume_init: true
```

The information is reported here, but it does not work for me when I first deploy the application. I need to apply it to the object itself after the deployment started.

https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/database-configuration.html#initialize-postgres-data-volume

**Comment by howardjones** [comment]
@TheRealHaoLiu what is the resolution that creates a working database?

**Comment by howels** [comment]
Confirm this is not fixed in current Helm chart version of AWX-Operator - created a simple AWX object and postgresql is stuck in CrashLoopBackoff and setting `postgres_data_volume_init: true` on the AWX object does not seem to fix the situation after deployment.
