### ISSUE TITLE
failed to fetch https://ansible.github.io/awx-operator/index.yaml : 404 Not Found

### ISSUE THREAD

**Issue by hivagr** [ansible/tower-operator#1940]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When I try to use the awx HELM Charts, I receive a 404 because the `index.yaml` is not found.

### AWX Operator version

2.19.1

### AWX version

latest

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.29.2

### Modifications

no

### Steps to reproduce

`wget https://ansible.github.io/awx-operator/index.yaml`

### Expected results

Receive a `index.yaml`

### Actual results

```
wget https://ansible.github.io/awx-operator/index.yaml
--2024-08-08 09:49:26--  https://ansible.github.io/awx-operator/index.yaml
Resolving ansible.github.io (ansible.github.io)... 185.199.108.153, 185.199.111.153, 185.199.109.153, ...
Connecting to ansible.github.io (ansible.github.io)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-08 09:49:26 ERROR 404: Not Found.
```

**Comment by kurokobo** [comment]
See https://forum.ansible.com/t/upcoming-changes-to-awx-operator-installation-methods/7598?u=kurokobo

**Comment by howardjones** [comment]
This cool, except that (1) today is Aug 8 not 9, and (2) the change did not include updating the install instructions.

By sheer luck, I am installing a test AWX instance this morning to investigate how upgrades will work for us, and following the instructions in the awx-operator manual (for a helm install) doesn't work.

**Comment by howardjones** [comment]
The new repo is here (which has the 2.19.1 operator) - it also wasn't documented in their docs either:

    helm repo add awx-operator https://ansible-community.github.io/awx-operator-helm/

**Comment by jdelvecchio** [comment]
not cool

**Comment by sgreiner** [comment]
I had the same issue today...

```bash
helm repo remove awx-operator
helm repo add awx-operator https://ansible-community.github.io/awx-operator-helm/
helm repo list
helm repo update
helm search repo awx-operator
```
