### ISSUE TITLE
LoadBalancer ingress type cannot be created without annotations

### ISSUE THREAD

**Issue by RylandDeGregory** [ansible/tower-operator#196]
Based on the [`tower_service.yaml`](https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_service.yaml.j2#L12) template definition lines 12-15, one cannot deploy a service of type LoadBalancer without defining annotations for it. Based on the [documentation for LoadBalancer type ingress](https://github.com/ansible/awx-operator#tls-termination), the default value for `tower_loadbalancer_annotations` is an empty string. This prevents the service from being able to deploy given the default configuration for that ingress type.

The template should be constructed in the same manner as the [`tower_ingress.yaml`](https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_ingress.yaml.j2#L13) template definition lines 13-16, where an annotations block is only defined when the `tower_ingress_annotations` variable is defined, not every time someone sets their `tower_ingress_type` to ingress, which is the current configuration of the LoadBalancer ingress type.

**Comment by shanemcd** [comment]
Fantastic!
