### ISSUE TITLE
"public_base_url" should not have default value.

### ISSUE THREAD

**Issue by goldyfruit** [ansible/tower-operator#1994]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Since PR https://github.com/ansible/awx-operator/pull/1982 got merged, every new installation or upgrade got the redirection page message.

![image](https://github.com/user-attachments/assets/60b5ef50-6c1e-4801-aa17-f0763fa05ee0)

[publci_base_url](https://github.com/ansible/awx-operator/blob/devel/config/crd/bases/awx.ansible.com_awxs.yaml#L2015
) should not have default value

### AWX Operator version

devel

### AWX version

devel

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.29

### Modifications

no

### Steps to reproduce

Follow the documentation to deploy AWX via the operator.

### Expected results

At the end of the installation the login page should be displayed

### Actual results

The login page never shows but only the redirection page.

**Comment by esimphlet** [comment]
I too cannot login, I am being redirected..
