### ISSUE TITLE
Update AWX to 12.0.0, unify AWX images

### ISSUE THREAD

**Issue by geerlingguy** [ansible/tower-operator#2]
See: https://groups.google.com/forum/#!topic/awx-project/rxUjrWsfO9A

This is a major new release of AWX, and the images for the web/task containers are now unified (like in Tower downstream). There might need to be one or two other small changes, not sure, but the main one is the new image source/structure.

**Comment by ryanpetrello** [comment]
@geerlingguy I imagine you can also lose a bunch of memcached-specific bits, because that's entirely gone as a dependency now, too.

**Comment by geerlingguy** [comment]
@ryanpetrello - Ah yes... that too. Though is Tower 3.7 still using it? If so we'll have to put it behind a switch.

**Comment by ryanpetrello** [comment]
Right, all of the above *only* applies to Tower > 3.7.

**Comment by matburt** [comment]
We're up to 14 at this point.
