### ISSUE TITLE
Is it possible to use service type ClusterIP?

### ISSUE THREAD

**Issue by andy-hcc** [ansible/tower-operator#202]
Is it possible to for the AWX service to be created using type ClusterIP?

I am trying to setup AWX accessed via an ingress however setting the `tower_ingress_type: Ingress` results in the service being created using NodePort which exposes AWX directly from the cluster unnecessarily.

Attempting to patch the service as follows works temporarily but this then gets reverted back to NodePort after a few minutes:

```bash
kubectl patch svc awx-service -n awx -p '{"spec": {"type": "ClusterIP"}}'
```

**Comment by aubert-aurelien** [comment]
To work around the problem, I blocked on firewall.
There should be an option to disable the NodePort, I don't understand the use when using Ingress.

**Comment by andy-hcc** [comment]
Looks like this might be configured by the following template:  https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_service.yaml.j2

This looks like the service type will be set as follows based on how the `tower_ingress_type` is specified in the install yaml:

- If specifying `tower_ingress_type: LoadBalancer` the service will use `type: LoadBalancer`
- If specifying `tower_ingress_type: Ingress` or `tower_ingress_type: Route`  the service will use `type: NodePort`
- If no `tower_ingress_type` is specified no `type` will be specified for the service.

Could the template be updated as follows to use ClusterIP when specifying an Ingress will be being used?

```yaml
...
{% if tower_ingress_type | lower == "loadbalancer" %}
  type: LoadBalancer
{% elif tower_ingress_type | lower == "ingress" %}
  type: ClusterIP
{% elif tower_ingress_type != "none" %}
  type: NodePort
{% endif %}
```

**Comment by tchellomello** [comment]
Yes, that makes sense. @andy-hcc  want to send a PR for this change?

**Comment by andy-hcc** [comment]
@tchellomello pull request #204 has been created as requested.  Hope it looks ok!
