### ISSUE TITLE
Please share the complete installation steps for AWX 18/19

### ISSUE THREAD

**Issue by unixplex** [ansible/tower-operator#220]
Anyone could you please share the complete installation steps for AWX 18/19

**Comment by tchellomello** [comment]
@unixplex  we see that you reported also https://github.com/ansible/awx-operator/issues/219 which was already answered by @shanemcd with the following:

https://github.com/ansible/awx-operator#basic-install
https://github.com/ansible/awx/blob/devel/INSTALL.md

Are you hitting any issues to get it installed?

**Comment by UnderGrounder96** [comment]
@unixplex I have created a repo that installs AWX v19.
Maybe that's the answer you're looking for, please have a look at: https://gitlab.com/UnderGrounder96/awx_install

**Comment by unixplex** [comment]
Thank you for your response. let me try and update you

**Comment by UnderGrounder96** [comment]
> Thank you for your response. let me try and update you

@unixplex if you would happen to have any questions regarding my installation approach, please create an issue ticket under my gitlab repo. 😄

**Comment by unixplex** [comment]
yes sure 👍

**Comment by unixplex** [comment]
@UnderGrounder96 I have installed AWX with Kubernetes. It works. Thank you.

Let me try to install using docker way of installation.

**Comment by unixplex** [comment]
@UnderGrounder96 , I have installed AWX 19 through Docker Compose for Development. but unable to connect AWX GUI.
I have used ports mentioned in the compose file (using http and https)

Could you please assist here?


# docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED       STATUS          PORTS                                                                                                                                                                                                                                                                                          NAMES
7e031188c1d6   quay.io/awx/awx_devel:devel   "/entrypoint.sh laun…"   3 hours ago   Up 23 minutes   0.0.0.0:6899->6899/tcp, :::6899->6899/tcp, 0.0.0.0:7899-7999->7899-7999/tcp, :::7899-7999->7899-7999/tcp, 0.0.0.0:8013->8013/tcp, :::8013->8013/tcp, 0.0.0.0:8043->8043/tcp, :::8043->8043/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 22/tcp, 0.0.0.0:8888->8888/tcp, :::8888->8888/tcp   tools_awx_1
a625cab19122   postgres:12                   "docker-entrypoint.s…"   3 hours ago   Up 23 minutes   5432/tcp                                                                                                                                                                                                                                                                                       tools_postgres_1
549bc0bda402   redis:latest                  "redis-server /usr/l…"   4 hours ago   Up 23 minutes   6379/tcp                                                                                                                                                                                                                                                                                       tools_redis_1



As you mentioned, I was unable to create ticket under your gitlab
