### ISSUE TITLE
problem with the name of the image

### ISSUE THREAD

**Issue by marioncaze** [ansible/tower-operator#223]
Hi,

When installing my awx, I had the following problem:

`"error": 422, "item": "tower_deployment", "msg": "Failed to apply object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Deployment.apps \\\\\"awx\\\\\" is invalid: [metadata.labels: Invalid value: \\\\\"5000/awx\\\\\": a valid label must be an empty string or consist of alphanumeric characters, \\'-\\', \\'\\' or \\'.\\', and must start and end with an alphanumeric character (e.g. \\'MyValue\\',  or \\'my_value\\',  or \\'12345\\', regex used for validation is \\'(([A-Za-z0-9][-A-Za-z0-9.])?[A-Za-z0-9])?\\'), `

In my "tower image" variable, I have the following information:
tower_image : registry_docker:5000/awx:19.0.0

The regex prevents me from entering the port in this variable. I didn't have the problem with the other variables (tower_redis_image, tower_postgres_image, tower_ee_images).

Is it a desire to set up this regex only for the "tower_image" variable?

Thanks

**Comment by tchellomello** [comment]
@marioncaze yes, this seems to be a valid bug. Thanks for reporting and PR #224 should take care of it. 

If you want to test it on your, please let us know the results. Thanks!

**Comment by marioncaze** [comment]
Hi @tchellomello,

I just restarted the installation with your fix and it works!

Thanks
