### ISSUE TITLE
Root access at awx-operator container

### ISSUE THREAD

**Issue by vipamadi** [ansible/tower-operator#229]
Hi, I need a way to access root user at the awx-operator docker container.

```
[root@lbpocawx01 ~]# kubectl get pods | grep awx-operator
awx-operator-6495f4579-rgpsx   1/1     Running   0          43h
[root@lbpocawx01 ~]# kubectl exec -it awx-operator-6495f4579-rgpsx -- /bin/bash
bash-4.4$ id
uid=1001(ansible-operator) gid=0(root) groups=0(root)
```

Is there any way to do it? 
Where can I find the root password or modify it before deploying the pod?

I need it to modify the file /opt/ansible/roles/installer/templates/tower_deployment.yaml.j2 .  Problem: #211 Resolution: #212

```
bash-4.4$ ls -l /opt/ansible/roles/installer/templates/tower_deployment.yaml.j2
-rw-r--r-- 1 root root 9076 Mar 18 18:16 /opt/ansible/roles/installer/templates/tower_deployment.yaml.j2
```

**Comment by tchellomello** [comment]
@vipamadi you can´t modify the files once the container is already running. You will need to modify the playbook, then rebuild the `awx-operator` container yourself to get that change applied.  You could do something like:

```sh
git clone https://github.com/ansible/awx-operator.git
cd awx-operator
<MAKE YOUR CHANGE>
docker|podman  build . -f build/Dockerfile -t $REGISTRY/$OPERATOR_IMAGE:$TAG
```

Or if you want, in the meantime, you could use the image I hosted here: https://hub.docker.com/repository/docker/tchellomello/awx-operator/
