### ISSUE TITLE
Changing redis:latest in main.yml does nothing

### ISSUE THREAD

**Issue by evilmonkeyslayer** [ansible/tower-operator#232]
I've recently had the issue [as mentioned here](https://github.com/ansible/awx-operator/issues/211) where no matter what I do awx-operator tries to pull redis:latest from the internet.

On line 130 of awx-operator/roles/installer/defaults/main.yml on line 130 is the text:

`tower_redis_image: redis:latest`

If this is changed to: `tower_redis_image: redis:6.2.1` it still tries to grab the latest tag instead of 6.2.1.

If this is changed to: `tower_redis_image: registry.local:5443/redis:latest` to connect to my test lan docker registry it still tries to get it from registry-1.docker.io

Here is an example output using `kubectl describe pod awx-b5f6cf4d4-2f679`
```

  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m36s                   default-scheduler  Successfully assigned default/awx-b5f6cf4d4-2f679 to kurlawx19-2
  Normal   Started    8m35s                   kubelet            Started container awx-web
  Normal   Pulled     8m35s                   kubelet            Container image "quay.io/ansible/awx:19.0.0" already present on machine
  Normal   Pulled     8m35s                   kubelet            Container image "quay.io/ansible/awx:19.0.0" already present on machine
  Normal   Created    8m35s                   kubelet            Created container awx-web
  Normal   Pulled     8m34s                   kubelet            Container image "quay.io/ansible/awx-ee:0.1.1" already present on machine
  Normal   Started    8m34s                   kubelet            Started container awx-task
  Normal   Started    8m34s                   kubelet            Started container awx-ee
  Normal   Created    8m34s                   kubelet            Created container awx-ee
  Normal   Created    8m34s                   kubelet            Created container awx-task
  Warning  Failed     8m18s                   kubelet            Failed to pull image "redis:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 18.213.137.78:443: connect: network is unreachable
  Normal   BackOff    8m5s (x3 over 8m33s)    kubelet            Back-off pulling image "redis:latest"
  Warning  Failed     7m51s (x3 over 8m35s)   kubelet            Error: ErrImagePull
  Warning  Failed     7m51s (x2 over 8m35s)   kubelet            Failed to pull image "redis:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp 35.169.249.115:443: connect: network is unreachable
  Normal   Pulling    7m51s (x3 over 8m35s)   kubelet            Pulling image "redis:latest"
  Warning  Failed     3m28s (x20 over 8m33s)  kubelet            Error: ImagePullBackOff
```

As you can see, it's like this isn't even used from the yml file.

Am I doing something wrong here?

**Comment by tchellomello** [comment]
@evilmonkeyslayer  are you setting the `tower_redis_image` on your  `AWX` kind?  For example:
```yaml
$ kubectl edit awx awx 
...
spec:
  tower_redis_image: redis:6.2.1
```

Then  the  `awx-operator`  will work to reconcile the deployment, which means after this change, you should expect a `rollout`.  Then confirm if the  `awx` has the change you performed and check the deployment.

**Comment by evilmonkeyslayer** [comment]
> 
> 
> @evilmonkeyslayer are you setting the `tower_redis_image` on your `AWX` kind? For example:
> 
> ```yaml
> $ kubectl edit awx awx 
> ...
> spec:
>   tower_redis_image: redis:6.2.1
> ```
> 
> Then the `awx-operator` will work to reconcile the deployment, which means after this change, you should expect a `rollout`. Then confirm if the `awx` has the change you performed and check the deployment.

This is modifying the file mentioned above before running `kubectl apply -f deploy/awx-operator.yaml` and `kubectl apply -f my-awx.yml`

After modifying the files mentioned above I expected it to try and install redis 6.2.1 or from my test lan registry.

Ah.

I just modifed my-awx.yml with:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_redis_image: registry.local:5443/redis:latest
```

And it successfully grabbed redis.

```
kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
awx-6466598d7b-g5bn6            4/4     Running   0          65s
awx-operator-779747fb97-8f8f8   1/1     Running   0          44m
awx-postgres-0                  1/1     Running   0          71s
```

EDIT: I am now using the change from [this branch](https://github.com/ansible/awx-operator/pull/224), so I suspect this helps things along.
