### ISSUE TITLE
External Database Password with Special Characters

### ISSUE THREAD

**Issue by afhtan** [ansible/tower-operator#239]
When deploying AWX with external database configuration; the password in awx-web:/etc/tower/conf.d/credentials.py has additional single quotes around the password if the password contains special characters.

As a result, the awx-web container is unable to connect to the database and I am getting errors related to invalid credentials.

When the special characters are removed from the password the additional single quotes are not added to the credentials.py file.

ansible-operator version: 0.8

**Comment by shanemcd** [comment]
@tchellomello We fixed this right? Maybe we just haven't pushed it out in a release yet?

**Comment by tchellomello** [comment]
@shanemcd yes, that was fixed by https://github.com/ansible/awx-operator/pull/206 

@afhtan if you deploy the devel image, you should be fine.

**Comment by afhtan** [comment]
Thanks. The devel branch awx-operator image does not have this issue.

Note: I downloaded the devel branch awx-operator.yaml file and updated the deployment definitions image version. It is set to 0.8.0 in the image version instead of 'devel'
