### ISSUE TITLE
Switch to using Red Hat's postgresql-12 image

### ISSUE THREAD

**Issue by shanemcd** [ansible/tower-operator#240]
Right now we are using the upstream `postgres:12` image. Before we can ship this to customer's we need to start using `registry.redhat.io/rhel8/postgresql-12`.

This is not a simple drop-in replacement like the `redis` image because the environment variables are different.

Upstream postgres uses variables prefixed with `POSTGRES_`. Red Hat's image uses `POSTGRESQL_`

Things we need to figure out:

- Do we want to spend the time and figure out how to template out these differences so that we can keep using `postgres:12` upstream? Or do we just want to use the Red Hat image everywhere.
- If we were to use the Red Hat image everywhere, it would require people to provide an imagePullSecret for registry.redhat.io. This would need to be very clearly documented. Our CI checks would also need to be updated to use an imagePullSecret.

**Comment by shanemcd** [comment]
@Spredzy @Zokormazo We already did this right? Can we move to needs_test? Or close?

**Comment by Zokormazo** [comment]
I'm fine with closing it
