### ISSUE TITLE
Allow Nodeport as Ingress

### ISSUE THREAD

**Issue by deeco** [ansible/tower-operator#25]
Is it possible to use Nodeport as option to connect to AWX web frontend as per ingress options https://github.com/ansible/awx-operator#ingress-types

**Comment by deeco** [comment]
# AWX Service.
{% if 'cluster' == tower_service_type|lower %}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ meta.name }}-service'
  namespace: '{{ meta.namespace }}'
  labels:
    app: awx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8052
    name: http
  selector:
    app: awx
{% endif %}

{% if 'node' == tower_service_type|lower %}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ meta.name }}'
  namespace: '{{ meta.namespace }}'
  labels:
    app: awx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30920
      name: http
  selector:
    app: awx
{% endif %}

**Comment by deeco** [comment]
am able to patch with `kubectl patch svc awx-service -n ansible-awx -p '{"spec": {"type": "NodePort"}}'`

**Comment by tchellomello** [comment]
Closing as it was included on PR #204
