### ISSUE TITLE
awx installation by awx-operator

### ISSUE THREAD

**Issue by DanRod1** [ansible/tower-operator#270]
Hi,
i am spending several days to install awx on the my kubernetes cluster.
I try to follow the documentation which is a little light but no result.

I use the awx-operator 0.8.0
My manifest is on the zip attached.

The result of apply is a lot pods in evicted state 
**[binfra.ansible.user@s491liak8mstr1 ~]$** kubectl get pod -n awx
NAME READY STATUS RESTARTS AGE
awx-7cc97f7bd-rf45f 0/4 ContainerCreating 0 33m
awx-operator-f768499d-2rbg7 1/1 Running 3 4d
awx-operator-f768499d-7qv8q 0/1 Evicted 0 34m
awx-operator-f768499d-965kq 0/1 CrashLoopBackOff 11 25m
awx-web-5b4877b656-5vk8l 0/4 Pending 0 5m59s
awx-web-5b4877b656-6245v 0/4 Evicted 0 19m
awx-web-5b4877b656-8lqt2 0/4 Evicted 0 19m
awx-web-5b4877b656-bhjr2 0/4 Evicted 0 25m
awx-web-5b4877b656-gvfs2 0/4 Evicted 0 19m
awx-web-5b4877b656-hq548 0/4 Evicted 0 26m
awx-web-5b4877b656-hz69x 0/4 Evicted 0 12m
awx-web-5b4877b656-kpglb 0/4 Evicted 0 19m
awx-web-5b4877b656-rzjh9 0/4 Evicted 0 19m
awx-web-5b4877b656-s58vr 0/4 Evicted 0 19m
awx-web-5b4877b656-vr5cp 0/4 Evicted 0 19m
awx-web-5b4877b656-vz86b 0/4 Evicted 0 19m
awx-web-5b4877b656-x6c2z 0/4 Evicted 0 19m
awx-web-postgres-0 0/1 Pending 0 26m
**[binfra.ansible.user@s491liak8mstr1 ~]$** kubectl logs pod/awx-7cc97f7bd-rf45f -n awx
error: a container name must be specified for pod awx-7cc97f7bd-rf45f, choose one of: [redis awx-web awx-task awx-ee]
**[binfra.ansible.user@s491liak8mstr1 ~]$** kubectl logs pod/awx-operator-f768499d-7qv8q -n awx
Error from server (BadRequest): container "awx-operator" in pod "awx-operator-f768499d-7qv8q" is not available
**[binfra.ansible.user@s491liak8mstr1 ~]$** kubectl logs pod/awx-web-5b4877b656-5vk8l -n awx
error: a container name must be specified for pod awx-web-5b4877b656-5vk8l, choose one of: [redis awx-web-web awx-web-task awx-web-ee]
**[binfra.ansible.user@s491liak8mstr1 ~]$** kubectl logs pod/awx-web-postgres-0 -n awx
**[binfra.ansible.user@s491liak8mstr1 ~]$**

[kube-awx.zip](https://github.com/ansible/awx-operator/files/6415640/kube-awx.zip)

**Comment by tchellomello** [comment]
@DanRod1 can you please try again with the latest `0.9.0`. 

If you experiece the same issue, please provide the following:

```sh
kubectl get awx -o yaml <AWX_INSTANCE_NAME>
kubectl describe pod <AWX_POD_NAME>
```

**Comment by DanRod1** [comment]
Thanks for your reply seems to be ok with the 0.9.0 verssion
