### ISSUE TITLE
How to Backup awx environment 

### ISSUE THREAD

**Issue by eniomachado** [ansible/tower-operator#274]
##### ISSUE TYPE
 - Backup Information

##### SUMMARY

root(ocp:awx-operator) $ oc get pods
NAME                          READY   STATUS    RESTARTS   AGE
awx-b5f6cf4d4-66v24           4/4     Running   0          4d8h
awx-operator-f768499d-rd7dg   1/1     Running   0          4d8h
awx-postgres-0                1/1     Running   0          4d8h

ansible root(ocp:awx-operator) $ oc get pvc
NAME                      STATUS   VOLUME                    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
postgres-awx-postgres-0   Bound    postgres-awx-postgres-0   20Gi       RWO            non-dynamic    4d12h
ansible root(ocp:awx-operator) $ oc get pv postgres-awx-postgres-0
NAME                      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                  STORAGECLASS   REASON   AGE
postgres-awx-postgres-0   20Gi       RWO            Retain           Bound    awx-operator/postgres-awx-postgres-0   non-dynamic             4d12h
ansible root(ocp:awx-operator) $

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-awx-postgres-0
  namespace: awx-operator
  labels:
    env: prd
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /nfs/openshift/postgresql/postgresql-pv-1
    server: hostname
  storageClassName: non-dynamic

##### ENVIRONMENT
* AWX version: 19.0.0
* Operator version: 0.9.0
* Kubernetes version: 
* AWX install method: openshift 4.6.13

**Comment by tchellomello** [comment]
@eniomachado  this PR was added a few days ago https://github.com/ansible/awx-operator/pull/133/files#diff-0d4d815153ba25c9d4dabe30adac405ce39e5acf6cb24b82931fc52fe6f1c267

 You will need to use the `devel` image and then follow the documentation ^. If you find anything that worth changing or enhancement, PR's are welcome!.

**Comment by bnaydenov** [comment]
@tchellomello I have successfully installed AWX operator from the latest `devel` branch into EKS 1.18 cluster, and everything was successful. AWX is deployed via the operator and installed into the `default` namespace" with the name `awx`.

I want to test backup, and I created and successfully applied the following AWXBackup to k8s.

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awxbackup
  namespace: default
spec:
  deployment_name: awx
```

```bash
kubectl get awxbackup -o yaml
```

```yaml
apiVersion: v1
items:
- apiVersion: awx.ansible.com/v1beta1
  kind: AWXBackup
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"awx.ansible.com/v1beta1","kind":"AWXBackup","metadata":{"annotations":{},"name":"awxbackup","namespace":"default"},"spec":{"deployment_name":"awx"}}
    creationTimestamp: "2021-05-20T00:09:50Z"
    generation: 1
    managedFields:
    - apiVersion: awx.ansible.com/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:deployment_name: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2021-05-20T00:09:50Z"
    name: awxbackup
    namespace: default
    resourceVersion: "19889510"
    selfLink: /apis/awx.ansible.com/v1beta1/namespaces/default/awxbackups/awxbackup
    uid: 3e66e592-ded2-439b-94f8-37d0c42fdbb4
  spec:
    deployment_name: awx
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Now there are no errors, but the backup job is not to run, PVC to store backup is not created, and it looks like nothing happens. 

What else is needed to trigger the backup job to run?

**Comment by bnaydenov** [comment]
I figure it out what was wrong. So I deploy wax-opreator from latest `devel` branch as suggested by README.md, but the code in this branch still uses image `quay.io/ansible/awx-operator:0.9.0` see [here](https://github.com/ansible/awx-operator/blob/d0a74edd342506954fbdc88942e9d076f3607535/deploy/awx-operator.yaml#L621)

```yaml
spec:
      serviceAccountName: awx-operator
      containers:
        - name: awx-operator
          image: "quay.io/ansible/awx-operator:0.9.0"
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
``` 

This image `quay.io/ansible/awx-operator:0.9.0` does not contain roles for backup and restore in it.

Once I manually change awx-operator deployment to use `quay.io/ansible/awx-operator:devel` I have PVC `awx-backup-claim` created. I have pod `awxbackup-db-management` created and mounted this PV `awx-backup-claim`, but folder `backups` inside pod  `awxbackup-db-management` is empty, and no backups created.

I also created a new backup with:

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awxbackup2
  namespace: default
spec:
  deployment_name: awx
```

But still no backup created. 

And this is the status of this `awxbackup2`

```yaml
status:                                                                                                                                                                                       │
│   conditions:                                                                                                                                                                                 │
│   - lastTransitionTime: "2021-05-20T13:58:25Z"                                                                                                                                                │
│     message: Running reconciliation                                                                                                                                                           │
│     reason: Running                                                                                                                                                                           │
│     status: "False"                                                                                                                                                                           │
│     type: Running                                                                                                                                                                             │
│   - ansibleResult:                                                                                                                                                                            │
│       changed: 3                                                                                                                                                                              │
│       completion: 2021-05-20T14:04:40.55262                                                                                                                                                   │
│       failures: 1                                                                                                                                                                             │
│       ok: 14                                                                                                                                                                                  │
│       skipped: 6                                                                                                                                                                              │
│     lastTransitionTime: "2021-05-20T14:04:40Z"                                                                                                                                                │
│     message: unknown playbook failure                                                                                                                                                         │
│     reason: Failed                                                                                                                                                                            │
│     status: "True"                                                                                                                                                                            │
│     type: Failure
```


@tchellomello What else I need to do to trigger successful  backup job and create backup?

**Comment by rooftopcellist** [comment]
Hi @bnaydenov , 

Your first issue as you said was the old image being pinned.  Pointing to devel as you mentioned should solve that.  Alternatively, you can build your own image from the source code, pushing it to your registry of choice, then specifying that in your spec:

```
#> operator-sdk build quay.io/<user>/awx-operator:test
#> docker push quay.io/<user>/awx-operator:test
```

For your second issue, it looks like that has been fixed since your comment, it's hard to pin down the exact issue (there were a couple bugfixes recently) without logs though.  I couldn't reproduce here.  Can you try this with devel and see if you can reproduce?

**Comment by shanemcd** [comment]
Closing due to lack of response. Please let us know if we should reopen this issue.
