### ISSUE TITLE
unknown field "tower_ee_extra_volume_mounts" in com.ansible.awx.v1beta1.AWX.spec; if you choose to ignore these errors, turn validation off with --validate=false

### ISSUE THREAD

**Issue by washburnjoe** [ansible/tower-operator#277]
I could be WAY off base as I am new to this deployment model.  I have built an EE environment that has an extra directory that I need to mount.

I am trying to deploy AWX and mount that volume and getting the error:

minikube kubectl apply -- -f my-awx.yml 
error: error validating "my-awx.yml": error validating data: ValidationError(AWX.spec): unknown field "tower_ee_extra_volume_mounts" in com.ansible.awx.v1beta1.AWX.spec; if you choose to ignore these errors, turn validation off with --validate=false

ENV:
Minkube 

Operator 0.8.0 deployed 

Created a my-awx.yml file
`---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx

spec:
  tower_ingress_type: ingress
  tower_hostname: testawx.internal.com
  tower_ingress_tls_secret: oursecret 
  tower_admin_user: admin
  tower_ee_extra_volume_mounts: |
    - name: ISOs
        mountPath: /var/lib/awx/public/extradir
`

**Comment by TheITRx** [comment]
Not sure what the trick is. But I usually just --validate=false. This is if Im confident that my yaml is valid with right indentation,etc.

**Comment by tchellomello** [comment]
@TheITRx the  `0.8.0` version does not have the option `tower_ee_extra_volume_mounts` as you can see at https://github.com/ansible/awx-operator/blob/0.8.0/deploy/awx-operator.yaml. 

However, that is present on the `0.9.0` at https://github.com/ansible/awx-operator/blob/0.9.0/deploy/awx-operator.yaml

Update to the latest version and then make sure the documentation steps at https://github.com/ansible/awx-operator/blob/devel/README.md#custom-volume-and-volume-mount-options as you will also need to specify the `tower_extra_volumes` so it can be used as reference.

**Comment by washburnjoe** [comment]
The error is gone.  Thank you.  I am struggling a bit with understanding the extra volume mounts.  

I have created an EE with an extra volume /var/lib/awx/public/extradir.  That built successfully and I can browse it add files, etc.

Now on the operator side I am trying to understand how I work with that.  Why does the Operator need to know about the EE extra volume mount

**Comment by TheITRx** [comment]
> @TheITRx the `0.8.0` version does not have the option `tower_ee_extra_volume_mounts` as you can see at https://github.com/ansible/awx-operator/blob/0.8.0/deploy/awx-operator.yaml.
> 
> However, that is present on the `0.9.0` at https://github.com/ansible/awx-operator/blob/0.9.0/deploy/awx-operator.yaml
> 
> Update to the latest version and then make sure the documentation steps at https://github.com/ansible/awx-operator/blob/devel/README.md#custom-volume-and-volume-mount-options as you will also need to specify the `tower_extra_volumes` so it can be used as reference.

>
this is awesome. I just tried it and works like a charm. What I was saying in my previous statement is that I have run into instances in the past where the kubectl apply does not take well on yamls with multi-line values "|". I usually just do --validate-false and things just work fine like how they should. 

thanks much for the info. The new EE thing is an amazing feature. Not a lot yet are grasping well as to how it works.

**Comment by tchellomello** [comment]
> The error is gone. Thank you. I am struggling a bit with understanding the extra volume mounts.
> 
> I have created an EE with an extra volume /var/lib/awx/public/extradir. That built successfully and I can browse it add files, etc.
> 
If you mounting an extra directory to have like a `venv` directory, you might want to add the dependencies directly to your container specification. That was the main idea of moving to the `ee` to facilitate the deployment. 

However, if you are mounting this to save artifacts then it would make (of course there are more scenarios in which mounting an extra dir is applicable). 

> Now on the operator side I am trying to understand how I work with that. Why does the Operator need to know about the EE extra volume mount

Since the operator is the central management piece of your AWX instance, it's expected that any extra volumes you need on your deployments to be managed by the `awx-operator` itself, therefore, the need of adding the information there. 

Since it worked for both I'm closing this for now, but feel free to reopen if needed.
