### ISSUE TITLE
Feature request: arm64 version.

### ISSUE THREAD

**Issue by TheBFGNL** [ansible/tower-operator#280]
Hello,

More and more people like mw are building Raspberry PI clusters. AWX might help in maintaining them. 

However the images aren't compatible with arm64. Is there any possibility that they can be made compatible with arm64?

**Comment by etowntec** [comment]
Fully agree with this request. I would love to be able to install this on my turingpi cluster

**Comment by wenottingham** [comment]
This would need done in AWX itself, not in the operator. See https://github.com/ansible/awx/issues/7051.
