### ISSUE TITLE
Playbooks aren’t showing up in the “Job Template” drop-down

### ISSUE THREAD

**Issue by eniomachado** [ansible/tower-operator#285]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When running through the basic "playbook" example template the "PLAYBOOK: Choose a playbook" dropdown doesn't not populate any playbooks from gitlab. I can add the project but cant see any playbooks inside of it. Using basic "playbook" example template helloworld project from https://github.com/ansible/tower-example, I can add the project and can see playbooks to choose a playbook dropdown . I double-checked projects in /var/lib/awx/projects/* is visible, no issues adding the project itself.

##### ENVIRONMENT
* AWX version: 19.0.0
* Operator version: 0.9.0
* Kubernetes version: 
* AWX install method: openshift 4.6.13

##### STEPS TO REPRODUCE

Create project:
![image](https://user-images.githubusercontent.com/13068058/117167110-5a37a900-ad9d-11eb-8eff-27b6fd28b394.png)
![image](https://user-images.githubusercontent.com/13068058/117167261-79ced180-ad9d-11eb-86c9-8b44f67e05f6.png)

##### EXPECTED RESULTS

![image](https://user-images.githubusercontent.com/13068058/117165687-16906f80-ad9c-11eb-8ed0-edad3be047d7.png)

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/13068058/117165923-4c355880-ad9c-11eb-95b0-1b220427d561.png)
![image](https://user-images.githubusercontent.com/13068058/117166483-cb2a9100-ad9c-11eb-9098-ad9779ec1006.png)

**Comment by tchellomello** [comment]
@eniomachado the right repo for this issue would be the https://github.com/ansible/awx itself as it is not related with the `awx-operator` directly.  The fact of working for a project and not for another is a good indicator the issue should be located on project. 

Having said this, if you look at https://github.com/ansible/awx/blob/devel/awx/main/utils/ansible.py#L42, you will see the method that validates if the file is valid `yaml` file  and therefore will be displayed in the list. 

Having said that, if you copy the `helloworld.yml` to the `intergragh` project, resync, you will be able to see the playbook listed in the project.

**Comment by eniomachado** [comment]
@tchellomello your information works for me, thanks for your help.

![image](https://user-images.githubusercontent.com/13068058/117203306-3c7e3a00-adc5-11eb-8550-75c57f8c2a42.png)

**Comment by tchellomello** [comment]
Feliz em ter ajudado @eniomachado ! :)
