### ISSUE TITLE
Issues Installing AWX Operator On K8s 

### ISSUE THREAD

**Issue by jacklikethings** [ansible/tower-operator#298]
Hi and thank you in advance for any help,

I have been trying and failing to install the AWX Operator on K8s. I am currently running a cluster consisting of two nodes, Kubem01 and Kubew02. I am assuming that I have set them up correctly, but it has been a while since I used Kubernetes.

When I run the `kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/0.9.0/deploy/awx-operator.yaml`, everything seems to go through fine. Everything gets created and we move on.

But then roughly 30 seconds later the pod goes into a "CrashBackLoop" and when you do a `kubectl describe pods` I am given the below output:

Events:
  Type     Reason     Age                   From               Message
  Normal   Scheduled  11m                   default-scheduler  Successfully assigned default/awx-operator-5d9d764bcd-brjkt to kubew01
  Normal   Pulled     11m                   kubelet            Successfully pulled image "quay.io/ansible/awx-operator:0.9.0" in 1.349392139s
  Normal   Pulled     10m                   kubelet            Successfully pulled image "quay.io/ansible/awx-operator:0.9.0" in 1.332981249s
  Normal   Pulled     9m42s                 kubelet            Successfully pulled image "quay.io/ansible/awx-operator:0.9.0" in 1.359420131s
  Normal   Killing    9m24s                 kubelet            Container awx-operator failed liveness probe, will be restarted
  Normal   Pulling    9m23s (x4 over 11m)   kubelet            Pulling image "quay.io/ansible/awx-operator:0.9.0"
  Normal   Started    9m22s (x4 over 11m)   kubelet            Started container awx-operator
  Normal   Created    9m22s (x4 over 11m)   kubelet            Created container awx-operator
  Normal   Pulled     9m22s                 kubelet            Successfully pulled image "quay.io/ansible/awx-operator:0.9.0" in 1.320444622s
  Warning  Unhealthy  5m44s (x6 over 10m)   kubelet            Liveness probe failed: Get "http://xx.xx.1.4:6789/healthz": dial tcp xx.xx.1.4:6789: connect: connection refused
  Warning  BackOff    60s (x33 over 9m58s)  kubelet            Back-off restarting failed container

From here I did some further digging and got the log on the pod/awx-operator. From that output what is below is what I think might lead to the solution:

{"level":"error","ts":1620420610.4648674,"logger":"controller-runtime.manager","msg":"Failed to get API Group-Resources","error":"Get https://xx.xx.0.1:443/api?timeout=32s: dial tcp xx.xx.0.1:443: i/o timeout","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/manager/manager.go:258\ngithub.com/operator-framework/operator-sdk/pkg/ansible.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/run.go:124\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/ansible-operator/main.go:32\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/runtime/proc.go:203"}
{"level":"error","ts":1620420610.465071,"logger":"cmd","msg":"Failed to create a new manager.","Namespace":"","error":"Get https://xx.xx.0.1:443/api?timeout=32s: dial tcp xx.xx.0.1:443: i/o timeout","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/run.go:126\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/ansible-operator/main.go:32\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/runtime/proc.go:203"}
time="2021-05-07T20:50:10Z" level=fatal msg="Get https://10.96.0.1:443/api?timeout=32s: dial tcp xx.xx.0.1:443: i/o timeout"

This is all I can really think of doing, but if there is anything else that I may need to do, please just let me know and I will try and get that done for you.

Stay Safe,
Jack

**Comment by tchellomello** [comment]
@jacklikethings the error you pointed is related to the k8s trying to `livenessProbe` to check if the operator has started correctly:

```yaml
 638           livenessProbe:
 639             httpGet:
 640               path: /healthz
 641               port: 6789
 642             initialDelaySeconds: 15
 643             periodSeconds: 20
```
Since you are getting the `CrashBackLoop`, it's expected for the `livenessProbe` to fail because the `awx-operator` did not start as expected. 

What is the output if you do:

```yaml
# kubectl get nodes
# kubectl api-resources | grep awx
# kubectl api-versions | grep awx
# kubectl explain awx
# kubectl get awx -A 
# kubectl get crd  awxs.awx.ansible.com
# kubectl get crd  awxs.awx.ansible.com -o yaml
```

On your `kubectl config`, are you binding it using a `admin` user that has privileges to create the expected `crds`?

**Comment by Bidhanbst** [comment]
Hi, I had also faced same issue. The requested output is attached herewith. 

![Screenshot (28)](https://user-images.githubusercontent.com/34091194/118391344-8aabfc80-b653-11eb-8236-78b999ead4bf.png)
![Screenshot (29)](https://user-images.githubusercontent.com/34091194/118391355-90094700-b653-11eb-9467-de7db10986ff.png)

Yaml of awx crd

[operator.txt](https://github.com/ansible/awx-operator/files/6488925/operator.txt)

 Thank you in advance for any help.

**Comment by Bidhanbst** [comment]
> Hi and thank you in advance for any help,
> 
> I have been trying and failing to install the AWX Operator on K8s. I am currently running a cluster consisting of two nodes, Kubem01 and Kubew02. I am assuming that I have set them up correctly, but it has been a while since I used Kubernetes.
> 
> When I run the `kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/0.9.0/deploy/awx-operator.yaml`, everything seems to go through fine. Everything gets created and we move on.
> 
> But then roughly 30 seconds later the pod goes into a "CrashBackLoop" and when you do a `kubectl describe pods` I am given the below output:
> 
> Events:
> Type Reason Age From Message
> Normal Scheduled 11m default-scheduler Successfully assigned default/awx-operator-5d9d764bcd-brjkt to kubew01
> Normal Pulled 11m kubelet Successfully pulled image "quay.io/ansible/awx-operator:0.9.0" in 1.349392139s
> Normal Pulled 10m kubelet Successfully pulled image "quay.io/ansible/awx-operator:0.9.0" in 1.332981249s
> Normal Pulled 9m42s kubelet Successfully pulled image "quay.io/ansible/awx-operator:0.9.0" in 1.359420131s
> Normal Killing 9m24s kubelet Container awx-operator failed liveness probe, will be restarted
> Normal Pulling 9m23s (x4 over 11m) kubelet Pulling image "quay.io/ansible/awx-operator:0.9.0"
> Normal Started 9m22s (x4 over 11m) kubelet Started container awx-operator
> Normal Created 9m22s (x4 over 11m) kubelet Created container awx-operator
> Normal Pulled 9m22s kubelet Successfully pulled image "quay.io/ansible/awx-operator:0.9.0" in 1.320444622s
> Warning Unhealthy 5m44s (x6 over 10m) kubelet Liveness probe failed: Get "http://xx.xx.1.4:6789/healthz": dial tcp xx.xx.1.4:6789: connect: connection refused
> Warning BackOff 60s (x33 over 9m58s) kubelet Back-off restarting failed container
> 
> From here I did some further digging and got the log on the pod/awx-operator. From that output what is below is what I think might lead to the solution:
> 
> {"level":"error","ts":1620420610.4648674,"logger":"controller-runtime.manager","msg":"Failed to get API Group-Resources","error":"Get https://xx.xx.0.1:443/api?timeout=32s: dial tcp xx.xx.0.1:443: i/o timeout","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/manager/manager.go:258\ngithub.com/operator-framework/operator-sdk/pkg/ansible.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/run.go:124\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/ansible-operator/main.go:32\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/runtime/proc.go:203"}
> {"level":"error","ts":1620420610.465071,"logger":"cmd","msg":"Failed to create a new manager.","Namespace":"","error":"Get https://xx.xx.0.1:443/api?timeout=32s: dial tcp xx.xx.0.1:443: i/o timeout","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/run.go:126\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/ansible-operator/main.go:32\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/runtime/proc.go:203"}
> time="2021-05-07T20:50:10Z" level=fatal msg="Get https://10.96.0.1:443/api?timeout=32s: dial tcp xx.xx.0.1:443: i/o timeout"
> 
> This is all I can really think of doing, but if there is anything else that I may need to do, please just let me know and I will try and get that done for you.
> 
> Stay Safe,
> Jack

I was able to solve this issue by enabling cni0 interface in firewalld.

`sudo firewall-cmd --zone=trusted --add-interface=cni0 --permanent`
`sudo systemctl restart firewalld`
