### ISSUE TITLE
Add support for Pulling an Image from a Private Registry

### ISSUE THREAD

**Issue by dericcrago** [ansible/tower-operator#30]
It would be nice to be able to use images from private registries, perhaps something like:

```yaml
image_pull_secret: NAME_OF_IMAGE_PULL_SECRET
tower_task_image: private.example.com/ansible/awx:14.1.0
```

I already started a [branch](https://github.com/ansible/awx-operator/compare/devel...dericcrago:image_pull_secret) that I think might work if this is something worth considering.

**Comment by mijenki** [comment]
Hi @dericcrago I took a look at your branch and that's the solution I was thinking of too. Is there a reason you didn't PR your branch?

**Comment by dericcrago** [comment]
hi @mijenki - I was just trying to judge interest; I'll get a PR submitted.
