### ISSUE TITLE
Documentation request: How to upgrade existing AWX >= 19.0 without losing tower data

### ISSUE THREAD

**Issue by lemmy04** [ansible/tower-operator#300]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have a working AWX 19.0, I want to upgrade to 19.1 without losing my data
This process is not documented anywhere.

##### ENVIRONMENT
* AWX version: 19.x & 19.x+1
* Operator version: 0.8.0, 0.9.0
* Kubernetes version: K3s 1.20.4 on debian buster
* AWX install method: AWX-operator

##### STEPS TO REPRODUCE

1. install AWX 19.0
2. See that there's AWX 19.1 out
3. try to find documentation about how to upgrade without losing data

##### EXPECTED RESULTS

I'd expect a paragraph in the AWX operator readme to tell me how to upgrade without losing my data

##### ACTUAL RESULTS

trial and error...

##### AWX-OPERATOR LOGS

n/a.

**Comment by hyacin75** [comment]
and now for 0.14.0 this method no longer works.
