### ISSUE TITLE
Can't set '' as storageClassName value on pvcs

### ISSUE THREAD

**Issue by Zokormazo** [ansible/tower-operator#304]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

As an openshift operator, sometimes I could want to bind my pvc to a pv without any storage class. 

To be able to do this on a cluster with a default sotrage class I should set `storageClassName: ''` on the pvc spec: 

https://docs.openshift.com/container-platform/4.7/storage/understanding-persistent-storage.html#pvc-storage-class_understanding-persistent-storage
> When a default storage class is configured, the PVC must explicitly ask for StorageClass or storageClassName annotations set to "" to be bound to a PV without a storage class.
>

But the operator will not set an storageClassName if the respective var's value is `''`:
https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_postgres.yaml.j2#L97 
https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_persistent.yaml.j2#L18
https://github.com/ansible/awx-operator/blob/devel/roles/backup/templates/backup_pvc.yml.j2#L10

So there is now way to set the explicit '' to bound the PVC to a PV without a storage class

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: devel
* Kubernetes version:  OCP 4.7
* AWX install method: operator

##### STEPS TO REPRODUCE

try to set '' as storage_class for any of the storage_class vars

##### EXPECTED RESULTS

The PVC has `storageClassName: ''` on the spec

##### ACTUAL RESULTS

There is not `storageClassName` on the pvc spec

**Comment by tchellomello** [comment]
Closing this as it was fixed by #315 and #318
