### ISSUE TITLE
get status terminating after try to uninstall operator 

### ISSUE THREAD

**Issue by duchri66** [ansible/tower-operator#305]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: v19
* Operator version: 0.9.0
* Kubernetes version: 
* AWX install method:  okd4

**Comment by duchri66** [comment]
solved

**Comment by duchri66** [comment]
solved with info from https://www.redhat.com/sysadmin/openshift-terminating-state

**Comment by tchellomello** [comment]
That will be fixed by https://github.com/ansible/awx-operator/pull/299 as well
