### ISSUE TITLE
Execution Environments do not set ImagePullSecrets for registry credentials

### ISSUE THREAD

**Issue by bergmannf** [ansible/tower-operator#314]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Execution Environments do not use the configured registry credentials, when pulling from a private registry.

This seems to be related to https://github.com/ansible/awx/issues/7066, however the fix of providing login details using the private-data-dir will not work, as the container image the EE will run in can not be pulled before that.

In k8s the ImagePullSecrets must be set instead.

##### ENVIRONMENT

* AWX version: 19.1.0
* Operator version: 0.9.0
* Kubernetes version: 1.18
* AWX install method: VMWare Tanzu TKGs

##### STEPS TO REPRODUCE

Attempt to use a awx-ee image with adjustments that needs to be pulled from a private registry and needs registry credentials.

The credentials can be added to the image in the UI, however will not be used as a ImagePullSecrets when a new Pod is started.

##### EXPECTED RESULTS

The EE should configure the started Pod with a correct ImagePullSecret so it can be pulled from the registry.

##### ACTUAL RESULTS

The EE does not configure a ImagePullSecret and runs into an ImagePullBackOff error.

**Comment by rooftopcellist** [comment]
Hi @bergmannf, thank you for the feedback!  There is already an issue for this https://github.com/ansible/awx/issues/10114.  I think the fix should be on the AWX side, so I will close this issue in favor of that one.  

Also, there is a PR up for it which should make it in shortly [here](https://github.com/ansible/awx/pull/10204)

In the meantime, a work-around would be to manually create a pull secret in the namespace of your k8s/ocp cluster, then specify your `imagePullSecret` in the podspec of your Container Group in AWX.
