### ISSUE TITLE
Setting proxy environment

### ISSUE THREAD

**Issue by mothy60** [ansible/tower-operator#316]
##### ISSUE TYPE
 - User issue

##### SUMMARY
I cannot find how to get the AWX UI to honour proxy environment vars under Minikube. I can get minikube/docker and the pods all to works like so;

minikube start --cpus=2 --memory=4g --addons=ingress --docker-env http_proxy=$http_proxy --docker-env https_proxy=$https_proxy

vi myawx.yml
~~~
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_ingress_type: Ingress
  tower_task_extra_env: |
    - name: http_proxy
      value: http://192.168.1.12:3128
    - name: https_proxy
      value: http://192.168.1.12:3128
    - name: no_proxy
      value: localhost,127.0.0.1      
  tower_web_extra_env: |
    - name: http_proxy
      value: http://192.168.1.12:3128
    - name: https_proxy
      value: http://192.168.1.12:3128
    - name: no_proxy
      value: localhost,127.0.0.1      
~~~

However the UI isn't using the settings, I've also tried setting AWX_TASK_ENV but nothing I've tried is working. 
What im trying to do it add a GIT project tree, but its just timing out and i never see anything hit the proxy, if I shell into a container i can curl it without issues and what im passing here is in the env;

bash-4.4$ env | grep -i prox
HTTP_PROXY=http://x.x.x.x:3128
NO_PROXY=localhost,127.0.0.1
HTTPS_PROXY=http://x.x.x.x:3128
AWX_TASK_ENV=http_proxy=http://x.x.x.x:3128,https_proxy=http://x.x.x.x:3128

**Comment by tchellomello** [comment]
@mothy60 it seems the `awx-operator` is passing the variables as expected. I would say its something up on your network. 

So in light of this, what happens if you enable the "Run Project Updates With Higher Verbosity" on Settings -> Jobs and then re-run the project sync. Could you share that output?

**Comment by shanemcd** [comment]
Closing due to lack of response. Please let us know if we should reopen this issue.
