### ISSUE TITLE
Backup TLS secret if specified on the spec

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/tower-operator#322]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We need to conditionally backup and restore the TLS secret if it is specified on the spec or the AWX CR or else the restore will fail.  

Bonus: If this can be done in a dynamic way that will make it easier to add new secrets to the backup and restore roles later on, that would be ideal.  

Ideas:
* Create a `k8s_dump_resource` module.  Have a step where we gather a list of secrets that need to be backed up based on the spec, then iterate across that list producing a YAML file with all of the secret definitions in it.  This single definition file could then easily be applied in a single task at restore time.  

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: 0.9.0

##### ADDITIONAL INFO

The Route TLS cert gets loaded [here](https://github.com/ansible/awx-operator/blob/7b7965d506a71f62ac867203613e9b752ff4e440/roles/installer/tasks/main.yml#L37-L41).  

The LDAP cert secret also needs to be backed up, that gets pulled in [here](https://github.com/ansible/awx-operator/blob/7b7965d506a71f62ac867203613e9b752ff4e440/roles/installer/tasks/main.yml#L23-L26).

**Comment by rooftopcellist** [comment]
We need to add the `image_pull_secret` as part of this.  This is the list:
* route_tls_secret
* ldap_cacert_secret
* image_pull_secret

**Comment by Zokormazo** [comment]
Verified, the tls cert is properly backed and restored with https://github.com/ansible/awx-operator/pull/397
