### ISSUE TITLE
AWX-OPERATOR NOT DEPLOY A BASIC INSTANCE OF AWX

### ISSUE THREAD

**Issue by DanRod1** [ansible/tower-operator#325]
[kube-awx.zip](https://github.com/ansible/awx-operator/files/6507712/kube-awx.zip)
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After deploying an AWX instance with the last awx-operator on an simple K8S cluster every thing seems to be correct with no errors but the awx application do not responding.

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: 0.9.0
* Kubernetes version: v1.20.5
* AWX install method: awx-operator

##### STEPS TO REPRODUCE

kubectl create -f kube-awx.yaml ( see file join )

##### EXPECTED RESULTS

Access to Webui of awx

##### ACTUAL RESULTS

--2021-05-19 11:28:17--  http://s491liak8node1:32455/
Resolving s491liak8node1 (s491liak8node1)... 10.28.19.15
Connecting to s491liak8node1 (s491liak8node1)|10.28.19.15|:32455... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2021-05-19 11:28:17 ERROR 500: Internal Server Error.

##### ADDITIONAL INFORMATION
After deploying the CDR AWX with my manifest kube-awx.yaml everything is correct.
I chose the tower_ingress_type: Ingress

I see the service correctly defined and the docker instance running on the correct node and binding the correct tcp port.
**[binfra.ansible.user@s491liak8mstr1 ~]$ kubectl describe svc awx-service -n awx**
Name:                     awx-service
Namespace:            awx
Labels:                     app.kubernetes.io/component=awx
                                app.kubernetes.io/managed-by=awx-operator
                                app.kubernetes.io/name=awx
                                app.kubernetes.io/part-of=awx
Annotations:            <none>
Selector:                  app.kubernetes.io/component=awx,app.kubernetes.io/managed-by=awx-operator,app.kubernetes.io/name=awx
Type:                      NodePort
IP Families:             <none>
IP:                           10.108.108.18
IPs:                          10.108.108.18
Port:                         http  80/TCP
TargetPort:               8052/TCP
**NodePort:                http  32455/TCP**
Endpoints:               172.16.98.168:8052
Session Affinity:       None
External Traffic Policy:  Cluster
**Events:                   <none>**

here is the status of the pods created by awx-operator

**[binfra.ansible.user@s491liak8mstr1 ~]$ kubectl get pod -n awx -o wide**
NAME                            READY   STATUS             RESTARTS   AGE     IP              NODE             NOMINATED NODE   READINESS GATES
**awx-85d7cbfb8-nfq2m             4/4     Running            0          44h     172.16.98.168   s491liak8node1   <none>           <none>**
awx-operator-5595d6fc57-4hn55   1/1     Running            4          12d     172.16.98.156   s491liak8node1   <none>           <none>
awx-operator-5595d6fc57-6z5xp   0/1     CrashLoopBackOff   2786       6d23h   172.16.98.167   s491liak8node1   <none>           <none>
**awx-postgres-0                  1/1     Running            0          44h     172.16.184.27   s491liak8node2   <none>           <none>**

when I try to simply connect with curl or a more sophicated browser got 500 error:
**[binfra.ansible.user@s491liak8mstr1 ~]$ wget http://s491liak8node1:32455**
--2021-05-19 11:28:17--  http://s491liak8node1:32455/
Resolving s491liak8node1 (s491liak8node1)... 10.28.19.15
Connecting to s491liak8node1 (s491liak8node1)|10.28.19.15|:32455... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2021-05-19 11:28:17 ERROR 500: Internal Server Error.

**Comment by tchellomello** [comment]
@DanRod1 try to inspect the logs from your `awx` pod to see why you are getting the error 500.

**Comment by wenottingham** [comment]
Closing due lack of input.
