### ISSUE TITLE
awx deployment with external db issue.

### ISSUE THREAD

**Issue by psreddy22** [ansible/tower-operator#328]
Hello Team,

Can someone look into below issue and un-block us !!

By using awx-operator [ansible/awx-operator:**0.9.0**] trying to install awx with the option of external postgress server. except postgress connection everything is working as expected.

below debugging output.

```yaml
**sh-4.4$ cat /etc/tower/conf.d/credentials.py**
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awxdev",
        'USER': "awxdev",
        'PASSWORD': "thepass",
        'HOST': '10.10.10.12',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
                     'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        },
    }
}

BROADCAST_WEBSOCKET_SECRET = "J0S6aYKCbquzZUQFUYVt317nhHidpyL8"


**sh-4.4$ awx-manage check_db**


2021-05-20 16:59:28,847 ERROR    [-] awx.main.utils.encryption Failed to decrypt `Setting(pk=13).value`; if you've recently restored from a database backup or are running in a clustered environment, check that your `SECRET_KEY` value is correct
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/fernet.py", line 104, in _verify_signature
    h.verify(data[-32:])
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify
    ctx.verify(signature)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.


**sh-4.4$ psql -h 10.10.10.12 -U awxdev -d awxdev**
Password for user awxdev: 
psql (12.5, server 10.6)
Type "help" for help.

awxdev=> \q
```

is there any relation with the SPEC variable (privilised)

Any leads will be helpful to un-block. Thanks in advance.

Thanks, Srinivasa

**Comment by tchellomello** [comment]
@psreddy22 I believe the error you are hitting is related to the `SECRET_KEY` (https://github.com/ansible/awx-operator/blob/devel/docs/migration.md#secret-key) not matching with the one when the external database was populated. 

If you look on your `web-task` container you will see the following:

```sh
kubectl iexec awx /bin/bash
Namespace: default | Pod: ✔ awx-toca-56b4565768-4djp7
Container: ✔ awx-toca-task
bash-4.4$ cat /etc/tower/SECRET_KEY 
fgCf1!J%3XXXXSSW
bash-4.4$ 
```

This secret is the one used to encrypt/decrypt the things on your database. For example, if you tried to deploy the `awx` multiple times using the same external database, it could be that the version now mismatches with when the database was successfully populated. 

So you have 2 options: 

1) If you know the correct secret,  create a secret as explained in the documentation https://github.com/ansible/awx-operator/blob/devel/docs/migration.md#secret-key and that will be always used for the AWX instance `<resource_name>`.  Then re-deploy the awx instance which should do fine. 

2) If you don't know the expected SECRET_KEY and this is a fresh new database, destroy the database and create a new empty one. Before starting the AWX instance, create the secret_key as explained above and then it should be fine.

**Comment by psreddy22** [comment]
@tchellomello 

Thanks for your quick reply. Yes, I'm using the old database. I modified the secret. Now I'm able to connect with old database and able to login without any issues.

Ps: If we lost the secret-key !! is there any way to retrive secret_key from database.

Once again thanks for your quick reply.

**Comment by tchellomello** [comment]
@psreddy22 great that you were able to fix it.  No, besides doing brute force, I don't know  a method to recover it. 

Since it worked for you, I'm closing this one. Thank you!
