### ISSUE TITLE
installing ansible modules

### ISSUE THREAD

**Issue by acelabs88** [ansible/tower-operator#329]
Can someone tell me how to install ansible modules? I am using winrm to control windows host but getting error like _winrm or requests is not installed: No module named 'winrm'_

**Comment by metabsd** [comment]
You can build your own execution environment with ansible-builder. So you can use it with AWX. I'm using my own one with 19.1.0.

**Comment by acelabs88** [comment]
Awesome - let me check it out. Thanks @metabsd !

**Comment by acelabs88** [comment]
I got it working. Looks like the latest awx-ee already has this supported: https://github.com/ansible/awx-ee/pull/54

Thanks @metabsd again for the pointer.
