### ISSUE TITLE
Manifest file

### ISSUE THREAD

**Issue by sry90** [ansible/tower-operator#336]
Hi ! 

I am looking for the manifest file location that specify the deployment resource for pods replica (awx and not the operator).
Do you know where can i find it ? 

Thanks a lot

**Comment by tchellomello** [comment]
@sry90 not sure if I'm following your question, but you can look at the deployment template at https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/deployment.yaml.j2.

**Comment by sry90** [comment]
Thanks for your answer @tchellomello :)
Okay nice, but i notice in that file that the replica parameter take the variable "replica" that is 1 by default in the variable default file. When i launch the manifest deploy my-awx, the awx pods are 4 , where is the "4" value that i can changed (or not ?).
I don't know if i'm clear :p

Thanks !

**Comment by tchellomello** [comment]
The 4 you see it's the number containers you have in that pod. If you look at the file I linked, you will see the `image` listed for times. (web, task, memcache and we). 

When you add a new replica, you will see another pod with a another set of 4.

**Comment by sry90** [comment]
Oh oK ok very thanks for your reply :)
