### ISSUE TITLE
AWX instance template variables require "tower_"

### ISSUE THREAD

**Issue by bandwiches** [ansible/tower-operator#340]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX instance variables fail to validate without "tower_" being prepended.

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: 0.9.0
* Kubernetes version: minikube (v1.18.0 and v1.20.0)
* AWX install method: docker on linux

##### STEPS TO REPRODUCE
Follow install steps in `README.md`

##### EXPECTED RESULTS
To validate and install the AWX instance.

##### ACTUAL RESULTS
AWX instance template fails validation and never gets applied.
```
error: error v alidating "awx.yml": error validating data: [ValidationError(AWX.spec): unknown field "hostname" in com.ansible.awx.v1beta1.AWX.spec ...
```
This error is present for every variable listed under `spec`.

##### ADDITIONAL INFORMATION

#331 removed the `tower_` prepend from the instructions, but the latest awx-operator release (0.9.0) doesn't support the current instructions.

Prepending variables with "tower_" fixes the issue.

##### AWX-OPERATOR LOGS
N/A

**Comment by tchellomello** [comment]
@bandwiches the version `0.9.0` was released before PR #331 and therefore you still need you use the `tower_` to get things configured. The new format is currently only in the `devel` branch and it will be present whenever the newer version gets released. 

If you are using the `0.9.0` version, then you have to follow the docs on the same branch at https://github.com/ansible/awx-operator/tree/0.9.0
