### ISSUE TITLE
Ansible Collections path still not set ALL Inventory plugins broken

### ISSUE THREAD

**Issue by frenchtoasters** [ansible/tower-operator#36]
Version: 0.5.0
Issue: 
The `AWX_ANSIBLE_COLLECTIONS_PATHS = '/var/lib/awx/vendor/awx_ansible_collections'` is not being set still in the lastest version of the operator. Without this it is not possible to use the VMware inventory plugin. 

FIX:
Ensure that the latest version that is built picks up the changes to the https://github.com/ansible/awx-operator/blob/devel/roles/awx/templates/tower_config.yaml.j2 template

**Comment by frenchtoasters** [comment]
I have tested out the latest build of the operator 0.5.0 and this path is still not being added to the `awx-settings` configmap that is generated. The path is already on the devel branch and the operator container just needs to be rebuilt to reflect the change in this template file https://github.com/ansible/awx-operator/blob/devel/roles/awx/templates/tower_config.yaml.j2

**Comment by thedavidwhiteside** [comment]
I ran into this same issue.  Rebuilt the container from source and it resolved the issue.  It would be nice if there was a release that fixed this as it is a major blocker for using awx.

**Comment by frenchtoasters** [comment]
Ya i know that I could build my own image with it however id rather not do that and have to migrate back to main image later on. This is a simple rebuild of the image and it was already in the repo before 0.5.0 was released. So not sure if RedHat/Ansible has plans too keep the fix out of the project cause they want us to pay for Tower or it was just missed in the update of the image to 0.5.0 cause of caching issue or something like that.

**Comment by thedavidwhiteside** [comment]
I built an image from dev and put it on dockerhub.

docker pull starboarder2001/awx-operator:0.5.1

**Comment by frenchtoasters** [comment]
After some additional testing I have found that this issue _also_ effects _ALL_ collections and not just VMware. In testing the openstack inventory I received the same error just with the openstack plugin as the missing plugin. The fix for this is already on master we just need the images updated to actually pull in the changes made to this template, https://github.com/ansible/awx-operator/blob/devel/roles/awx/templates/tower_config.yaml.j2#L39 so that the operator is maintaining a working version of the `tower_config.yaml`.

**Comment by minyor** [comment]
Can I meanwhile, somehow update generated by minikube AWX installation using master latest?
@thedavidwhiteside I tried your image but it gives me error in the logs about non-existent private key or something and I'm not qualified enough to try and resolve it myself..

**Comment by tchellomello** [comment]
worked for me. It's present on the `task_ee` now and worked as expected. 
```bash
kubectl iexec awx-toca /bin/bash                                         13:30:48
Container: ✔ awx-toca-task
bash-4.4$ awx-manage shell_plus --quiet
Python 3.8.3 (default, Aug 31 2020, 16:03:14) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> settings.AWX_ANSIBLE_COLLECTIONS_PATHS
'/var/lib/awx/vendor/awx_ansible_collections'
``` 
```yaml
# kubectl images awx-toca                                                  13:31:59
[Summary]: 1 namespaces, 1 pods, 4 containers and 3 different images
+---------------------------+---------------+------------------------------+
|          PodName          | ContainerName |        ContainerImage        |
+---------------------------+---------------+------------------------------+
| awx-toca-77d8755cd6-6kqv6 | redis         | redis:latest                 |
+                           +---------------+------------------------------+
|                           | awx-toca-web  | quay.io/ansible/awx:19.0.0   |
+                           +---------------+                              +
|                           | awx-toca-task |                              |
+                           +---------------+------------------------------+
|                           | awx-toca-ee   | quay.io/ansible/awx-ee:0.1.1 |
+---------------------------+---------------+------------------------------+
```

Closing but feel free to reopen if needed. Thanks!
