### ISSUE TITLE
Install awx-operator all resources in one namespace

### ISSUE THREAD

**Issue by mo-saeed** [ansible/tower-operator#360]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I would like to install AWX operator resource in one namespace but this is not possible coz some resources generated in this file https://raw.githubusercontent.com/ansible/awx-operator/0.10.0/deploy/awx-operator.yaml have namespace "default" hardcoded (e.g. serviceaccount, clusterrolebinding) 

How can i install awx-operator in namespace other than default without the need to download the file each time and modify the namespace manually?

##### ENVIRONMENT
* AWX version: latest
* Operator version: latest
* Kubernetes version: 1.20.4
* AWX install method: awx-operator

##### STEPS TO REPRODUCE
running kubectl apply - n awx-operator -f https://raw.githubusercontent.com/ansible/awx-operator/0.10.0/deploy/awx-operator.yaml 

instead of installing all resources in awx-operator namespace, it will install some resources in default namespace.

##### EXPECTED RESULTS
install all awx-operator components in one single namespace

**Comment by Zokormazo** [comment]
donwload the file, modify those `namespace: default` as you wish and deploy with `-f ./awx-operator.yaml`

**Comment by mo-saeed** [comment]
I am looking for sth dynamic, downloading the file for each version and modify the namespace is not really how it should work.

**Comment by mo-saeed** [comment]
maybe solution for that, create namespace in the yaml file (e.g. with name `awx-operator` and add it to all resources to avoid installing software in default namespace

**Comment by mo-saeed** [comment]
Right now also I have another issue, which the current installation procedure requires me to update the yaml files manually.

in our cluster we are using node selectors and node taints, which needs to be added to the deployment file so the pod can be scheduled in a specific node.

The installation procedure in this way is just a nightmare if we need every time to upgrade the operator, is there any plans to support somehow better way of installation e.g. using helm or using ansible ?

**Comment by ghost** [comment]
I'm trying to install the awx-operator in its own namespace called AWX.  I tried changing all instances of the namespace keyword from default to awx and it's still creating some resources in default.

**Comment by BrandonALXEllisSS** [comment]
Wouldn't it be best to just use a kustomization.yml file and use that to edit the namespaces (instead of manually setting it yourself)?

Here's what I used:

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./awx-operator.yml
  - ./awx-config.yml
namespace: ${Namespace}
```
Where `${Namespace}` is the name of your namespace, `awx-operator.yml` is the Custom Resource Definition config file you downloaded from `https://raw.githubusercontent.com/ansible/awx-operator/<TAG>/deploy/awx-operator.yaml`, and `awx-config.yml` is the config file you were prompted to apply 

i.e. something like 
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  ingress_type: none
  hostname: awx-demo.example.com
```

When you have all three of those files `awx-config.yml`, `awx-operator.yml`, and `kustomization.yml`, put them in a single folder (let's say it's named "folder") and run the command `kubectl apply -k folder`

**Comment by TheITRx** [comment]
> I'm trying to install the awx-operator in its own namespace called AWX. I tried changing all instances of the namespace keyword from default to awx and it's still creating some resources in default.

I'm having the same issue. I hope we can put all the resource in one bucket (namespace).

**Comment by Chris-Carmichael** [comment]
> Wouldn't it be best to just use a kustomization.yml file and use that to edit the namespaces (instead of manually setting it yourself)?
> 
> Here's what I used:
> 
> ```
> ---
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> resources:
>   - ./awx-operator.yml
>   - ./awx-config.yml
> namespace: ${Namespace}
> ```
> 
> Where `${Namespace}` is the name of your namespace, `awx-operator.yml` is the Custom Resource Definition config file you downloaded from `https://raw.githubusercontent.com/ansible/awx-operator/<TAG>/deploy/awx-operator.yaml`, and `awx-config.yml` is the config file you were prompted to apply
> 
> i.e. something like
> 
> ```
> apiVersion: awx.ansible.com/v1beta1
> kind: AWX
> metadata:
>   name: awx-demo
> spec:
>   service_type: nodeport
>   ingress_type: none
>   hostname: awx-demo.example.com
> ```
> 
> When you have all three of those files `awx-config.yml`, `awx-operator.yml`, and `kustomization.yml`, put them in a single folder (let's say it's named "folder") and run the command `kubectl apply -k folder`

This is the right answer, but more clear documentation and examples for folks that aren't familiar with kustomize would be super helpful.

I'm deploying this for a new gig and will share what I come up with.

**Comment by wenottingham** [comment]
The way to do this right now is to edit the namespace in the deployment before deploying. You can use the kustomization.yml as described as well. Let us know if that doesn't work for you.

**Comment by israelintersect** [comment]
I follow the exact steps as indicated by BrandonALXEllisSS but got an error at the end:

> kubectl apply -k folder
customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com created
customresourcedefinition.apiextensions.k8s.io/awxrestores.awx.ansible.com created
customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com created
serviceaccount/awx-operator unchanged
clusterrole.rbac.authorization.k8s.io/awx-operator created
clusterrolebinding.rbac.authorization.k8s.io/awx-operator created
deployment.apps/awx-operator created
error: unable to recognize "folder": no matches for kind "AWX" in version "awx.ansible.com/v1beta1"

Unsure if the kustomization has some extra steps.
