### ISSUE TITLE
Upgrading AWX to 19.2 from 19.1 with Operator fails

### ISSUE THREAD

**Issue by ckozler** [ansible/tower-operator#367]
Hello - I did the `kubectl apply -f <url>awx-operator.yaml` as I have before and Operator normally updates the running version of awx, however, after multiple restarts the 19.1 is not being updated. When I look at the logs for Operator, this is what I see

`,\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"Service \\\\\\\\\\\"awx-service\\\\\\\\\\\" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is \\\\'ClusterIP\\\\'\\\",\\\"reason\\\":\\\"Invalid\\\",\\\"details\\\":{\\\"name\\\":\\\"awx-service\\\",\\\"kind\\\":\\\"Service\\\",\\\"causes\\\":[{\\\"reason\\\":\\\"FieldValueForbidden\\\",\\\"message\\\":\\\"Forbidden: may not be used when `type` is \\\\'ClusterIP\\\\'\\\",\\\"field\\\":\\\"spec.ports[0].nodePort\\\"}]},\\\"code\\\":422}\\\\n'\", \"reason\": \"Unprocessable Entity\", \"status\": 422}\nok: [localhost] => (item=ingress) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"item\": \"ingress\", \"result\": {\"results\": []}}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=29   changed=0    unreachable=0    failed=1    skipped=26   rescued=0    ignored=0   \r\n\n",`

The only thing that worked for me was 

` kubectl patch service/awx-service --type='json' -p '[{"op":"replace","path":"/spec/type","value":"ClusterIP"},{"op":"replace","path":"/spec/ports/0/nodePort","value":null}]'`

Not sure if I changed something along the way but when trying to upgrade it failed on service/awx-service with the above error. Trying to use kubectl edit did not work but patch did 

Disclaimer: I am still a bit new with kube so its very likely I did something before and then creating the error scenario that we see here

**Comment by MaximilianMeister** [comment]
> Disclaimer: I am still a bit new with kube so its very likely I did something before and then creating the error scenario that we see here

@ckozler JFYI: I have encountered the same error while upgrading from 19.1.0 to 19.2.0

There have been some notable breaking changes you need to address. In this case you need to set a `service_type` through the awx spec, and also all variables lost the `tower_` prefix, see https://github.com/ansible/awx-operator/blob/devel/CHANGELOG.md#0100-jun-1-2021 and https://github.com/ansible/awx-operator/blob/devel/README.md#service-type

**Comment by ckozler** [comment]
Apologies, what do I need to address? I have 19.2 running by running the patch command in my original post. I've never actually accessed operator so, for me, whether it is ClusterIP or NodePort or LoadBalancer is irrelevant

**Comment by AndrewSav** [comment]
> I have 19.2 running by running the patch command in my original post. I've never actually accessed operator so, for me, whether it is ClusterIP or NodePort or LoadBalancer is irrelevant

It may be irrelevant for you but from the error message clearly relevant for the operator ;)

> Apologies, what do I need to address?

It sounds like you already solved your issues with the patch command you quoted. I'm guessing that incompatibilities like that are more or less unavoidable, while the team is experimenting with the operator on the way to version 1 (and even after that I have not seen any compatibility promises ;)

**Comment by tchellomello** [comment]
@ckozler this issue is expected due to the breaking change introduced by https://github.com/ansible/awx-operator/pull/330

Before the `NodePort` was always added, while with the new version, you must set the `service_type: NodePort` in order to have it. 

You should be able to adjust it by modifying your `spec` and determining if you either want to use `NodePort` or `ClusterIP`. (see https://github.com/ansible/awx-operator#service-type). Then if you delete your service the `awx-operator` should reconcile with no problems. 

I'm going to close it but if that does not work for you, feel free to reopen it.  Then please share your `awx` spec.
