### ISSUE TITLE
dhcp enterprise network

### ISSUE THREAD

**Issue by v1rtual-exe** [ansible/tower-operator#371]
Hello.
Tell me ...
Installed AWX in the enterprise network ... 10.50 ....
How to make the address from the DHCP server of the local network, and not 192.168 ..... ??

**Comment by Gamerboy59** [comment]
You mean exposing awx ingress on your public network for remote access (eth0, vnet0 etc.) and not for internal access (192.168.x.x),?

**Comment by AndrewSav** [comment]
Yeah, it's not clear what's being asked. At the face value awx-opearator is not something that is concerned with networking, questions like that are usually solved on docker/kubernetes level and are not specific to particular apps such as awx.

**Comment by v1rtual-exe** [comment]
> 
> 
> You mean exposing awx ingress on your public network for remote access (eth0, vnet0 etc.) and not for internal access (192.168.x.x),?

Yes, that would be the address from my dhcp server

**Comment by v1rtual-exe** [comment]
> 
> 
> Yeah, it's not clear what's being asked. At the face value awx-opearator is not something that is concerned with networking, questions like that are usually solved on docker/kubernetes level and are not specific to particular apps such as awx.

Most likely it was incorrectly expressed, I still feel bad in docker/kubernetes.

**Comment by tchellomello** [comment]
As noted above, your question is more related to the k8s infrastructure than the `awx-operator` itself.  I would recommend checking how to configure an ingress controller, or implementing a `LoadBalancer` such as `metallb`  on your k8s cluster choice.

Closing it for now.

**Comment by v1rtual-exe** [comment]
> 
> 
> As noted above, your question is more related to the k8s infrastructure than the `awx-operator` itself. I would recommend checking how to configure an ingress controller, or implementing a `LoadBalancer` such as `metallb` on your k8s cluster choice.
> 
> Closing it for now.

So what's the problem?
This is all part of one ... Maybe someone will have the same question and he will need a decision ... or he already decided to ...
