### ISSUE TITLE
as an ansible user I would like to install the AWX using ansible

### ISSUE THREAD

**Issue by mihai-satmarean** [ansible/tower-operator#375]
##### ISSUE TYPE
 - Feature request

##### SUMMARY

Before the mandatory use of the AWX operator, we had a nice simple ansible playbook to maintain the whole life cycle of an AWX service. We would like to have that with the AWX operator. Unfortunately, the operator is ever-changing so any attempts to maintain a playbook are failing.

**Comment by andrewsav-bt** [comment]
Just my two cents: Given that the team recently chose to depart from the legacy installation way with an ansible playbook to use more modern operator approach, it is not very likely that they will bring the old way back. They [already stated](https://github.com/ansible/awx/issues/10340#issuecomment-854049813) that they are a small team and can do only so much, so they are primarily focused on what's beneficial for _them_. From all I can see what you are suggesting is not beneficial, which is evidenced by the recent switch to the operator.

Good question, but in realty chances are low.

As for the ever-changing operator, they have not hit version 1 yet, so there is no compatibility expectation and this is more or less expected.

**Comment by AndrewSav** [comment]
Just my two cents: Given that the team recently chose to depart from the legacy installation way with an ansible playbook to use more modern operator approach, it is not very likely that they will bring the old way back. They [already stated](https://github.com/ansible/awx/issues/10340#issuecomment-854049813) that they are a small team and can do only so much, so they are primarily focused on what's beneficial for _them_. From all I can see what you are suggesting is not beneficial, which is evidenced by the recent switch to the operator.

Good question, but in realty chances are low.

As for the ever-changing operator, they have not hit version 1 yet, so there is no compatibility expectation and this is more or less expected.

**Comment by wenottingham** [comment]
This is correct - it was an intentional decision to move to operator-first deployment, to have a more native k8s way of doing it. We don't intend to go back to playbook-based deployments for that.

**Comment by mihai-satmarean** [comment]
Hi guys, @wenottingham long time no see :) last time I guess was at Paris automate.
I agree with you that you need to move to more k8s'quesque ways. What I just wanted to point is that we are used with Ansible and every tool surrounding it as a "battery included" philosophy. While now, with the operator, the AWX becomes a lotus on the lake. You need to make the planet, the lake, and the operator just gets you the lotus.
What I would like to have, even participate and help, is something like @geerlingguy  describes here, https://www.ansible.com/blog/how-useful-is-ansible-in-a-cloud-native-kubernetes-environment, a playbook or a set of playbooks/roles that can manage the infrastructure as code and the configuration part of the installation.
If not in sight for now, I am pretty sure that you guys when you develop the operator and the AWX deploy a lot of clusters and maintain a ton of text files, maybe you can share what tools are useful to which part of the process.
My issue here, and maybe not only mine, is that we were used installing Ansible tower from tar file, which is bad bad we made it work. Next came docker, we loved the part that you do not need to write and maintain your own roles to manage Ansible Tower.
The shock came next month after ver 17.0.0 where the Operator is mandatory. That did not gave enough time for people using it in production to automate kubernetes clusters same way we have automated docker hosts. Additionally there are some particularities and customisations that we needed to make inside the dockerized versions to work with site to site VPN's across hybrid clouds and on premises infra, all kind of plugins like proxmoxer or vmware, that all of the sudden we have no idea how to port them to the new way.
So what I am asking, if not a nice playbook, is where can we turn to with those questions, to have them answered by people close to the AWX development strategy and then we can adapt our current deployments to those ideas and tools.
Hope is not too long and it makes sense,

Always appreciated your efforts and let me congratulate you guys once more for the tremendous tools you put on the scene!

Cheers,
Mihai
