### ISSUE TITLE
how to best manage custom python dependencies when using the awx-operator?

### ISSUE THREAD

**Issue by jcomito** [ansible/tower-operator#38]
What is the recommenced approach to adding custom modules (ex, PyWinRM) or making other needed changes in the containers without modifying the image itself?

**Comment by kladiv** [comment]
+1
But i guess we should check new Container Groups (and Execution Environment) approch:
https://docs.ansible.com/ansible-tower/latest/html/administration/external_execution_envs.html#create-a-container-group

**Comment by ryanpetrello** [comment]
Hey folks 👋, AWX 18.0.0 is out now, and supported via this operator; Execution Environments are *the* sanctioned approach for customized Python dependency management.
