### ISSUE TITLE
configure execution_envs pod spec during installation

### ISSUE THREAD

**Issue by mo-saeed** [ansible/tower-operator#382]
##### SUMMARY
Is it possible to configure execution environment pod spec https://docs.ansible.com/ansible-tower/latest/html/administration/external_execution_envs.html#customize-the-pod-spec during AWX installation by the operator  ?

##### ENVIRONMENT
* AWX version: latest
* Operator version: latest
* Kubernetes version: 1.20.4

**Comment by tchellomello** [comment]
@mo-saeed currently it's not.  You can determine the EE images (https://github.com/ansible/awx-operator#deploying-a-specific-version-of-awx)  via the operator spec, but not customize spec. 

Closing as duplicated at https://github.com/ansible/awx-operator/issues/242

**Comment by kevrrnet** [comment]
@tchellomello 
is this the case ? 
have we add this feature ?
