### ISSUE TITLE
Node Selector for Execution Environments

### ISSUE THREAD

**Issue by nniehoff** [ansible/tower-operator#389]
I'm not sure if this is a bug, if so I can provide more info, but I'm hoping it's a simple question.  I need to provide a `nodeSelector` for the execution environments.  I have added `node_selector` to the spec of the awx object and I can see it in the awx deployment but execution environments are spun up on the wrong hosts, not following the `node_selector`.  Is there a way to specify a nodeSelector for the ee environments?

**Comment by wenottingham** [comment]
Marking as a duplicate of https://github.com/ansible/awx-operator/issues/242
