### ISSUE TITLE
Updating 'admin' username after data migration fails 

### ISSUE THREAD

**Issue by KarthikKalla** [ansible/tower-operator#390]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I have completed data migration from Old to New Postgres. Therefore admin username will exist and "initialize_django.yml"
is supposed to update it depending on its first task. But sadly it fails with few errors. which i'll provide below.
Next it skips to creating admin user and it fails due to the error(ID already exists)

##### ENVIRONMENT
* AWX version: 19.2.0
* Operator version: 0.10.0
* Kubernetes version: 1.20
* AWX install method: Minikube with latest kubernetes and docker 19

##### STEPS TO REPRODUCE

Install with old postgres config and by checking operator logs while initialize_django.yml is running.
I basically edited to get debug output of the task.

##### EXPECTED RESULTS

initialize_django.yml is supposed to get the correct result while checking for existing user and then update admin password should run.

##### ACTUAL RESULTS

The admin password isnt updated and couldnt login to AWX.
I had to manually change the admin password : " awx-manage update_password --username admin --password ****  "

##### ADDITIONAL INFORMATION
Reason for this error which i could find. Its the variable assignment with single quotes.
variable from code: **username='{{ admin_user }}'** . Here single quotes are missing after assignment.

bash-4.4$ awx-manage shell
Python 3.8.3 (default, Aug 31 2020, 16:03:14)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.contrib.auth.models import User;
>>> User.objects.filter(is_superuser=True, **username='admin'**).count()
1

>>> User.objects.filter(is_superuser=True, **username=admin**).count()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'admin' is not defined
>>>

##### AWX-OPERATOR LOGS
--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Check if there are any super users defined.] *****************
task path: /opt/ansible/roles/installer/tasks/initialize_django.yml:2

-------------------------------------------------------------------------------
{"level":"info","ts":1623606340.169214,"logger":"logging_event_handler","msg":"[playbook task]","name":"awx-demo","namespace":"awx-helm","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"2775422040480279449","EventData.Name":"installer : Check if there are any super users defined."}
.
.
.
 TASK [debug] ********************************
ok: [localhost] => {
    "users_result": {
        "changed": true,
        "failed": false,
        "return_code": 1,
        "stderr": "Traceback (most recent call last):\n  File \"/usr/bin/awx-manage\", line 8, in <module>\n    sys.exit(manage())\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py\", line 164, in manage\n    execute_from_command_line(sys.argv)\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line\n    utility.execute()\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py\", line 375, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py\", line 323, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py\", line 364, in execute\n    output = self.handle(*args, **options)\n  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/commands/shell.py\", line 92, in handle\n    exec(sys.stdin.read())\n  File \"<string>\", line 1, in <module>\nNameError: name 'admin' is not defined\n",
        "stderr_lines": [
            "Traceback (most recent call last):",
            "  File \"/usr/bin/awx-manage\", line 8, in <module>",
            "    sys.exit(manage())",
            "  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py\", line 164, in manage",
            "    execute_from_command_line(sys.argv)",
            "  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py\", line 381, in execute_from_command_line",
            "    utility.execute()",
            "  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py\", line 375, in execute",
            "    self.fetch_command(subcommand).run_from_argv(self.argv)",
            "  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py\", line 323, in run_from_argv",
            "    self.execute(*args, **cmd_options)",
            "  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py\", line 364, in execute",
            "    output = self.handle(*args, **options)",
            "  File \"/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/commands/shell.py\", line 92, in handle",
            "    exec(sys.stdin.read())",
            "  File \"<string>\", line 1, in <module>",
            "NameError: name 'admin' is not defined"

**Comment by shanemcd** [comment]
Hi. This was a bug fixed in https://github.com/ansible/awx-operator/commit/6b57caeb9237501c27d1aae18a996fde15baa7f5 and will be out in the next release of the operator later today.
