### ISSUE TITLE
Adding extra search domain to AWX "/etc/resolv.conf" file

### ISSUE THREAD

**Issue by felipe4334** [ansible/tower-operator#403]
Hello guys, so I'm having an issue that after hours of trying different solutions I have not been able to resolve. Currently I have a Kubernetes cluster hosted on Oracle Cloud. One of the limitations of Oracle is that the DHCP configuration for the network only supports one search domain at a time, therefore, when my pods(AWX) inherit the `/etc/resolv.conf` from the cluster they can only search on one domain(office.domain.com). I understand that with a normal pod you can do something like this:
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
```
spec:
  dnsConfig:
    searches:
      - office.domain.com
      - prod.domain.com
```

But AWX does not support that. 

I tried creating a coredns-custom name servers like this:
https://docs.microsoft.com/en-us/azure/aks/coredns-custom

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  domain.server: | 
    prod.domain.com:53 {
        errors
        cache 30
        forward . 10.5.0.31
    }
```

and although I can hit a server by using the full FQDN path(servername.prod.domain.com) when I try just hitting(servername) I cant since the `prod.domain.com` is not part of the search domains on /etc/resolv.conf. I know that I can manually change this value of this pods but I would like to have a solution that can be replicated and not have to worry about the pods being recreated and losing the changes. Thank you so much for your help.

![image](https://user-images.githubusercontent.com/13802820/122163893-e4b30400-ce43-11eb-9658-1e3dbedb1e43.png)

"coredns" ConfigMap
```
.:53 {
  errors
  health
  ready
  kubernetes cluster.local in-addr.arpa ip6.arpa {
    pods insecure
    fallthrough in-addr.arpa ip6.arpa
  }
  forward . /etc/resolv.conf
  cache 30
  loop
  reload
  loadbalance
}
import custom/*.server
```

**Comment by felipe4334** [comment]
@tchellomello Have you every come across something similar?

**Comment by felipe4334** [comment]
Any help would be appreciated.

**Comment by tchellomello** [comment]
@felipe4334 are you trying to hit just the shortname when running a playbook (via ee) or when trying to sync hosts via inventory?

Could you provide us an example why or how you are using a shortname resolution? 

Thanks

**Comment by felipe4334** [comment]
@tchellomello I'm trying to hit short names when running playbooks via EE. The inventory I work with use short names and it's not possible to get the FQDN for the inventory at the moment. 
![image](https://user-images.githubusercontent.com/13802820/122648658-28359880-d0f8-11eb-8074-844d8e8e88e8.png)

I'm trying to run playbooks on hosts that look like the picture above. Those hosts are part of groups, and the groups can have production or non-production hosts in them.

**Comment by tchellomello** [comment]
@felipe4334  I hear you. So, have you tried to customize the pod spec for your instance group, so the `ee` will have the `spec.dnsConfig.searches` properties that you are looking for?  something like this?

![image](https://user-images.githubusercontent.com/809840/122648885-24564600-d0f9-11eb-9c2c-52b364ffebaa.png)

**Comment by felipe4334** [comment]
@tchellomello You're a genius. automation-jobs pods are now able to resolve prod servers, you rock!
![image](https://user-images.githubusercontent.com/13802820/122649521-253ca700-d0fc-11eb-8cfa-3e0bc9b957fe.png)

EE is still not able to but I'm guessing for that I will need to create my own custom image and just provide it here?
![image](https://user-images.githubusercontent.com/13802820/122649533-384f7700-d0fc-11eb-8e84-bdc04b790e78.png)

**Comment by tchellomello** [comment]
Glad it worked for you! You are correct. You can build your own EE so you can build your image (or it can be a clone or a new tag) from the original one and then provide your own pod spec.  There is currently a PR around the `control_plane` to enhance the documentation in this area at https://github.com/ansible/awx-operator/pull/412.

**Comment by tchellomello** [comment]
Closing this as #412  got merged and documentation has been updated

**Comment by ebarped** [comment]
This is still a "workaround". The awx CRD should have a podSpec field that enables the user to override config like this (dnsConfig, securityContext, etc.)
