### ISSUE TITLE
Add livenessProbe, startupProbe  do AWX deployment

### ISSUE THREAD

**Issue by tchellomello** [ansible/tower-operator#414]
##### ISSUE TYPE
 - Feature Idea
 
##### SUMMARY
Adding *livenessProbe*, *startupProbe* is a step towards the right direction to use HPA rules and ensure pod availability.

**Comment by wenottingham** [comment]
See also: https://github.com/ansible/awx/issues/7828

**Comment by rooftopcellist** [comment]
This was implemented and merged here:
* https://github.com/ansible/awx-operator/pull/1674

Please check it out!
