### ISSUE TITLE
how to import database from old awx installation

### ISSUE THREAD

**Issue by 0xbrigles** [ansible/tower-operator#416]
Hello, i can't find a related topic for my problem so created a new one.
SInce we change from the docker based awx installation to awx-operator I'm not able to import our database.
I scaled the deployments to "0" but when I use the drop command in postgres i became the message `ERROR:  cannot drop the currently open database`.

To reproduce i use the following commands:
```
# to prevent using database i scale down the deployments
minikube kubectl -- scale deployment awx-test-maschine --replicas=0
minikube kubectl -- scale deployment awx-operator --replicas=0

# after the deployments halted i try to delete the current db to import a new one in same namespace (awx)
minikube kubectl -- exec -it awx-test-maschine-postgres-0 -- psql -U awx
awx=# DROP DATABASE awx;
ERROR:  cannot drop the currently open database
```
I've tried as much i can but the established connection is still available.
My goals were:
* drop default awx db
* create new awx db
* import old db to newly created awx

Is there an issue in my mind which cause the trouble, maybe there is another way to import the old database? I'm using k8s or better minikube just to work with awx-operator since a few days. Cause of this my skills are not so much at this time. Thats why I'm asking you :)

**Comment by rooftopcellist** [comment]
If your previous deployment was in k8s (via the old playbook installer), then you can use the migration logic we added.  Here are the docs: https://github.com/ansible/awx-operator/blob/devel/docs/migration.md

If you had a local docker deployment (containers on your machine, no cluster), then you will probably want to do a `[pg_dump](https://www.postgresql.org/docs/10/app-pgdump.html)` and `[pg_restore](https://www.postgresql.org/docs/10/app-pgrestore.html)` to the new postgresql pod. 

If you have further questions, the [awx-project mailing list](https://groups.google.com/g/awx-project/) is a good place to ask.
