### ISSUE TITLE
awx-operator 0.11.0 and 0.12.0: Deployment with database migration fails

### ISSUE THREAD

**Issue by lemmy04** [ansible/tower-operator#420]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Deploying AWX > 19.1 with migration / import of an older AWX database (from 17.1 in my case) fails with "role AWX not found" errors

##### ENVIRONMENT
* AWX version: 19.2.x
* Operator version: 0.11.0
* Kubernetes version:
```
mathias@appsrv:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
* AWX install method: kubernetes (k3s) on debian buster

##### STEPS TO REPRODUCE

Follow the steps described in https://github.com/ansible/awx-operator/blob/devel/docs/migration.md

##### EXPECTED RESULTS

It should end up with a running AWX instance prefilled with the content of the older database

##### ACTUAL RESULTS

The deployment eventually ends, with only the postgres pod created, and in the awx-operator logs you find a huge number of database errors, all following the same pattern:
`pg_restore: error: could not execute query: ERROR:  role \\\"awx\\\" does not exist\"`

##### ADDITIONAL INFORMATION

Up to AWX 19.1.0 / awx-operator 0.9.0 this process worked as expected.
A in-place update from 19.1 to 19.2.x fails with the same errors....

##### AWX-OPERATOR LOGS

Full awx operator logs from such a failed attempt are attached.
[failed-awx_migration.txt](https://github.com/ansible/awx-operator/files/6699949/failed-awx_migration.txt)

**Comment by AlekseiSaff** [comment]
I just finished exactly the same migration. And the only working path was to update for operator 0.8.0 and then to 0.11.0

**Comment by lemmy04** [comment]
This still happens with the 0.12.0 operator.

**Comment by ctournoux-maincare** [comment]
I still have the problem in the latest versions of the operator. 
 Any solution to solve postgres resolution problem ?

**Comment by molson504x** [comment]
I also experienced the same thing when attempting to deploy an upgraded instance of AWX 19 using the awx-operator.  

Details:
AWX 15 -> AWX 19 upgrade
AWX 15 running on Postgres 11 (Azure Postgres), AWX 19 running on containerized Postgres 12
Secret key was updated to match on both.
We had the same error about a role not existing.

**Comment by antonmatsiuk** [comment]
im my case upgrade for operator fails from 0.10.0 to 0.11.0 without any meaningful message in the log 
attempt to upgrade 0.10.0 to 0.12.0 fails with `ERROR:  column main_executionenvironment.managed does not exist at character 375` in postgres log

**Comment by chicoraf** [comment]
> im my case upgrade for operator fails from 0.10.0 to 0.11.0 without any meaningful message in the log attempt to upgrade 0.10.0 to 0.12.0 fails with `ERROR: column main_executionenvironment.managed does not exist at character 375` in postgres log

I'm having the same problem right now. I successfully upgrade the database of a AWX version 9.2.0 on docker to 19.2.0 (operator 0.10.0) on k8s, but now I cant update to a new version because of the same error as you, during database migration. Tried operators 11,12,13 and 0.14.0, without success..

**Comment by rooftopcellist** [comment]
If a straight upgrade is not working from these old versions of AWX, I would recommend trying the `migration.md` workflow:
* https://ansible.readthedocs.io/projects/awx-operator/en/latest/migration/migration.html

If you are still experiencing issues, please open a new issue with details. Thanks!
