### ISSUE TITLE
ErrImagePull on AWX-Demo.yml

### ISSUE THREAD

**Issue by cbermudez82** [ansible/tower-operator#422]
Just doing the basic install options following the AWX Operator instructions.  I'm getting this error every time.   This was working a couple of weeks ago.  Has anyone else been getting this issue?
ENVIRONMENT
AWX version: 19.2.1
Operator version: 0.11.0
MiniKube with Kubernates stable version and Docker Docker version 20.10.7, build f0df350

![AWX-19-2-1](https://user-images.githubusercontent.com/38468200/123099199-f6764780-d3ff-11eb-827e-15eb89a15778.png)

**Comment by shanemcd** [comment]
Can you provide the output of `kubectl describe pod awx-demo-578b...`?

**Comment by cbermudez82** [comment]
> Can you provide the output of `kubectl describe pod awx-demo-578b...`?

Shanemcd,
   Thanks I think the helped me figure out my issue.  Looks like my /var/ partition ran out of space since Minikube is using that partition to run.  I will extend the partition and try again.

**Comment by cbermudez82** [comment]
Issue was the /var partition didn't have enough space for Minikube and docker to run.
