### ISSUE TITLE
Ansible version in the execution environment is generating warnings

### ISSUE THREAD

**Issue by AndreasDavour** [ansible/tower-operator#428]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The ansible version in the execution environment is sprouting warnings, as it is a development version. I expected it to be the latest release, at the most. Maybe this could be configurable?

This is how it looks like when running jobs in AWX:

> [WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.

##### ENVIRONMENT
* AWX version: 19.2.1
* Operator version: 0.11.0
* AWX install method: operator installation on rancher

##### STEPS TO REPRODUCE

Spin up a rancher cluster. 
Download 0.11.0 release of the operator -> kubectl apply
Create yaml with an instance of the Kind: AWX and apply it -> kubectl apply
Login to AWX instance and run a job.

##### EXPECTED RESULTS

An Ad hoc job with the command module running 'hostname' should print the hostname

##### ACTUAL RESULTS

An Ad hoc job with the command module running 'hostname'  print the hostname and you also get the warning.

[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.

SSH password:

192.168.1.35 | CHANGED | rc=0 >>

##### ADDITIONAL INFORMATION
If execing into the container running the execution environment I find this ansible version installed:
ansible [core 2.12.0.dev0]

##### AWX-OPERATOR LOGS

Where do I find those?

**Comment by wenottingham** [comment]
This is an issue with how the execution environment is built. Can you file this against https://github.com/ansible/awx-ee? It would need to pull a particular ansible-runner image to change this.

**Comment by AndreasDavour** [comment]
There is already [one](https://github.com/ansible/awx-ee/issues/72) that's soon a month old, unassigned and not commented upon.
