### ISSUE TITLE
Deployment fails when migrating PostgreSQL Database from Docker AWX 17 to Kubernetes AWX 19

### ISSUE THREAD

**Issue by thorian93** [ansible/tower-operator#439]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When deploying AWX using the `awx-operator` in minikube and performing a database migration from an existing AWX setup running on local docker the awx-web container gives the error message below. We followed the installation instructions from this very project to the letter.

##### ENVIRONMENT
* AWX version: 19.2.2 (bundled with operator)
* Operator version: 0.12.0 
* Kubernetes version: 1.21.0
* AWX install method: minikube

##### STEPS TO REPRODUCE

Run the following commands one after another:

1. `minikube start --addons=ingress --cpus=4 --cni=flannel --install-addons=true --kubernetes-version=stable --memory=6g`
2. `kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/0.12.0/deploy/awx-operator.yaml`
3. `kubectl apply -f /opt/awx/awx.yml`
4. `kubectl logs -f deployments/awx awx-web`

The logs show the error below.

##### EXPECTED RESULTS

The database was migrated from local docker into minikube and AWX is up and running.

##### ACTUAL RESULTS

AWX is not accessible, the awx-web container has high load and keeps printing below error.

##### ADDITIONAL INFORMATION

awx.yml:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-secret-key
  namespace: default
stringData:
  secret_key: <REDACTED>
type: Opaque

apiVersion: v1
kind: Secret
metadata:
  name: awx-old-postgres-configuration
  namespace: default
stringData:
  host: <REDACTED>
  port: "<REDACTED>"
  database: <REDACTED>
  username: <REDACTED>
  password: <REDACTED>
type: Opaque

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: default
spec:
  service_type: nodeport
  ingress_type: none
  hostname: <REDACTED>
  old_postgres_configuration_secret: awx-old-postgres-configuration
```

We also found #402 outlining that one needs to give the values in the  `stringData` blocks for the secrets as base64 encoded, but that lead to the same results or different errors, depending on which values where encoded.

We also triple checked the `secret_key` itself and it is definitly the correct one.

Frankly we ran out of ideas where to look.

##### AWX-OPERATOR LOGS

```
2021-06-30 09:17:28,005 ERROR    [-] awx.main.utils.encryption Failed to decrypt `Setting(pk=27).value`; if you've recently res
tored from a database backup or are running in a clustered environment, check that your `SECRET_KEY` value is correct          
Traceback (most recent call last):                                                                                             
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/fernet.py", line 104, in _verify_signature            
    h.verify(data[-32:])                                                                                                       
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify        
    ctx.verify(signature)                                                                                                      
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify  
    raise InvalidSignature("Signature did not match digest.")                                                                  
cryptography.exceptions.InvalidSignature: Signature did not match digest.                                                      
                                                                                                                               
During handling of the above exception, another exception occurred:
```

**Comment by tchellomello** [comment]
@thorian93 this is happening because the `SECRET_KEY` you have does not match with the old instance you are trying to import. 

If you look at your old instance, you will see a `SECRET_KEY` under `/etc/tower/SECRET_KEY`. Basically what you need to do is to modify or create a new secret `awx-secret-key` with that content and then you will able to decrypt the information in the database. 

```yaml
apiVersion: v1
data:
  secret_key: XXXXXXXXXXXXXXXXXXXXdecodedX
kind: Secret
metadata:
  name: awx-secret-key
type: Opaque
```

**Comment by tchellomello** [comment]
@thorian93 here is the function that does that https://github.com/ansible/awx/blob/a58d5718586483da4aacacb88cd54645dcee74e6/awx/main/utils/encryption.py#L140

So if you try it manually via `awx-manage shell_plus` are you able to decrypt it?

```yaml
bash-4.4$ awx-manage shell_plus --quiet
Python 3.8.6 (default, Jan 29 2021, 17:38:16) 
[GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)

## confirm credential
>>> settings.SECRET_KEY
b'OR4RGbd1dVVsaJ6yrluGZ8RR47UuywiW'

## show all credentials
>>> Credential.objects.all()

## get a credential which has a 
>>> Credential.objects.get(id=15).inputs
{'password': '$encrypted$UTF8$AESCBC$Z0xxxxxxxxxxxxxx==', 'username': 'default'}

>>> Credential.objects.get(id=15).get_input('password')
'password'
```

**Comment by thorian93** [comment]
> @thorian93 here is the function that does that https://github.com/ansible/awx/blob/a58d5718586483da4aacacb88cd54645dcee74e6/awx/main/utils/encryption.py#L140
> 
> So if you try it manually via `awx-manage shell_plus` are you able to decrypt it?
> 
> ```yaml
> bash-4.4$ awx-manage shell_plus --quiet
> Python 3.8.6 (default, Jan 29 2021, 17:38:16) 
> [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> (InteractiveConsole)
> 
> ## confirm credential
> >>> settings.SECRET_KEY
> ```

Hi @tchellomello and thanks for the prompt help!

I ran the command `settings.SECRET_KEY` on the old system and can verify that the SECRET_KEY I used for the new deployment is the very same. I assume the `b'` in the beginning and `'` in the end need to be omitted? So I have the right old key.

Update: I just logged into the newly created `awx_web` container and looked into `/etc/tower/SECRET_KEY` and guess what? There is a wrong key in it. Any idea what we are doing wrong? Why does the operator not use our configured key?

**Comment by tchellomello** [comment]
Hello @thorian93, now that you are sure that your `<awx-resourcename>-secret-key` looks correct. What happens if you do:
```bash
$ kubectl delete awx <awx-resourcename>
$ kubectl get awx -A   # should show your wax instance
$ kubectl get secrets <awx-resource>-secret-key # must show your secret key
$ kubectl apply -f <awx-resource-name>
```

Then check again if the `secret_key` inside the container got populated as expected.

**Comment by thorian93** [comment]
Hi @tchellomello, below for reference the output of your commands:

    user@awx:~$ kubectl get awx -A
    NAMESPACE   NAME   AGE
    default     awx    5m19s
    user@awx:~$ kubectl delete awx awx
    awx.awx.ansible.com "awx" deleted
    user@awx:~$ kubectl get awx -A
    No resources found
    user@awx:~$ kubectl get secret awx-secret-key
    NAME             TYPE     DATA   AGE
    awx-secret-key   Opaque   1      56m
    user@awx:~$ kubectl apply -f /opt/awx/awx.yml
    secret/awx-old-postgres-configuration configured
    awx.awx.ansible.com/awx created

The issue with the wrong key persists, BUT: I just realized, that the key in both attempts to follow your instructions stays the same. Only when I run `minicube delete` and `minicube start` the key changes. Maybe that helps to identify the cause?

Or might there be a problem with us naming the `<awx-resource-name>` "`awx`"?

One more thing I just realized: When running `kubectl apply -f <awx-resource-name>` I get two lines of output, although there are three elements in my `.yml` file:

    user@awx:~$ kubectl apply -f /opt/awx/awx.yml
    secret/awx-old-postgres-configuration configured
    awx.awx.ansible.com/awx created

**Comment by t6nisalt** [comment]
Shouldn't the first two secrets in the awx.yml have the three dashes in between them, like so:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-secret-key
  namespace: default
stringData:
  secret_key: <REDACTED>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-old-postgres-configuration
  namespace: default
stringData:
  host: <REDACTED>
  port: "<REDACTED>"
  database: <REDACTED>
  username: <REDACTED>
  password: <REDACTED>
type: Opaque
```

For me it worked like this, didn't test without the dashes.

**Comment by thorian93** [comment]
I am not sure if this is still embarrassing or just plain stupid. That did it. The frigging three dashes caused us weeks of headache.
This issue is not a bug then but rather a layer 8 error.
Huge thanks to @t6nisalt for pointing out something now obvious!

I created https://github.com/ansible/awx-operator/pull/512, so others can avoid this issue in the first place.

**Comment by alexbmw00** [comment]
Hi Guys,

I got solved a problem with recreate a credentials in Ansible AWX (Credentials entry) , perhaps a bug after upgrade operator.

"AWX 2.2.1 provided by Ansible"
