### ISSUE TITLE
Request forbidden by administrative rules.

### ISSUE THREAD

**Issue by sysnasri** [ansible/tower-operator#443]
##### ISSUE TYPE
 - Request forbidden by administrative rules.

##### SUMMARY
After AXW installation on kubernetes, When I go to dashboard or jobs or any resource on the web panel I get the following error.

OPTIONS /api/v2/unified_jobs/ 403
<html><body><h1>403 Forbidden</h1> Request forbidden by administrative rules. </body></html> 

##### ENVIRONMENT
* AWX version:  AWX 19.2.0
* Operator version: 0.10.0
* Kubernetes version: v1.18.2
* AWX install method: pure kuberenetes with kubespray 

##### STEPS TO REPRODUCE

ingress log 

`[root@kube-master1 backyard-dep-new]# kubectl logs -f --tail=30 -n ingress-nginx ingress-nginx-controller-55d7f9d474-8qxhp
10.233.67.128 - - [01/Jul/2021:12:01:12 +0430] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" 261 0.012 [discovery-fast-security-6070] [] 10.233.84.33:6070 0 0.012 302 e2ec46e05cb0ac53402586a3424d5470
10.233.67.128 - - [01/Jul/2021:12:03:40 +0430] "GET / HTTP/1.1" 308 164 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" 294 0.000 [discovery-fast-security-6070] [] - - - - cf976aae369e432a86c75ef169053801
10.233.67.128 - - [01/Jul/2021:12:38:38 +0430] "GET / HTTP/1.1" 200 1082 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1942 0.113 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 1082 0.114 200 868935565a9560a3c75b862bd0fc4ae6
10.233.67.128 - - [01/Jul/2021:12:38:38 +0430] "GET /robots.txt HTTP/1.1" 404 3854 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1790 0.154 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 3854 0.154 404 1ea3668f1f0953a731134ea4b307be74
10.233.67.128 - - [01/Jul/2021:12:38:39 +0430] "GET /static/css/2.506c9f1b.chunk.css HTTP/1.1" 200 796487 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1864 0.020 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 796487 0.020 200 4af2e3089aaf4e2ab70efd9aa8c0d5f4
10.233.67.128 - - [01/Jul/2021:12:38:39 +0430] "GET /static/js/runtime-main.300dce4a.js HTTP/1.1" 304 0 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1933 0.002 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 0.002 304 9390ac94bbf39778ec0bbf959ad77c25
10.233.67.128 - - [01/Jul/2021:12:38:40 +0430] "GET /static/js/main.d7631a83.chunk.js HTTP/1.1" 200 1302822 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1850 0.388 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 1302822 0.388 200 2e935336440000dcba8df01e99361d44
10.233.67.128 - - [01/Jul/2021:12:38:40 +0430] "GET /static/js/2.78721e99.chunk.js HTTP/1.1" 200 2278002 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1847 1.291 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 2278002 1.291 200 e32b972d492c28430a329ca4e7d62380
10.233.67.128 - - [01/Jul/2021:12:39:57 +0430] "GET /static/js/3.2a6f1a71.chunk.js HTTP/1.1" 304 0 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1930 0.003 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 0.003 304 2295d0fd848147ea6b6261f76285bc33
10.233.67.128 - - [01/Jul/2021:12:40:03 +0430] "GET /static/media/pfbg_2000.3b693db0.jpg HTTP/1.1" 304 0 "http://awx.new.xxxxxx.com/static/css/2.506c9f1b.chunk.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2028 0.002 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 0.002 304 4b2a45a0426e59a44be9ebe1cf0cdc14
10.233.67.128 - - [01/Jul/2021:12:40:03 +0430] "GET /static/media/logo-login.svg HTTP/1.1" 304 0 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1988 0.002 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 0.002 304 af8411bdb0ffd82553cc33f60e2c8d7b
10.233.67.128 - - [01/Jul/2021:12:40:03 +0430] "GET /api/ HTTP/1.1" 200 186 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1981 0.121 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 186 0.121 200 19febce13aaa78a08e741e31f9734707
10.233.67.128 - - [01/Jul/2021:12:40:03 +0430] "GET /static/media/default.strings.json HTTP/1.1" 304 0 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2040 0.001 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 0.001 304 ee9c2f0c957355b2f65d124d94e61a82
10.233.67.128 - - [01/Jul/2021:12:40:03 +0430] "GET /api/v2/auth/ HTTP/1.1" 200 2 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1989 0.147 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 2 0.147 200 cffd1f90e253c8b966dfa34f231b59c5
10.233.67.128 - - [01/Jul/2021:12:40:03 +0430] "GET /static/media/RedHatText-Regular.81aade5a.woff HTTP/1.1" 304 0 "http://awx.new.xxxxxx.com/static/css/2.506c9f1b.chunk.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2012 0.003 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 0.003 304 fc07d744bd098729e54e959e9f42f674
10.233.67.128 - - [01/Jul/2021:12:40:03 +0430] "GET /static/media/RedHatText-Medium.47a03d21.woff HTTP/1.1" 304 0 "http://awx.new.xxxxxx.com/static/css/2.506c9f1b.chunk.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2011 0.002 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 0.002 304 15b5eb992b2af52b5dafc52e3ed32295
10.233.67.128 - - [01/Jul/2021:12:40:04 +0430] "GET /static/media/RedHatDisplay-Medium.732b5ddb.woff HTTP/1.1" 304 0 "http://awx.new.xxxxxx.com/static/css/2.506c9f1b.chunk.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2014 0.002 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 0.002 304 f4b0b714ad1a4f22a7b4b19453c92034
10.233.67.128 - - [01/Jul/2021:12:41:10 +0430] "GET /api/login/ HTTP/1.1" 200 5680 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1937 0.127 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 5680 0.127 200 77c66969ba52a57dc34aa7694b45a46e
10.233.67.128 - - [01/Jul/2021:12:41:11 +0430] "POST /api/login/ HTTP/1.1" 302 0 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2128 0.477 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 0.475 302 ffd8ebba219418b1da3b3b1ffaa19ec0
10.233.67.128 - - [01/Jul/2021:12:41:11 +0430] "GET /api/v2/config/ HTTP/1.1" 200 2002 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1984 0.145 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 2002 0.145 200 731bfb8355f4b4152483717465e4c980
10.233.67.128 - - [01/Jul/2021:12:41:11 +0430] "GET /static/media/logo-header.svg HTTP/1.1" 304 0 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2032 0.003 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 0.003 304 0b8987af8fc17be813c4b0d54b80394b
10.233.67.128 - - [01/Jul/2021:12:41:12 +0430] "GET /api/v2/config/ HTTP/1.1" 200 2002 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2034 0.142 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 2002 0.142 200 45df8d2bf13da91d8dbfdc390298e6ce
10.233.67.128 - - [01/Jul/2021:12:41:12 +0430] "GET /api/v2/me/ HTTP/1.1" 200 941 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1980 0.171 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 941 0.171 200 5e15063282f15fd7eec2a14ac550d4eb
10.233.67.128 - - [01/Jul/2021:12:41:13 +0430] "GET /api/v2/workflow_approvals/?page_size=1&status=pending HTTP/1.1" 200 52 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2018 0.168 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 52 0.168 200 318c99394dc4ff504af02d8a34ab89eb
10.233.67.128 - - [01/Jul/2021:12:41:13 +0430] "GET /api/v2/dashboard/graphs/jobs/?job_type=all&period=month HTTP/1.1" 200 1090 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2020 0.208 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 1090 0.208 200 d827afb8a8dc4182e6315197c274a4be
10.233.67.128 - - [01/Jul/2021:12:41:13 +0430] "GET /api/v2/dashboard/ HTTP/1.1" 200 1428 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1987 0.226 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 1428 0.226 200 ce1c451520390bc87d27e9e8bb218657
10.233.67.128 - - [01/Jul/2021:12:42:52 +0430] "GET /api/v2/unified_jobs/?not__launch_type=sync&order_by=-finished&page=1&page_size=20 HTTP/1.1" 200 1664 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2046 0.401 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 1664 0.401 200 2f7b3a66f49b35a02e9b2c7c16985eb6
10.233.67.128 - - [01/Jul/2021:12:44:43 +0430] "GET /static/media/pfbg_992@2x.30e8d31f.jpg HTTP/1.1" 200 588571 "http://awx.new.xxxxxx.com/static/css/2.506c9f1b.chunk.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 1990 0.020 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 588571 0.021 200 c3848fb89cf6fe7cfa23771d1ac44832
10.233.67.128 - - [01/Jul/2021:12:48:34 +0430] "GET /websocket/ HTTP/1.1" 101 339 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2006 341.994 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 0 341.994 101 29744cb498dd07789e56ebd381fcd0dd
10.233.67.128 - - [01/Jul/2021:12:48:35 +0430] "GET /api/v2/schedules/?order_by=name&page=1&page_size=20 HTTP/1.1" 200 4072 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 2016 0.477 [ansible-awx-awx-ansible-service-80] [] 10.233.97.253:8052 4072 0.477 200 a0c6fa6ceebc776b6c7784bbf917a69f
`

##### AWX-OPERATOR LOGS

ansible-web logs 

`[root@kube-master1 backyard-dep-new]# kubectl logs -f --tail=30 -n ansible-awx awx-ansible-7589dfcf8d-jmlc9 --container awx-ansible-web
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
10.233.66.161 - - [01/Jul/2021:08:18:16 +0000] "GET /websocket/ HTTP/1.1" 101 339 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "10.233.67.128"
2021-07-01 08:18:17,680 INFO     [44543bfa5f5d4bd78403c7a7ff5f5813] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/schedules/?order_by=name&page=1&page_size=20'>, response_time: 0.470s
[pid: 26|app: 0|req: 25/88] 10.233.66.161 () {60 vars in 2586 bytes} [Thu Jul  1 08:18:17 2021] GET /api/v2/schedules/?order_by=name&page=1&page_size=20 => generated 4072 bytes in 473 msecs (HTTP/1.1 200) 14 headers in 585 bytes (1 switches on core 0)
10.233.66.161 - - [01/Jul/2021:08:18:17 +0000] "GET /api/v2/schedules/?order_by=name&page=1&page_size=20 HTTP/1.1" 200 4072 "http://awx.new.xxxxxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "10.233.67.128"
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
RESULT 2
OKREADY
2021-07-01 08:24:31,509 DEBUG    [2605bf20525e4cd8b70b60ed40e50294] awx.api.serializers Failed to parse activity stream relationship type awx.main.models.unified_jobs.UnifiedJobTemplate_credentials
2021-07-01 08:24:31,835 DEBUG    [2605bf20525e4cd8b70b60ed40e50294] awx.api.serializers Failed to parse activity stream relationship type awx.main.models.organization.OrganizationGalaxyCredentialMembership
2021-07-01 08:24:31,836 DEBUG    [2605bf20525e4cd8b70b60ed40e50294] awx.api.serializers Failed to parse activity stream relationship type awx.main.models.organization.OrganizationGalaxyCredentialMembership
2021-07-01 08:24:32,997 INFO     [2605bf20525e4cd8b70b60ed40e50294] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/activity_stream/?order_by=-timestamp&page=1&page_size=20'>, response_time: 2.483s
[pid: 26|app: 0|req: 26/89] 10.233.66.161 () {60 vars in 2610 bytes} [Thu Jul  1 08:24:30 2021] GET /api/v2/activity_stream/?order_by=-timestamp&page=1&page_size=20 => generated 14231 bytes in 2486 msecs (HTTP/1.1 200) 14 headers in 580 bytes (1 switches on core 0)
10.233.66.161 - - [01/Jul/2021:08:24:32 +0000] "GET /api/v2/activity_stream/?order_by=-timestamp&page=1&page_size=20 HTTP/1.`

![image](https://user-images.githubusercontent.com/73346319/124092761-73db3100-da6c-11eb-9f20-c33f982b7635.png)

**Comment by sysnasri** [comment]
![image](https://user-images.githubusercontent.com/73346319/124092625-50b08180-da6c-11eb-89d2-236144a86582.png)

**Comment by shanemcd** [comment]
Sounds like a config issue with your Kubernetes environment. You may have better luck troubleshooting on IRC or the mailing list.

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project

**Comment by sysnasri** [comment]
@shanemcd 

I fixed this problem with following edit on the awx ingress service .
First you should find ingress resource definition file on your cluster , for mine this is the resource 
`kubectl edit ingress awx-ansible-ingress -n ansible-awx`

then I have added the following piece of codes 

```
  annotations:
    kubernestes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
```

in the same file then I added this too
```
spec:
  tls:
    - hosts:
        - awx.mydomain.com
      secretName: awx-web-tls

```
