### ISSUE TITLE
Connection to external postgres not possible if ca-certificate verification using custom cert is required

### ISSUE THREAD

**Issue by marcoatenway** [ansible/tower-operator#454]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using AWX-Operator on a hoster requiring a ca certificate for connection verification (like Digitalocean) a connection to the database can not be established.

As a workaround one can mount a ca-bundle containing the needed ca certificate to /etc/pki/tls/certs/ca-bundle.crt to make a connection possible but many tasks like the operator itself are not using that certificate and therefore initialisation is not working.

There should be an option like for ldap ca-certificate to specify a secret containing the ca-certificate.

##### ENVIRONMENT
* AWX version: X.Y.Z
* Operator version: 0.12.0
* Kubernetes version: 1.21.2
* AWX install method: Kubernetes as a service @ digitalocean

##### STEPS TO REPRODUCE

- Start kubernetes Cluster on DigitalOcean
- Follow installation instructions
- see there is no database propagated
- check database logs for ssl ca errors

##### EXPECTED RESULTS

established connection using the ca-certificate

##### ACTUAL RESULTS

no established connection using the ca-certificate

**Comment by ddellarocca** [comment]
Same problem here on GCP with a managed Postgres SQL instance in CloudSQL.

**Comment by tchellomello** [comment]
Yes, I can work in something similar, however, I just want one clarification @marcoatenway. The database population happens on the `awx-task` container and when you have the `ca_trust_bundle` mounted, it should work as expected. 

I can work in providing one dedicated certificate tag for PostgreSQL, however, you mentioned that `many tasks like the operator itself are not working`. Could you please clarify it?

**Comment by marcoatenway** [comment]
Hi,
with "many tasks" i mean the stuff in: "roles/installer/tasks/main.yml"
this stuff is executed on the operator not in the task pod, or are i'am wrong?

**Comment by marcoatenway** [comment]
Hey @tchellomello any update regarding this?

**Comment by sdigit** [comment]
Hi,

I would also like to use CloudSQL for my AWX database. If I can help test a fix for this, please let me know.

**Comment by marcoatenway** [comment]
This bug is fixed in 0.13.0 using the documented spec.bundle_cacert_secret

Thank you @tchellomello
