### ISSUE TITLE
Jobs continue to remain in Pending State

### ISSUE THREAD

**Issue by aporwal3** [ansible/tower-operator#457]
##### ISSUE TYPE
 - Bug Report

Any job that is launched on AWX goes to the Pending state and does not start.

##### SUMMARY
I did a fresh install of AWX and launched a job but it goes to the Pending state and does not start.

##### ENVIRONMENT
* AWX version: 15.0
* Operator version: 0.6.0
* Kubernetes version: 1.20
* AWX install method: docker on linux

##### STEPS TO REPRODUCE

Create a fresh install of AWX 15.0
Create a Job of any kind (Project synch, inventory synch, job template etc etc )
Run the Job

##### EXPECTED RESULTS

Jobs should go to Running state

##### ACTUAL RESULTS

Jobs goes into Pending state

**Comment by ZachHoiberg** [comment]
What worked for me on Operator 0.12.0 is dropping into the minikube via Docker, then using Docker to restart the K8S_NAME-task-name container

**Comment by tchellomello** [comment]
You mentioned using the operator `0.6.0` which is quite outdated. Please try again using the latest version and reopen if the issue happens again.
