### ISSUE TITLE
Failed to parse CRD on restore

### ISSUE THREAD

**Issue by dimatha** [ansible/tower-operator#459]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The restore fails when ingress_annotations is defined.
##### ENVIRONMENT
* AWX version: 19.2.0
* Operator version: 10.0.0
* Kubernetes version: 1.21
* AWX install method: operator

##### STEPS TO REPRODUCE

Create AWX CR and define ingress annotations:

>spec:
>  ingress_annotations: |
>    cert-manager.io/cluster-issuer: company2letsencrypt-production-issuer
>    kubernetes.io/ingress.class: nginx

Based on the example here: https://github.com/ansible/awx-operator/blob/0.10.0/roles/installer/defaults/main.yml

##### EXPECTED RESULTS

Backup restores the instance with no errors

##### ACTUAL RESULTS

Here is the error from the operator log:

> task path: /opt/ansible/roles/restore/tasks/deploy_awx.yml:26\nfatal: [localhost]: FAILED! => {\"ansible_facts\"
: {}, \"ansible_included_var_files\": [], \"changed\": false, \"message\": \"We were unable to read either as JSON nor YAML, these are the errors we got from each:\\nJSON: Expecting property name enclosed in double quotes: line 1 column
 2 (char 1)\\n\\nSyntax Error while loading YAML.\\n  expected ',' or '}', but got ':'\\n\\nThe error appears to be in '/tmp/ansible.euktv70e': line 1, column 470

Here is how awx_object on the backup PV looks like:

> {admin_email: ITS-IS-System@company.com, admin_user: system, api_version: awx.ansible.com/v1beta1, create_preload_data: True, deployment_type: awx, ee_images: [{image: harbor.in.company.com/library/quay.io/ansible/awx-ee:0.3.0, name: default-awx-ee}], garbage_collect_secrets: False, hostname: tower-dev.in.company.com, image: harbor.in.company.com/library/quay.io/ansible/awx, image_pull_policy: IfNotPresent, image_version: 19.2.0, ingress_annotations: cert-manager.io/cluster-issuer: company2letsencrypt-production-issuernkubernetes.io/ingress.class: nginxn, ingress_tls_secret: tower-dev.in.company.com, ingress_type: ingress, kind: AWX, loadbalancer_port: 80, loadbalancer_protocol: http, postgres_image: harbor.in.company.com/library/company/postgres, postgres_resource_requirements: {limits: {cpu: 1000m, memory: 4Gi}, requests: {cpu: 500m, memory: 2Gi}}, postgres_storage_class: standard, projects_persistence: False, projects_storage_access_mode: ReadWriteMany, projects_storage_size: 8Gi, redis_image: harbor.in.company.com/library/company/redis, replicas: 1, route_tls_termination_mechanism: Edge, task_privileged: False, task_resource_requirements: {limits: {cpu: 1000m, memory: 2Gi}, requests: {cpu: 500m, memory: 1Gi}}, web_resource_requirements: {limits: {cpu: 2000m, memory: 4Gi}, requests: {cpu: 1000m, memory: 2Gi}}}

**Comment by shanemcd** [comment]
@rooftopcellist Is this one of the things we fixed recently? It might be resolved the next time we release?

**Comment by shanemcd** [comment]
Hi - can you test with the latest version of the operator?

**Comment by dimatha** [comment]
@shanemcd, my apologies for the late reply. Yes, I can confirm that with operator 0.12.0 it works just fine. thanks !
