### ISSUE TITLE
Missing static web resources when deploying on Azure AKS

### ISSUE THREAD

**Issue by worfinator** [ansible/tower-operator#466]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Web instance is missing static resources. /var/lib/awx/public directory is missing.

##### ENVIRONMENT
* AWX version: 19.2.2
* Operator version: 0.12.0
* Kubernetes version: 1.19.11 - 1.21.1
* AWX install method: Azure AKS

##### STEPS TO REPRODUCE

1. Deploy 0.11.0 - 0.12.0 AWX Operator to Cluster
2. Apply an AWX.yml template (Even the basic version)
3. Create Ingress
4. Load AWX URL

##### EXPECTED RESULTS

Login webpage loads correctly

##### ACTUAL RESULTS

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/5388776/125377851-cbb95680-e3e1-11eb-9231-f058bdd3651a.png">

##### ADDITIONAL INFORMATION

<img width="276" alt="image" src="https://user-images.githubusercontent.com/5388776/125377935-f2778d00-e3e1-11eb-873b-3c8d83f4d89a.png">

**Comment by metabsd** [comment]
I also experienced that bug. I redeploy and it worked. Don't know why. I was thinking that was my microk8s setup the problem. Maybe not.

**Comment by wenottingham** [comment]
See #461 and #357.
