### ISSUE TITLE
What are the basic steps to get started with AWX 19.2.0?

### ISSUE THREAD

**Issue by bsushant-athena** [ansible/tower-operator#471]
I was trying the awx operator way but the installation page is a little confusing for me. I completed the steps till "You just completed the most basic install of an AWX instance via this operator. Congratulations!!!!". Can someone suggest/help now with how to get the AWX GUI? 

Are there more steps needed? I think it would be much easier if there would have been a step-by-step guide.

**Comment by karezza** [comment]
You can run:
```
minikube service awx-demo-service
```
and this should start up your browser with the url to access the installation.

In my case I installed chromium-browser and when that command is run it will start up chromium if it is not already running.  The documentation has:  minikube service awx-demo-service --url which should just give you the url.

**Comment by bsushant-athena** [comment]
thanks @karezza , it worked!

NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
awx-demo-postgres      ClusterIP   None                    <none>        5432/TCP            34m
awx-demo-service       NodePort    10.100.181.127   <none>        80:32179/TCP        34m
awx-operator-metrics   ClusterIP   10.97.177.180    <none>        8383/TCP,8686/TCP   35m
kubernetes             ClusterIP          10.96.0.1           <none>        443/TCP             38m

This service, I'm running inside an instance with public IP, and I want to access this service outside the instance.
Do you know how to access `awx-demo-service` outside the instance?

**Comment by karezza** [comment]
I know how to do this in general using a reverse proxy, here's the technique over at minikube:  https://minikube.sigs.k8s.io/docs/tutorials/nginx_tcp_udp_ingress/

But, I have not been able to figure out how to do it via the technique described in the Network and TLS Configuration section on the AWX Operator install page.  I'll watch this Issue with interest for the solution.  I've got a ticket in for some additional detail regarding this setup:  #468

**Comment by karezza** [comment]
I'm not positive at the moment but I think it may be a requirement with minikube to add a port forward rule on the host system to point to the internal ip used by minikube such as:

```
sudo firewall-cmd --permanent --add-forward-port=port=443:proto=tcp:toport=443:toaddr=<minikube ip>
sudo firewall-cmd --reload
```

**Comment by bsushant-athena** [comment]
@karezza is it possible to share the repo/files which you are using for awx demo purposes?
as per required by this link >> https://minikube.sigs.k8s.io/docs/tutorials/nginx_tcp_udp_ingress/

**Comment by bsushant-athena** [comment]
Hey, I followed this doc and it worked for me
https://www.techbeatly.com/2021/07/install-ansible-awx-on-kubernetes.html

and this as well >> https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network

**Comment by bsushant-athena** [comment]
Now I'm facing an issue where for inventory to fetch the hosts it needs a python SDK installation. In awx v16 as the venv was same we used to run the install python sdk job template followed by the inventory sync. But in v19.2.2 venv's are not supported. 
I tried to keep the execution environment same but no luck

**Comment by shanemcd** [comment]
Hello,

This issue tracker is for tracking feature enhancements and bugs for the AWX Operator.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project
