### ISSUE TITLE
Fresh deployment no access to web gui

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ansible/tower-operator#473]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: X.Y.Z
* Operator version: 0.12.0
* Kubernetes version: latest minikube
* AWX install method:  docker on linux

##### STEPS TO REPRODUCE

Use instruction "Basic install" step by step from here : 
https://github.com/ansible/awx-operator#basic-install

kubectl get secrets
```
NAME                          TYPE                                  DATA   AGE
awx-operator-token-bkb6t      kubernetes.io/service-account-token   3      84m
awx1-admin-password           Opaque                                1      80m
awx1-app-credentials          Opaque                                3      79m
awx1-broadcast-websocket      Opaque                                1      80m
awx1-postgres-configuration   Opaque                                6      80m
awx1-secret-key               Opaque                                1      80m
awx1-token-jlx9c              kubernetes.io/service-account-token   3      79m
default-token-l425t           kubernetes.io/service-account-token   3      96m
```
Expose port: 

ssh -i ~/.minikube/machines/minikube/id_rsa docker@$(minikube ip) -L \*:31342:0.0.0.0:31342  

Get admin password :
kubectl get secret awx1-admin-password -o jsonpath="{.data.password}" | base64 --decode 

Used decoded password on exposed web page : 
i get :
There was a problem logging in. Please try again.

##### EXPECTED RESULTS

At least to be able to login

##### ACTUAL RESULTS

i get :
There was a problem logging in. Please try again.

**Comment by tchellomello** [comment]
@jpVm5jYYRE1VIKL  we will need more information to understand the error. Could you provide some of the logs so we can better idea of what is going on?

**Comment by jpVm5jYYRE1VIKL** [comment]
went away from awx
