### ISSUE TITLE
extra ees' created using ee_images dont have ee_extra_env and ee_extra_volume_mounts applied

### ISSUE THREAD

**Issue by MrBones757** [ansible/tower-operator#476]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When deploying AWX with a pre-defined set of ee_images that are globally available, i expected the ee_extra_env and ee_extra_volume_mounts would be applied to these images as per the documentation:

'''
The ee_extra_volume_mounts and extra_volumes will only take effect to the globally available Execution Environments. For custom ee, please customize the Pod spec.
'''
Since ees created using ee_images are globally available i expected that these params would apply, however it seems to only apply to the control plane ee. is this expected?

##### ENVIRONMENT
* AWX version: 19.2.2
* Operator version: 0.12.0
* Kubernetes version: 1.16.x
* AWX install method: rke

##### STEPS TO REPRODUCE

1) Deploy AWX with ee_images, and configure ee_extra_env and / or extra_volumes and ee_extra_volume_mounts
2) Run a job

##### EXPECTED RESULTS

Job EE Pod should have the values defined for ee_extra_env and ee_extra_volume_mounts since they are globally available

##### ACTUAL RESULTS

Job EE Pods dont have values propogated, only control plane ee.

##### ADDITIONAL INFORMATION

Had a look though the souce, it appears ee_images is consumed in execution_environments.py.j2. No pod spec is defined here, so unsure what it actually uses.
If this expected behavior is not intended this is just a docs update exercise, or something needs to be added to the operator to allow this propagation.

**Comment by wenottingham** [comment]
We may look at this, but "For custom ee, please customize the Pod spec." is correct - for customizations to EEs, it's better to have that in the podspec that is on the EE object.

**Comment by wenottingham** [comment]
Chatting with engineering - those variables are for modifying the control plane EE only.
