### ISSUE TITLE
Admin password is reset to initial value following scale =0 operation (awx-operator 0.12.0)

### ISSUE THREAD

**Issue by amtilghman** [ansible/tower-operator#477]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Running oc scale --replicas=0 deployment <AWX-DEPLOYMENT> and allowing awx-operator to restore the replica to operational status will result in the admin password being reset to the default value.  Is there a way to set a new default value so that when the admin password is rotated it will stay at the new value?

By default value I am referencing the value obtained by oc get secret <awx-XXX-admin-password -o jsonpath....>

##### ENVIRONMENT
* AWX version: 19.2.2
* Operator version: 0.12.0
* Kubernetes version: v1.20.0-1085+01c9f3f43ffcf0-dirty
* AWX install method: openshift

##### STEPS TO REPRODUCE

Stand up AWX on openshift with the awx-operator
Create a route so you can browse to AWX with a browser
Login and change the admin password
oc scale --replicas=0 deployment <AWX-DEPLOYMENT>
watch the awx pods terminate
watch the awx pods restart automatically (because I did not scale down awx-operator)
fail to login with the admin password i changed it to previously
get the default password with (oc get secret <awx-XXX-admin-password -o jsonpath....>)
login with the default password

##### EXPECTED RESULTS

I expected the admin password change to not be overwritten when the deployment was scaled down and restarted by awx-operator

##### ACTUAL RESULTS

The default password was restored by awx-operator

**Comment by wenottingham** [comment]
When scaling a deployment done by an operator, you have to set the replicas on the awx object, not try and run `oc scale` directly. Please try that and reopen if it doesn't work.

**Comment by amtilghman** [comment]
I've provided the exact steps I'm performing below.
Prior to awx-operator when I've upgraded/reinstalled AWX the admin password was always preserved and not overwritten.
As you can see in the output below some data is being preserved but the admin password is being overwritten, is this a bug or am i going about this the wrong way?

#This is the password set by the installer
$ kubectl get secret awx-demo-admin-password -o jsonpath="{.data.password}" | base64 --decode
G2jE1X46OfX09Va8G6FXtbXs5supqtFk

#I now login to the AWX UI and change the admin password to password

#I also create a new user called newuser and set the password to password


#I can curl the api with the admin user and it's new password
$ curl -sk -u admin:password http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
"admin"

#I can curl the api with the newuser user and it's new password
$ curl -sk -u newuser:password http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
"newuser"

#The password set by the installer does not work, this is good
$ curl -sk -u admin:G2jE1X46OfX09Va8G6FXtbXs5supqtFk http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
jq: error (at <stdin>:0): Cannot iterate over null (null)


#I am running 1 replica of awx-demo and 1 replica of awx-operator
$ oc get rs
NAME                     DESIRED   CURRENT   READY   AGE
awx-demo-9975db9b6       1         1         1       3d19h
awx-operator-79bc95f78   1         1         1       3d19h


#I scale down awx-demo
$ oc scale deployment --replicas=0 awx-demo
deployment.apps/awx-demo scaled


#I see awx-demo was scaled down
$ oc get rs
NAME                     DESIRED   CURRENT   READY   AGE
awx-demo-9975db9b6       0         0         0       3d19h
awx-operator-79bc95f78   1         1         1       3d19h


#I see operator has restored awx-demo
$ oc get rs
NAME                     DESIRED   CURRENT   READY   AGE
awx-demo-9975db9b6       1         1         1       3d19h
awx-operator-79bc95f78   1         1         1       3d19h


#The admin password I had set prior no longer works
$ curl -sk -u admin:password http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
jq: error (at <stdin>:0): Cannot iterate over null (null)


#The newuser account is fine
$ curl -sk -u newuser:password http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
"newuser"


#I see the default password set by the installer has been reset
[root@lab0l00 /]# curl -sk -u admin:G2jE1X46OfX09Va8G6FXtbXs5supqtFk http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
"admin"
