### ISSUE TITLE
External DB issue: migrations not running

### ISSUE THREAD

**Issue by fr33f411** [ansible/tower-operator#48]
Hello, guys!

I tried to run AWX Operator in K8s with external DB but I got an error on a step "Create preload data if necessary"

Logs from operator pod, ansible container:

https://dpaste.org/gZz7

Logs from ansible pod, aawx-task container:

https://dpaste.org/SJrp

What this error stands for and how can I fix it?

Thanks in advance!

**Comment by shanemcd** [comment]
Strange. I noticed: 

```
column \"max_hosts\" of relation \"main_organization\"
```

Implies that migrations didnt run / didnt finish. Can you grab the operator logs a little further up? These tasks:

https://github.com/ansible/awx-operator/blob/f4b619a185ac0cb5736b229c61e56ed91237d16a/roles/awx/tasks/main.yml#L91-L114

**Comment by shanemcd** [comment]
Actually it seems like the logic there might not be sufficient. I see now that check is only looking for the presence of a specific db table.

As a workaround, you can try exec'ing into the task container and running `awx-manage migrate --noinput`.

I'll leave this issue open until we identify and implement a proper solution.

**Comment by fr33f411** [comment]
> Strange. I noticed:
> 
> ```
> column \"max_hosts\" of relation \"main_organization\"
> ```
> 
> Implies that migrations didnt run / didnt finish. Can you grab the operator logs a little further up? These tasks:
> 
> https://github.com/ansible/awx-operator/blob/f4b619a185ac0cb5736b229c61e56ed91237d16a/roles/awx/tasks/main.yml#L91-L114

Sure, here they are https://dpaste.org/aFKm.

But I want to notice that it is not a migration. I setup a new instance with external DB.

**Comment by fr33f411** [comment]
> Actually it seems like the logic there might not be sufficient. I see now that check is only looking for the presence of a specific db table.
> 
> As a workaround, you can try exec'ing into the task container and running `awx-manage migrate --noinput`.
> 
> I'll leave this issue open until we identify and implement a proper solution.

https://dpaste.org/oLCW

**Comment by fr33f411** [comment]
And its working now :) you save my day, thanks a lot. But what was the problem?
