### ISSUE TITLE
[RFE] Create a must-gather to collect logs for AAP

### ISSUE THREAD

**Issue by davidtluong** [ansible/tower-operator#486]
##### ISSUE TYPE
 - Feature Request

##### SUMMARY

Currently there is no way to easily collect logs for the operator.  Sosreports can no longer be used as it's overkill to get it for the openshift nodes.

##### ENVIRONMENT
* AWX version: X.Y.Z
* Operator version: 2.0.0
* Kubernetes version: v1.20.0+2817867
* AWX install method: openshift

##### STEPS TO REPRODUCE

Try and collect logs

##### EXPECTED RESULTS

Easy must-gather command

##### ACTUAL RESULTS

Nothing exists for AAP operator at the moment, so cannot

##### ADDITIONAL INFORMATION

I've created a custom must-gather here, based off of the ACM must-gather image, feel free to fork it:
https://github.com/rh-dluong/must-gather-aap

Not sure if it should live here, or as a separate repository.  I believe it should be a separate repository as it's not actually installed with the operator.

**Comment by wenottingham** [comment]
Closing this, this should be tracked elsewhere.
