### ISSUE TITLE
Ingress annotations/tls?

### ISSUE THREAD

**Issue by howardjones** [ansible/tower-operator#49]
What is the intended flow for an Ingress with an awx instance created by awx-operator?

For the Ingress to be useful, my ingress controller (Azure App Gateway, but I think others are similar) requires specific annotations for it to pick up the newly created service, and then cert-manager also looks for tls config inside the Ingress.

I can add those after the install, but will they "stick"? Is that how it's intended to work? It feels a little dirty.

(or should I just be creating the AWX resource and Ingress using say, helm, or a higher-level manifest?)

**Comment by shanemcd** [comment]
Can you take a look at this code and let me know if this variable does what you want? https://github.com/ansible/awx-operator/blob/f4b619a185ac0cb5736b229c61e56ed91237d16a/roles/awx/templates/tower.yaml.j2#L264-L267

**Comment by shanemcd** [comment]
Usage: https://github.com/ansible/awx-operator/blob/f4b619a185ac0cb5736b229c61e56ed91237d16a/roles/awx/defaults/main.yml#L5-L9

**Comment by howardjones** [comment]
I was looking at the ansible playbooks just now, and saw that in the template. It doesn't seem to appear in my Ingress if I use it though, so I was trying to figure out which git revision `awx-operator:0.5` would have come from, to see if I need to build my own.

The end of my `kind: AWX` spec is:

```
   tower_ingress_annotations: |
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
   tower_ingress_tls_secret: awx-web-tls
```

but my Ingress ends up with no annotations (and no TLS config).

**Comment by howardjones** [comment]
And that would be it. The 0.5.0 image that is on dockerhub, and referred to by the install instructions doesn't include that. It'd be really cool if there were git tags for the images.

I'll build my own image for now. Thanks!

**Comment by howardjones** [comment]
Hmmm, except that the build instructions don't seem to match up with current `operator-sdk`. Seems like it is expecting to generate a makefile?

```
▶ operator-sdk version                         
operator-sdk version: "v1.1.0", commit: "9d27e224efac78fcc9354ece4e43a50eb30ea968", kubernetes version: "v1.18.2", go version: "go1.15 linux/amd64", GOOS: "linux", GOARCH: "amd64"
(venv) 
Work/other-peoples-code/awx-operator  devel ✗                                                                                                13d ◒  
▶ operator-sdk build ansible/awx-operator:0.5.1
Error: unknown command "build" for "operator-sdk"
Run 'operator-sdk --help' for usage.
FATA[0000] unknown command "build" for "operator-sdk"  
```

**Comment by shanemcd** [comment]
I dont think we are ready to update to operator-sdk 1.0+. Can you try downloading the latest 0.x release?

**Comment by howardjones** [comment]
Excellent! That builds, and I get my Ingress configured as expected. Thanks! I find this much nicer to deal with than the ansible installer that comes with awx (and faster).

**Comment by Spredzy** [comment]
@howardjones The way I read it is that your issue is solved. Hence I'll be closing this issue. If there is something still not working, feel free to re-open it. Thank you !
