### ISSUE TITLE
 password authentication failed for user "awx"

### ISSUE THREAD

**Issue by stasstryukov** [ansible/tower-operator#497]
Hi.
I have a problem with fresh install of awx on CentOS 8. I made all like in this instruction https://github.com/ansible/awx-operator.  But when i made all i cant' connect to web. There is an error "Server Error A server error has occurred". When I opened logs, i saw, that in postgress pod are errors: 
2021-08-12 14:11:52.734 UTC [62] FATAL:  password authentication failed for user "awx"
2021-08-12 14:11:52.734 UTC [62] DETAIL:  Connection matched pg_hba.conf line 99: "host all all all scram-sha-256"

I tryed differents versions of awx-opeartor (from 0.9.0 to 0.12.0), k8s (1.20 - 1.22) and even docker. But the problem are always the same. How can I solve it? Or there is any workaround?

**Comment by shanemcd** [comment]
Hello,

This issue tracker is for tracking feature enhancements and bugs to AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project
