### ISSUE TITLE
Failed to pull image "quay.io/ansible/awx-ee:0.5.0": rpc error: code = Unknown desc = Error writing blob: error storing blob to file "/var/tmp/storage419932491/8": error happened during read: unexpected EOF

### ISSUE THREAD

**Issue by anolan80** [ansible/tower-operator#498]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: latst
* Operator version: 0.12.0
* Kubernetes version:  1.20
* AWX install method: openshift

##### STEPS TO REPRODUCE

installed the operator - then deployed awx

##### EXPECTED RESULTS

awx to run fine 

##### ACTUAL RESULTS

Failed to pull image "quay.io/ansible/awx-ee:0.5.0": rpc error: code = Unknown desc = Error writing blob: error storing blob to file "/var/tmp/storage419932491/8": error happened during read: unexpected EOF

I tried 0.2.0 but that ee has errors -

**Comment by shanemcd** [comment]
This looks like a transient error with either quay or kubernetes. Either way, this is not an issue with AWX itself.
