### ISSUE TITLE
unknown field errors applying my-awx.yml

### ISSUE THREAD

**Issue by kylecurtis-od** [ansible/tower-operator#50]
It appears as though trying to apply a basic file, generates errors about unknown fields.

error: error validating "my-awx.yaml": error validating data: [ValidationError(AWX.spec): unknown field "tower_admin_email" in com.ansible.awx.v1beta1.AWX.spec, ValidationError(AWX.spec): unknown field "tower_admin_password" in com.ansible.awx.v1beta1.AWX.spec, ValidationError(AWX.spec): unknown field "tower_admin_user" in com.ansible.awx.v1beta1.AWX.spec, ValidationError(AWX.spec): unknown field "tower_broadcast_websocket_secret" in com.ansible.awx.v1beta1.AWX.spec, ValidationError(AWX.spec): unknown field "tower_extra_volumes" in com.ansible.awx.v1beta1.AWX.spec, ValidationError(AWX.spec): unknown field "tower_hostname" in com.ansible.awx.v1beta1.AWX.spec, ValidationError(AWX.spec): unknown field "tower_ingress_annotations" in com.ansible.awx.v1beta1.AWX.spec, ValidationError(AWX.spec): unknown field "tower_ingress_type" in com.ansible.awx.v1beta1.AWX.spec, ValidationError(AWX.spec): unknown field "tower_replicas" in com.ansible.awx.v1beta1.AWX.spec, ValidationError(AWX.spec): unknown field "tower_task_extra_volume_mounts" in com.ansible.awx.v1beta1.AWX.spec, ValidationError(AWX.spec): unknown field "tower_web_extra_volume_mounts" in com.ansible.awx.v1beta1.AWX.spec]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by shanemcd** [comment]
Can you post the contents of `my-awx.yaml`?

**Comment by kylecurtis-od** [comment]
```yml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: ansible-awx
spec:
  deployment_type: awx
  tower_admin_user: test
  tower_admin_email: someuser@domain.com
  tower_admin_password: changeme
  tower_broadcast_websocket_secret: changeme
  external_database: true
  tower_ingress_type: Ingress
  tower_ingress_annotations: |
    kubernetes.io/ingress.class: nginx-int
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tower_hostname: mytowerurl.com
  tower_replicas: "2"
  tower_task_extra_volume_mounts: |
    - name: awx-projects-efs
      mountPath: /var/lib/awx/projects
  tower_extra_volumes: |
    - name: awx-projects-efs
      persistentVolumeClaim:
        claimName: awx-projects-efs-predev-np
  tower_web_extra_volume_mounts: |
    - name: awx-projects-efs
      mountPath: /var/lib/awx/projects

**Comment by kylecurtis-od** [comment]
Just curious if anyone has looked at this.  The my-awx.yml example provided is on a real kube environment that is currently at version 1.15.

**Comment by kylecurtis-od** [comment]
switched to using eks on aws, which is kubernetes 1.17 currently, and there are no issues doing an apply of the yaml.
