### ISSUE TITLE
Install awx-operator with an unprivileged user

### ISSUE THREAD

**Issue by marc-ledent** [ansible/tower-operator#516]
##### ISSUE TYPE
 - Improvement

##### SUMMARY
Lower priority needed to install awx-operator to work insid a project

##### ENVIRONMENT
* AWX version: 19.x
* Operator version: 0.13.0
* Kubernetes version: v1.11.0+d4cacc0
* AWX install method: openshift

##### STEPS TO REPRODUCE

Standard install with unprivileged user

##### EXPECTED RESULTS

To be able to install/use awx-operator inside a project without clusterrole

##### ACTUAL RESULTS

Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/ansible/awx-operator/0.13.0/deploy/awx-operator.yaml": clusterroles.rbac.authorization.k8s.io is forbidden: User "XXX" cannot create clusterroles.rbac.authorization.k8s.io at the cluster scope: no RBAC policy matched

##### AWX-OPERATOR LOGS

Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/ansible/awx-operator/0.13.0/deploy/awx-operator.yaml": clusterroles.rbac.authorization.k8s.io is forbidden: User "XXX" cannot create clusterroles.rbac.authorization.k8s.io at the cluster scope: no RBAC policy matched

**Comment by shanemcd** [comment]
Should have been addressed in https://github.com/ansible/awx-operator/pull/541, which will go out in the next release of the operator sometime within the next week or so.
