### ISSUE TITLE
ldap authentication issue

### ISSUE THREAD

**Issue by mibfb23** [ansible/tower-operator#517]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
ldap authentication issue

##### ENVIRONMENT
* AWX version: 19.3.0
* Operator version: 0.13.0
* Kubernetes version: 1.20.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker

##### STEPS TO REPRODUCE

configured the ldap parameters for ldap authentication and at the first login with an ldap user you are able to log in with the user created in the user section.

##### EXPECTED RESULTS

In the previously installed version (17.0.1) of awx, once ldap was configured and the first login was performed, the user entry was created in the user section with the wording LDAP next to the name of the user. Then the login worked and you kept logging in.

##### ACTUAL RESULTS

In this version it is not specified that it is an ldap user and therefore at the first login a user is created as if it were a local user with the password field empty. The result is that at the next login it returns the error "Invalid username or password. Please try again." most likely because the user created at the first login has no password as if a local user were created without the password.

**Comment by tchellomello** [comment]
Duplicated of https://github.com/ansible/awx-operator/issues/507

Should be fixed by ansible/awx#10965
