### ISSUE TITLE
ldap user getting created as a local user

### ISSUE THREAD

**Issue by AbhinitMallick** [ansible/tower-operator#519]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
ldap user getting created as a local user
When an ldap user first tries to login his account gets created as a local user, so the user is able to login for the first time but once he logs out he cannot log back in as his password field is created and set to blank as he is a local user and not an ldap user

##### ENVIRONMENT
* AWX version: 19.3.0
* Operator version: 0.13.0
* Kubernetes version: minikube version: v1.22.0
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker

##### STEPS TO REPRODUCE

This is a fresh install where I am using an external postgres DB ( but everything is fresh install )

1. Create the secret 
kubectl create secret generic awx-custom-certs \
    --from-file=ldap-ca.crt=/etc/openldap/cacerts/PLC_INTER_CA2_V1.pem  \
    --from-file=bundle-ca.crt=/etc/openldap/cacerts/PLC_INTER_CA2_V1.pem
2. Now the awx file

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  ingress_type: ingress
  route_tls_termination_mechanism: Edge
  route_tls_secret: ingress-lnxs-secret
  hostname: unix-awx-np.plc.com
  admin_password_secret: awx-admin-password
  ldap_cacert_secret: awx-custom-certs
  bundle_cacert_secret: awx-custom-certs
  postgres_configuration_secret: awx-postgres-configuration
  ingress_tls_secret: ingress-lnxs-secret
  
3. Once AWX is started and up and running configure ldap settings

4. Now try and login as the ldap user and go to the users section and you would find that your userid does not have ldap mentioned against it which is wrong it means that you will have password fields created which is wrong.

5.  this basically means if you log out and log back in your userid will not let you login as it is created as a local user and your password field is not set

##### EXPECTED RESULTS

When an ldap user tries to login his user id must be created as ldap userid and not a local userid

##### ACTUAL RESULTS

Now try and login as the ldap user and go to the users section and you would find that your userid does not have ldap mentioned against it which is wrong it means that you will have password fields created which is wrong.

 this basically means if you log out and log back in your userid will not let you login as it is created as a local user and your password field is not set

##### ADDITIONAL INFORMATION

In the awx task container I did notice something which caught my eye but I don't know whether that's the issue

/etc/tower/conf.d/ldap.py file points to a CA file but that CA file does not exist , I don't know how is the awx speaking with ldap on the first place as our ldap would allow unencrypted connections and it will only allow ldaps, I don't know whether it is able to speak because of the bundle certificate I am using.

I don't think this is a ldap connection issue otherwise it wont let me login using ldap id in the first instance.

I have similar setup up and running in non-prod estate and prod estate ( the only difference is in non-prod we have fresh install from 0.12.0 and then upgraded to 0.13.0 and prod was fresh install directly to 0.13.0 )

bash-4.4$ cat /etc/tower/conf.d/ldap.py
AUTH_LDAP_GLOBAL_OPTIONS = {
    ldap.OPT_X_TLS_REQUIRE_CERT: True,
    ldap.OPT_X_TLS_CACERTFILE: "/etc/openldap/certs/ldap-ca.crt"
}

bash-4.4$ ls -l /etc/openldap/certs/ldap-ca.crt
ls: cannot access '/etc/openldap/certs/ldap-ca.crt': No such file or directory

**Comment by tchellomello** [comment]
Hello @AbhinitMallick 

For the ldap issue you mentioned, its a dup of #517 #507 and should be fixed by ansible/awx#10965

In regards to the `ldap-ca.crt`, I see on your spec that  you passed `ldap_cacert_secret: awx-custom-certs`. Could you share the content of this secret (obfuscate the content).  `kubectl describe secret awx-custom-certs`

**Comment by AbhinitMallick** [comment]
@tchellomello 
I create them using the below command ( it is the same file that I use for both bundle and ldap ca crt )

kubectl create secret generic awx-custom-certs \
    --from-file=ldap-ca.crt=/etc/openldap/cacerts/KFPLC_INTER_CA2_V1.pem  \
    --from-file=bundle-ca.crt=/etc/openldap/cacerts/KFPLC_INTER_CA2_V1.pem
    
[root@lnxs awx_operator]# kubectl describe secrets awx-custom-certs
Name:         awx-custom-certs
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
bundle-ca.crt:  3867 bytes
ldap-ca.crt:    3867 bytes

**Comment by damluji** [comment]
Any updates when a release with this fix (LDAP issue) is coming out please?

**Comment by chrismeyersfsu** [comment]
This issue will be fixed in the next AWX release.
