### ISSUE TITLE
Helm Chart for AWX Operator

### ISSUE THREAD

**Issue by afritzler** [ansible/tower-operator#52]
Hi,

is there already a helm chart available for the AWX operator?

Regards,
Andreas

**Comment by shanemcd** [comment]
Hello. No, there isnt.

**Comment by howardjones** [comment]
I have one. I will try to figure out if/how I could share it. It's not complicated! (1 CRD, 4 templates)

**Comment by Andysimcoe** [comment]
@howardjones I don't suppose you were able to share the Helm chart were you?

**Comment by tchellomello** [comment]
Since currently, we are using the `operator-sdk`, a Helm chart is not yet in the plans but PR's will be always welcome! Closing this for now!

**Comment by howardjones** [comment]
@Andysimcoe  this is what I did (apologies for thread-reaping a little bit): https://groups.google.com/g/awx-project/c/wBKJri1OvOI/m/JAJ5F_2hAQAJ
