### ISSUE TITLE
Pod for run job not use 'node_selector'

### ISSUE THREAD

**Issue by dolgovas** [ansible/tower-operator#526]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When i run job, awx-operator create a new pod named like automation-job-NUMBER on wrong node. It doesn't use node_selector for choose valid node.
How i can fix it?

##### ENVIRONMENT
* AWX version: 19.2.2
* Operator version: 0.12
* Kubernetes version: k8s 1.21.0

**Comment by shanemcd** [comment]
Have you updated the pod definition on the default Container Group to include your node selectors? If you applied them in your operator config, those will only apply to the control plane pods, not the job runtime pods.

**Comment by shanemcd** [comment]
Closing due to lack of response.

**Comment by kevrrnet** [comment]
@shanemcd 
how do we configure custom pod spec for automation job pod ?
