### ISSUE TITLE
Accessing AWX outside of localhost

### ISSUE THREAD

**Issue by natsumi12** [ansible/tower-operator#531]
Hello guys, 
I am new to AWX/kubernetes. I am trying to have the AWX web gui accessible from other servers via the servers IP:AWX port.
I have basic latest AWX install deployed on Minikube v1.21.0. 
On the GUI server where the AWX is running I can access the AWX via link provided by "minikube service awx-demo-service --url", but not outside of the server. I did also try to use "kubectl portforward" on the pod but that could be also accessible only via localhost.

I assume the resolution is rather easy but I have been struggling with this for  some time now. 

Thank you

**Comment by chrismeyersfsu** [comment]
Can you ask this question on the mailing list @natsumi12 ?
