### ISSUE TITLE
ansible-controller is not creating 

### ISSUE THREAD

**Issue by techdiaters** [ansible/tower-operator#537]
{"level":"error","ts":1631461497.2144506,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"awx-controller","request":"default/ansible-awx","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go

it is showing this error ansible-postgress is creating but ansible-controller is not creating 
can anyone please help me on this issue

**Comment by slaurencelle** [comment]
Hello techdiaters,

Are you trying to install it with the awx operator on kubernetes cluster 1.22.xx ?
if yes there is another ticket open for that and you are not alone i have the same bug it'seem to be working well on kubernetes cluster 1.21.2 but not with the 1.22 version where are still waiting for a solution.

Regards,

Stephane

**Comment by slaurencelle** [comment]
Here is the other ticket that is open for that bug

Can't deploy AWX w/ custom database configuration #511

Hope other can help with a solution

Stephane

**Comment by techdiaters** [comment]
I am installing in minikube ansible-controller is not creating 

i will refer that issue

**Comment by slaurencelle** [comment]
which version of minikube ? since minikube permit you to run kubernetes on single node cluster, i suppose that it could be having the same issue depending on the kubernetes that you run on minikube.

Stephane

**Comment by slaurencelle** [comment]
i just check and you can not use minikube 1.23 but you can use minikube 1.22 and lower version since on 1.22 it's kubernetes 1.21.2 that is deploy by default and on 1.23 it's 1.22.x.

Stephane

**Comment by shanemcd** [comment]
Should be fixed with awx-operator 0.14.0
