### ISSUE TITLE
change postgres settings

### ISSUE THREAD

**Issue by AlekseiSaff** [ansible/tower-operator#538]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
need to change postgres settings

##### ENVIRONMENT
* AWX version: 19.3
* Operator version: 0.13
* AWX install method: minikube

##### STEPS TO REPRODUCE

I need to change postgres setting to avoid production failures
https://github.com/ansible/awx/issues/10996#issuecomment-917686258

##### EXPECTED RESULTS

postgres should be run with modified settings

##### ACTUAL RESULTS

postgres is running with default settings

##### ADDITIONAL INFORMATION

https://github.com/ansible/awx/issues/10996#issuecomment-917686258
here is the problem and the way how to resolve it. Need to know how to implement this via awx-operator

**Comment by chris93111** [comment]
+1 same problem with production tunning, need to change max_connections 

maybe allow args params for postgresql launch , or mount configmap with name defined by user in operator

**Comment by shanemcd** [comment]
Seems like you have already done the hard work - please feel free to open a PR.

**Comment by rooftopcellist** [comment]
This Issue was resolved by https://github.com/ansible/awx-operator/pull/753
