### ISSUE TITLE
custom env

### ISSUE THREAD

**Issue by metabsd** [ansible/tower-operator#54]
There a way to create custom env like describe here --> https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md#kubernetes-custom-virtualenvs

Thx a lot

**Comment by shanemcd** [comment]
Negative. That feature is actually going away sometime before this operator GAs. More info here: https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/eYqt8BmxAgAJ
