### ISSUE TITLE
Post Install operations to AWX instance

### ISSUE THREAD

**Issue by suukit** [ansible/tower-operator#542]
##### ISSUE TYPE
 - Feature request

##### SUMMARY
After having the operator running to setup the AWX instance it would be good to be able to run additional ansible code to configure the instance (e.g. add git repos). This ansible code could be provided as config map and be included by the operator for the instance.

**Comment by shanemcd** [comment]
We're unlikely to do this. Instead, try writing a playbook that deploys your AWX and then does whatever provisioning you need.

**Comment by suukit** [comment]
I think this is harsh restriction as many parties (including us) are using gitops tools like argocd or flux and operators to setup and maintain infrastructures as AWX. If I follow your advice I'd need an external ansible execution service (maybe an already build up and working AWX) to finish my AWX setup. I think https://github.com/ansible/awx-operator/issues/522 goes in the same direction. The operator is great but there will be work that needs to be done afterwards and has to be triggered from within the operator instance to provide a good usability in reality.
