### ISSUE TITLE
awx-demo.yml Pods are stuck in Pending state

### ISSUE THREAD

**Issue by sam-sre** [ansible/tower-operator#543]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx-demo.yml Pods are stuck in Pending state.

##### ENVIRONMENT
* AWX version: 0.13.0
* Operator version:  0.13.0
* Kubernetes version:  v1.20
* AWX install method: local K8s cluster booted with Kubeadm

##### AWX-OPERATOR LOGS

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Apply deployment resources] **********************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:35

-------------------------------------------------------------------------------
{"level":"info","ts":1631628283.6133819,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/version","Verb":"get","APIPrefix":"","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
{"level":"info","ts":1631628283.6185794,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/version/openshift","Verb":"get","APIPrefix":"","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
{"level":"info","ts":1631628283.622401,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/apis","Verb":"get","APIPrefix":"","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
{"level":"info","ts":1631628283.6295416,"logger":"proxy","msg":"Skipping cache lookup","resource":{"IsResourceRequest":false,"Path":"/apis/apps/v1","Verb":"get","APIPrefix":"apis","APIGroup":"","APIVersion":"","Namespace":"","Resource":"","Subresource":"","Name":"","Parts":null}}
{"level":"info","ts":1631628283.6368983,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/default/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"default","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1631628283.6407337,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/default/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"default","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1631628283.6620295,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/default/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"default","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1631628288.6718981,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/default/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"default","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1631628293.6835659,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/default/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"default","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1631628298.6939487,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/default/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"default","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}

**Comment by slaurencelle** [comment]
Hello,
I suppose it is stuck because you did not configure any pv and pvc for the postgress storage ?
you did not gave us too much information to what is happening.

can you do a kubectl get all of the specific namespace where you install the awx operator and awx-demo 



Stephane

**Comment by sam-sre** [comment]
@slaurencelle  Thanks for the fast reply.
I thought the Operator will take care of the PVC/PV creation if using Kubeadm 
Now it is working after I deployed an nfs-provisioner with a storage class that AWX can consume.

BR
Anas

**Comment by slaurencelle** [comment]
i thought so too but it's not,

glad i could help you on this one  :)

Stephane
