### ISSUE TITLE
Can't use the parameter nodeport_port with apiVersion awx.ansible.com/v1beta1 

### ISSUE THREAD

**Issue by derdude000** [ansible/tower-operator#547]
Why doesn't work the parameter nodeport_port ?

 error validating data: ValidationError(AWX.spec): unknown field "nodeport_port" in com.ansible.awx.v1beta1.AWX.spec;

AWX Operator: 0.13
 AWX Version 19.3.0

  apiVersion: awx.ansible.com/v1beta1
   kind: AWX
   metadata:
     name: awx-01
     labels:
   spec:
     service_type: NodePort
     nodeport_port: 30080
     ingress_type: none
  
Which apiVersion should I use or what is wrong ?

**Comment by derdude000** [comment]
Has someone any idea ?

**Comment by shanemcd** [comment]
You were probably trying to install from devel, which contained unreleased code. Try again with 0.14.0.
