### ISSUE TITLE
AWX operator fails create awx service pod on kubernetes  1.22

### ISSUE THREAD

**Issue by cerberek** [ansible/tower-operator#548]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Deploy with latest minikube and stable kubernetess failles create awx pod

Erros are censored:
TASK [installer : Apply Resources] ********************************************************************************************************************************************************************************************************************************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:20
ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

So after editing this role and commenting not_tag i got:
failed: [localhost] (item=service_account) => {"ansible_loop_var": "item", "changed": false, "item": "service_account", "msg": "Failed to find exact match for rbac.authorization.k8s.io/v1beta1.RoleBinding by [kind, name, singularName, shortNames]"}
failed: [localhost] (item=ingress) => {"ansible_loop_var": "item", "changed": false, "item": "ingress", "msg": "Failed to find exact match for extensions/v1beta1.Ingress by [kind, name, singularName, shortNames]"}

Then you can find why this failled here https://kubernetes.io/docs/reference/using-api/deprecation-guide/
The networking.k8s.io/v1beta1 API version of IngressClass is no longer served as of v1.22.
The rbac.authorization.k8s.io/v1beta1 API version of ClusterRole, ClusterRoleBinding, Role, and RoleBinding is no longer served as of v1.22.

Deleting 1.22 kubernetes minikube container and creating new 1.21 works nicely and AWX is UP

##### ENVIRONMENT
* AWX version: 19.3.0
* Operator version: 0.13
* Kubernetes version:  1.22
* AWX install method: awx operator

##### STEPS TO REPRODUCE

Install AWX with default awx operator config

##### EXPECTED RESULTS

working AWX

##### ACTUAL RESULTS

missing pod for AWX

sudo -u awx minikube kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
awx-operator-69c646c48f-tppq7   1/1     Running   0          61m
awx-postgres-0                  1/1     Running   0          60m

**Comment by slaurencelle** [comment]
Hello Cerberek,

so since now we know what is causing the problem does that mean that the awx-operator will be repair to work with kubernetes 1.22 ?

regards,
Stephane

**Comment by cerberek** [comment]
I don't know. I was only figuring out last days why it failed. Solution for me is doing AWX deploy on kubernetes v1.21.

**Comment by slaurencelle** [comment]
i don't think it's a solution, it's have to be resolve because we won't be able to update the kubernetes cluster in the future because of that.

Can a developper give us a little feedback about that ?
Stephane

**Comment by ggiinnoo** [comment]
Check out this issue, perhaps it can help you: https://github.com/ansible/awx-operator/issues/494

**Comment by shanemcd** [comment]
Most likely resolved by #569

**Comment by shanemcd** [comment]
Closing - #569 has been released in 0.14.0.
