### ISSUE TITLE
uWSGI Harakiri troubleshooting

### ISSUE THREAD

**Issue by fr33f411** [ansible/tower-operator#55]
Hello Ansible Team!

I use Ansible AWX operator ~1 month and recently I started to get errors with Microsoft oauth (it worked fine before). 
When backend receives MS oauth ticket it goes down and I don't know why and how to fix it. 

Log example:

```
Fri Nov 20 14:40:42 2020 - *** HARAKIRI ON WORKER 2 (pid: 83, try: 1) ***
Fri Nov 20 14:40:42 2020 - HARAKIRI !!! worker 2 status !!!
Fri Nov 20 14:40:42 2020 - HARAKIRI [core 0] 172.17.176.122 - GET /sso/complete/azuread-oauth2/?code=0.AS8APW17qF7Ym02HBGrtdqSURCAv2PPkSBlDv0l-6sfh_cgvAME.AQABAAIAAAB2UyzwtQEKR7-rYcChUZzztB7g37Xbuo0KyqwGe5wlliAA&state=gyEMxxLQhlhWe7FLZk9TVbVx3xqaBsXR&session_state=ad627b1a-92f3-494a-8609-f1606594f71a since 1605883121
Fri Nov 20 14:40:42 2020 - HARAKIRI !!! end of worker 2 status !!!
DAMN ! worker 2 (pid: 83) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 2 (new pid: 267)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x229d510 pid: 267 (default app)
```

Could you give me any help/advice how to resolve this?

Thanks in advance!

With best regards,
Andrey

**Comment by wupeng606** [comment]
The "GET" action is over the uwsgi harakiri timeout 120s, so the worker of uwsgi was killed.
"since 1605883121" in the means since 2020-11-20 10:38:41 CST

I am facing similar issue. I am searching the help/advice.
