### ISSUE TITLE
AWX login with LDAP doesnt work after first login

### ISSUE THREAD

**Issue by leociociano** [ansible/tower-operator#550]
**Environment:**
AWX-Operator: v0.13.0
AWX: v19.3
Infra: OpenShift 4.6
Authentication Type: LDAP with ActiveDirectory

**Settings:**
LDAP Authentication
Logging Aggregator Level Threshold: DEBUG

**What Happens:**
LDAP Authentication works fine on the first user login.  After logout, I try to relogin with the same user and I get "Invalid username or password".

**What should happen:**
LDAP Authentication should work fine with every user login.

**Logs:**
I get LDAP logs on the first login in the awx-web container, which say user was found and authenticated.  After the second login (which fails) I don't get any LDAP logs (even with Logging Level in DEBUG). I just get:  awx.api.generics Login failed for user \<username\> from \<ipaddress\>

**What I found:**
After first login, the user is registered in AWX Console (I can see it under Users menu). With this registered user (after first login), I can't login any more. 
On the other hand, If I delete said user, I can login again with it, but after it gets re-registered, I get the same story. 

**Assumptions**
I assume that LDAP settings are OK, since it works the first login time (when the user is not registered in AWX yet). But I can't troubleshoot anything cause I don't get any useful log of the event.

Thanks.

**Comment by kurokobo** [comment]
This is a known issue for AWX 19.3.0 deployed with AWX Operator 0.13.0 (ansible/awx#10883, #507). This should be fixed in the next release.

As a current workaround, use AWX Operator 0.12.0 to deploy AWX 19.2.2.

**Comment by leociociano** [comment]
Thank you very much. I'll just close this issue.
