### ISSUE TITLE
Running older version of Ansible

### ISSUE THREAD

**Issue by pbrisson73** [ansible/tower-operator#555]
AWX operator is running an older version of Ansible causing module issues that I use in 2.11, is there a near future updates that will include Ansible core 2.11 or higher?

`kubectl exec --stdin --tty awx-operator-69c646c48f-9jkcs -- /bin/bash`
bash-4.4$ `ansible --version`
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/openshift']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
bash-4.4$

**Comment by shanemcd** [comment]
I believe this is on the roadmap for the operator-sdk team. We're going to need them to bump Ansible, as we just use their base image.

**Comment by pbrisson73** [comment]
Thanks for the update
