### ISSUE TITLE
Operator User and namespace

### ISSUE THREAD

**Issue by kenichimilo** [ansible/tower-operator#56]
Hi,
After trying to test the operator OOTB, i landed into two issues :-
- Namespace that will house awx not available , which is documented, though as there is a service account with cluster credentials wouldn't it be better to check if the namespace exists and if not create it .. 
- The operator is looking to run as a certain user.. 
KeyError: 'getpwuid(): 
muddled over this for a while and the only way i managed to get it working was to rebuild the operator with

USER root

RUN useradd -m -u 1002670000 -s /sbin/nologin awx-operator 

# Install Ansible requirements.
COPY requirements.yml ${HOME}/requirements.yml
RUN ansible-galaxy collection install -c -r ${HOME}/requirements.yml \
 && chmod -R ug+rwx ${HOME}/.ansible

COPY watches.yaml ${HOME}/watches.yaml

COPY main.yml ${HOME}/main.yml
COPY roles/ ${HOME}/roles/

USER 1002670000

If there are other solutions for the user , would be grt to get a new build.. 
thanks

**Comment by tchellomello** [comment]
@kenichimilo  could you please try again with the latest version and then report if that still happens?

**Comment by kenichimilo** [comment]
Ok will do and let you know

**Comment by kenichimilo** [comment]
Unfortunately the error is still present..

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'getpwuid(): uid not found: 1000080000'
  | fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

perhaps an entrypoint file would help in making sure that the operator is running as the right user..

**Comment by wenottingham** [comment]
Hi -

The intiial issue describes changes to the AWX environment (installing roles) that is incompatible with how jobs are now run in execution environments. Please try again with AWX 19 and building a custom execution environment with your content.
