### ISSUE TITLE
unable to reach awx web gui after being able to deploy awx opearator and awx database + apps

### ISSUE THREAD

**Issue by slaurencelle** [ansible/tower-operator#561]
Hello,

i was able to manager with help of the community here to deploy my awx operator and awx apps.

but now i am unable to reach the awx web gui, i have define the service_type has nodeport for the moment to be able to reach it outside of the kubernetes cluster. When this part will work i will change the access with an ingress.

Do you have any idea what could cause my issue ?
I have been working with kubernetes for the last 2 years but never encounter so much problem with an oparator or in the deployment of awx on docker. This is my first try with th operator and i hit a lot of bump on that road so far.

Starting to loose my positivity on that one :(

Hope you can help me on this one !!!

Stephane

**Comment by slaurencelle** [comment]
Did someone encounter the same trouble accessing the awx web gui ?

Help would be really appreciated :(

Regards,

Stephane

**Comment by slaurencelle** [comment]
Hello,
i check on each awx pod , and here is what i get in there logs : 

k8s_awx-web pod and k8s_awx-task pod
[wait-for-migrations] Waiting 8 seconds before next attempt

what does it mean ?

Stephane

**Comment by shanemcd** [comment]
Hello,

I'm sorry but without more context or logs we can't help you.

This issue tracker is for tracking feature enhancements and bugs in AWX itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project

**Comment by slaurencelle** [comment]
Hello Shane,

This is an issue, this is the first time i am using the awx-operator and never before got so much trouble installing awx.
Each step is a pain, so the only thing i need is help on what is happening when the operator is manging the deployment of the awx part.
my database pod is running and so are my awx pod.
but i am not able to access the web gui and this is the error i got on those pods in the log.
If you need more info i will be glad to give those to you.

Regards,

stephane
