### ISSUE TITLE
 [RFE] Add node_selector, tolerations setting for automation-job-X pods created by AWX

### ISSUE THREAD

**Issue by mick1627** [ansible/tower-operator#562]
##### ISSUE TYPE
We have node_selector, tolerations settings for the AWX pods but this setting are not applied for pods automation-job-X  created by AWX.

##### SUMMARY
Be able to set  node_selector,  tolerations for pods  automation-job-X pods created by AWX

##### ENVIRONMENT
* AWX version: 19.3.0 
* Operator version: 0.13.0
* Kubernetes version: v1.20.9-gke.300

**Comment by shanemcd** [comment]
Would be happy to review a PR for this.

**Comment by mick1627** [comment]
In fact, we can do this in the "Container group" configuration =>  https://docs.ansible.com/ansible-tower/latest/html/administration/external_execution_envs.html#customize-the-pod-spec
