### ISSUE TITLE
Unable to deploy AWX Operator 0.14.0 because the image awx-operator:0.14.0 does not exist on Quay.io

### ISSUE THREAD

**Issue by kurokobo** [ansible/tower-operator#578]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Deployment of AWX Operator `0.14.0` fails because the container image `quay.io/ansible/awx-operator:0.14.0` does not exist.

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version:  v1.21.5+k3s1
* AWX install method: K3s

##### STEPS TO REPRODUCE

```bash
git clone https://github.com/ansible/awx-operator.git
cd awx-operator
git checkout 0.14.0
export NAMESPACE=awx
make deploy
```

##### EXPECTED RESULTS

AWX Operators' pod has been started in `awx` namespace.

##### ACTUAL RESULTS

AWX Operators' pod got `ImagePullBackOff` and never be started.

```bash
$ kubectl -n awx get pods
NAME                                               READY   STATUS             RESTARTS   AGE
awx-operator-controller-manager-68d787cfbd-t8dm2   1/2     ImagePullBackOff   0          58s
```

The event `quay.io/ansible/awx-operator:0.14.0: not found` has been recorded.

```bash
$ kubectl -n awx describe pod awx-operator-controller-manager-68d787cfbd-t8dm2
...
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  77s                default-scheduler  Successfully assigned awx/awx-operator-controller-manager-68d787cfbd-t8dm2 to kuro-awx01.krkb.lab
  Normal   Pulling    77s                kubelet            Pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0"
  Normal   Pulled     73s                kubelet            Successfully pulled image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0" in 4.39818265s
  Normal   Created    72s                kubelet            Created container kube-rbac-proxy
  Normal   Started    72s                kubelet            Started container kube-rbac-proxy
  Normal   Pulling    31s (x3 over 72s)  kubelet            Pulling image "quay.io/ansible/awx-operator:0.14.0"
  Warning  Failed     30s (x3 over 72s)  kubelet            Failed to pull image "quay.io/ansible/awx-operator:0.14.0": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/ansible/awx-operator:0.14.0": failed to resolve reference "quay.io/ansible/awx-operator:0.14.0": quay.io/ansible/awx-operator:0.14.0: not found
  Warning  Failed     30s (x3 over 72s)  kubelet            Error: ErrImagePull
  Normal   BackOff    3s (x5 over 72s)   kubelet            Back-off pulling image "quay.io/ansible/awx-operator:0.14.0"
  Warning  Failed     3s (x5 over 72s)   kubelet            Error: ImagePullBackOff
```

##### ADDITIONAL INFORMATION

Currently there is no image with tag `0.14.0` on [quay.io/repository/ansible/awx-operator](https://quay.io/repository/ansible/awx-operator?tag=latest&tab=tags). Seems [the related GitHub Actions](https://github.com/ansible/awx-operator/actions/runs/1298976642) had been failed.

I think the maintainers are already aware of this issue, but I am creating this issue to document the situation for someone else just in case.
Thanks for awesome project :)

##### WORKAROUND

Use `0.13.0` instead; <https://github.com/ansible/awx-operator/tree/0.13.0>

**Comment by shanemcd** [comment]
Oops, sorry about that. I got a little too confident and walked away from my computer without checking on the final step 😅. The image is up there now, can you give it a whirl?

**Comment by kurokobo** [comment]
Works good, thanks!
