### ISSUE TITLE
AWX Operator 0.14.0 sets pathType: Prefix on Ingress resources, which breaks Google load balancing

### ISSUE THREAD

**Issue by sdigit** [ansible/tower-operator#580]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using an ingress configured like so:
```
  ingress_path: /*
  ingress_type: ingress
  ingress_tls_secret: awx-ops-domain-net-tls
  ingress_annotations: |
    kubernetes.io/ingress.global-static-ip-name: ops-k8s-awx-lb
    networking.gke.io/v1beta1.FrontendConfig: "tls-modern"
  hostname: awx.ops.domain.net
```

AWX 19.3.0 works just fine behind an HTTP load balancer in GKE.

AWX 19.4.0 does not, as Operator 0.14.0 adds `pathType: Prefix` to the `Ingress` on line 23 of `roles/installer/templates/ingress.yaml.j2`

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version: v1.20.9-gke.1001
* AWX install method: kubernetes

##### STEPS TO REPRODUCE
Provision an AWX on GKE and attempt to use an http load balancer in front of it via ingress settings

##### EXPECTED RESULTS
A working AWX

##### ACTUAL RESULTS
A failed load balancer provision
##### ADDITIONAL INFORMATION

if pathType were configurable that would be great.

##### AWX-OPERATOR LOGS
From `kubectl describe ingress -n awx`:
```
Events:
  Type     Reason     Age                    From                     Message
  ----     ------     ----                   ----                     -------
  Normal   Sync       3m36s (x2 over 3m36s)  loadbalancer-controller  Scheduled for sync
  Warning  Translate  52s (x16 over 3m36s)   loadbalancer-controller  Translation failed: invalid ingress spec: only "ImplementationSpecific" path type is supported
```

The following PR fixes this:
https://github.com/ansible/awx-operator/pull/579

**Comment by shanemcd** [comment]
Thanks for the patch. Will be in the next release.
