### ISSUE TITLE
Deployment to GKE - Ansible play "Apply Deployment Resources" timing out

### ISSUE THREAD

**Issue by gatboccia** [ansible/tower-operator#583]
Not sure exactly what I am doing wrong here. At this point I am following the steps in the readme and deploying the basic example. I was hitting the same issue when also applying a custom spec for using an external DB. Basically seems like the deployment apply times out. Not sure if anyone else is seeing this issue? I am only getting the single play failure, everything else seems to apply fine.

--------------------------- Ansible Task StdOut -------------------------------

 TASK [Apply deployment resources] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "duration": 120, "method": "apply", "msg": "Resource apply timed out",

**Comment by shanemcd** [comment]
That's weird. What kind of Kubernetes environment are you deploying into?

**Comment by gatboccia** [comment]
Apologies for not including those details. 

I'm deploying into a fresh cluster in GKE (1.20.10-gke.301). Nothing custom has been done, simply spun up the cluster and attempted the demo deployment in the awx namespace.

**Comment by gatboccia** [comment]
Closing this as a non-issue. Turned out to be some resource scaling issues with my nodes.
