### ISSUE TITLE
lookup plugin (hashi_vault) not found

### ISSUE THREAD

**Issue by sgeraskin** [ansible/tower-operator#588]
What needs to be done to make the function work?

`test_kubeconfig: "{{ lookup('hashi_vault', 'secret=secret/data/k8s/rancher/kubeconfig/test token={{ v_token }} url={{ v_url }}') }}"`

Im used 0.14.0
And I get the error

`  "msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ lookup('hashi_vault', 'secret=secret/data/k8s/rancher/kubeconfig/test token={{ v_token }} url={{ v_url }}') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: lookup plugin (hashi_vault) not found",`

**Comment by kimbernator** [comment]
At the top level of your project repository, include the following in `collections/requirements.yml`:

```YAML
---
collections:
  - name: community.hashi_vault
    version: 1.1.3 # this is optional
```

You'll also want to ensure "Enable collections download" is turned on in settings -> Job settings.

Then when AWX syncs the project it will check for that requirements.yml file and install the collection you need.

**Comment by sgeraskin** [comment]
Thanks!
I did as you said. But nothing has changed.
In the logs awx_task during project synchronization there are no records about the installation of the collection

**Comment by sgeraskin** [comment]
```
TASK [fetch galaxy collections from collections/requirements.(yml/yaml)] *******11:24:59
27
[WARNING]: Unable to find
28
'/var/lib/awx/projects/_12__ansible_sgeraskin/collections' in expected paths
29
(use -vvvvv to see paths)
```

**Comment by sgeraskin** [comment]
Sorry, I'm an idiot :)
Put the file in the wrong branch!
Thanks! Everything works as it should!

`Please pip install hvac to use the hashi_vault lookup module.`

Where do I need to install the hvac module?

**Comment by kimbernator** [comment]
Yep, we had the same problem. Unfortunately the only "official" way is to build your own EE image with that package installed and maintain it. You can look into [Ansible-Builder](https://www.ansible.com/blog/introduction-to-ansible-builder) if you want to get deep into the woods with customizing your EE, but the following dockerfile was a pretty easy way for me to build an image that did what I needed:

```
FROM <my_docker_registry>/ansible/awx-ee:0.6.0
RUN pip3 install --no-cache-dir hvac==0.10.8
```

Then you'll need to figure out where to store your modified image and assign it as an EE in the awx operator config:

```
  ee_images:
  - name: Custom AWX EE
    image: <my_docker_registry>/my-repo/my-custom-ee:0.1.0
  control_plane_ee_image: <my_docker_registry>/my-repo/my-custom-ee:0.1.0
```

You're also able to have multiple entries under `ee_images` that you can then assign job templates to individually if you find that useful.

Bit of a frustrating process for sure.

**Comment by chrismeyersfsu** [comment]
Closing. This is not a problem related to this project, `awx-operator`.

**Comment by yw5vruox7dr** [comment]
@kimbernator is your method still working?  

Tried the same but got a permission error: https://github.com/ansible/awx/issues/11854
