### ISSUE TITLE
Create new instance with 0.14.0 fails: `/bin/sh: 1: kubectl: not found`

### ISSUE THREAD

**Issue by Commifreak** [ansible/tower-operator#590]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When following the basic install steps step by step (using minikube) the deploy fails with `/bin/sh: 1: kubectl: not found`:

<details>
<summary>minikube kubectl -- get pods -A</summary>

```
NAMESPACE       NAME                                        READY   STATUS      RESTARTS      AGE
ingress-nginx   ingress-nginx-admission-create--1-qs5t9     0/1     Completed   0             14m
ingress-nginx   ingress-nginx-admission-patch--1-kxvns      0/1     Completed   1             14m
ingress-nginx   ingress-nginx-controller-69bdbc4d57-59lxh   1/1     Running     0             14m
kube-system     coredns-78fcd69978-vg7kp                    1/1     Running     0             14m
kube-system     etcd-minikube                               1/1     Running     0             14m
kube-system     kube-apiserver-minikube                     1/1     Running     0             14m
kube-system     kube-controller-manager-minikube            1/1     Running     0             14m
kube-system     kube-proxy-scsmg                            1/1     Running     0             14m
kube-system     kube-scheduler-minikube                     1/1     Running     0             14m
kube-system     storage-provisioner                         1/1     Running     1 (14m ago)   14m
```
</details>

Then cloning master and checkout 0.14.0 - ok
The docs say: `Let's create an alias for easier usage:` - okay. `kubectl` now executes kubectl in my minikube env.
Then `export NAMESPACE=my-namespace` and finally `make deploy` results in:

```
make deploy
cd config/manager && /home/awx/awx-operator/bin/kustomize edit set image controller=quay.io/ansible/awx-operator:0.14.0
cd config/default && /home/awx/awx-operator/bin/kustomize edit set namespace my-namespace
/home/awx/awx-operator/bin/kustomize build config/default | kubectl apply -f -
/bin/sh: 1: kubectl: not found
make: *** [Makefile:82: deploy] Error 127
```

Whats wrong?

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version: 1.22.2
* AWX install method: minikube docker driver

##### STEPS TO REPRODUCE

See problem description :)

##### EXPECTED RESULTS

Deployment starts

##### ACTUAL RESULTS

Deployment fails

##### ADDITIONAL INFORMATION
none

**Comment by shemi-plgs** [comment]
Hi ! I had the same issue, i guess it has something to do with the shell used by the script (not sure)
A fix that worked for me was just using sed to replace the kubectl with minikube kubectl -- on the Makefile

`sed 's/kubectl/minikube kubectl --/g' -i Makefile`

**Comment by Commifreak** [comment]
Sounds logical. I thought the same. Aliases seems not to work inside the male process.

Yet another way to set awx up… everytime I update awx, I fear the new mechanisms 😵‍💫😅

**Comment by Commifreak** [comment]
That worked! The Makefile should cover that automagically.
