### ISSUE TITLE
0.14.0 operator fails to deploy without access to clusterscope 

### ISSUE THREAD

**Issue by olokolo250** [ansible/tower-operator#591]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Not sure if thats a bug or feature but does the version 0.14.0 still requires access to sclusterscope ? 
Thought that this development will allow me to install AWX in an environment where I only have an access to project and my own namespace. 

##### ENVIRONMENT
* AWX version: latest 
* Operator version: 0.14.0
* Kubernetes version: 1.19.8
* AWX install method: openshift

##### STEPS TO REPRODUCE

as per https://github.com/ansible/awx-operator

export NAMESPACE=awx
make deploy
cd config/manager && /var/tmp/osw02/awx-operator/bin/kustomize edit set image controller=quay.io/ansible/awx-operator:0.14.0
cd config/default && /var/tmp/osw02/awx-operator/bin/kustomize edit set namespace awx
/var/tmp/osw02/awx-operator/bin/kustomize build config/default | kubectl apply -f -
Warning: resource namespaces/awx is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create
--save-config or kubectl apply. The missing annotation will be patched automatically.
namespace/awx configured
serviceaccount/awx-operator-controller-manager created
configmap/awx-operator-manager-config created
service/awx-operator-controller-manager-metrics-service created
deployment.apps/awx-operator-controller-manager created
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "awxbackups.awx.ansible.com", Namespace: ""
from server for: "STDIN": customresourcedefinitions.apiextensions.k8s.io "awxbackups.awx.ansible.com" is forbidden: User "u-x7mwk4kzns" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "awxrestores.awx.ansible.com", Namespace: ""
from server for: "STDIN": customresourcedefinitions.apiextensions.k8s.io "awxrestores.awx.ansible.com" is forbidden: User "u-x7mwk4kzns" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "awxs.awx.ansible.com", Namespace: ""
from server for: "STDIN": customresourcedefinitions.apiextensions.k8s.io "awxs.awx.ansible.com" is forbidden: User "u-x7mwk4kzns" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=roles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=Role"
Name: "awx-operator-leader-election-role", Namespace: "awx"
from server for: "STDIN": roles.rbac.authorization.k8s.io "awx-operator-leader-election-role" is forbidden: User "u-x7mwk4kzns" cannot get resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "awx"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=roles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=Role"
Name: "awx-operator-manager-role", Namespace: "awx"
from server for: "STDIN": roles.rbac.authorization.k8s.io "awx-operator-manager-role" is forbidden: User "u-x7mwk4kzns" cannot get resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "awx"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterroles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRole"
Name: "awx-operator-metrics-reader", Namespace: ""
from server for: "STDIN": clusterroles.rbac.authorization.k8s.io "awx-operator-metrics-reader" is forbidden: User "u-x7mwk4kzns" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterroles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRole"
Name: "awx-operator-proxy-role", Namespace: ""
from server for: "STDIN": clusterroles.rbac.authorization.k8s.io "awx-operator-proxy-role" is forbidden: User "u-x7mwk4kzns" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=rolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=RoleBinding"
Name: "awx-operator-leader-election-rolebinding", Namespace: "awx"
from server for: "STDIN": rolebindings.rbac.authorization.k8s.io "awx-operator-leader-election-rolebinding" is forbidden: User "u-x7mwk4kzns" cannot get resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "awx"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=rolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=RoleBinding"
Name: "awx-operator-manager-rolebinding", Namespace: "awx"
from server for: "STDIN": rolebindings.rbac.authorization.k8s.io "awx-operator-manager-rolebinding" is forbidden: User "u-x7mwk4kzns" cannot get resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "awx"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding"
Name: "awx-operator-proxy-rolebinding", Namespace: ""
from server for: "STDIN": clusterrolebindings.rbac.authorization.k8s.io "awx-operator-proxy-rolebinding" is forbidden: User "u-x7mwk4kzns" cannot get resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
make: *** [deploy] Error 1

##### EXPECTED RESULTS

Expected to deploy operator in k8s cluster 

##### ACTUAL RESULTS

first deploy step fails

**Comment by hungpr0** [comment]
For `CustomResourceDefinition`, you will need cluster admin right

**Comment by shanemcd** [comment]
Closing this, the comment above is correct.
