### ISSUE TITLE
https://raw.githubusercontent.com/ansible/awx-operator/0.14.0/deploy/awx-operator.yaml not found

### ISSUE THREAD

**Issue by olegsidokhmetov** [ansible/tower-operator#594]
##### ISSUE TYPE
 - Bug Report
`kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/0.14.0/deploy/awx-operator.yaml`
`error: unable to read URL "https://raw.githubusercontent.com/ansible/awx-operator/0.14.0/deploy/awx-operator.yaml", server reported 404 Not Found, status code=404`

##### SUMMARY

Tried to deploy awx-operator, but get error that unable to read URL 

##### ENVIRONMENT
* AWX version: X.Y.Z
* Operator version: 0.14.0
* Kubernetes version: 1.22.2
* AWX install method: docker on linux

##### EXPECTED RESULTS

Using correct command to download awx-operator  kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/0.14.0/deploy/awx-operator.yaml

**Comment by malcolmohare** [comment]
The install process for the operator changed from 0.13.0 to 0.14.0, so this is expected.

**Comment by mrwiora** [comment]
@olegsidokhmetov try these steps:
https://github.com/ansible/awx-operator/issues/582#issuecomment-934536812 

@malcolmohare this was so helpful, as you wouldn't have written anything....

**Comment by shanemcd** [comment]
Current install steps are in the readme. On a related note, see https://github.com/ansible/awx-operator/issues/657
