### ISSUE TITLE
Is this operator only supporting AWX

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#6]
With the move of this operator, is this only looking to target AWX? Or will this continue to support Ansible Tower as well?

**Comment by tylerauerbeck** [comment]
@matburt @geerlingguy Anyway to get some clarification on this?

**Comment by matburt** [comment]
For the moment yes, I cover this in this PR: 

https://github.com/ansible/awx-operator/pull/4#issuecomment-654565855

The plan for Tower is to find a way to stabilize the CRDs and move them under the OLM. The typical pattern for these operators is to maintain them seperately.
