### ISSUE TITLE
Minikube Overlay2 is to high

### ISSUE THREAD

**Issue by clementbey** [ansible/tower-operator#609]
##### ISSUE TYPE
 - Overlay2 is to high

##### SUMMARY
`/var/lib/docker/volumes/minikube/_data/lib/docker/overlay2` is very high

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version: Minikube v1.22.0
* AWX install method: docker on Linux (Debian 11)

##### STEPS TO REPRODUCE
New install (following documentation awx-operator 0.13.0, nothing more) with new server (august end) AWX-Operator 0.13.0 and AWX 19.3.0 and migrate last week to AWX-Operator 0.14.0 (with AWX 19.4.0). I see folder `/var/lib/docker/volumes/minikube/_data/lib/docker/overlay2` taking all my drive space... Do you know a solution to clean minikube overlay2 ? How to reduce him ?

![image](https://user-images.githubusercontent.com/88830012/137753665-4bf82b58-9257-43fd-bd33-612329ab4ae5.png)

This AWX have just 1 task the sunday for 230 servers and he just past a command to PowerShell... He's not very used...
A `docker system prune -a` change nothing.
I think it's not a awx-operator problem, and I am sorry to post a issue here, but I don't know where to find solution :(

Thanks for your help
Clement.

**Comment by shanemcd** [comment]
Is AWX the only thing running on your minikube cluster?

Are you able to dig a little deeper and get a sense of which kinds of files are piling up?

**Comment by clementbey** [comment]
Thanks for fasting answing 

Yes, this server is a deditated server for AWX alone.

I count more than 500 folders. 
![image](https://user-images.githubusercontent.com/88830012/137864027-2d156834-8380-4542-91c8-f964d9d6dd2d.png)
Same structure foreach folder : 2 folders : "Diff", "work" and 3 files : "lower", "link" and "commited".

In the largest folder, it looks like a contents of a pod? 
![image](https://user-images.githubusercontent.com/88830012/137863469-b5d12f69-6d70-4ad4-a7a3-951a8760d65f.png)

any idea ?

**Comment by clementbey** [comment]
I post a solution :
``` bash
docker exec -it fe /bin/bash
docker system prune -a -f
```
`/var` on my server goes from 32Gb to 7Gb.
you have to enter in the minikube container and only after, run the prune command.

**Comment by GitGorgon** [comment]
ty Clement, your suggestion has helped.
But is is a hopeless and sad disgrace that docker/minikube/awx leaves this much garbage behind.
This mess should be cleaned up automatically, or it is just a timebomb waiting to cause problems when we least expect it.
