### ISSUE TITLE
awx-task and awx-pod stuck in migration status

### ISSUE THREAD

**Issue by slaurencelle** [ansible/tower-operator#610]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 1.19.3
* Operator version: 0.14.0
* Kubernetes version: 1.21.3
* AWX install method:  docker on linux

##### AWX-OPERATOR LOGS
Hope you can help me solving this quickly because never been so hard to install awx before.

Regards,
Stephane

**Comment by slaurencelle** [comment]
You can close this case i solve it !

tks

**Comment by nodecaf** [comment]
> You can close this case i solve it !
> 
> tks

Hi @slaurencelle , any chance you would be able to shed some light on how you resolved it? I'm hitting the same issue, and looking for leads. Thanks in advance!
