### ISSUE TITLE
"make deploy"-command doesn't work on arm64

### ISSUE THREAD

**Issue by test123-all** [ansible/tower-operator#628]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
"make deploy"-command doesn't work on arm64(Ubuntu 20.04.3 LTS)

##### ENVIRONMENT
* AWX version: latest
* Operator version: 0.14.0
* Kubernetes version: 
* AWX install method: minikube as explained in [README.md under Basic Install](https://github.com/ansible/awx-operator/blob/0.14.0/README.md#basic-install)

##### STEPS TO REPRODUCE
1. install minikube on arm64
2. git clone repository
3. cd in the directory
3. git checkout 0.14.0
4. create namespace(is successful)
5. make deploy

##### EXPECTED RESULTS

Should install the awx-operator

##### ACTUAL RESULTS

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [Makefile:95: kustomize] Error 2

##### ADDITIONAL INFORMATION

I'm not into make and quite a beginner with kubernetes. I tried "make --help" but cant find a "deploy" option. 
Therefore I don't understand what the command really does and don't know where to look next, to resolve the problem by myself.

Thank you in advance for your help

**Comment by rrobe53** [comment]
I had to install kustomize on my ARM based Mac to get it working.

**Comment by pygoubet** [comment]
In order to fix the download URLs (for kustomize and ansible-operator), I had to path the Makefile as below
-ARCH := $(shell uname -m | sed 's/x86_64/amd64/')
+ARCH := $(shell uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')

**Comment by straes** [comment]
The above works to get past the error on the kustomize installation.  However, there appears to be an issue with the following: standard_init_linux.go:228: exec user process caused: exec format error

**Comment by Kpovoc** [comment]
Installing kustomize on an M1 Mac through brew does seem to allow the `make deploy` command. However, I still had issues with the operator after deployment, since it seems the container images were for the wrong architecture (to the best of my knowledge). Even after trying @pygoubet comment, undeploying, and deploying again, the operator would not stand up.

**Comment by rooftopcellist** [comment]
Multi-arch support, included arm was added in this PR:

https://github.com/ansible/awx-operator/pull/1681

With that change, arm operator images are now available.
