### ISSUE TITLE
Add Custom Virtual Environment Support

### ISSUE THREAD

**Issue by barryCrunch** [ansible/tower-operator#63]
_Not sure if support for this already exists._

Add support for custom virtual environments much the same way the installer in the awx repo does. Create an init container that would build the venv's and then mount the volume to the awx_task and awx_web containers.

**Comment by metabsd** [comment]
I ask this couple week ago.

#54

**Comment by shanemcd** [comment]
Hi. AWX no longer supports custom virtual environments. More info here: https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/eYqt8BmxAgAJ
