### ISSUE TITLE
Handle spaces in directory name for the 0.14.0 installation process

### ISSUE THREAD

**Issue by Kaauw** [ansible/tower-operator#633]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I'm using WSL (Because Powershell installation not working on 0.14.0) and working directory have whitespace in it's name.
When I issue the "make deploy" command, i have several errors messages.

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version: 1.22.0
* AWX install method: 
  - On premise kubernetes cluster
  - Using WSL

##### STEPS TO REPRODUCE

- On windows, create directory with whitespace (Like Onedrive does)
- Git clone awx-operator and switch to tag 0.14.0
- Issue make deploy command 

##### EXPECTED RESULTS

Should work.

##### ACTUAL RESULTS

```
❯ make deploy
cd config/manager && /mnt/c/Users/bdenece/OneDrive - Groupe IJNEXT/Documents/DevDir/awx-operator/bin/kustomize edit set image controller=quay.io/ansible/awx-operator:0.14.0
/bin/sh: 1: /mnt/c/Users/bdenece/OneDrive: Permission denied <-- whitespaces are not handled correctly
make: *** [Makefile:80: deploy] Error 126
```

##### ADDITIONAL INFORMATION

I tried to double quote the "$(shell pwd)" but i think problem is present in some other MakeFile steps.

**Comment by chrismeyersfsu** [comment]
@Kaauw can you try asking on the mailing list? Maybe someone on the mailing list has experience with getting the operator working with WSL.
