### ISSUE TITLE
Add support for remote execution nodes

### ISSUE THREAD

**Issue by erezo9** [ansible/tower-operator#634]
##### ISSUE TYPE
Question

##### SUMMARY
How do I add awx isolated nodes via the operator? is that even possible?

I want to create an instance group which will contain an isolated node that will run jobs on that node
i am able to create instance groups via the api of awx, but how do I create a node or add a node that will run the jobs?

**Comment by chrismeyersfsu** [comment]
You can probably see how it is technically possible to add a remote execution node. However, we just haven't had time to bake it into the operator and make it a first-class feature.

**Comment by erezo9** [comment]
@chrismeyersfsu Is there a way to edit the tower inventory file? from all the docs read 
https://docs.ansible.com/ansible-tower/latest/html/administration/external_execution_envs.html
it states i need to edit the inventory file of the ansible tower and then check if it is available, but im guessing it applies for linux envs and not container environment

**Comment by chrismeyersfsu** [comment]
I see where you are coming from.

Isolated instance groups are a supported Tower/Controller only feature. I think the community has gotten them to work in the past in AWX. The code for them is all contained in AWX but we just don't have any code for standing them up.

Fast forward to today. Isolated nodes have been removed. The plan is to replace them with what we call Receptor or execution nodes. (execution nodes are nodes that only run Receptor). We've thought about how this might work in openshift/kubernetes but haven't had time to implement it. The TL;DR is that you would need to configmap the Receptor config in the operator for control plane nodes to reach out to the isolated Receptor nodes.

**Comment by erezo9** [comment]
@chrismeyersfsu so do you have an example how to do it? that you think is going to be implemented in the future?

or should i move to vm installation and ditch the operator for now

**Comment by chrismeyersfsu** [comment]
The operator is the only supported installation method so you'd be on your own if you try and install to a VM. I don't have an example of how to do it. I think it would involve a configuration map of the receptor config to reach out the isolated nodes running receptor. I also don't know the timeline on this feature.

**Comment by erezo9** [comment]
@chrismeyersfsu do you have any docs on how i configure the receptor so i can modify the operator accordingly?

or if there is another solution for that matter

**Comment by chrismeyersfsu** [comment]
@erezo9 yep! https://receptor.readthedocs.io/en/latest/connecting_nodes.html

**Comment by rhessing** [comment]
@erezo9 did you find a way to get the receptors to work? We have deployed the isolated nodes with a previous version but it does not seem to work anymore with future versions.

Also, I must say that I'm disappointed in the way this community handled such a feature..

**Comment by whoamiUNIX** [comment]
@erezo9 do have any news how to achieve this?

**Comment by erezo9** [comment]
Hi,
@whoamiUNIX  @rhessing 
Sorry I have not tried the method suggested 
we had move to using container and using nodeselectors instead

**Comment by rhessing** [comment]
> Hi, @whoamiUNIX @rhessing Sorry I have not tried the method suggested we had move to using container and using nodeselectors instead

Thank you, I'm dropping my search for how to get this to work, also because it's not officially supported yet, hacking it in isn't something I want to do. We'll build a cross subnet K8S cluster and use nodeselectors as well.

**Comment by cidrbl0ck** [comment]
Did this (or a similar function) ever get added?

**Comment by AlanCoding** [comment]
Implemented in https://github.com/ansible/awx/pull/12744 and https://github.com/ansible/awx-operator/pull/1012

**Comment by erezo9** [comment]
@AlanCoding is it only for execution nodes? what about hop nodes?

**Comment by AlanCoding** [comment]
There is an open issue to support hop nodes in this context

**Comment by erezo9** [comment]
@AlanCoding can you please prvoide the issue link?

**Comment by AlanCoding** [comment]
There are a number of issues prefixed with `[hop node]` which are part of that work https://github.com/ansible/awx/issues?q=is%3Aissue+is%3Aopen+hop+node
