### ISSUE TITLE
unable to use other image in awx instance (awx-demo)

### ISSUE THREAD

**Issue by Mihgo2** [ansible/tower-operator#640]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Trying to change image from quay.io too an artifactory image. I have changed all possibilities in the repository, and i got the awx operator to work.  
kubectl get deployment
awx-operator-controller-manager   1/1     1            1

kubectl get pods 
awx-operator-controller-manager-647ddd888-tkb4x   2/2     Running            0

But when i run kubectl apply -f awx-demo.yaml then it will run with the quay.io, docker.io ect. and not with the image i changed. !
It seems like impossible to make that change?.

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version: v1.22.2
* AWX install method: kubectl (Rancher/k8s)

##### ADDITIONAL INFORMATION
example on the error
- image: quay.io/ansible/awx:19.4.0
    imageID: ""
    lastState: {}
    name: awx-demo-task
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "quay.io/ansible/awx:19.4.0"
        reason: ImagePullBackOff
  - image: quay.io/ansible/awx:19.4.0
    imageID: ""
    lastState: {}
    name: awx-demo-web
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "quay.io/ansible/awx:19.4.0"
        reason: ImagePullBackOff
##### AWX-OPERATOR LOGS
----------
{"level":"error","ts":1635935001.021385,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Reconciler error","name":"awx-demo","namespace":"mynamespace","error":"event runner on failed","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214"}

**Comment by hungtran84** [comment]
@Mihgo2 
you can specify your own image by adding it to your awx manifest file (`awx-demo.yaml` in your case). Find the example as below:
```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  replicas: 1
  image: your.repo.abc/awx
  image_version: 19.4.0
```

**Comment by chrismeyersfsu** [comment]
@Mihgo2 did this fix it for you?

**Comment by jkousuke** [comment]
I'm same.
I cannot fix it yet.

**Comment by rverhe** [comment]
any ideas about this? when iam using custom images i get this error...

**Comment by shanemcd** [comment]
Hey folks, this look like user error rather than a bug. If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project

**Comment by rverhe** [comment]
Disabling ingress in deployment and deploying ingress by hand works for me.
