### ISSUE TITLE
LDAP setting via Operator extra_settings doesn't work

### ISSUE THREAD

**Issue by hungtran84** [ansible/tower-operator#642]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 0.19.4
* Operator version: 0.14.0
* Kubernetes version: v1.20.9
* AWX install method:  Azure Kubernetes

##### STEPS TO REPRODUCE

```
  extra_settings:

    - setting: AUTH_LDAP_SERVER_URI
      value: >-
        "ldaps://ldapserver.prod.company.net:636"

    - setting: AUTH_LDAP_BIND_DN
      value: >-
        "CN=LDAP User,OU=Service Accounts,OU=product.com,DC=prod,DC=company,DC=net"

    - setting: AUTH_LDAP_BIND_PASSWORD
      value: >-
        "zzzzzzz"

    - setting: AUTH_LDAP_START_TLS
      value: false

    - setting: AUTH_LDAP_GROUP_TYPE
      value: >-
        "ActiveDirectoryGroupType"

    - setting: AUTH_LDAP_GROUP_TYPE_PARAMS
      value: {
        "name_attr": "cn"
      }


    - setting: AUTH_LDAP_REQUIRE_GROUP
      value: >-
        "CN=operators,OU=Groups,OU=product.com,DC=prod,DC=company,DC=net"

    - setting: AUTH_LDAP_USER_DN_TEMPLATE
      value: >-
        "uid=%(user)s,OU=Users,OU=product.com,DC=prod,DC=company,DC=net"
    
    
    - setting: AUTH_LDAP_USER_SEARCH
      value: 
        - >-
          "DC=prod,DC=company,DC=net"
        - >-
          "SCOPE_SUBTREE"
        - >-
          "(sAMAccountName=%(user)s)"

    - setting: AUTH_LDAP_GROUP_SEARCH
      value: 
        - >-
          "OU=product.com,DC=prod,DC=company,DC=net"
        - >-
          "SCOPE_SUBTREE"
        - >-
          "(objectClass=group)"

    - setting: AUTH_LDAP_USER_FLAGS_BY_GROUP
      value: {
        "is_superuser": [
          "CN=DBAs,OU=Groups,OU=product.com,DC=prod,DC=company,DC=net"
        ]
      }

    - setting: AUTH_LDAP_USER_ATTR_MAP
      value: {
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail"
      }

    - setting: AUTH_LDAP_ORGANIZATION_MAP
      value: {
        "myorg": {
          "admins": "CN=DBAs,OU=Groups,OU=product.com,DC=prod,DC=company,DC=net",
          "remove_users": false,
          "remove_admins": false,
          "users": true
        }
      }

    - setting: AUTH_LDAP_TEAM_MAP
      value: {
        "DBA": {
          "remove": true,
          "users": "CN=DBAs,OU=Groups,OU=product.com,DC=prod,DC=company,DC=net",
          "organization": "myorg"
        }
      }
```

##### EXPECTED RESULTS

Worked as expected. Actually, the same configuration in UI already worked

##### ACTUAL RESULTS

```
rest_framework.exceptions.ValidationError: [ErrorDetail(string="Expected an instance of LDAPGroupType but got <class 'str'> instead.", code='type_error')]
2021-11-04 07:16:55,561 WARNING  [54be3b19014e468497b4b064cec8bfad] awx.conf.registry Unable to retrieve default value for setting "AUTH_LDAP_GROUP_TYPE".
```

**Comment by hungtran84** [comment]
Hi fork, for the one who has the same issue, I ended up with changing operator CRD and installer role to load LDAP Bind password from k8s secret and add missing LDAPSearch module.

Eventually, my awx deployment (with Argo CD) is up and running with LDAP configured without any human intervention required.

Find the pending PR at https://github.com/ansible/awx-operator/pull/659

**Comment by anthonylavado** [comment]
@hungtran84 Thanks for working on that. So looking at the example included in the PR, if implemented, I don't have to specify the bind password in extra settings. Is that correct? It will get filled in/replaced by the secret?

**Comment by hungtran84** [comment]
@anthonylavado yes, all you need is to create a k8s secret for your LDAP Bind Password. I also update the readme in that PR so you will find the instruction as well as sample settings for LDAP.

**Comment by flytbird** [comment]
Hi, 

I have same problem with "PosixGroupType" class

When i set the value via extra_settings : 
```
      - setting: AUTH_LDAP_GROUP_TYPE
        value: >-
          "PosixGroupType"
```
I have always same result with : 
```
 "AUTH_LDAP_GROUP_TYPE": "MemberDNGroupType",
````



ENVIRONMENT
AWX version: 21.0.0
Operator version: 0.21.0
Kubernetes version: k3s v1.23.6+k3s1

**Comment by djohnson1865** [comment]
> Hi,
> 
> I have same problem with "PosixGroupType" class
> 
> When i set the value via extra_settings :
> 
> ```
>       - setting: AUTH_LDAP_GROUP_TYPE
>         value: >-
>           "PosixGroupType"
> ```
> 
> I have always same result with :
> 
> ```
>  "AUTH_LDAP_GROUP_TYPE": "MemberDNGroupType",
> ```
Also having the same issue on AUTH_LDAP_GROUP_TYPE, though with `ActiveDirectoryGroupType` rather than `PosixGroupType`. Though I doubt that is relevent.

@flytbird I am also having issues getting the LDAP Bind password to set via a secret. Wasn't sure if that was related. If your bind password is working I'm guessing it's a separate issue. 

Update: Got the bind password working and still no dice on the group type. So definitely unrelated.

**Comment by mac-chaffee** [comment]
The extra_settings get inserted literally into a settings.py file, but in this case the AUTH_LDAP_GROUP_TYPE is not expected to be a string, it should be a Python class: https://django-auth-ldap.readthedocs.io/en/latest/reference.html#auth-ldap-group-type

But looks like the settings.py template is missing an import for that class anyway, so you need to a hack like this currently:

```
- setting: AUTH_LDAP_SERVER_URI
  # This hack is needed to import the GroupOfNamesType class to be used later
  value: '"ldaps://ad.renci.org"; from django_auth_ldap.config import GroupOfNamesType'
- setting: AUTH_LDAP_GROUP_TYPE
  value: "GroupOfNamesType(name_attr='cn')"
```

A PR which fixes the settings.py template to import all those LDAPGroupTypes and to include this AUTH_LDAP_GROUP_TYPE example in the readme would be ideal

**Comment by rooftopcellist** [comment]
The fix has been merged.  All ldap group types classes are now imported, making the hack mentioned above no longer need.  

https://github.com/ansible/awx-operator/pull/961

Thank you @mac-chaffee !

**Comment by marcos-bonfanti-me** [comment]
Hi! I'm having a similar issue but I cant get what is failing, which are the pods and container logs that I should watch for the troubleshooting
For me it's no clear which should be the value of AUTH_LDAP_GROUP_TYPE in th UI,  i have set in an old installation ActiveDirectoryGroupType,
But in the example of the readme, it says value: 'GroupOfNamesType(name_attr="cn")'

AWX Operator version 0.29.0
<  AWX 21.8.0  >
