### ISSUE TITLE
Unable to use k8s HostAliases

### ISSUE THREAD

**Issue by CWollinger** [ansible/tower-operator#646]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
With the current version of the operator it is not possible to use HostAliases in k8s for the AWX deployment/pod.

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version: 1.20
* AWX install method: openshift

##### STEPS TO REPRODUCE

- Apply new AWX deployment
- Use FQDNs without DNS resolution or use NAT

##### EXPECTED RESULTS
Able to set HostAliases, to use "classic /etc/hosts" entries.
Used for NAT or additional host entires without DNS resolution 

##### ACTUAL RESULTS
Unable to set HostAliases for the pod/deployment. DNS will always be used.
Modification of /etc/hosts in the AWX container is not possible. 
There is no support for HostAliases in the currently CRDs for AWX deployments.

**Comment by chrismeyersfsu** [comment]
@CWollinger This is a feature request not a bug, is that correct?

**Comment by CWollinger** [comment]
If there is currently no other solution, yes.

**Comment by merickso** [comment]
This would be a really useful feature, I was hoping to use this for a problem I'm having (where I need to overwrite an ip)

**Comment by merickso** [comment]
A workaround I found was to use the hosts plugin within CoreDNS 
https://stackoverflow.com/questions/65326757/adding-hosts-to-coredns
