### ISSUE TITLE
Backup fails when Istio is activated on kubernetes namespace

### ISSUE THREAD

**Issue by stegar123** [ansible/tower-operator#651]
[##### ISSUE TYPE
 - backup/restore fail when Istio is activated
 
##### SUMMARY
we have an installation of AWX on the EKS platform also the Istio is activated on the namespace where AWX is deployed, the issue 

##### ENVIRONMENT
* AWX version: 0.14.0
* Operator version: 19
* Kubernetes version: 1.21
* AWX install method: EKS

##### AWX-OPERATOR LOGS
](https://github.com/ansible/awx-operator/pull/625/files#diff-4d238c40e041dc6999021a7fa71cbdbac0a9d0090baae0defb2747573751ccf6R86

##### ISSUE TYPE
 - backup/restore fail when Istio is activated
 
##### SUMMARY
we have an installation of AWX on the EKS platform also the Istio is activated on the namespace where AWX is deployed, the issue is when we create backups the next play is failing

https://github.com/ansible/awx-operator/blob/devel/roles/backup/tasks/postgres.yml#L95
because Istio is injecting a new container in pod and in the play was not specified the "container" option. 

##### ENVIRONMENT
* AWX version: 0.14.0
* Operator version: 19
* Kubernetes version: 1.21
* AWX install method: EKS

##### STEPS TO REPRODUCE

1 install Istio on kubernetes and add activate it where AWX is deployed
2 follow the documentation https://github.com/ansible/awx-operator/blob/devel/roles/backup/README.md
##### EXPECTED RESULTS

A succesful backup 

##### ACTUAL RESULTS

A failed backup

##### ADDITIONAL INFORMATION

To make compatibe the backup of AWX with istio is needed to add option "container" in every play where the module k8s_exec is used:
Ex.

- name: Create directory for backup
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-db-management"
    container: "{{ ansible_operator_meta.name }}-db-management"    
    command: >-
      mkdir -p {{ backup_dir }}

##### AWX-OPERATOR LOGS
![error-backup](https://user-images.githubusercontent.com/53397145/141463758-08fd6109-0504-46af-997a-79ab1f0fed0a.png)

**Comment by chrismeyersfsu** [comment]
Can you try asking your question on the AWX mailing list https://groups.google.com/g/awx-project ?

This deviates from our normal supported test path and we don't have expertise in this realm.
