### ISSUE TITLE
Openshift install still requires Cluster Admin privileges

### ISSUE THREAD

**Issue by Zype76** [ansible/tower-operator#664]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In the previous install process, openshift cluster admin privileges were required for AWX installations because of the dependency on bubblewrap (see https://github.com/ansible/awx/pull/3116 ). 

It seems that this new operator setup still requires cluster admin privileges for creating Custom Resource Definitions. The operator install for non cluster admins doc (https://docs.openshift.com/container-platform/4.7/operators/admin/olm-creating-policy.html) doesn't seem to provide a way to address that, as "A service account associated with an Operator group should never be granted privileges to write these resources.". 

##### Question:
Is there any future plan to reduce the permission requirements for installing AWX?
It seems that execution environments can address the previous sandboxing concern. It also looks like while openshift doesn't right now, kubernetes can support scoping custom resource definitions to namespaces.

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition

**Comment by shanemcd** [comment]
Hello. I think you might be misunderstanding what `scope: Namespaced` means. I just tried it out using the example you linked to:


```
$ kubectl create sa hello
```

```
$ cat role.yml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: full-control
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: full-control
  namespace: default
subjects:
- kind: User
  name: hello
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: full-control
  apiGroup: rbac.authorization.k8s.io
```

```
$ kubectl apply -f role.yml
role.rbac.authorization.k8s.io/full-control unchanged
rolebinding.rbac.authorization.k8s.io/full-control created
```

```
$ kubectl --as hello apply -f crd.yml -n default
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "crontabs.stable.example.com", Namespace: ""
from server for: "crd.yml": customresourcedefinitions.apiextensions.k8s.io "crontabs.stable.example.com" is forbidden: User "hello" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

See https://github.com/kubernetes/kubernetes/issues/65551#issuecomment-400909534 for more info.

In any case, yes, installing the operator requires a cluster admin. But once set up, normal users can install AWX within namespaces they have access to.

**Comment by tsaridas** [comment]
> In any case, yes, installing the operator requires a cluster admin. But once set up, normal users can install AWX within namespaces they have access to.

I'm curious if what you wrote is true currently and what permissions are required to have this configured so that there is a one time installation with admin and then users running the operator without issues and creating AWX instances.
