### ISSUE TITLE
Unable to connect to external Postgres DB

### ISSUE THREAD

**Issue by lindy63** [ansible/tower-operator#665]
##### ISSUE TYPE
 - General troubleshooting

##### SUMMARY
Unable to connect to external Postgres DB - (GCP Cloud SQL Private Instance) 

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0 
* Kubernetes version: 1.21.5-gke.1302 
* AWX install method: GKE
* Postgres: GCP Cloud SQL private instance (version 12)

##### STEPS TO REPRODUCE

I've been using and testing AWX/Operator  on GKE for sometime, and have many times deleted the AWX instance and then created a new one, and it has happily reconnected to the same Postgres Cloud SQL database, but I've now run into an issue that is no longer the case and it goes straight from Redis reporting the server is ready to the dreaded ***[wait-for-migrations] Waiting for database migrations*** and then stays stuck in that loop forever

This isn't when changing/upgrading Operator or AWX versions, just recreating another 19.4.0 AWX instance, from operator v0.14.0 

The bit that is baffling me is that I can't see ***any*** logon activity in Cloud SQL at all, not even a connection attempt

If I use an incorrect password/database name etc in the AWX secret, I can see the failed logon error in Cloud Logging from Cloud SQL when AWX tries to connect, and I can also connect to SQL from another pod on the same cluster, so I know connectivity is OK

I can also run psql on a Compute Engine instance and connect to the database OK, and it shows all the tables etc  (not that I really not what to do in psql when I get connected!)

I can create a new database (on the same Cloud SQL instance) and it works fine right away, and as I have backups to import it's not a major issue and more of an educational one, but I just wanted to know if there was any way to find out why AWX doesn't even appear to try and initiate a connection to the DB, or what logs I can look in for more info? ( I am sure it is trying to connect, I just can't see it! :-) )

##### EXPECTED RESULTS

new AWX instance should reconnect to existing Cloud SQL Postgres Database

##### ACTUAL RESULTS

AWX instance doesn't try to connect, but will on a new database on same Cloud SQL instance

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/61848016/142720917-9cf6be1a-84cc-488f-885c-2ed9bdc084bb.png)

**Comment by omargohan** [comment]
I had the same issue, but I was able to fix it by applying the awx postgres secrets first and making sure my postgres was running version 12.

I hope this helps.

**Comment by lindy63** [comment]
Thanks @omargohan , but yep, secret is always deployed first and the DB is running v12 (managed Cloud SQL instance) and I can connect it using psql as per above..

I've also checked the following, and reflect the same (correct) info specified in the secret
/etc/tower/conf.d/credentials.py
/etc/tower/SECRET_KEY

I wondered if there might be a way to increase logging on the Operator playbook output (as per below), or anywhere else it might be logged on the AWX/Operator side to say that it has tried (and failed) to connect to SQL, as don't see any connection attempts in SQL logs

![image](https://user-images.githubusercontent.com/61848016/142835715-0b9602bc-ddf7-415e-96b7-bc4cf4e16ba7.png)

**Comment by vrubiolo** [comment]
@lindy63 : thanks for reporting, this is interested to help in diagnosing such issues.
I see in the code+operator that there is some logic around the `no_log` boolean. From what I see, it might be to obscure sensitive things like crendentials in the logs but there might be more here (I have not tried to change it though).

**Comment by lindy63** [comment]
Hello @vrubiolo and thanks for the message!

I've just replaced every occurrence of ```no_log: true``` with ```no_log: false``` in the awx-operator files, then recreated the operator and redeployed AWX, but (despite getting very excited), it didn't actually show anything more around the database creation stages (same output as above)

I was wondering if the output is also restricted by the ```log-level: info``` as per below, but the only file I can find that references a log level is ```./roles/installer/templates/config.yaml.j2``` and that is already set to ```debug```

![image](https://user-images.githubusercontent.com/61848016/142852636-2b782037-7b49-40f7-9b03-8e6507f4aba6.png)

![image](https://user-images.githubusercontent.com/61848016/142853088-aae6770b-2ffe-4d80-a5b0-63b1f9d1448e.png)

**Comment by vrubiolo** [comment]
Hi @lindy63 , you're welcome!

I am glad you could try the setting out. I understand you checked and saw the boolean being set to `true` in the logs yet nothing coming out (your capture above did not show AFAIK).

Great find w.r.t the `log-level` variable. I also see the internal doc about the loggers integration mentions the internal logs as well (via https://github.com/ansible/awx/blob/devel/docs/logging_integration.md#awx-logs), maybe looking into `settings.LOG_AGGREGATOR_LOGGERS` is worth a try here. 

In particular I see https://github.com/ansible/awx/blob/devel/awx/conf/views.py#L175 which might mean some stuff is also sent via `rsyslogd` during operation (it seems to be checking the config file here). Not sure though, just a thought ...

**Comment by lindy63** [comment]
Thanks again @vrubiolo, it's really useful and something I will come back to .. unfortunately I am going to have to park this as I need to rebuild some stuff so will lose my SQL instance and the dodgy database, and not going to have time at the moment to dig deeper!

The fix for me as described above was to recreate the database and restore from AWX cli export

 Big thanks to everyone who develops the AWX Operator, it's really awesome :-)
