### ISSUE TITLE
Issue when 'make deploy' run 

### ISSUE THREAD

**Issue by Davidffry** [ansible/tower-operator#667]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: devel (after git checkout)
* Operator version: 0.15.0
* Kubernetes version: 1.21.5
* AWX install method: wsl with docker desktop for windows

##### STEPS TO REPRODUCE

```make deploy```

##### EXPECTED RESULTS

Execution

##### ACTUAL RESULTS
```
$  make deploy
make gen-resources | kubectl apply -f -
error: error validating "STDIN": error validating data: ValidationError(Namespace): unknown field "make[1]" in io.k8s.api.core.v1.Namespace; if you choose to ignore these errors, turn validation off with --validate=false
Makefile:87: recipe for target 'deploy' failed
make: *** [deploy] Error 1
```

##### ADDITIONAL INFORMATION

- One thing to change into the Makerfile : add `-k` to all curl because certificate issue.
- When rollback the commit : 782f97c42cc589419200bfccfd44c342ba010826
it seems to work, with other issue.

##### AWX-OPERATOR LOGS
No.

**Comment by syswipe** [comment]
I have the same problem, but I use k3s instead of k8s cluster. Any suggestion?

**Comment by jonathon2nd** [comment]
I get the same when I have devel checked-out. Try a tag, 0.15.0 works for me on a rancher managed k8s cluster, though I had to modify the makefile to include the kubeconfig.

**Comment by Davidffry** [comment]
Ok, I ll recheck that. Thanks

**Comment by syswipe** [comment]
i rolled back to 0.14.0 and all run well

**Comment by Davidffry** [comment]
I retest it from scratch (wsl with windows) is ok
I'll test it with k3s...

**Comment by Davidffry** [comment]
You're right, I close the issue. my bad ;-)
