### ISSUE TITLE
How do I know what version of ansible does the operator will use.

### ISSUE THREAD

**Issue by koshrf** [ansible/tower-operator#670]
Hi,

Is there is a table that describe what version of ansible will the operator install when deploying an AWX? I know that 0.11 will use ansible 2.12 for example, and I was thinking to upgrade some of my clusters, and I want an AWX with 2.9, but there is no documentation (that I'm aware of) that describe this kind of information and I end up just spinning an operator to findout what ansible it uses.

Thanks in advance.

**Comment by kdelee** [comment]
So there is the version of ansible that is _in the operator image_ and then there is the version of ansible in the AWX execution environment. These two are not necessarily the same. AFAIK the operator has ansible 2.9.z in it, based on the ansible-operator image we use
https://github.com/ansible/awx-operator/blob/8972cae1cc3dc680e8fc3c2db5fb27d1e497df97/Dockerfile#L1

and its pip  requirements seen here:  https://github.com/operator-framework/operator-sdk/blob/d3b2761afdb78f629a7eaf4461b0fb8ae3b02860/images/ansible-operator/Pipfile#L11


Meanwhile, the latest awx-ee  has the latest runner image : https://github.com/ansible/awx-ee/blob/24e267c3919e2d868c7107aeff0551b836506925/Containerfile#L1  at which point I lose the thread, but you could  do:

```
docker run -it quay.io/ansible/ansible-runner:latest ansible --version
```  which at this time shows  ansible being 2.11.z

**Comment by koshrf** [comment]
Thank you, I think that answer the question.
