### ISSUE TITLE
/bin/sh: kubectl: command not found make: *** [deploy] Error 127

### ISSUE THREAD

**Issue by ZacharyWallace** [ansible/tower-operator#678]
I receive the following error when attempting to execute `make deploy` as outlined in the readme, despite setting my alias also as outlined `alias kubectl="minikube kubectl --"`. 

`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}`

Is there a better installation guide than the Readme? Am I missing something else? Let me know if any further information is required.

Editing to add full output, apologies it isn't displaying new lines and treating it all as a single line. 

`$ make deploy
cd config/manager && /opt/awx/awx-operator/bin/kustomize edit set image controller=quay.io/ansible/awx-operator:0.15.0
cd config/default && /opt/awx/awx-operator/bin/kustomize edit set namespace my-namespace
/opt/awx/awx-operator/bin/kustomize build config/default | kubectl apply -f -
/bin/sh: kubectl: command not found
make: *** [deploy] Error 127`

**Comment by stuieordie** [comment]
Same issue here - running microk8s, not minikube

Error:
```
$ alias kubectl
alias kubectl='microk8s kubectl'

$ export NAMESPACE="default"
$ make deploy
cd config/manager && /home/mrstuar-a/awx-upgrade-20211206/awx-operator/bin/kustomize edit set image controller=quay.io/ansible/awx-operator:0.15.0
cd config/default && /home/mrstuar-a/awx-upgrade-20211206/awx-operator/bin/kustomize edit set namespace default
/home/mrstuar-a/awx-upgrade-20211206/awx-operator/bin/kustomize build config/default | kubectl apply -f -
/bin/sh: 1: kubectl: not found
make: *** [Makefile:82: deploy] Error 127
```

MicroK8s Version:
```
$ snap info microk8s
name:      microk8s
summary:   Kubernetes for workstations and appliances
publisher: Canonical✓
store-url: https://snapcraft.io/microk8s
<output omitted>
snap-id:      EaXqgt1lyCaxKaQCU349mlodBkDCXRcg
tracking:     1.21/stable
refresh-date: 11 days ago, at 22:51 EST
```

K8s version:
```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.7-3+7700880a5c71e2", GitCommit:"7700880a5c71e25c44491ef5c7d7fb30527d8337", GitTreeState:"clean", BuildDate:"2021-11-17T22:07:23Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.7-3+7700880a5c71e2", GitCommit:"7700880a5c71e25c44491ef5c7d7fb30527d8337", GitTreeState:"clean", BuildDate:"2021-11-17T22:02:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ZacharyWallace** [comment]
I was able to get around this by adding the alias in the Makefile in the 4 spots (on version 0.15.0) where kubectl was called. Not elegant but worked.
