### ISSUE TITLE
The right way to make changes to an existing deployment

### ISSUE THREAD

**Issue by syswipe** [ansible/tower-operator#680]
Hi, guys!
I have an installation of the awx-operator deployed in K3S. Now, I need to make some changes e.g. add additional environment options into the existing pod using _*_extra_env_. What is the recommended way to do this?

**Comment by vrubiolo** [comment]
Hi, I am interested in doing so too, to enable `AWX_CLEANUP_PATHS`, cf https://groups.google.com/g/awx-project/c/XhY-uDSxDIo

Edit: I would expect that redeploying the operator w/ that setting turned on would do it, but I don't know how far the CRD goes w.r.t to the K8S control loop i.e. is it also watching the environment variables as well.

**Comment by shanemcd** [comment]
Hello,

This issue tracker is for tracking feature enhancements and bugs.

If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on https://libera.chat/
https://groups.google.com/forum/#!forum/awx-project
