### ISSUE TITLE
Find default AWX Version in AWX operator

### ISSUE THREAD

**Issue by derhoeppi** [ansible/tower-operator#682]
My initial problem was described in https://github.com/ansible/awx-operator/issues/655

Now i find a hint in https://github.com/ansible/awx-operator/blob/57aa585a2e041337ce88f4e09a7af543ef0dfc68/roles/installer/defaults/main.yml#L111 to overwrite the awx verion. My question is: where is the DEFAULT_AWX_VERSION described? Sure i can overwrite this but i'm searching for the default definition of this fact.

**Comment by DeLoWaN** [comment]
Actually a subsequent question is how to upgrade AWX since its version release is different than the operator ones ?

Let's say AWX release a 19.6 version (currently it's 19.5). How to upgrade to the next version ? What action on the operator it implies ?

And if ever I want to upgrade to something that is not `latest`, how can I overwrite `DEFAULT_AWX_VERSION` in the k8s manifest ?

Thank you.

**Comment by shanemcd** [comment]
This is injected whenever we stage the release, which can be done via the awx workflow or one specific to the operator

https://github.com/ansible/awx/blob/devel/.github/workflows/stage.yml#L78

https://github.com/ansible/awx-operator/blob/devel/.github/workflows/stage.yml#L63

**Comment by cnukwas** [comment]
> This is injected whenever we stage the release, which can be done via the awx workflow or one specific to the operator
> 
> https://github.com/ansible/awx/blob/devel/.github/workflows/stage.yml#L78
> 
> https://github.com/ansible/awx-operator/blob/devel/.github/workflows/stage.yml#L63

@shanemcd , I was looking 0.18 operator files and don't see a specific AWX version in there. Any idea how DEFAULT_AWX_VERSION env variable is set during 'make deploy' of the operator?

Thanks

**Comment by kurokobo** [comment]
@cnukwas 
The one of the simplest way to confirm `DEFAULT_AWX_VERSION` is:

```bash
$ kubectl run -i --rm --restart=Never awx-operator --image=quay.io/ansible/awx-operator:0.18.0 --command -- env | grep DEFAULT_AWX_VERSION
DEFAULT_AWX_VERSION=20.0.1
```

You can also dig into the log of the `staging` workflow:
<https://github.com/ansible/awx/runs/5471221182?check_suite_focus=true#step:11:8>

**Comment by adpavlov** [comment]
> 

I think I found easy way to overwrite DEFAULT_AWX_VERSION env variable that comes along with image build.
There is env section in this file:

https://github.com/ansible/awx-operator/blob/3ac0232e89e3fc5a1aa5358ad84d54bb3957d982/config/manager/manager.yaml#L34

Adding below section allows to override env value in container:
```
          env:			
            - name: DEFAULT_AWX_VERSION
              value: 21.0.0	
```
