### ISSUE TITLE
ingress_path will never work

### ISSUE THREAD

**Issue by jpic** [ansible/tower-operator#684]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Currently, the `ingress_path` setting allows to deploy AWX in a sub path such as `/foo` instead of `/`.

However, [AWX is unable to serve from anywhere else than `/` because it builds an index.html that has `/static/` links generated by webpack, NOT by Django, as such, does not respect STATIC_URL](https://github.com/ansible/awx/issues/631#issuecomment-987970351).

As such, the `ingress_path` setting will never work before ansible/awx#631 is fixed.

##### ENVIRONMENT

* AWX version: Any
* Operator version: Any
* Kubernetes version: Any
* AWX install method: Any

##### STEPS TO REPRODUCE

Set ingress_path to anything that is not `/`, such as `/foo`

##### EXPECTED RESULTS

AWX loading static from `/foo/static/main.xxx.js`

##### ACTUAL RESULTS

AWX failing to load static from `/static/main.xxx.js`

##### ADDITIONAL INFORMATION

AWX issue that has been closed but should probably reopen: https://github.com/ansible/awx/issues/631#issuecomment-987970351

Or, remove ingress_path feature because it can't work.

**Comment by shanemcd** [comment]
This will be addressed by https://github.com/ansible/awx-operator/pull/652 and https://github.com/ansible/awx/pull/11342

**Comment by shanemcd** [comment]
PRs have been merged. This will be in the next release, or you can build from devel in the meantime.
