### ISSUE TITLE
Create alternatives to Nodeport for ingress

### ISSUE THREAD

**Issue by chadmf** [ansible/tower-operator#687]
##### ISSUE TYPE
 - Bug Report/Feature request

##### SUMMARY
Currently the Kubernetes operator uses nodeport to allow ingress into the cluster which opens up a security hole at the cluster level.
If we could change the ingress to use something like Metal LB to manage this it would remove the security issues
##### ENVIRONMENT
* AWX version: AAP 2.1
* Operator version: stable-2.1
* Kubernetes version:  1.22
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
Openshift using argo https://github.com/redhat-cop/gitops-catalog/
##### STEPS TO REPRODUCE

Service is currently created via:
https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/service.yaml.j2 

##### EXPECTED RESULTS

Change to use a more secure ingress via a kubernetes route, or metallb

##### ACTUAL RESULTS

N/A

##### ADDITIONAL INFORMATION
Removed private jira ticket

**Comment by shanemcd** [comment]
Based on the [documentation](https://metallb.universe.tf/usage/), it looks like this is already possible. You need to set `service_type` to `LoadBalancer` and add an annotation with `loadbalancer_annotations`.

Also, please do not link to things that are not publicly visible in an open source repo.

**Comment by chadmf** [comment]
In order to make sure we are providing a secure solution that isnt opening random ports on the cluster should we consider making someting like metallb the default vs an option?
