### ISSUE TITLE
CI Checks not catching some fatal bugs 

### ISSUE THREAD

**Issue by kdelee** [ansible/tower-operator#689]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Although in AWX there exists a workflow that executes the molecule tests here (https://github.com/ansible/awx/blob/9a930cbd95379eaf90b9804dbd6c034ad1d58a8c/.github/workflows/ci.yml#L203-L213) which appear to deploy the operator and then an AWX where it runs a Demo Job (https://github.com/ansible/awx-operator/blob/8972cae1cc3dc680e8fc3c2db5fb27d1e497df97/molecule/default/tasks/awx_test.yml#L47-L54), this process was unable to catch a "fatal" bug in the "production" awx images built (https://github.com/ansible/awx/pull/11428)

I'd like to identify exactly _why_ this is the case (are we using the k8s_dev built images? this would have gotten past the bug in question) and figure out if we can fix it.

##### ENVIRONMENT
* AWX version: X.Y.Z
* Operator version: X.Y.Z
* Kubernetes version: 
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker

##### STEPS TO REPRODUCE

CI Checks did not catch this bug for some time

##### EXPECTED RESULTS

Images built for k8s using https://github.com/ansible/awx/blob/devel/docs/build_awx_image.md#build--push-image work and this is what we use to test

##### ACTUAL RESULTS

Images built using https://github.com/ansible/awx/blob/devel/docs/build_awx_image.md#build--push-image had a bug that made the app non-functional, but our CI did not catch it.

**Comment by shanemcd** [comment]
I am not exactly sure where things went wrong for you, but `awx-manage` is created in the "official" images when we[ install the application via the sdist](https://github.com/ansible/awx/blob/696c0b00550c9092b39e4d39e2c5c82fc6554a47/setup.py#L146). I just reverted the commit, built the image, and it's there. Also, why would we copy something with `docker-compose` in the pathname into the non-development image? We need to revert that commit.
