### ISSUE TITLE
Suggestion: improve operator capabilities

### ISSUE THREAD

**Issue by absynth76** [ansible/tower-operator#700]
On top of installing a product, an operator should be able to support the day 2 operations, backup and restore is of course part of it but going to configuration is a must have. 

In the awx case, there is already a good amount of ansible roles available in the redhat CoP project and more specifically here:
https://github.com/redhat-cop/infra-ansible/tree/main/roles/ansible/tower

It would be interesting to integrate those or part of it within the operator, to create some objects (crd) that would corresponds to the different manage-* roles would be a good starts I think.

**Comment by AlanCoding** [comment]
@jamesmarshall24 we looked at this in the bug scrub but determined you would be the relevant person to triage.

**Comment by shanemcd** [comment]
I see you have opened the same issue over in https://github.com/ansible/awx-resource-operator/issues/62... Closing this in favor of that one.
