### ISSUE TITLE
Add yaml only option to Makefile

### ISSUE THREAD

**Issue by joshcorr** [ansible/tower-operator#704]
##### SUMMARY

Currently the install instructions for this operator require direct access to the cluster in order to deploy using `make deploy`
My current mechanism of deploying this operator requires a PR to branch, so I need to include the YAML in my own repo before deploying to the cluster. 

Could there be an additional make option that merely returns the yaml instead of piping to `kubectl apply -f -` ? I have been manually editing the make file to do this, but would be easier to include in the repo. 

##### ENVIRONMENT
* AWX version: 19.5.0
* Operator version: 0.15.0
* Kubernetes version: ?
* AWX install method: openshift, okd.

##### STEPS TO REPRODUCE

`make deploy`

##### EXPECTED RESULTS

`make build` (or some other name)
Does the same as above without applying directly to the cluster.

**Comment by DomPolizzi** [comment]
You could make Bash scripts that are called for by a YAML file. 
EXAMPLE:
pre-setup.sh

```
#!/bin/sh
echo "This script only needs to be ran to ensure the package MAKE is added to install the AWX Operator"

read -r -p "Are you sure you want to run? [Y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        apt-get update -y || exit 1
        #Add make for the Operator
        apt-get install -y --reinstall build-essential || exit 1
        ;;
    *)
        exit 0
        ;;
esac
```


setup.sh:

```
#!/bin/sh
export AWXOPVERSION="0.16.0"
export NAMESPACE=kube-awx-dev

rm -rf awx-operator 2> /dev/null 

git clone https://github.com/ansible/awx-operator.git

cd awx-operator || exit

git checkout $AWXOPVERSION

# Execute Makefile
make deploy || exit 1

```

Then call for these in a YAML

edits: Formatting

**Comment by shanemcd** [comment]
We added something like this in https://github.com/ansible/awx-operator/pull/627
