### ISSUE TITLE
Issue deploying on Ubuntu running on Raspberry Pi 4 8GB

### ISSUE THREAD

**Issue by straes** [ansible/tower-operator#708]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Issue deploying on Ubuntu running on Raspberry Pi 4 8GB

##### ENVIRONMENT
* AWX version: 0.15.0
* Operator version: Ubuntu Server 21.10
* Kubernetes version: MicroK8s

##### STEPS TO REPRODUCE
#Starting fresh if you did not select to install microk8s from the OS installer
sudo snap install microk8s --classic
sudo usermod -a -G microk8s $USER
sudo chown -f -R $USER ~/.kube
newgrp microk8s

#Enabling DNS and Storage modules for MicroK8s
microk8s enable storage dns

#Alias the kubectl command
echo "alias kubectl='microk8s.kubectl'" >> ~/.bash_aliases && source ~/.bash_aliases

#Symlink the microk8s.kubectl bin to kubectl. Typically you just
#alias this, however the AWX-Operator make step fails unless you do this
sudo ln -s /snap/bin/microk8s.kubectl /snap/bin/kubectl
sudo ln -s /snap/microk8s /snap/kubectl
sudo ln -s /var/lib/snapd/snaps/microk8s_<variable>.snap /var/lib/snapd/snaps/kubectl_<variable>.sna

#By default Ubuntu Server does not include the make package so let's install it
sudo apt install make
	
#Clone awx-operator repo and change the HEAD to 0.15.0
git clone https://github.com/ansible/awx-operator.git
cd awx-operator
git checkout 0.15.0

#Modified Makefile line per issue 628
-ARCH := $(shell uname -m | sed 's/x86_64/amd64/')
+ARCH := $(shell uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')

export NAMESPACE=awx-namespace
make deploy

##### EXPECTED RESULTS
Successful deployment

kubectl get pod
NAME                                               READY   STATUS    RESTARTS   AGE
awx-operator-controller-manager-647f4c5c7d-th8vg   2/2     Running   0          108m
awx-postgres-0                                     1/1     Running   0          107m
awx-7d4f664875-jl5r7                               4/4     Running   0          107m

##### ACTUAL RESULTS

ubuntu@ubuntu:~/awx-operator$ make deploy
cd config/manager && /home/ubuntu/awx-operator/bin/kustomize edit set image controller=quay.io/ansible/awx-operator:0.15.0
cd config/default && /home/ubuntu/awx-operator/bin/kustomize edit set namespace awx
/home/ubuntu/awx-operator/bin/kustomize build config/default | kubectl apply -f -
namespace/awx created
customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com unchanged
customresourcedefinition.apiextensions.k8s.io/awxrestores.awx.ansible.com unchanged
customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com unchanged
serviceaccount/awx-operator-controller-manager created
role.rbac.authorization.k8s.io/awx-operator-awx-manager-role created
role.rbac.authorization.k8s.io/awx-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/awx-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/awx-operator-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/awx-operator-awx-manager-rolebinding created
rolebinding.rbac.authorization.k8s.io/awx-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/awx-operator-proxy-rolebinding configured
configmap/awx-operator-awx-manager-config created
service/awx-operator-controller-manager-metrics-service created
deployment.apps/awx-operator-controller-manager created
ubuntu@ubuntu:~/awx-operator$ kubectl get pod
NAME                                               READY   STATUS             RESTARTS       AGE
awx-operator-controller-manager-647f4c5c7d-v7zwc   1/2     CrashLoopBackOff   14 (21s ago)   34m
ubuntu@ubuntu:~/awx-operator$ kubectl logs -f deployments/awx-operator-controller-manager -c awx-manager
standard_init_linux.go:228: exec user process caused: exec format error

##### ADDITIONAL INFORMATION
Credit https://jameysteinmann.com/ansible-awx-operator-on-ubuntu-with-microk8s/
https://github.com/ansible/awx-operator/issues/628

##### AWX-OPERATOR LOGS
 kubectl logs -f deployments/awx-operator-controller-manager -c awx-manager
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by kurokobo** [comment]
> exec user process caused: exec format error

This is the typical error when running AMD64-based binary on ARM platform. Currently there seems to be no pre-built container images of AWX and AWX Operator for ARM, therefore you have to build your own images runnable on ARM, I think.

**Comment by straes** [comment]
@geerlingguy by chance, do you know if there is already an effort in development, possibly to permit AWX to run on the upcoming turing pi2?

**Comment by geerlingguy** [comment]
@straes - No, haven't seen anything for it.

**Comment by ffirg** [comment]
This isn't something we're going to provide at this time, but welcome PRs from the community.
