### ISSUE TITLE
Need help on awx deployment with external postgress db

### ISSUE THREAD

**Issue by gullapallir** [ansible/tower-operator#713]
We need help on awx deployment with external postgress db, could someone guide us with the proper approach.

Planning to go with Minikube and AWX latest version

minikube version: v1.24.0
AWX operator version: 0.15.0 (https://api.github.com/repos/ansible/awx-operator/releases/latest)

Please note we followed inbuild postgress pod and able to login to AWX UI but we want to go with External postgres DB only while installation itself.

**Comment by ffirg** [comment]
Please use https://groups.google.com/g/awx-project for such assistance. This is not a support forum.
