### ISSUE TITLE
Awx ldap authentication with openldap

### ISSUE THREAD

**Issue by sysnasri** [ansible/tower-operator#714]
Hi, I am pretty sure with the same details in the past I could use ldap authentication but with a new awx installation it does not seem to be working. 

**LDAP Bind DN**
``` cn=admin,dc=ldap,dc=modirserver,dc=com ``` 

**LDAP User DN Template**
``` uid=%(user)s,OU=People,DC=ldap,DC=modirserver,DC=com ```

**LDAP Group Type**
```  MemberDNGroupType ```
 

I only set these two settings , this environment is testing.  

I have tried several settings but was not successful.

**Comment by longns1** [comment]
Hi, You should turn on the debug logs for LDAP as [here](https://docs.ansible.com/ansible-tower/latest/html/administration/ldap_auth.html#enabling-logging-for-ldap) to see what's the issue.

**Comment by ffirg** [comment]
To help troubleshoot this issue I suggest you try https://groups.google.com/g/awx-project
If you believe this to be a bug after more extensive testing, please raise another issue with detailed information (there is nothing to work with here). Thanks.
