### ISSUE TITLE
Allow installation of old versions of AWX with operator

### ISSUE THREAD

**Issue by jontow** [ansible/tower-operator#724]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Attempting to install old versions (basically any from dockerhub, so < 18.0.0 ?) fails with a non-obvious KeyError.

##### ENVIRONMENT
* AWX version: 14.0.0
* Operator version: latest/devel
* Kubernetes version: minikube 1.24.0
* AWX install method: awx-operator on minikube

##### STEPS TO REPRODUCE

Per awx-operator README, use "make deploy", then apply awx-demo.yml with the following lines added to spec to override image source to dockerhub and target AWX version:

```
spec:
  image: ansible/awx
  image_version: 14.0.0
```

After awx-operator-controller-manager completes a run, you have a mostly complete, but non-working AWX 14.0.0 install.  "awx-manage" script is unable to run migrations (or anything else) due to a KeyError regarding a nonexistent 'guid' logging filter, added in later AWX version but unconditionally included in configuration by operator.

##### EXPECTED RESULTS

A working AWX 14.0.0 installation.

##### ACTUAL RESULTS

awx-manage unable to run initial migrations, database is never properly initialized, awx-web displays "Internal Server Error"

##### ADDITIONAL INFORMATION

See also:
* https://github.com/ansible/awx-operator/issues/139
* https://github.com/ansible/awx/issues/9421
* https://github.com/ansible/awx/issues/9419

Whether or not the included patch is a correct solution is debatable, but it is a working patch for me.  I'm including it because, even if not accepted by the project, it may help someone like me who just needs to reproduce an environment for upgrade reasons, and wishes to use awx-operator for the entire lifecycle:

```
diff --git a/roles/installer/templates/config.yaml.j2 b/roles/installer/templates/config.yaml.j2
index 903994d..7100fa4 100644
--- a/roles/installer/templates/config.yaml.j2
+++ b/roles/installer/templates/config.yaml.j2
@@ -65,7 +65,9 @@ data:
         '()': 'logging.StreamHandler',
         'level': 'DEBUG',
         'formatter': 'simple',
+{% if image_version == 'latest' or (image_version[:2] | int) > 17 %}
         'filters': ['guid'],
+{% endif %}
     }
     
     LOGGING['loggers']['django.request']['handlers'] = ['console']
```

After applying the above patch, "make docker-build", tag the resulting image as your own and push to accessible place, then "IMG=customplace make deploy" to try again.

**Comment by shanemcd** [comment]
The AWX Operator did not come into existence until AWX 18. The architecture fundamentally changed at that point, so what you are asking for is not possible without basically rewriting the entire thing. If you want to create your own operator for older versions of AWX, feel free, but this isn't something we're going to do.
