### ISSUE TITLE
AWX operator should not set app.kubernetes.io/managed-by label on AWX resources

### ISSUE THREAD

**Issue by mkjpryor** [ansible/tower-operator#756]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The AWX operator is incorrectly (IMHO) patching the labels of `AWX` resources to have `app.kubernetes.io/managed-by: awx-operator`. This label is supposed to indicate who is responsible for creating, updating and deleting the resource. The AWX operator does not do this - it reacts to changes in the `AWX` resource made by someone/something else, hence it should not change the `app.kubernetes.io/managed-by` label on the `AWX` resource.

It is correct for the AWX operator to set `app.kubernetes.io/managed-by: awx-operator` on the resources that it creates, e.g. `Deployment`s.

My use case, which is currently being prevented by this bug, is that I have an `AWX` resource as part of a Helm chart. Helm sets the `app.kubernetes.io/managed-by` label to `Helm`, and refuses to manage the resource once that label has been changed.

##### ENVIRONMENT
* AWX version: Default for 0.15.0
* Operator version: 0.15.0
* Kubernetes version: 1.22
* AWX install method: k3s

##### STEPS TO REPRODUCE

Make an AWX resource with the `app.kubernetes.io/managed-by` set to something other than `awx-operator`:

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: my-awx
  labels:
    app.kubernetes.io/managed-by: manual
```

##### EXPECTED RESULTS

That the label `app.kubernetes.io/managed-by` would not change.

##### ACTUAL RESULTS

The label `app.kubernetes.io/managed-by` is set to `awx-operator`.

##### ADDITIONAL INFORMATION

N/A

##### AWX-OPERATOR LOGS

Not relevant.

**Comment by mkjpryor** [comment]
At the very least, the AWX operator should not override labels that already exist, even if it still wants to set them when they are not present.

**Comment by mkjpryor** [comment]
I believe that this is the relevant code - https://github.com/ansible/awx-operator/blob/ebe5d1e2f4afd7fd329c18420947ff5840670293/roles/installer/tasks/main.yml#L2

**Comment by shanemcd** [comment]
IIRC, OpenShift uses this label to generate a helpful link in the OCP UI. I dont think we can do this without creating a worse experience for those users.

**Comment by mkjpryor** [comment]
@shanemcd 

Can we at least change the behaviour so that the label is not overridden if it already exists?

**Comment by mkjpryor** [comment]
Because this behaviour makes it _impossible_ to create AWX instances as part of a Helm chart.

**Comment by mkjpryor** [comment]
If OpenShift wants the label for something, shouldn’t the thing that creates the AWX instance be adding it? That seems like the correct use of the `managed-by` label. The AWX operator is not managing the AWX instance, so it should not be adding that label to them (IMHO). But it is managing components on behalf of the AWX instances, e.g. deployments and secrets, and it should add the label to those.
