### ISSUE TITLE
Has awx operator been replaced by AAP operator in OpenShift distros?

### ISSUE THREAD

**Issue by piyat** [ansible/tower-operator#759]
##### ISSUE TYPE
- Can't upgrade OCP 4.8.24 -> 4.9.x because "ClusterServiceVersions blocking cluster upgrade: open-cluster-management/awx-resource-operator.v0.1.1 is incompatible with OpenShift minor versions greater than 4.8"

##### SUMMARY
- With v0.1.1 of AWX operator installed (the latest version available in OLM), I can't upgrade my cluster to 4.9.

##### ENVIRONMENT
* Operator version: 0.1.1
* Kubernetes version: v1.21.6+c180a7c
* AWX install method: openshift

##### STEPS TO REPRODUCE

Install awx operator in 4.8.x
Navigate to cluster settings -> ClusterOperators

ClusterOperator: operator-lifecycle-manager should be in a "cannot update" state with the message printed above.

<br class="Apple-interchange-newline">

##### EXPECTED RESULTS

Cluster could be upgraded.

##### ACTUAL RESULTS

Cluster can't be upgraded.

##### ADDITIONAL INFORMATION

In a 4.9.x cluster, the awx-operator is not available for installation. The Ansible Automation Platform operator is available. Has awx-operator been deprecated in favour of AAP?

**Comment by shanemcd** [comment]
`0.1.1` is not a version of the operator that we ever released. Can you double check and confirm what you are actually using?

**Comment by piyat** [comment]
Hey @shanemcd - here's what I see, am I misunderstanding?

![ 2022-01-27 at 14 02 13](https://user-images.githubusercontent.com/33325022/151374155-02d9a518-1b68-40c2-a0b1-b83d3c708cf8.png)

**Comment by piyat** [comment]
Ah - silly me, I'm in the wrong place.. apologies!
