### ISSUE TITLE
Unable to sync azure devops git towards awx

### ISSUE THREAD

**Issue by tn5134** [ansible/tower-operator#764]
**ISSUE TYPE**
Issue Report
**SUMMARY**
Error while trying to sync repo from azure devops towards awx

**ENVIRONMENT**
AWX version: 19.5.0
Operator version: 0.15
Kubernetes version: 1.20.11
AWX install method: make deploy(AWX is installed on K8S)
**STEPS TO REPRODUCE**
Start the sync process
**EXPECTED RESULTS**
Sync process runs successfully

**ACTUAL RESULTS**
Sync gives a timeout error

**AWX-OPERATOR LOGS**
PLAY [Update source tree if necessary] *****************************************
TASK [update project using git] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote 'https://$encrypted$:$encrypted$@gemisrocs.visualstudio.com/gemisrocs/_git/AnsiblePlaybooks' -h refs/heads/Production", "msg": "fatal: unable to access 'https://gemisrocs.visualstudio.com/gemisrocs/_git/AnsiblePlaybooks/': Failed to connect to gemisrocs.visualstudio.com port 443: Connection timed out", "rc": 128, "stderr": "fatal: unable to access 'https://gemisrocs.visualstudio.com/gemisrocs/_git/AnsiblePlaybooks/': Failed to connect to gemisrocs.visualstudio.com port 443: Connection timed out\n", "stderr_lines": ["fatal: unable to access 'https://gemisrocs.visualstudio.com/gemisrocs/_git/AnsiblePlaybooks/': Failed to connect to gemisrocs.visualstudio.com port 443: Connection timed out"], "stdout": "", "stdout_lines": []}

Doing a git clone from the container (task & web) itself is working fine with the credentials configured on the GUI of AWX.
I added our proxy in the awx-install.yml for http_proxy & https_proxy.

**Comment by shanemcd** [comment]
The project updates happen in the control plane ee. I do not currently have the cycles to help debug this, but hopefully it points you in the right direction.

**Comment by tn5134** [comment]
> The project updates happen in the control plane ee. I do not currently have the cycles to help debug this, but hopefully it points you in the right direction.

Thank you so much! Putting the proxy settings also in the ee container fixed my issue. :)
