### ISSUE TITLE
AWX Operator make deploy [Makefile:89: deploy] Error 127

### ISSUE THREAD

**Issue by mihoos** [ansible/tower-operator#765]
Hello, 

I'm trying to make deploy with current version (devel) and 0.16.0 of AWX Operator on K8s cluster. 
Following official install guide. 

For example: 
$ git clone https://github.com/ansible/awx-operator.git
$ export NAMESPACE=my-namespace

ubuntu@admin-ci-awx-k8s3:~/AWXOperator/awx-operator$ make deploy
/bin/sh: 1: kubectl: not found
make: *** [Makefile:89: deploy] Error 127

Same issue when: 
$ git clone -b 0.16.0 https://github.com/ansible/awx-operator.git

**Comment by DomPolizzi** [comment]
try this on for size:
```
#set AWX Operator Version and the Namespace
export AWXOPVERSION="0.16.0"
export NAMESPACE=my-namespace

rm -rf awx-operator 2> /dev/null 

# clone, enter, and checkout the latest AWX Operator version
git clone https://github.com/ansible/awx-operator.git

cd awx-operator || exit

git checkout $AWXOPVERSION

# Execute Makefile
make deploy || exit 1
```

**Comment by Colyn1337** [comment]
By chance did you forget to set your alias to minikube?  Assuming you're using minikube.

alias kubectl="minikube kubectl --"

**Comment by superteece** [comment]
I am have the same issue as OP.

I've tried DomPolizzi's steps and I've verified that I have the alias set.

**Comment by mihoos** [comment]
> By chance did you forget to set your alias to minikube? Assuming you're using minikube.
> 
> alias kubectl="minikube kubectl --"

I'm using 3 node K8s cluster.

**Comment by mihoos** [comment]
@DomPolizzi I did try your steps but I get the same error **with version 0.16.0**. 

ubuntu@admin-ci-awx-k8s3:~/AWXOperator/awx-operator$ make deploy
/bin/sh: 1: kubectl: not found
make: *** [Makefile:89: deploy] Error 127

**With version 0.15.0** I get error like below:
ubuntu@admin-ci-awx-k8s3:~/AWXOperator/awx-operator$ make deploy
cd config/manager && /home/ubuntu/AWXOperator/awx-operator/bin/kustomize edit set image controller=quay.io/ansible/awx-operator:0.15.0
cd config/default && /home/ubuntu/AWXOperator/awx-operator/bin/kustomize edit set namespace my-namespace
/home/ubuntu/AWXOperator/awx-operator/bin/kustomize build config/default | kubectl apply -f -
/bin/sh: 1: kubectl: not found
make: *** [Makefile:82: deploy] Error 127

**With version 0.14.0** I get error like below:
ubuntu@admin-ci-awx-k8s3:~/AWXOperator/awx-operator$ make deploy
cd config/manager && /home/ubuntu/AWXOperator/awx-operator/bin/kustomize edit set image controller=quay.io/ansible/awx-operator:0.14.0
cd config/default && /home/ubuntu/AWXOperator/awx-operator/bin/kustomize edit set namespace my-namespace
/home/ubuntu/AWXOperator/awx-operator/bin/kustomize build config/default | kubectl apply -f -
/bin/sh: 1: kubectl: not found
make: *** [Makefile:82: deploy] Error 127

**With version 0.13.0** I get error like below:
ubuntu@admin-ci-awx-k8s3:~/AWXOperator/awx-operator$ make deploy
make: Nothing to be done for 'deploy'.

**Comment by superteece** [comment]
Here's the verbose version of the error:
```
make deploy --trace                                  
Makefile:102: target 'kustomize' does not exist
{ \
set -e ;\
mkdir -p /home/tc/projects/awx-operator/bin/ ;\
curl -sSLo - https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.8.7/kustomize_v3.8.7_linux_amd64.tar.gz | \
tar xzf - -C bin/ ;\
}
Makefile:87: update target 'deploy' due to: kustomize
cd config/manager && /home/tc/projects/awx-operator/bin/kustomize edit set image controller=quay.io/ansible/awx-operator:0.16.0
cd config/default && /home/tc/projects/awx-operator/bin/kustomize edit set namespace my-namespace
/home/tc/projects/awx-operator/bin/kustomize build config/default | kubectl apply -f -
/bin/sh: kubectl: command not found
make: *** [Makefile:89: deploy] Error 127
```

My alias:
```
which kubectl                                                                                                                                                       2 ↵
kubectl='minikube kubectl --'
	/usr/bin/minikube
```

**New Info**
It's probably no surprise but installing kubectl resolves the issue. But that isn't a solution whatever is causing the error when following the published instructions.

**Comment by mihoos** [comment]
Ok, we were able to resolve this issue. 
In my case fix is to create bash script in **/usr/local/bin/** named **kubectl** like this:
<pre>
#!/bin/bash
args="$@"
microk8s kubectl $args
</pre>
Change permissions to this script by:
**chmod 755 /usr/local/bin/kubectl**

Result of make deploy (with AWX Operator version 0.16.0): 
<pre>
root@admin-ci-awx-k8s3:/home/ubuntu/AWXOperator/awx-operator# make deploy
namespace/my-namespace created
customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com created
customresourcedefinition.apiextensions.k8s.io/awxrestores.awx.ansible.com created
customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com created
serviceaccount/awx-operator-controller-manager created
role.rbac.authorization.k8s.io/awx-operator-awx-manager-role created
role.rbac.authorization.k8s.io/awx-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/awx-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/awx-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/awx-operator-awx-manager-rolebinding created
rolebinding.rbac.authorization.k8s.io/awx-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/awx-operator-proxy-rolebinding created
configmap/awx-operator-awx-manager-config created
service/awx-operator-controller-manager-metrics-service created
deployment.apps/awx-operator-controller-manager created
</pre>
<pre>
root@admin-ci-awx-k8s3:/home/ubuntu/AWXOperator/awx-operator# kubectl get pods -n my-namespace
NAME                                               READY   STATUS    RESTARTS   AGE
awx-operator-controller-manager-7f56f8b69c-6sskn   2/2     Running   0          3m5s
</pre>
