### ISSUE TITLE
Do not delete already existing namespaces with make undeploy

### ISSUE THREAD

**Issue by luhahn** [ansible/tower-operator#771]
In Version 0.16.0 make is required, which is fine. 
However the operator does seem to ignore resources, which are deployed in the different namespaces than the operator himself.

For example:

Operator is deployed into a namespace called "awx-operator".
I now want AWX to be deployed into a namespace called "services".
-> The operator does nothing and ignores the deployed ressources. That was different back in 0.12.0

However, i can work with this and deploy the operator into the services namespace. -> Everything gets deployed as expected.

Until i call the undeploy target in the makefile, which will now delete the entire
"services" namespace including all other pods running in that namespace. 

Is there a flag to disable the namespace deletion or something like that?

That behaviour is pretty destructive :D

**Comment by shanemcd** [comment]
That part of the Makefile comes from the scaffolding generated by the [operator-sdk](https://github.com/operator-framework/operator-sdk). I would encourage you to ask them for that functionality. This is not something we will prioritize on our end, at least any time soon.
