### ISSUE TITLE
upgrade guide

### ISSUE THREAD

**Issue by thedavidwhiteside** [ansible/tower-operator#78]
It would be helpful to have a guide for upgrading the installations after the initial deployment.

**Comment by kapilkumartrivedi** [comment]
i realized it half way. @thedavidwhiteside were you able to deploy the awx using the operator? i am new and got confused about how the secrets are to be passed...

**Comment by thedavidwhiteside** [comment]
I was able to deploy using the operator, but ran into issues when I upgraded the AWX version.  Currently just staying on the older version of AWX for now until I have time to work through the issues.

**Comment by keyz182** [comment]
We need to upgrade our deployment (15.0.0) as we're running into a bug that's been fixed in a newer version (17.1.0). Is there any path to upgrade?

**Comment by deztin** [comment]
I was able to edit the my-awx.yml to include:

spec:  
  tower_image: ansible/awx:17.1.0
  tower_image_pull_policy: Always

kubectl delete -f my-awx.yml
kubectl apply -f my-awx.yml

**Comment by keyz182** [comment]
I was finally able to do it. I needed to ssh into one of the containers and run `awx-manage migrate --noinput`. There was a migration in 15.0.x > 16.0.0 that wasn't being run for some reason.	I also needed to pin the postgres db to 10.

**Comment by tchellomello** [comment]
Upgrades should be automatically whenever the `awx-operator` gets upgraded. Please note as the only supported AWX version is the one shipped with the current `awx-operator` version as explained at https://github.com/ansible/awx-operator#deploying-a-specific-version-of-awx 

Closing this for now since it is already present in the `README`

**Comment by eselvam** [comment]
Hi All,

I try to do the upgrade as per readme however it is not working as expected.  The operator get updated however not the awx version.

I am doing upgrade from 19.1 to 19.3

Current version: ansible/awx:19.1.0,quay.io/ansible/awx-ee:0.2.0
Current operator: 0.13.0

**Comment by DaDenniX** [comment]
Hey, same for me.
Upgrading like it is said in the README doesn't help.
After upgrading awx-operator, the awx instance stays the same (upgrading from 19.5.0 to 20.0.0).

What I did was:
$ git pull https://github.com/ansible/awx-operator 0.17.0
From https://github.com/ansible/awx-operator
 * tag               0.17.0     -> FETCH_HEAD
Already up to date.

$ make deploy
namespace/awx unchanged
customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com unchanged
customresourcedefinition.apiextensions.k8s.io/awxrestores.awx.ansible.com unchanged
customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com configured
serviceaccount/awx-operator-controller-manager unchanged
role.rbac.authorization.k8s.io/awx-operator-awx-manager-role configured
role.rbac.authorization.k8s.io/awx-operator-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/awx-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/awx-operator-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/awx-operator-awx-manager-rolebinding unchanged
rolebinding.rbac.authorization.k8s.io/awx-operator-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/awx-operator-proxy-rolebinding unchanged
configmap/awx-operator-awx-manager-config unchanged
service/awx-operator-controller-manager-metrics-service unchanged
deployment.apps/awx-operator-controller-manager configured

$ kubectl get pods
NAME                                               READY   STATUS        RESTARTS         AGE
awx-7d74496d7d-grmsq                               4/4     Running       20 (3m34s ago)   46d
awx-postgres-0                                     1/1     Running       5 (3m34s ago)    46d
awx-operator-controller-manager-774bbb775-qnnkk    2/2     Running       0                70s
awx-operator-controller-manager-6d959bd7dd-gvtfr   2/2     Terminating   4 (3m34s ago)    20d

But image version of awx is still 19.5.0:

$ kubectl describe pod awx-7d74496d7d-grmsq | grep -i "image:"
    Image:         quay.io/centos/centos:8
    Image:         docker.io/redis:latest
    Image:          quay.io/ansible/awx:19.5.0
    Image:         quay.io/ansible/awx:19.5.0
    Image:         quay.io/ansible/awx-ee:latest

How to upgrade awx/awx-operator is really intransparent and difficult for kubernetes-newbies.
What can I do? Thanks in advance.

**Comment by eselvam** [comment]
Please follow below instruction:
update from 0.13.0 operator to 0.14.0 and awx from 19.3.0 to 19.4.0
Execute below:

Awx upgrade based on k8 operator:
kubectl delete deployment awx-operator
kubectl delete serviceaccount awx-operator
kubectl delete clusterrolebinding awx-operator
kubectl delete clusterrole awx-operator

unzip -d awx-operator-0.14.0.zip
export NAMESPACE=awxPlease go to the unzipped directory and execute below
make deploy

The operator will be successfully installed however the postgress configuration i.e secret is not available in operator hence it will fail to
update the awx ansible tower.
Follow the below to update ansible tower aka awx

kubectl -n awx edit deployment.apps/awx
Change the image_verison to the latest one. example: 19.4.0

It will automatically pull the image and install it.
Once done, run below i.e. after all the pods and container on running.

kubectl -n awx exec -it pod/podname -c awx-web bash
awx-manage showmigrations | grep -v '[X]' | grep '[ ]' | wc -l
awx-manage showmigrations
awx-manage migrate --noinput
awx-manage  changepassword admin
Once above done, then you have successfully updated the awx from 19.x to 19.4.0
Note: THE Postgres is external.

    On Monday, February 28, 2022, 04:34:46 PM GMT+5:30, Dennis ***@***.***> wrote:  
 
 


Hey, same for me.
Upgrading like it is said in the README doesn't help.
After upgrading awx-operator, the awx instance stays the same (upgrading from 19.5.0 to 20.0.0).

What I did was:
$ git pull https://github.com/ansible/awx-operator 0.17.0
From https://github.com/ansible/awx-operator
   
   - tag 0.17.0 -> FETCH_HEAD   
Already up to date.

$ make deploy
namespace/awx unchanged
customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com unchanged
customresourcedefinition.apiextensions.k8s.io/awxrestores.awx.ansible.com unchanged
customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com configured
serviceaccount/awx-operator-controller-manager unchanged
role.rbac.authorization.k8s.io/awx-operator-awx-manager-role configured
role.rbac.authorization.k8s.io/awx-operator-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/awx-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/awx-operator-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/awx-operator-awx-manager-rolebinding unchanged
rolebinding.rbac.authorization.k8s.io/awx-operator-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/awx-operator-proxy-rolebinding unchanged
configmap/awx-operator-awx-manager-config unchanged
service/awx-operator-controller-manager-metrics-service unchanged
deployment.apps/awx-operator-controller-manager configured

$ kubectl get pods
NAME READY STATUS RESTARTS AGE
awx-7d74496d7d-grmsq 4/4 Running 20 (3m34s ago) 46d
awx-postgres-0 1/1 Running 5 (3m34s ago) 46d
awx-operator-controller-manager-774bbb775-qnnkk 2/2 Running 0 70s
awx-operator-controller-manager-6d959bd7dd-gvtfr 2/2 Terminating 4 (3m34s ago) 20d

But image version of awx is still 19.5.0:

$ kubectl describe pod awx-7d74496d7d-grmsq | grep -i "image:"
Image: quay.io/centos/centos:8
Image: docker.io/redis:latest
Image: quay.io/ansible/awx:19.5.0
Image: quay.io/ansible/awx:19.5.0
Image: quay.io/ansible/awx-ee:latest

How to upgrade awx/awx-operator is really intransparent and difficult for kubernetes-newbies.
What can I do? Thanks in advance.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DaDenniX** [comment]
Does not work, as I'm running already awx-operator 0.16.0 and awx 19.5.0.

$ kubectl delete deployment awx-operator
Error from server (NotFound): deployments.apps "awx-operator" not found
$ kubectl delete serviceaccount awx-operator
Error from server (NotFound): serviceaccounts "awx-operator" not found
$ kubectl delete clusterrolebinding awx-operator
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "awx-operator" not found
$ kubectl delete clusterrole awx-operator
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "awx-operator" not found

**Comment by eselvam** [comment]
shall we know src(current version) and targeted version upgrade?
no need to worry about it. just share requested infor, I will guide you.


    On Tuesday, March 1, 2022, 02:28:59 PM GMT+5:30, Dennis ***@***.***> wrote:  
 
 


Does not work, as I'm running already awx-operator 0.16.0 and awx 19.5.0.

$ kubectl delete deployment awx-operator
Error from server (NotFound): deployments.apps "awx-operator" not found
$ kubectl delete serviceaccount awx-operator
Error from server (NotFound): serviceaccounts "awx-operator" not found
$ kubectl delete clusterrolebinding awx-operator
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "awx-operator" not found
$ kubectl delete clusterrole awx-operator
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "awx-operator" not found

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DaDenniX** [comment]
Trying to migrate from 19.5.0 to 20.0.0 (with awx-operator 0.16.0 to 0.17.0)

**Comment by eselvam** [comment]
Thanks.  Please share the error which you are getting while following up my instruction.




    On Tuesday, March 1, 2022, 05:33:38 PM GMT+5:30, Dennis ***@***.***> wrote:  
 
 


Trying to migrate from 19.5.0 to 20.0.0 (with awx-operator 0.16.0 to 0.17.0)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DaDenniX** [comment]
Please check out my previous comment (https://github.com/ansible/awx-operator/issues/78#issuecomment-1055177013)...

**Comment by eselvam** [comment]
You have to give namespace in which it is running. I think >19.x it is running in namespace scope.  

could you please share,kubectl get allkubectl get namespaces
Thanks.

    On Tuesday, March 1, 2022, 02:28:59 PM GMT+5:30, Dennis ***@***.***> wrote:  
 
 


Does not work, as I'm running already awx-operator 0.16.0 and awx 19.5.0.

$ kubectl delete deployment awx-operator
Error from server (NotFound): deployments.apps "awx-operator" not found
$ kubectl delete serviceaccount awx-operator
Error from server (NotFound): serviceaccounts "awx-operator" not found
$ kubectl delete clusterrolebinding awx-operator
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "awx-operator" not found
$ kubectl delete clusterrole awx-operator
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "awx-operator" not found

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by auroraqin** [comment]
Upgrading not work for me neither. I met the PV mount error for [postgres-awx-postgres-0]

MountVolume.SetUp failed for volume "pvc-0eb05452-2586-448c-**********" : mount command failed, status: Failure, reason: Error while mounting the volume &errors.errorString{s:"RWO check has failed. 

The accessmod for postgres PVC was readwriteonce by default, but upgrading looks like it needs a RWM volume.
