### ISSUE TITLE
Deployment does not have minimum availability.

### ISSUE THREAD

**Issue by stimad** [ansible/tower-operator#781]
Hi. I have problem with awx-operator in installing process of AWX. 
When I run installation process for first time everything works as expected, and than after system reboot I saw `awx-demo-864dcb9dbb-qng6d                          3/4     CrashLoopBackOff   6 (3m36s ago)`. 

On executing kubectl describe pod awx-demo-xyc I got:

```
awx-demo-ee:
    Container ID:  docker://585232b391501b87d422722b2cf15f0a17c77ea80824671cb3e446581b71d43b
    Image:         quay.io/ansible/awx-ee:latest
    Image ID:      docker-pullable://quay.io/ansible/awx-ee@sha256:b44776bdd8e01f066446c07f75825f4c0dd0fa6fb9ff8684249b9fecd5458016
    Port:          <none>
    Host Port:     <none>
    Args:
      receptor
      --config
      /etc/receptor/receptor.conf
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 04 Feb 2022 11:41:42 +0100
      Finished:     Fri, 04 Feb 2022 11:41:42 +0100
    Ready:          False
    Restart Count:  6
    Requests:
      cpu:        500m
      memory:     1Gi
    Environment:  <none>
    Mounts:
      /etc/receptor/receptor.conf from awx-demo-receptor-config (ro,path="receptor.conf")
      /var/lib/awx/projects from awx-demo-projects (rw)
      /var/run/receptor from receptor-socket (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zvfrr (ro)
```
and on executing kubectl logs -f deployments/awx-operator-controller-manager -c awx-manager
i got status:

`"status": {
            "conditions": [
                {
                    "lastTransitionTime": "2022-02-04T10:01:11Z",
                    "lastUpdateTime": "2022-02-04T10:01:11Z",
                    "message": "Deployment does not have minimum availability.",
                    "reason": "MinimumReplicasUnavailable",
                    "status": "False",
                    "type": "Available"
                },
                {
                    "lastTransitionTime": "2022-02-04T10:01:11Z",
                    "lastUpdateTime": "2022-02-04T10:01:11Z",
                    "message": "ReplicaSet \"awx-demo-864dcb9dbb\" is progressing.",
                    "reason": "ReplicaSetUpdated",
                    "status": "True",
                    "type": "Progressing"
                }
            ],
            "observedGeneration": 1,
            "replicas": 1,
            "unavailableReplicas": 1,
            "updatedReplicas": 1
        }`
It is hard to believe to me that it needs more resources (cpu or RAM)
I started awx-demo in minikube as described in installation guide with 4cpus ( 2.20GHz), 8GB memory and none driver on Rocky Linux VM.
I am also new in kubernetes and sorry in advance if I miss out something obvious.
Can someone help please?

**Comment by nixocio** [comment]
Hello,

This looks a problem with your environment.

This issue tracker is for tracking feature enhancements and bugs.

If you need help troubleshooting or are looking for help using AWX, try our mailing list or IRC channel:

#ansible-awx on[ https://libera.chat/](https://libera.chat/)
https://groups.google.com/forum/#!forum/awx-project
