### ISSUE TITLE
Installing additional packages

### ISSUE THREAD

**Issue by klimoff72** [ansible/tower-operator#795]
Hey! Please tell me how can I install additional packages in pod ansible awx.
I will be very grateful to you for any information. I tried to go to the pod and put it there but there are not enough rights to install it.
installed locally like this sudo python3 -m pip install

**Comment by shanemcd** [comment]
@klimoff72 Do you want to install additional packages on the control plane, or in the job environment?

**Comment by klimoff72** [comment]
The package needs to be installed in the working environment under the task for the correct operation of inventory mdhowle.ad.ad_inventory.
application error: with auto plugin: No module named 'ldap3'
There were no problems with the docker, I put the necessary package in the dockerfile.

**Comment by shanemcd** [comment]
It sounds like you need to build a custom Execution Environment to use for your inventory updates. Please see https://github.com/ansible/ansible-builder. Once you have an EE you can associate it with your inventory source.
