### ISSUE TITLE
awx-operator cannot deploy instances of awx

### ISSUE THREAD

**Issue by Mercwri** [ansible/tower-operator#8]
Following the default example given awx-operator fails to create the deployments. The following error is given.

`{
  "level": "error",
  "ts": 1594441722.4744725,
  "logger": "cmd",
  "msg": "Proxy or operator exited with error.",
  "Namespace": "",
  "error": "no matches for kind \"AWX\" in version \"awx.ansible.com/v1beta1\"",
  "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/run.go:196\ngithub.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint.newRunAnsibleCmd.func1\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint/ansible.go:44\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/main.go:39\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/proc.go:203"
}`

**Comment by geerlingguy** [comment]
Related: https://github.com/ansible/awx-operator/issues/7

I think this PR will need to be merged and a new operator image will need to be built (like 0.5.0) so the new image deals with the new default CRD parameters.

**Comment by jcomito** [comment]
Able to pull ansible/awx-operator:0.4.0 again now, but my containers are crashing with the same types of errors: 

"Proxy or operator exited with error.", "Namespace": "", "error": "no matches for kind \"AWX\" in version \"awx.ansible.com/v1beta1\"

Docker version: 19.03.8
Kubectl version: 1.18.2

**Comment by jconallen** [comment]
getting the same error.  when will 0.5.0 be available?

**Comment by matburt** [comment]
This should be fixed up since my large refactoring/reworking PR merged a few days ago.

**Comment by golgotow** [comment]
is anything how to fix this issue ?

operator pod ends with logs like below

{"level":"error","ts":1605008744.4674327,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"AWX.awx.ansible.com","error":"no matches for kind \"AWX\" in version \"awx.ansible.com/v1beta1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/source/source.go:104\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/manager/internal.go:473"}
{"level":"error","ts":1605008744.4676604,"logger":"cmd","msg":"Proxy or operator exited with error.","Namespace":"","error":"no matches for kind \"AWX\" in version \"awx.ansible.com/v1beta1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible.Run\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/run.go:196\ngithub.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint.newRunAnsibleCmd.func1\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint/ansible.go:44\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/operator-sdk/main.go:39\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/proc.go:203"}
