### ISSUE TITLE
Multi-Attach error for `check-db-pvc` Volume used by `database-check` initContainer

### ISSUE THREAD

**Issue by stanislav-zaprudskiy** [ansible/tower-operator#802]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX installation with managed DB hangs, as it can't attach `check-db-pvc` Volume required by `database-check` initContainer mounts. The Volume in question is coming from the managed DB's PVC and is attached to its StatefulSet, thus it can't be attached to other Pods (`accessModes: [ReadWriteOnce]`)

##### ENVIRONMENT
* AWX version: 20.0.0
* Operator version: 0.17.0
* Kubernetes version: 1.20.8
* AWX install method: normal Kubernetes

##### STEPS TO REPRODUCE

Just follow normal installation guidelines using the versions provided.

##### EXPECTED RESULTS

Installation comes to completion successfully.

##### ACTUAL RESULTS

Installation hangs and never completes.

##### ADDITIONAL INFORMATION

Kubernetes emits the following events:

```
Warning   FailedAttachVolume       pod/awx-test-pr-43-5cc8f75ff9-g976f                        Multi-Attach error for volume "pv-awx-qa-9ead74f3f626427c8e22ca4d522794f8-b9be9476-9e1a-4fdd-994d-46e46af188c3" Volume is already used by pod(s) awx-test-pr-43-postgres-0
```

```
Warning   FailedMount              pod/awx-test-pr-43-5cc8f75ff9-g976f                        Unable to attach or mount volumes: unmounted volumes=[check-db-pvc], unattached volumes=[receptor-socket awx-test-pr-43-redis-data rsyslog-socket awx-test-pr-43-projects rsyslog-dir awx-test-pr-43-application-credentials supervisor-socket awx-test-pr-43-bundle-cacert awx-test-pr-43-nginx-conf ca-trust-extracted awx-test-pr-43-receptor-config awx-test-pr-43-secret-key check-db-pvc awx-test-pr-43-token-rpmvh awx-test-pr-43-redis-config awx-test-pr-43-settings awx-test-pr-43-redis-socket]: timed out waiting for the condition
```

Similar installations worked fine with version of operator 0.14.0.

And interestingly, the same installation comes to completion when deploying into Docker for Mac (3.6.0; engine 20.10.8) with Kubernetes v1.21.3. And just for the sake of completeness, installations using external PostgreSQL using the referenced versions of Kubernetes and AWX/operator work fine.

The corresponding AWX Deployment manifest updates have been brought in the following PRs:
* https://github.com/ansible/awx-operator/pull/755
* https://github.com/ansible/awx-operator/pull/772

##### AWX-OPERATOR LOGS

Operator, according to its logs, hangs on this task:

```
TASK [installer : Apply deployment resources] **********************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:93
```

until it fails with the following message

```
{"level":"error","ts":1645442244.568491,"logger":"logging_event_handler","msg":"","name":"awx-test-pr-43","namespace":"awx-test-pr-43","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"runner_on_failed","job":"5549470635859682950","EventData.Task":"Apply deployment resources","EventData.TaskArgs":"","EventData.FailedTaskPath":"/opt/ansible/roles/installer/tasks/resources_configuration.yml:93","error":"[playbook task failed]"}
```

followed by huge dump of data and eventual play failure:

```
PLAY RECAP *********************************************************************
localhost                  : ok=49   changed=0    unreachable=0    failed=1    skipped=27   rescued=0    ignored=0
```

**Comment by per-lind** [comment]
Seeing the same thing, can get around it by scaling down the postgres statefulset, and then scaling up again after the awx pod have done its check.

**Comment by dj27972** [comment]
I'm seeing the same issue with awx-operator 0.16.1.27-g7002131 and vsphere 6.7u2 csi.  

database-check fails to mount with postgres already running:
  Warning  FailedAttachVolume  7m20s  attachdetach-controller  Multi-Attach error for volume "pvc-aad798ce-5f17-411e-a234-2e8472163178" Volume is already used by pod(s) awx-sc-postgres-0

**Comment by leogolds** [comment]
Same here awx-operator 0.17.0. The suggestion by @per-lind works for me to finish the install

**Comment by TeraShark** [comment]
I have what appears to be the same issue, running awx-operator 0.17.0 on Tanzu Kubernetes. Works fine on Minikube, but breaks on Tanzu K8s Cluster with 'Multi-Attach error for volume...'.

Simple, straight-forward deployment, defined as follows:
```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-csc
spec:
  service_type: LoadBalancer
  loadbalancer_protocol: https
  loadbalancer_port: 443

```

K8s version info:
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0+vmware.wcp.2", GitCommit:"d5bb17833505d15ce5f40815bb14fede978fe8c1", GitTreeState:"clean", BuildDate:"2021-08-14T16:41:48Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```
Pods:
```
k get pods
NAME                                               READY   STATUS     RESTARTS   AGE
awx-csc-5664fb8f85-z2df7                           0/4     Init:0/1   0          3s
awx-csc-postgres-0                                 1/1     Running    0          18s
awx-operator-controller-manager-775b5cfc56-dmsth   2/2     Running    0          91s
```
Describing the problematic pod after waiting about 20 mins returns:
```
Events:
  Type     Reason              Age    From                     Message
  ----     ------              ----   ----                     -------
  Normal   Scheduled           23m    default-scheduler        Successfully assigned default/awx-csc-5664fb8f85-z2df7 to awx-workers-9lfpq-54cbcbffff-kfs67
  Warning  FailedAttachVolume  23m    attachdetach-controller  Multi-Attach error for volume "pvc-2418722c-0576-4a40-a889-781b72a15f79" Volume is already used by pod(s) awx-csc-postgres-0
  Warning  FailedMount         21m    kubelet                  Unable to attach or mount volumes: unmounted volumes=[check-db-pvc], unattached volumes=[awx-csc-redis-socket awx-csc-receptor-config awx-csc-redis-config rsyslog-socket awx-csc-projects awx-csc-redis-data receptor-socket awx-csc-nginx-conf check-db-pvc awx-csc-secret-key supervisor-socket kube-api-access-gmzqc awx-csc-application-credentials awx-csc-settings rsyslog-dir]: timed out waiting for the condition
  Warning  FailedMount         19m    kubelet                  Unable to attach or mount volumes: unmounted volumes=[check-db-pvc], unattached volumes=[awx-csc-receptor-config receptor-socket supervisor-socket awx-csc-application-credentials rsyslog-socket check-db-pvc kube-api-access-gmzqc awx-csc-redis-socket awx-csc-redis-data awx-csc-nginx-conf awx-csc-projects awx-csc-redis-config awx-csc-secret-key awx-csc-settings rsyslog-dir]: timed out waiting for the condition

```

**Comment by mkjpryor** [comment]
I am also hitting this issue. What was this behaviour introduced to address? Because it basically makes it impossible to deploy AWX with a RWO volume reliably on a cluster with more than one node...

**Comment by ReinholdFarschNLB** [comment]
Same in AKS (Azure Kubernetes Service)
It's a strange behaviour. Deploying in a second namespace while the first was stuck worked fine.
After a whole restart of AKS, AWX from the first stuck deployment was running fine.

For me it's sort of a race condition.

I'm using 0.17.0

Edit:

Today I restartet AKS and run into the same problem, 
Multi-Attach error for volume "pvc-***" Volume is already used by pod(s) awx-csc-postgres-0

**Comment by kurokobo** [comment]
@ReinholdFarschNLB 

> **ReadWriteOnce**
the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.
> https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

So, luckily, if by chance both AWX and PSQL's Pods happen to be scheduled **on the same node**, they can be successfully launched. Unfortunately if not, it will be fail to launch.

**Comment by mkjpryor** [comment]
@kurokobo 

One possible workaround is to make that not luck, by setting affinity rules. But it sucks.

**Comment by ReinholdFarschNLB** [comment]
@kurokobo thanks for pointing this out

Don't know if it's good or bad 

```
diff --git a/roles/installer/templates/postgres.yaml.j2 b/roles/installer/templates/postgres.yaml.j2
index 817485c..503120c 100644
--- a/roles/installer/templates/postgres.yaml.j2
+++ b/roles/installer/templates/postgres.yaml.j2
@@ -105,7 +105,7 @@ spec:
         name: postgres
       spec:
         accessModes:
-          - ReadWriteOnce
+          - ReadWriteMany
 {% if postgres_storage_class is defined %}
         storageClassName: '{{ postgres_storage_class }}'
 {% endif %}
```

**Comment by mkjpryor** [comment]
@ReinholdFarschNLB 

Good spot. I have no idea why Postgres would even want a RWX volume. It sounds dangerous. Even in the replicated or sharded case, I would expect Postgres to be a StatefulSet where each instance has its own RWO volume.

**Comment by ReinholdFarschNLB** [comment]
@mkjpryor 
actually it's not a Postgres issue. RWO is fine for the db.

The error is from Init Container > database-check, where is trying to mount the volume. And as @kurokobo mentioned, this is not possible outside of a node.

```
Controlled By:  ReplicaSet/awx-core-97ff46445
Init Containers:
  database-check:
    Container ID:
    Image:         quay.io/centos/centos:8
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      [[ -d /check-db/pgsql/data ]] && rm -rf /check-db/data && mv /check-db/pgsql/data/ /check-db/data/ && rm -rf /check-db/pgsql || true

    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /check-db from check-db-pvc (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-n8gqc (ro)
```

**Comment by mkjpryor** [comment]
@ReinholdFarschNLB 

I saw that. This is a relatively recent change though - it looks like the init container was introduced at some point after 0.16.0 but before 0.17.0. Do you have any idea why it was introduced? I can’t really think of a good reason why another pod would need to mount the data volume of a Postgres database.

Surely they must have known that this would basically break any deployment that uses the default block storage on any of the cloud providers…!

**Comment by GeneralFox** [comment]
I've seen the same on a rke2 cluster running on vmware during upgrade from 0.14.0 to 0.17.0.
I've solved changing the node scheduling option of operator deployment and postgres statefulset in rancher binding it to a specific node. Not the optimal solution but it works for now.

**Comment by dj27972** [comment]
> I've seen the same on a rke2 cluster running on vmware during upgrade from 0.14.0 to 0.17.0.
> I've solved changing the node scheduling option of operator deployment and postgres statefulset in rancher binding it to a specific node. Not the optimal solution but it works for now.

@GeneralFox - What did you find was the best way to modify the operator deployment and Postgres statefulset in Rancher?  I'm assuming its in the awx-operator deployment yaml, as the Rancher UI doesn't allow you to make changes to the statefulset node scheduling.

**Comment by GeneralFox** [comment]
> > I've seen the same on a rke2 cluster running on vmware during upgrade from 0.14.0 to 0.17.0.
> > I've solved changing the node scheduling option of operator deployment and postgres statefulset in rancher binding it to a specific node. Not the optimal solution but it works for now.
> 
> @GeneralFox - What did you find was the best way to modify the operator deployment and Postgres statefulset in Rancher? I'm assuming its in the awx-operator deployment yaml, as the Rancher UI doesn't allow you to make changes to the statefulset node scheduling.

@redi-dangeloj from the rancher ui I have edited the yaml config of awx-operator-controller-manager and the yaml of statefulset adding some basic constraint in affininity:{} like 
```
nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: awx.tower
            operator: In
            values:
            - yes
```

Only one node has the label awx.tower:yes and until now it seem to work fine.

**Comment by mkjpryor** [comment]
FWIW, I worked around it by deploying Postgres using the Bitnami chart and using the AWX operator's support for external Postgres databases.

Because AWX doesn't "own" the database, it doesn't attempt to mount the volume.

Bitnami's deployment is probably a nicer one for the long term anyway, as it supports replication etc.

But this issue should still definitely be fixed!

**Comment by shanemcd** [comment]
Sorry for the delay here folks. https://github.com/ansible/awx-operator/pull/803 just merged. It should go out in the next release on Tuesday-ish. In the meantime you can use what's in devel.
