### ISSUE TITLE
Unable to modify default control plane execution environment path in UI

### ISSUE THREAD

**Issue by ranjithavav** [ansible/tower-operator#804]
Can someone help to modify default execution environment path in awx? 
Also unable to delete it, showing permission issue. I would like to pull  awx-ee image from my private repo. Already tried by changing in templates, but it's not working.
Not sure if this is only for me, or it is locked by default.

**Comment by kimbernator** [comment]
This is supposed to be controlled by the `control_plane_ee_image` parameter in your spec. However, it's got a bug at the moment preventing it from being applied. This should be resolved by https://github.com/ansible/awx-operator/pull/873

**Comment by ranjithavav** [comment]
Perfect, that worked
