### ISSUE TITLE
Feature request: Resource settings (requests/limits) for custom EEs

### ISSUE THREAD

**Issue by rguhr** [ansible/tower-operator#820]
##### ISSUE TYPE
 - Feature request

##### SUMMARY

With `ee_resource_requirements` you can control the resource needs of the bundled EE.  
But it seems that there is no such setting for own custom EEs that are defined via  `ee_images`

##### Workaround

* Create own instance group with `Customize pod specification` and append needed resource requests/limits.
* Assign instance group to orgs, invs or templates

**Comment by nixocio** [comment]
The workaround described here is the proper way to achieve this. See #792
