### ISSUE TITLE
Deployment issue with awx-web and awx-task

### ISSUE THREAD

**Issue by SergeyKuzmitskiy** [ansible/tower-operator#828]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Deployment fails. awx-web and awx-task not starting

##### ENVIRONMENT
* AWX version: 20.0.1
* Operator version: 0.18.0
* Kubernetes version: openshift 4.7
* AWX install method: openshift

##### STEPS TO REPRODUCE
As per README:

git checkout 0.18.0
make deploy
oc apply -f awx-deploy.yml

cat awx-deploy.yml

apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: ClusterIP
  projects_persistence: false

##### EXPECTED RESULTS

Successfull deployment

##### ACTUAL RESULTS

awx-web and awx-task containers are not starting. Container logs below

##### AWX-OPERATOR LOGS
awx-web:
{"level":"info","ts":1647277332.7507594,"logger":"cmd","msg":"Version","Go Version":"go1.16.9","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.12.0","commit":"d3b2761afdb78f629a7eaf4461b0fb8ae3b02860"}
{"level":"info","ts":1647277332.75122,"logger":"cmd","msg":"Watch namespaces not configured by environment variable WATCH_NAMESPACE or file. Watching all namespaces.","Namespace":""}
I0314 17:02:13.802424       7 request.go:668] Waited for 1.042679828s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/whereabouts.cni.cncf.io/v1alpha1?timeout=32s
{"level":"info","ts":1647277335.5108502,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1647277335.5113833,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_AWX_AWX_ANSIBLE_COM","default":2}
{"level":"info","ts":1647277335.5114493,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_AWXBACKUP_AWX_ANSIBLE_COM","default":2}
{"level":"info","ts":1647277335.5114672,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_AWXRESTORE_AWX_ANSIBLE_COM","default":2}
{"level":"info","ts":1647277335.5115008,"logger":"cmd","msg":"Environment variable not set; using default value","Namespace":"","envVar":"ANSIBLE_DEBUG_LOGS","ANSIBLE_DEBUG_LOGS":false}
{"level":"info","ts":1647277335.511507,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"awx.ansible.com","Options.Version":"v1beta1","Options.Kind":"AWX"}
{"level":"info","ts":1647277335.5116293,"logger":"cmd","msg":"Environment variable not set; using default value","Namespace":"","envVar":"ANSIBLE_DEBUG_LOGS","ANSIBLE_DEBUG_LOGS":false}
{"level":"info","ts":1647277335.5116332,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"awx.ansible.com","Options.Version":"v1beta1","Options.Kind":"AWXBackup"}
{"level":"info","ts":1647277335.5116591,"logger":"cmd","msg":"Environment variable not set; using default value","Namespace":"","envVar":"ANSIBLE_DEBUG_LOGS","ANSIBLE_DEBUG_LOGS":false}
{"level":"info","ts":1647277335.5116622,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"awx.ansible.com","Options.Version":"v1beta1","Options.Kind":"AWXRestore"}
{"level":"info","ts":1647277335.5123577,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"info","ts":1647277335.5126386,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1647277335.5127165,"logger":"controller-runtime.manager.controller.awxbackup-controller","msg":"Starting EventSource","source":"kind source: awx.ansible.com/v1beta1, Kind=AWXBackup"}
{"level":"info","ts":1647277335.5127559,"logger":"controller-runtime.manager.controller.awxbackup-controller","msg":"Starting Controller"}
{"level":"info","ts":1647277335.5127962,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Starting EventSource","source":"kind source: awx.ansible.com/v1beta1, Kind=AWX"}
{"level":"info","ts":1647277335.512819,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Starting Controller"}
{"level":"info","ts":1647277335.512856,"logger":"controller-runtime.manager.controller.awxrestore-controller","msg":"Starting EventSource","source":"kind source: awx.ansible.com/v1beta1, Kind=AWXRestore"}
{"level":"info","ts":1647277335.5128694,"logger":"controller-runtime.manager.controller.awxrestore-controller","msg":"Starting Controller"}
E0314 17:02:15.514231       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXBackup: failed to list awx.ansible.com/v1beta1, Kind=AWXBackup: awxbackups.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxbackups" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:15.514304       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXRestore: failed to list awx.ansible.com/v1beta1, Kind=AWXRestore: awxrestores.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxrestores" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:15.514327       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWX: failed to list awx.ansible.com/v1beta1, Kind=AWX: awxs.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxs" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:16.481766       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXBackup: failed to list awx.ansible.com/v1beta1, Kind=AWXBackup: awxbackups.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxbackups" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:16.680980       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWX: failed to list awx.ansible.com/v1beta1, Kind=AWX: awxs.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxs" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:16.921667       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXRestore: failed to list awx.ansible.com/v1beta1, Kind=AWXRestore: awxrestores.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxrestores" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:18.377945       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWX: failed to list awx.ansible.com/v1beta1, Kind=AWX: awxs.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxs" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:19.465599       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXBackup: failed to list awx.ansible.com/v1beta1, Kind=AWXBackup: awxbackups.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxbackups" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:19.820527       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXRestore: failed to list awx.ansible.com/v1beta1, Kind=AWXRestore: awxrestores.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxrestores" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:22.875878       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXBackup: failed to list awx.ansible.com/v1beta1, Kind=AWXBackup: awxbackups.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxbackups" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:24.402049       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWX: failed to list awx.ansible.com/v1beta1, Kind=AWX: awxs.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxs" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:24.556763       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXRestore: failed to list awx.ansible.com/v1beta1, Kind=AWXRestore: awxrestores.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxrestores" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:32.489987       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWX: failed to list awx.ansible.com/v1beta1, Kind=AWX: awxs.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxs" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:32.666254       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXRestore: failed to list awx.ansible.com/v1beta1, Kind=AWXRestore: awxrestores.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxrestores" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:33.736457       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXBackup: failed to list awx.ansible.com/v1beta1, Kind=AWXBackup: awxbackups.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxbackups" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:49.223643       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXRestore: failed to list awx.ansible.com/v1beta1, Kind=AWXRestore: awxrestores.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxrestores" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:50.446408       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWX: failed to list awx.ansible.com/v1beta1, Kind=AWX: awxs.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxs" in API group "awx.ansible.com" at the cluster scope
E0314 17:02:53.510883       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXBackup: failed to list awx.ansible.com/v1beta1, Kind=AWXBackup: awxbackups.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxbackups" in API group "awx.ansible.com" at the cluster scope
E0314 17:03:26.589544       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXBackup: failed to list awx.ansible.com/v1beta1, Kind=AWXBackup: awxbackups.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxbackups" in API group "awx.ansible.com" at the cluster scope
E0314 17:03:36.365239       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWXRestore: failed to list awx.ansible.com/v1beta1, Kind=AWXRestore: awxrestores.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxrestores" in API group "awx.ansible.com" at the cluster scope
E0314 17:03:36.825292       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWX: failed to list awx.ansible.com/v1beta1, Kind=AWX: awxs.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxs" in API group "awx.ansible.com" at the cluster scope
E0314 17:04:10.009067       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch awx.ansible.com/v1beta1, Kind=AWX: failed to list awx.ansible.com/v1beta1, Kind=AWX: awxs.awx.ansible.com is forbidden: User "system:serviceaccount:awx:awx" cannot list resource "awxs" in API group "awx.ansible.com" at the cluster scope
{"level":"error","ts":1647277455.5136857,"logger":"controller-runtime.manager.controller.awxbackup-controller","msg":"Could not wait for Cache to sync","error":"failed to wait for awxbackup-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:195\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/manager/internal.go:696"}
{"level":"error","ts":1647277455.5140624,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Could not wait for Cache to sync","error":"failed to wait for awx-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:195\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/manager/internal.go:696"}
{"level":"error","ts":1647277455.5141046,"logger":"controller-runtime.manager.controller.awxrestore-controller","msg":"Could not wait for Cache to sync","error":"failed to wait for awxrestore-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:195\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/manager/internal.go:696"}
{"level":"error","ts":1647277455.5141234,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"failed to wait for awx-controller caches to sync: timed out waiting for cache to be synced"}
{"level":"error","ts":1647277455.5141368,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"failed to wait for awxrestore-controller caches to sync: timed out waiting for cache to be synced"}
{"level":"error","ts":1647277455.514154,"logger":"cmd","msg":"Proxy or operator exited with error.","Namespace":"","error":"failed to wait for awxbackup-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:79\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}

awx-task:
{"level":"info","ts":1647278295.9929373,"logger":"cmd","msg":"Version","Go Version":"go1.16.9","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.12.0","commit":"d3b2761afdb78f629a7eaf4461b0fb8ae3b02860"}
⚠{"level":"info","ts":1647278295.9932761,"logger":"cmd","msg":"Watch namespaces not configured by environment variable WATCH_NAMESPACE or file. Watching all namespaces.","Namespace":""}
I0314 17:18:17.043842       7 request.go:668] Waited for 1.042122256s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/build.openshift.io/v1?timeout=32s
{"level":"info","ts":1647278298.7490742,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"error","ts":1647278298.7493005,"logger":"controller-runtime.metrics","msg":"metrics server failed to listen. You may want to disable the metrics server or use another port if it is due to conflicts","error":"error listening on :8080: listen tcp :8080: bind: address already in use","stacktrace":"sigs.k8s.io/controller-runtime/pkg/metrics.NewListener\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/metrics/listener.go:48\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/manager/manager.go:353\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.run\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:191\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:79\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
{"level":"error","ts":1647278298.7495263,"logger":"cmd","msg":"Failed to create a new manager.","Namespace":"","error":"error listening on :8080: listen tcp :8080: bind: address already in use","stacktrace":"github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:79\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}

**Comment by konsumate** [comment]
Having exactly the same issue.
Deployment is on k3s
Tried awx-operator 0.18.0 0.20.0 and devel

Log of the awx-task container:

"metrics server failed to listen. You may want to disable the metrics server or use another port if it is due to conflicts","error":"error listening on :8080: listen tcp :8080: bind: address already in use"

**Comment by PaulVerhoeven1** [comment]
Got exactly the same issue and errorcode as @corecache and @SergeyKuzmitskiy
deployment is on eks
tried devel and and latest of the awx-operator

**Comment by PaulVerhoeven1** [comment]
i found the issue! 

in my awx-demo.yaml i used the wrong image...

example (what i used and was wrong):

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: nodeport
  task_privileged: false
  image: quay.io/ansible/awx-operator      <-
  image_version: devel      <-
```

The value of the image variable (what is highlited) should **not** be a **awx-operator** image but a **awx** image. example:

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: nodeport
  task_privileged: false
  image: quay.io/ansible/awx    <-
  image_version: 21.0.0   <-

```
this is the reason why it won't work beceause it tries to start 2 brand new awx-operators (awx-web and awx-task uses those image) but that won't work (for obvious reasons)
and maybe it's the same problem for @corecache and @SergeyKuzmitskiy ?

**Comment by konsumate** [comment]
Dang - this one hurts. You are correct - I ran into this because I had to specify the images themselves because I'm running a private registry to pull from. Many thanks for finding the configuration issue.
