### ISSUE TITLE
Can't deploy 20.0.1 on minikube

### ISSUE THREAD

**Issue by apiening** [ansible/tower-operator#839]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Following the guide **Basic Install on minikube (beginner or testing)** only the **postgresql** container is deployed. The awx-operator fails with an error.

##### ENVIRONMENT
* AWX version: 20.0.1
* Operator version: 0.18.0
* Kubernetes version: v1.22.5
* AWX install method: minikube (Parallels)

##### STEPS TO REPRODUCE

Follow https://github.com/ansible/awx-operator#basic-install-on-minikube-beginner-or-testing including the step
```
$ kubectl apply -f awx-demo.yml --namespace=$NAMESPACE
awx.awx.ansible.com/awx-demo created
```

##### EXPECTED RESULTS

```
kubectl get svc -l "app.kubernetes.io/managed-by=awx-operator"
```
should report `awx-demo-postgres` and `awx-demo-service`.

##### ACTUAL RESULTS

```
#> kubectl get svc -l "app.kubernetes.io/managed-by=awx-operator"                      
NAME                TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
awx-demo-postgres   ClusterIP   None         <none>        5432/TCP   54m
```

##### ADDITIONAL INFORMATION

I also tried this with a fresh minikube installation on another system: Same results.

##### AWX-OPERATOR LOGS

Last lines of the output from `kubectl logs -f deployments/awx-operator-controller-manager -c awx-manager`:
```
localhost                  : ok=36   changed=0    unreachable=0    failed=1    skipped=30   rescued=0    ignored=0   \r\n\n","job":"5865347057076655433","name":"awx-demo","namespace":"awx-test","error":"exit status 2"}
{"level":"error","ts":1647807108.1742287,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Reconciler error","name":"awx-demo","namespace":"awx-test","error":"event runner on failed","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214"}
```

**Comment by xyko0** [comment]
Hello, 
I got exactly the same problem on both minikube and K3S.
It finally worked with release 0.14.0 but would be nice if it could be resolved. Dunno the problem.
Thanks

**Comment by kurokobo** [comment]
@apiening 
If your `awx-demo.yml` contains the spec `service_type: nodeport` as the basic instructions guided, I guess you've faced the issue #814.
The issue is fixed but not released yet, so I recommend you to use `0.17.0` instead of `0.18.0`.

If your issue exists with `0.17.0` too, please provide your `awx-demo.yml` and more logs of the Operator (not just last 2 lines).

**Comment by apiening** [comment]
@kurokobo Thank you for your feedback and hints.
I was in fact able to deploy `0.17.0` successfully.

Does this mean, that `0.17.0` is the most current stable release, or can I upgrade using the operator `0.18.0` after a successful deployment with `0.17.0`?
Because how I understand https://github.com/ansible/awx-operator#upgrading it is required to have the latest operator in order to upgrade `awx` to the latest release. Is this correct?

**Comment by kurokobo** [comment]
> Does this mean, that 0.17.0 is the most current stable release, or can I upgrade using the operator 0.18.0 after a successful deployment with 0.17.0?

For the `nodeport` users, yes, `0.17.0` (AWX `20.0.0`) is the most stable one. Upgrading tp `0.18.0` will also trigger this issue.
If it's acceptable for you to use `clusterip` or `loadbalancer` instead of `nodeport`, you can use `0.18.0` (AWX `20.0.1`).

> Because how I understand https://github.com/ansible/awx-operator#upgrading it is required to have the latest operator in order to upgrade awx to the latest release. Is this correct?

Correct. Operator `0.17.0.` is tied to AWX `20.0.0`, and `0.18.0` is to `20.0.1`.

**Comment by apiening** [comment]
Thank you.

I'll leave this ticket open for now, it should be closed when the fix is released and `0.18.0` deploys successfully.

After deploying with the awx-operator `0.17.0` on minikube successfully, I tried to do a deployment ok `k3s` which failed.
I have created another issue for this because I assume these issues are not related to each other: https://github.com/ansible/awx-operator/issues/842

**Comment by fosterseth** [comment]
@apiening 0.19.0 has just released. The default awx-demo.yml (with nodeport) should work, so please try again!

**Comment by apiening** [comment]
Thank you @fosterseth!

I checked out the latest tag `0.19.0` of the `awx-operator` and I was able to upgrade my existing AWX `20.0.0` instance to `20.0.1` without any issues.

I'm closing this ticket.
