### ISSUE TITLE
Install of awx failed during Apply Resources

### ISSUE THREAD

**Issue by AnilVijayan** [ansible/tower-operator#846]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Install of awx failed during Apply Resources

##### ENVIRONMENT
* AWX version: X.Y.Z
* Operator version: 0.18.0
* Kubernetes version: v1.22.4
* AWX install method: K8s, docker on linux

##### STEPS TO REPRODUCE

`
cat awx-demo.yml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
`

`$ kubectl apply -f awx-demo.yml`

##### EXPECTED RESULTS

AWX should be up and running

##### ACTUAL RESULTS

kubectl logs -f deployments/awx-operator-controller-manager -c awx-manager

n\": \"awx.ansible.com/v1beta1\", \"fieldsType\": \"FieldsV1\", \"fieldsV1\": {\"f:metadata\": {\"f:annotations\": {\".\": {}, \"f:kubectl.kubernetes.io/last-applied-configuration\": {}}}, \"f:spec\": {\".\": {}, \"f:admin_user\": {}, \"f:create_preload_data\": {}, \"f:garbage_collect_secrets\": {}, \"f:image_pull_policy\": {}, \"f:loadbalancer_port\": {}, \"f:loadbalancer_protocol\": {}, \"f:nodeport_port\": {}, \"f:projects_persistence\": {}, \"f:projects_storage_access_mode\": {}, \"f:projects_storage_size\": {}, \"f:replicas\": {}, \"f:route_tls_termination_mechanism\": {}, \"f:service_type\": {}, \"f:task_privileged\": {}}}, \"manager\": \"kubectl-client-side-apply\", \"operation\": \"Update\", \"time\": \"2022-03-24T06:12:05Z\"}, {\"apiVersion\": \"awx.ansible.com/v1beta1\", \"fieldsType\": \"FieldsV1\", \"fieldsV1\": {\"f:metadata\": {\"f:labels\": {\".\": {}, \"f:app.kubernetes.io/component\": {}, \"f:app.kubernetes.io/managed-by\": {}, \"f:app.kubernetes.io/name\": {}, \"f:app.kubernetes.io/operator-version\": {}, \"f:app.kubernetes.io/part-of\": {}}}}, \"manager\": \"OpenAPI-Generator\", \"operation\": \"Update\", \"time\": \"2022-03-24T06:12:08Z\"}], \"name\": \"awx-demo\", \"namespace\": \"awx-k8s\", \"resourceVersion\": \"14329406\", \"uid\": \"ecfce6e7-0106-4da4-8f68-ca6418a13ade\"}, \"spec\": {\"admin_user\": \"admin\", \"create_preload_data\": true, \"garbage_collect_secrets\": false, \"image_pull_policy\": \"IfNotPresent\", \"loadbalancer_port\": 80, \"loadbalancer_protocol\": \"http\", \"nodeport_port\": 30080, \"projects_persistence\": false, \"projects_storage_access_mode\": \"ReadWriteMany\", \"projects_storage_size\": \"8Gi\", \"replicas\": 1, \"route_tls_termination_mechanism\": \"Edge\", \"service_type\": \"nodeport\", \"task_privileged\": false}, \"status\": {\"conditions\": [{\"lastTransitionTime\": \"2022-03-24T06:24:50Z\", \"reason\": \"Failed\", \"status\": \"False\", \"type\": \"Failure\"}, {\"lastTransitionTime\": \"2022-03-24T06:24:51Z\", \"reason\": \"Running\", \"status\": \"True\", \"type\": \"Running\"}]}}]}\n\r\nTASK [installer : Set actual old postgres configuration secret name] ***********\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:3\nskipping: [localhost] => {\"changed\": false, \"skip_reason\": \"Conditional result was False\"}\n\r\nTASK [installer : Store Database Configuration] ********************************\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:7\nskipping: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Default label selector to custom resource generated postgres] ***\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:16\nskipping: [localhost] => {\"changed\": false, \"skip_reason\": \"Conditional result was False\"}\n\r\nTASK [installer : Get the postgres pod information] ****************************\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:21\nskipping: [localhost] => {\"changed\": false, \"skip_reason\": \"Conditional result was False\"}\n\r\nTASK [installer : Set the resource pod name as a variable.] ********************\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:35\nskipping: [localhost] => {\"changed\": false, \"skip_reason\": \"Conditional result was False\"}\n\r\nTASK [installer : Scale down Deployment for migration] *************************\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:39\nskipping: [localhost] => {\"changed\": false, \"skip_reason\": \"Conditional result was False\"}\n\r\nTASK [installer : Set pg_dump command] *****************************************\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:42\nskipping: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Set pg_restore command] **************************************\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:53\nskipping: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Stream backup from pg_dump to the new postgresql container] ***\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:61\nskipping: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Set flag signifying that this instance has been migrated] ****\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:75\nskipping: [localhost] => {\"changed\": false, \"skip_reason\": \"Conditional result was False\"}\n\r\nTASK [installer : Load Route TLS certificate] **********************************\r\ntask path: /opt/ansible/roles/installer/tasks/main.yml:45\nskipping: [localhost] => {\"changed\": false, \"skip_reason\": \"Conditional result was False\"}\n\r\nTASK [installer : Include resources configuration tasks] ***********************\r\ntask path: /opt/ansible/roles/installer/tasks/main.yml:51\nincluded: /opt/ansible/roles/installer/tasks/resources_configuration.yml for localhost\n\r\nTASK [installer : Get the current resource pod information.] *******************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:3\nok: [localhost] => {\"api_found\": true, \"changed\": false, \"resources\": []}\n\r\nTASK [installer : Set the resource pod name as a variable.] ********************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:16\nok: [localhost] => {\"ansible_facts\": {\"tower_pod_name\": \"\"}, \"changed\": false}\n\r\nTASK [installer : Apply Resources] *********************************************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:20\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nfailed: [localhost] (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nfatal: [localhost]: FAILED! => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=36   changed=0    unreachable=0    failed=1    skipped=30   rescued=0    ignored=0   \r\n\n","job":"7047814981846550113","name":"awx-demo","namespace":"awx-k8s","error":"exit status 2"}

----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx-demo/awx-k8s) -----

`
$ kubectl get po,deploy,svc
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/awx-demo-postgres-0                                1/1     Running   0          6h17m
pod/awx-operator-controller-manager-5ddf49cc4f-b2hxj   2/2     Running   0          6h19m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-operator-controller-manager   1/1     1            1           6h21m

NAME                                                      TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/awx-demo-postgres                                 ClusterIP   None          <none>        5432/TCP   6h17m
service/awx-operator-controller-manager-metrics-service   ClusterIP   10.99.58.97   <none>        8443/TCP   23h
`

What am i missing here? Not sure how to debug this  further, any help is appreciated

**Comment by kurokobo** [comment]
@AnilVijayan 
Use `0.19.0` of Operator instead of `0.18.0`.
`service_type: nodeport` with Operator 0.18.0 has an issue #814 and is solved in 0.19.0

**Comment by AnilVijayan** [comment]
Thanks @kurokobo  for the swift response. I just tried with operator version 0.19.0, all the pods seems to be up and but node port is not responding 

```
$ kubectl get po
NAME                                               READY   STATUS    RESTARTS   AGE
awx-demo-7d855f96c6-f4nzb                          4/4     Running   0          11m
awx-demo-postgres-0                                1/1     Running   0          13m
awx-operator-controller-manager-6857bd4c9d-f2bk8   2/2     Running   0          15m
```

```
$ kubectl get svc
NAME                                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
awx-demo-postgres                                 ClusterIP   None             <none>        5432/TCP       16m
awx-demo-service                                  NodePort    10.105.187.189   <none>        80:30080/TCP   14m
awx-operator-controller-manager-metrics-service   ClusterIP   10.99.58.97      <none>        8443/TCP       24h
```

And the awx web container logs showing waiting for db migration as below,

```
$ kubectl logs -f awx-demo-7d855f96c6-f4nzb awx-demo-web
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1 of 30
[wait-for-migrations] Waiting 0.5 seconds before next attempt
[wait-for-migrations] Attempt 2 of 30
[wait-for-migrations] Waiting 1 seconds before next attempt
[wait-for-migrations] Attempt 3 of 30
[wait-for-migrations] Waiting 2 seconds before next attempt
[wait-for-migrations] Attempt 4 of 30
[wait-for-migrations] Waiting 4 seconds before next attempt
[wait-for-migrations] Attempt 5 of 30
[wait-for-migrations] Waiting 8 seconds before next attempt
[wait-for-migrations] Attempt 6 of 30
[wait-for-migrations] Waiting 16 seconds before next attempt
```

I guess this is a new issue. However any input on this?

**Comment by kurokobo** [comment]
@AnilVijayan 
Seems your AWX's pod can't communicate with PostgreSQL. It might be a network-related issue and not Operator's issue.
The reason of the situation usualy highly depends on your K8s distribution, but disabling `firewalld` or `ufw` sometimes solved similar issue in my past experience on K3s.

**Comment by AnilVijayan** [comment]
@kurokobo  yes you are right, there is some network issue there, but couldnt figure out the reason. Looks like the postgres db hostname is not resolving 

```Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/conf/settings.py", line 81, in _ctit_db_wrapper
    yield
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/conf/settings.py", line 405, in __getattr__
    value = self._get_local(name)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/conf/settings.py", line 349, in _get_local
    setting = Setting.objects.filter(key=name, user__isnull=True).order_by('pk').first()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/query.py", line 653, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor = self.connection.cursor()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "awx-demo-postgres" to address: Name or service not known
```
Any solution to this? Seen similar issue #761 reported but no resolution is provided

**Comment by kurokobo** [comment]
@AnilVijayan 
I think this is not Operator's issue and it's highly depends on your K8s distribution and your OS.
You should start debugging DNS issue by following K8s docs: <https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/>.

**Comment by AnilVijayan** [comment]
Finally it worked with a restart of coredns deployment !!! Thanks @kurokobo  for all your inputs
