### ISSUE TITLE
External postgres configuration secret being deleted by operator

### ISSUE THREAD

**Issue by TierThree** [ansible/tower-operator#851]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When trying to use an external postgres server, the configuration secret is being deleted by the operator. It reverts back to using the in cluster postgres container for the database instead of using the external postgres server.

##### ENVIRONMENT
* AWX version: 0.20.1
* Operator version: 0.18.0 and 0.19.0
* Kubernetes version: v1.21.5
* AWX install method: Kustomize with a custom deployment

##### STEPS TO REPRODUCE

1. Deploy the awx operator resource.
2. Deploy a secret called 'awx-postgres-configuration'.
3. Referenced the awx-postgres-configuration in the AWX object with postgres_configuration_secret.

##### EXPECTED RESULTS

AWX uses the external database as the postgres server.

##### ACTUAL RESULTS

AWX deletes the external postgres secret and then uses the local postgres container as a database.

##### ADDITIONAL INFORMATION

Please let me know any additional info to provide.

##### AWX OPERATOR LOGS
[operator.log](https://github.com/ansible/awx-operator/files/8381626/operator.log)

**Comment by TierThree** [comment]
Some updates: I worked to get this deployed with a minikube cluster and it seemed to work with an external postgres. Our guess is that it does not like working vault-secrets-operator. Have you folks ran into this before? If so, any suggestions?

**Comment by cs-amatziab** [comment]
i am deploying it with argocd (i took the yaml from kustomize output and made a helm chart) and using the secrets from vault (via csi driver).
i used **waves** in argocd to first install (argocd.argoproj.io/sync-wave: "1") the deployment and the secretproviderclass (the deployment has mounts for the secretproviderclass) and the operator (kind: awx) in argocd.argoproj.io/sync-wave: "5"

**Comment by rooftopcellist** [comment]
@TierThree Can you create a postgresql configuration secret with any other name but `awx-postgres-configuration`, specify it on the spec and try again?  I expect that will solve the problem. Specifically, external pg secret cannot take the form `<deployment-name>-postgres-configuration` or else the role logic will assume it is a generated secret.  

Docs have been updated here: https://github.com/ansible/awx-operator/pull/895

Please comment here if you still have issues after trying that.
