### ISSUE TITLE
README.md improvement 

### ISSUE THREAD

**Issue by BigBoatCap** [ansible/tower-operator#853]
##### ISSUE TYPE
 - Issue \ Feedback

##### SUMMARY
awx-operator Github Project page access delay

##### ENVIRONMENT
Google Chrome Web Browser

##### STEPS TO REPRODUCE
Huge delay with lag due to scrolling while accessing project page https://github.com/ansible/awx-operator caused by svg video loading from within README.md .

##### EXPECTED RESULTS
No delays after openning, comfortable srolling project page. 

##### ACTUAL RESULTS
Problem caused by loading https://raw.githubusercontent.com/ansible/awx-operator/devel/docs/awx-demo.svg and further playing on project page (README.md).

##### ADDITIONAL INFORMATION
Please, just leave that link to the video in README, and not the loaded svg content itself.
> For an example using the Nginx Controller in Minukube, don't miss our demo video.

Thank you.

**Comment by shanemcd** [comment]
I’d merge a PR for this.

**Comment by rooftopcellist** [comment]
This has been merged, thank you for the fix!

**Comment by BigBoatCap** [comment]
#817 Pt. 1 -  it was about "multiple seconds"
