### ISSUE TITLE
Fast disk space usage after update

### ISSUE THREAD

**Issue by ClaudioSousa14** [ansible/tower-operator#881]
Hi guys,

So recently (05-04-2022), I updated my installation from 19.2.2 to 20.0.1 (operator 0.12.0 to 0.20.0).
After that, awx is consuming disk very fast. Almost 17GB in 15days.
The graphic of space utilization (the drop on 12/04 is because I increased the disk size in 10GB):

![space-utilization](https://user-images.githubusercontent.com/50916789/164440867-ce44dcdd-7b0a-4045-b7a3-4493124e9208.jpg)

Anyone have any idea what can be the cause of my problem?

Thank you, in advance.

Best Regards,
Cláudio Sousa

**Comment by shanemcd** [comment]
AWX shouldn't be generating data beyond what your workload is producing. Do you have jobs producing lots of stdout? Does it help if you run the management job to clean up job details?

**Comment by ClaudioSousa14** [comment]
> AWX shouldn't be generating data beyond what your workload is producing. Do you have jobs producing lots of stdout? Does it help if you run the management job to clean up job details?

Hi @shanemcd,
Thank you for the quick reply.

So I runned all the "Management Jobs", maintaining only 15 days of data and I only get 1GB back. So doesn't seems that.

**Comment by fosterseth** [comment]
@ClaudioSousa14 have you been able to track down where the data is coming from? AWX does not persist data outside of the database. It does utilize /tmp/ directory in the awx-task pod, but those files should be cleaned up automatically as the application runs. Can you let us know the size of your postgres volume?

**Comment by ClaudioSousa14** [comment]
@fosterseth Unfortunately no. Postgres volume is only using 8GB:
![Screenshot 2022-04-26 113716](https://user-images.githubusercontent.com/50916789/165282014-4ba31bf9-aba1-44a0-9b8a-522e0e91f61f.jpg)

**Comment by ClaudioSousa14** [comment]
Sorry for the insistence but I really need to sort this out. The disk is increasing out of control.
And, in fact, the increase happens when jobs run. During the weekend the disk remains stable:
![awx](https://user-images.githubusercontent.com/50916789/165762713-ccdd3f31-b0c7-474f-b85f-b4af827c3db6.jpg)

The problem is that I manually runned all the maintenance jobs, maintaining 0 days of history and I only empty 100 MB of data.
What can I make more?

Any help will be appreciated. 

Thank you.

**Comment by ClaudioSousa14** [comment]
So I figured out where the space is being used.
I solved doing the following:

`$ minikube ssh`
`$ df -h`
![df-h](https://user-images.githubusercontent.com/50916789/165917428-e8cae277-cf97-4757-a22b-ea3e28753773.jpg)

`$ docker image prune -a`
"Total reclaimed space: 28.92GB"

This is normal? I need to make this periodically? The awx is allways downloading images?

Thank you.

**Comment by fosterseth** [comment]
each job will run in a separate pod/container. If are in `minikube ssh` and run `docker ps` while a job is running, you can see the container the job is running in
 e.g.
`k8s_worker_automation-job-11-7nkzb_awx_b2824caf-47f4-42a9-a18b-8949f4fc3c0e_0`

it only persists while the job runs, and is cleaned up as soon as the job completes.

By default the container uses the `quay.io/ansible/awx-ee` image, and it will reuse this image each time a job runs. However, it's possible for users to define their own images to run in using execution environments https://docs.ansible.com/automation-controller/latest/html/userguide/execution_environments.html#use-an-ee-in-jobs

Unless you are using a lot of custom images, I dont' see why the image list is building up. What does `docker images` show?

Also k8s has garbage collection that should clean up these unused images periodically https://kubernetes.io/docs/concepts/architecture/garbage-collection/

**Comment by AlanCoding** [comment]
> What does `docker images` show?

Yes, the evidence suggests this may have a lot of dangling images.

https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/cleanup.py

Our cleanup task attempts to do an image prune, but we may not have the ability to do it in the needed context here. It would also be interesting if you could give us a list of all the EE `image` values you have in your system, as I could see this being the consequence of pulling frequently-updating floating tags.

**Comment by ClaudioSousa14** [comment]
So @fosterseth running docker ps:
![containers](https://user-images.githubusercontent.com/50916789/166222437-09cd1007-fa90-440a-82b7-ceb449d0913c.png)

Also answering you and @AlanCoding, listing the images:
![images](https://user-images.githubusercontent.com/50916789/166222565-53dcd21c-6b04-4a7d-b257-1fe0fd2c4ec1.png)

I believe that I had more images but I made the `docker images prune -a` 3 days ago.

About the Execution Environments, most of my templates use the default "AWX EE (latest)", only 3 or 4 use the "AWX EE 0.5.0".

Should I make my own daily script to delete the old images?
