### ISSUE TITLE
Fresh install can't login

### ISSUE THREAD

**Issue by SgtBauerFR** [ansible/tower-operator#892]
Hi

I just installed minikube and kustomize with brew on macOS 11.6.5 then I follow the awx-operator deployment guide
1 issue with the kustomization.yaml I had to replace <tag> with the actual version 0.20.1 and then got all the pods running well.
But,
when I try to login in web, the password just don't work : 
_There was a problem logging in. Please try again._

Got the password with : 
kubectl get secret awx-demo-admin-password -o jsonpath="{.data.password}" | base64 --decode

Then I change the password with : 
kubectl exec -ti awx-demo-7db56584fb-5qg6c -c awx-demo-web -- awx-manage changepassword admin
change successful but still not able to login 

I even create a super user but no luck either
kubectl exec pod/awx-demo-7db56584fb-5qg6c --container awx-demo-web -it awx-manage createsuperuser

I don't see what I miss in the deployment guide

**Comment by BigBoatCap** [comment]
Hi there, try to follow web container logs and see what's in there:
```
kubectl logs -f deployments/awx-demo -c awx-demo-web
```

**Comment by SgtBauerFR** [comment]
Don't see much maybe : 
django.security.csrf Forbidden (CSRF cookie not set.): /api/login/
[awx.log](https://github.com/ansible/awx-operator/files/8572777/awx.log)

**Comment by basift** [comment]
That means you're running it with HTTP access.
I mean not HTTPS.
CSRF cookie is secure, so it is being rejected.

Configure the service with TLS.


The next issue you are going to face probably is an incorrect password.
I tried to create the secret or retrieve the existing one. Nothing worked for me.
So at the end, I connected to the web container and I've run "awx-manage changepassword admin"
Good luck! :)

**Comment by SgtBauerFR** [comment]
how do you run it with https the default deployment guide only gives me http

**Comment by basift** [comment]
Create ssl certificate,
add it as a secret.
Make sure you have ingress controller.
Run AWX controller with ingress.

You have these steps described here in manual:
https://github.com/ansible/awx-operator#ingress-type

**Comment by shatteredsword** [comment]
i thought it was just me. been tearing my hair out over this for 2 days now 😭

**Comment by deepakkamath01** [comment]
This seems like something introduced with v 0.20.1. older release (0.20.0) seems to be fine using HTTP.

**Comment by Sergiodcm00** [comment]
@deepakkamath01 yes! Downgrading operator to 0.20.0 now it works. Thanks.

**Comment by SgtBauerFR** [comment]
I had seen 2 days ago this pull https://github.com/ansible/awx-operator/pull/825 but unfortunately the awx container won't start now.
I'm stuck at the task Apply deployment resources has you can see in the end.
I try to cleanup with : 

kustomize build . | kubectl apply -f - --prune --all
kubectl delete all --all --namespace=awx
kubectl delete namespace awx

even with another namespace I got the same issue.
Maybe my kustomization files is wrong.
kustomization.yaml : 

```
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=0.20.0
  - awx-demo.yaml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.20.0
```





```
TASK [installer : Apply deployment resources] **********************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:75

-------------------------------------------------------------------------------
{"level":"info","ts":1651162594.6537843,"logger":"proxy","msg":"Cache miss: apps/v1, Kind=Deployment, awx/awx-demo"}
{"level":"info","ts":1651162594.6577446,"logger":"proxy","msg":"Cache miss: apps/v1, Kind=Deployment, awx/awx-demo"}
{"level":"info","ts":1651162594.6642444,"logger":"proxy","msg":"Injecting owner reference"}
{"level":"info","ts":1651162594.6658201,"logger":"proxy","msg":"Watching child resource","kind":"apps/v1, Kind=Deployment","enqueue_kind":"awx.ansible.com/v1beta1, Kind=AWX"}
{"level":"info","ts":1651162594.6659944,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Starting EventSource","source":"kind source: apps/v1, Kind=Deployment"}
{"level":"info","ts":1651162594.8376298,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1651162599.8512979,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1651162604.8575861,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1651162609.864366,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1651162614.8749473,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1651162619.8846445,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1651162624.8929374,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1651162629.903466,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1651162634.9112225,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]}}
{"level":"info","ts":1651162639.9222026,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/deployments/awx-demo","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"deployments","Subresource":"","Name":"awx-demo","Parts":["deployments","awx-demo"]
```

**Comment by shatteredsword** [comment]
> This seems like something introduced with v 0.20.1. older release (0.20.0) seems to be fine using HTTP.

lol i just upgraded to 0.20.1 because 0.20.0 had issues with deployment

**Comment by fosterseth** [comment]
this login bug was fixed with https://github.com/ansible/awx-operator/pull/886

please try our newest release, 0.20.2 https://github.com/ansible/awx-operator/releases/tag/0.20.2

**Comment by SgtBauerFR** [comment]
everything work great with 0.20.2 no issue with the install and I'm able to login properly =)

**Comment by Zeek3000** [comment]
I believe this has been re-introduced in 0.21.0. I tried to deploy using 0.21.0 and got the same error, I reverted to 0.20.2 which is fine.

**Comment by OrenAvinoam** [comment]
> This seems like something introduced with v 0.20.1. older release (0.20.0) seems to be fine using HTTP.

This guy saved my braincells thank you
