### ISSUE TITLE
Question: Exposing routes (OpenShift)

### ISSUE THREAD

**Issue by muyari** [ansible/tower-operator#900]
Any documentation on how to integrate the secrets / certs generated as part of the AWX deployment for exposing a route in OpenShift?

**Comment by muyari** [comment]
no need to address this comment I have identified where  I went wrong.

**Comment by bschonec** [comment]
It would be most helpful if you updated this issue with your findings.  I am having trouble exposing the AWX service with OpenShift.  "oc expose svc XXX" doesn't set up the route properly.
