### ISSUE TITLE
awx 21.0.0 external postgres 12.10 not able to connect

### ISSUE THREAD

**Issue by pratik-pagade** [ansible/tower-operator#902]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 21.0.0
* Operator version: 0.21.0
* Kubernetes version: 1.21.10
* AWX install method: kubernetes
* Postgres: 12.10 (Db hosted in aiven)

##### STEPS TO REPRODUCE

kubectl apply -f awx-admin-user-pass.yml
kubectl apply -f awx-external-db-secret.yml
kubectl apply -f awx-demo.yml

##### EXPECTED RESULTS

awx connects to Postgresql and awx is up and running

##### ACTUAL RESULTS

the logs of awx-task shows waiting for database migrations

##### ADDITIONAL INFORMATION

awx-external-db-secret
apiVersion: v1
kind: Secret
metadata:
  name: awx-demo-postgres-configuration
  namespace: awx
stringData:
  host: host-name
  port: "22660"
  database: awx
  username: awx
  password: password
  sslmode: require
  type: unmanaged
type: Opaque

---
awx-admin-user-pass.yaml

apiVersion: v1
kind: Secret
metadata:
  name: awx-demo-admin-password
  namespace: awx
stringData:
  password: password

---

awx-demo.yaml

apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  admin_user: test-user
  admin_password_secret: awx-demo-admin-password
  service_type: LoadBalancer
  loadbalancer_protocol: http
  loadbalancer_port: 80
  projects_persistence: true
  projects_storage_class: awx-storage-class
  projects_storage_size: 20Gi
  projects_storage_access_mode: ReadWriteOnce
  postgres_configuration_secret: awx-demo-postgres-configuration
  
  
I exec into the awx-demo-web container awx-manage check command
I see the following :
OperationalError: SSL error: certificate verify failed

I have applied the secrets first and then applied the operator yaml,
so there is no issue of timing as I read in one of the other issues

I have the sslmode as "require" for the db as well as I have set the type :unmanaged.

##### AWX-OPERATOR LOGS
```
[wait-for-migrations] Attempt 11 of 30
2022-05-04 17:05:34.053 PDT
awx-demo-web
[wait-for-migrations] Waiting 30 seconds before next attempt
```

**Comment by gek0** [comment]
Any update regarding this? Did you managed to fix it @pratik-pagade ?

As the same is happening to me using an external PostgreSQL database.
If I set the sslmode to `require` it stops working and awx-web container is stuck in the loop with 
```
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 12 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 13 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 14 of 30
...
```
