### ISSUE TITLE
Self signed SSL cert for external database

### ISSUE THREAD

**Issue by ddellarocca** [ansible/tower-operator#908]
##### SUMMARY
Is there any way to make AWX trust a self signed certificate in order to connect to a postgres instance?

##### ENVIRONMENT
* AWX version: 21.0.0
* Operator version: 0.19.0
* Kubernetes version: 1.21
* AWX install method: operator on k8s

**Comment by shanemcd** [comment]
See https://github.com/ansible/awx-operator#trusting-a-custom-certificate-authority
