### ISSUE TITLE
inventory from source control path problem

### ISSUE THREAD

**Issue by Hokwang** [ansible/tower-operator#910]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
after deploy awx on kubernetes (AWS EKS)
create project (from github)
create credential (for project sync)
create inventory from project

##### ENVIRONMENT
* AWX version: 21.0.0
* Operator version: 0.21.0
* Kubernetes version: 1.22.6
* AWX install method: kubernetes

##### STEPS TO REPRODUCE
project created, successfully synced -> /var/lib/awx/projects
![스크린샷 2022-05-11 01 33 26](https://user-images.githubusercontent.com/1247030/167678358-8f0aa14b-e63d-486f-a51c-08efb2d19ec9.png)
I can find source in awx-demo-ee container

but inventory > source is failed.
![스크린샷 2022-05-11 01 36 07](https://user-images.githubusercontent.com/1247030/167678844-54c72b1f-f739-45da-92dd-451103072a4b.png)

I think worker container, pod named `automation-job-num-xxx`, works from /runner/project.
And it is empty.
and I can confirm this pod does not attach project pvc.

```
'/var/lib/awx/projects/_9__github_awx_inven/inventories/aws/bigger_than_small'
is not a directory
host_list declined parsing /var/lib/awx/projects/_9__github_awx_inven/inventories/aws/bigger_than_small/aws_ec2.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /var/lib/awx/projects/_9__github_awx_inven/inventories/aws/bigger_than_small/aws_ec2.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
auto declined parsing /var/lib/awx/projects/_9__github_awx_inven/inventories/aws/bigger_than_small/aws_ec2.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /var/lib/awx/projects/_9__github_awx_inven/inventories/aws/bigger_than_small/aws_ec2.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /var/lib/awx/projects/_9__github_awx_inven/inventories/aws/bigger_than_small/aws_ec2.yml as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /var/lib/awx/projects/_9__github_awx_inven/inventories/aws/bigger_than_small/aws_ec2.yml as it did not pass its verify_file() method
[WARNING]: Unable to parse /var/lib/awx/projects/_9__github_awx_inven/inventori
es/aws/bigger_than_small/aws_ec2.yml as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

##### EXPECTED RESULTS
inventory sync

##### ACTUAL RESULTS
I didn't understand awx's worker model.
project synced awx-demo-ee container, but inventory synced worker container without git clone or mounting project volume.

What is right way to create inventory?

**Comment by fosterseth** [comment]
This issue may be well suited for the awx mailing list, so you might create a post there as well
https://groups.google.com/g/awx-project
