### ISSUE TITLE
[feature] awx_no_log variable to override no_log

### ISSUE THREAD

**Issue by fosterseth** [ansible/tower-operator#918]
Many of the operator ansible plays have `no_log: True` set.

It would be useful for debugging purposes to have an option override this

e.g. a setting in the operator like `awx_no_log`

the the no_log in the plays could be replaced with

```yaml
no_log: "{{ awx_no_log|default(true)|bool }}"
```

**Comment by PaulVerhoeven1** [comment]
+1
