### ISSUE TITLE
Kustomize build failing

### ISSUE THREAD

**Issue by ghost** [ansible/tower-operator#920]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Kustomize build using Github Link but 404 error: https://github.com/ansible/awx-operator/config/default?ref=0.21.0

This part of the documentation thus fail:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/awx-operator/config/default?ref=<tag>
```

**Comment by philipgierszal** [comment]
Struggling with the same issue.

**Comment by fosterseth** [comment]
that URL isn't intended to be browsed and the 404 is probably expected (I think this url is valid for go-getter)

unless you need to customize your kustomization.yml file, you can simply run `VERSION=0.21.0 make deploy` from the awx-operator directory and skip all the steps about kustomize build

so `make deploy` followed by `kubectl apply -f awx-demo.yml`
