### ISSUE TITLE
module/collections not working

### ISSUE THREAD

**Issue by rajspeed1** [ansible/tower-operator#940]
Hi All, 

Can someone help to suggest what is recommended way to use the modules inside ansible awx.

Version : ansible - AWX 21.0.0  

Facing issue while using modules through playbook.
  I've tried installing few modules through the playbook as below, but when running the job - > it fails to find the modules ERROR! couldn't resolve module/action 'community.vmware.vmware_vm_inventory'.

- name: Install Ansible Galaxy modules
  command:  ansible-galaxy  collection install "{{ item }}"  --ignore-certs
  loop:
    - citrix.adc
    - azure.azcollection

OUTPUT:

# /runner/requirements_collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.13.0 
citrix.adc         1.1.0  
community.vmware   2.6.0  

# /usr/share/ansible/collections/ansible_collections
Collection              Version
----------------------- -------
amazon.aws              3.3.0  
ansible.posix           1.4.0  
ansible.windows         1.10.0 
awx.awx                 21.1.0 
azure.azcollection      1.13.0 
community.vmware        2.6.0  
google.cloud            1.0.2  
kubernetes.core         2.3.1  
openstack.cloud         1.8.0  
ovirt.ovirt             2.0.4  
redhatinsights.insights 1.0.7  
theforeman.foreman      3.4.0  

Also tried through requirements.yml , but still NO LUCK.  

roles->collections->requirements.yml
roles->requirements.yml
playbook -> requirements.yml
playbook -> collections -> requirements.yml
---
collections:
- name: community.vmware

**Comment by PaulVerhoeven1** [comment]
Hi [rajspeed1](https://github.com/rajspeed1)

If you want te use custom collections in AWX you need to build an custom awx-ee container. This is the execution environment where the playbooks are running.

You can build this container with thecommandline tool ansible-builder (https://www.ansible.com/blog/introduction-to-ansible-builder) after you build the custom container you need to host this container on a registry and use that container in your configuration (https://github.com/ansible/awx-operator#advanced-configuration). After that you need to link the project / template etc to that custom awx-ee image and then everything should be working.

Hopefully you can go further with this information :)

**Comment by fosterseth** [comment]
You can specify a collections requirement by adding a collections/requirements.yml file in your project directory. At run time, awx will download any necessary collections modules.

https://docs.ansible.com/automation-controller/latest/html/userguide/projects.html#collections-support

Note, if these modules have specific system dependencies, then you will need to build out a custom EE that includes both the modules and the system dependencies., as @PaulVerhoeven1 pointed out

**Comment by PaulVerhoeven1** [comment]
Thanks for the information @fosterseth that's what i didn't know about the requirements.yml file 👍

**Comment by rajspeed1** [comment]
Thanks @PaulVerhoeven1 & @fosterseth for your suggestions.. this is helpful to fix

**Comment by rajspeed1** [comment]
Thanks @PaulVerhoeven1 & @fosterseth for your suggestions.. this is helpful to fix
