### ISSUE TITLE
Upgrading AWX operator disrupts the previous AWX deployments

### ISSUE THREAD

**Issue by AshokMishra** [ansible/tower-operator#968]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I have deployed AWX operator using Kustomize. The AWX operator version deployed is 0.16.1. I deployed 3 AWX resources as shown below:

NAME                                               READY   STATUS    RESTARTS   AGE
awx-operator-controller-manager-6d959bd7dd-wgznf   2/2     Running   0          10d
portal1-5c897f445d-vkxdv                           4/4     Running   0          10d
portal1-postgres-0                                 1/1     Running   0          10d
portal2-64b6666c7c-snb6p                           4/4     Running   0          10d
portal2-postgres-0                                 1/1     Running   0          10d
portal3-7669ff9dd4-tthxx                           4/4     Running   0          10d
portal3-postgres-0                                 1/1     Running   0          10d

However, when I try to update the AWX operator from 0.16.1 to 0.23.0 the AWX resources gets deleted automatically and does not reprovision. I checked the logs and found that the playbook errors out. But because of `no_log: true`, I am not able to debug the issue.

After no deployment occurs, if you try to manually deploy AWX resource

### AWX Operator version

0.16.1

### AWX version

19.5.1

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.22.8

### Modifications

no

### Steps to reproduce

- Deploy AWX Operator using Kustomize. Choose version 0.16.1
- Added AWX resource with postgress database using persistent volume.
- Upgrade the AWX operator to version 0.23.0
- You will see new AWX operator controller manager being deployed
- After sometime AWX resource will be deleted/scaled down
- Manual deployment of AWX resources also don't work

### Expected results

AWX operator upgrades properly with all the AWX resources updated automatically.

### Actual results

AWX resources gets deleted/scaled down
Manual deployment of AWX resources also do not work.

### Operator Logs

*****************************************\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:43\nskipping: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Set pg_restore command] **************************************\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:54\nskipping: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Stream backup from pg_dump to the new postgresql container] ***\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:62\nskipping: [localhost] => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nTASK [installer : Set flag signifying that this instance has been migrated] ****\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:76\nskipping: [localhost] => {\"changed\": false, \"skip_reason\": \"Conditional result was False\"}\n\r\nTASK [installer : Load Route TLS certificate] **********************************\r\ntask path: /opt/ansible/roles/installer/tasks/main.yml:50\nskipping: [localhost] => {\"changed\": false, \"skip_reason\": \"Conditional result was False\"}\n\r\nTASK [installer : Include resources configuration tasks] ***********************\r\ntask path: /opt/ansible/roles/installer/tasks/main.yml:56\nincluded: /opt/ansible/roles/installer/tasks/resources_configuration.yml for localhost\n\r\nTASK [installer : Get the current resource pod information.] *******************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:3\nok: [localhost] => {\"api_found\": true, \"changed\": false, \"resources\": []}\n\r\nTASK [installer : Set the resource pod name as a variable.] ********************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:16\nok: [localhost] => {\"ansible_facts\": {\"tower_pod_name\": \"\"}, \"changed\": false}\n\r\nTASK [installer : Set user provided control plane ee image] ********************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:20\nskipping: [localhost] => {\"changed\": false, \"skip_reason\": \"Conditional result was False\"}\n\r\nTASK [installer : Set Control Plane EE image URL] ******************************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:26\nok: [localhost] => {\"ansible_facts\": {\"_control_plane_ee_image\": \"quay.io/ansible/awx-ee:latest\"}, \"changed\": false}\n\r\nTASK [installer : Apply Resources] *********************************************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:30\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nfailed: [localhost] (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nok: [localhost] => (item=None) => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\nfatal: [localhost]: FAILED! => {\"censored\": \"the output has been hidden due to the fact that 'no_log: true' was specified for this result\", \"changed\": false}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=37   changed=0    unreachable=0    failed=1    skipped=32   rescued=0    ignored=0   \r\n\n","job":"4515935957301861557","name":"portal1-awx","namespace":"awx1","error":"exit status 2"}

----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, portal1-awx/awx1) -----

PLAY RECAP *********************************************************************
localhost                  : ok=37   changed=0    unreachable=0    failed=1    skipped=32   rescued=0    ignored=0

**Comment by kurokobo** [comment]
Could you please share the output of:

- `kubectl -n <namespace> get awx,all,ingress,secrets`
- `kubectl -n <namespace> describe awx`

The actual log is:

```text
TASK [installer : Apply Resources] *********************************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:30
ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
ok: [localhost] => (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```

So the error could have occurred in the deployment of `service.yaml.j2` in this loop: https://github.com/ansible/awx-operator/blob/34b6354001c0f044aaf56e62f3d4d4699a20fbbb/roles/installer/tasks/resources_configuration.yml#L30-L43

**Comment by AshokMishra** [comment]
**output of** - `kubectl -n <namespace> get awx,all,ingress,secrets`

```
NAME                              AGE
awx.awx.ansible.com/portal1-awx   9h
awx.awx.ansible.com/portal2-awx   9h

NAME                                                   READY   STATUS    RESTARTS   AGE
pod/awx-operator-controller-manager-5cd878cd68-rq4d2   2/2     Running   0          9h
pod/portal1-awx-postgres-0                             1/1     Running   0          9h
pod/portal2-awx-postgres-0                             1/1     Running   0          8h

NAME                                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   <IP>    <none>        8443/TCP       9h
service/portal1-awx-postgres                              ClusterIP   None             <none>        5432/TCP       9h
service/portal1-awx-service                               NodePort    <IP>   <none>        80:port/TCP   9h
service/portal2-awx-postgres                              ClusterIP   None             <none>        5432/TCP       8h

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-operator-controller-manager   1/1     1            1           9h
deployment.apps/portal1-awx                       0/0     0            0           9h

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/awx-operator-controller-manager-5cd878cd68   1         1         1       9h
replicaset.apps/awx-operator-controller-manager-6d959bd7dd   0         0         0       9h
replicaset.apps/portal1-awx-6ddc488dc7                       0         0         0       9h

NAME                                    READY   AGE
statefulset.apps/portal1-awx-postgres   1/1     9h
statefulset.apps/portal2-awx-postgres   1/1     8h

NAME                                            CLASS   HOSTS                             ADDRESS   PORTS     AGE
ingress.networking.k8s.io/portal1-awx-ingress   nginx   <FQDN>             80, 443   9h
ingress.networking.k8s.io/portal2-awx-ingress   nginx   <FQDN>             80, 443   9h

NAME                                                 TYPE                                  DATA   AGE
secret/awx-operator-controller-manager-token-r2gjh   kubernetes.io/service-account-token   3      9h
secret/default-token-98w2x                           kubernetes.io/service-account-token   3      9h
secret/portal1-awx-admin-password                    Opaque                                1      9h
secret/portal1-awx-app-credentials                   Opaque                                3      9h
secret/portal1-awx-broadcast-websocket               Opaque                                1      9h
secret/portal1-awx-postgres-configuration            Opaque                                6      9h
secret/portal1-awx-secret-key                        Opaque                                1      9h
secret/portal1-awx-token-drspp                       kubernetes.io/service-account-token   3      9h
secret/portal2-awx-admin-password                    Opaque                                1      9h
secret/portal2-awx-app-credentials                   Opaque                                3      8h
secret/portal2-awx-broadcast-websocket               Opaque                                1      9h
secret/portal2-awx-postgres-configuration            Opaque                                6      8h
secret/portal2-awx-secret-key                        Opaque                                1      9h
secret/portal2-awx-token-chhw2                       kubernetes.io/service-account-token   3      8h
```


**output of** - `kubectl -n <namespace> describe awx`

```
Name:         portal1-awx
Namespace:    awx1
Labels:       app.kubernetes.io/component=awx
              app.kubernetes.io/managed-by=awx-operator
              app.kubernetes.io/name=portal1-awx
              app.kubernetes.io/operator-version=0.23.0
              app.kubernetes.io/part-of=portal1-awx
Annotations:  <none>
API Version:  awx.ansible.com/v1beta1
Kind:         AWX
Metadata:
  Creation Timestamp:  2022-06-28T07:52:44Z
  Generation:          1
  Managed Fields:
    API Version:  awx.ansible.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:admin_user:
        f:create_preload_data:
        f:garbage_collect_secrets:
        f:image_pull_policy:
        f:loadbalancer_port:
        f:loadbalancer_protocol:
        f:node_selector:
        f:nodeport_port:
        f:postgres_storage_class:
        f:postgres_storage_requirements:
          .:
          f:requests:
            .:
            f:storage:
        f:projects_persistence:
        f:projects_storage_access_mode:
        f:projects_storage_size:
        f:replicas:
        f:route_tls_termination_mechanism:
        f:service_type:
        f:task_privileged:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-06-28T07:52:44Z
    API Version:  awx.ansible.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:      ansible-operator
    Operation:    Update
    Subresource:  status
    Time:         2022-06-28T07:52:46Z
    API Version:  awx.ansible.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
          f:app.kubernetes.io/operator-version:
          f:app.kubernetes.io/part-of:
    Manager:      OpenAPI-Generator
    Operation:    Update
    Time:         2022-06-28T07:52:49Z
    API Version:  awx.ansible.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:adminPasswordSecret:
        f:adminUser:
        f:broadcastWebsocketSecret:
        f:image:
        f:postgresConfigurationSecret:
        f:secretKeySecret:
        f:version:
    Manager:         OpenAPI-Generator
    Operation:       Update
    Subresource:     status
    Time:            2022-06-28T07:55:22Z
  Resource Version:  3840792
  UID:               a0ec4475-b86e-42b0-99b4-ddb24061176d
Spec:
  admin_user:               admin
  create_preload_data:      true
  garbage_collect_secrets:  false
  image_pull_policy:        IfNotPresent
  loadbalancer_port:        80
  loadbalancer_protocol:    http
  node_selector:            node_type: "<staging>"

  nodeport_port:           <port>
  postgres_storage_class:  <class>
  postgres_storage_requirements:
    Requests:
      Storage:                      200Gi
  projects_persistence:             false
  projects_storage_access_mode:     ReadWriteMany
  projects_storage_size:            8Gi
  Replicas:                         1
  route_tls_termination_mechanism:  Edge
  service_type:                     nodeport
  task_privileged:                  false
Status:
  Admin Password Secret:       portal1-awx-admin-password
  Admin User:                  admin
  Broadcast Websocket Secret:  portal1-awx-broadcast-websocket
  Conditions:
    Last Transition Time:         2022-06-28T17:40:39Z
    Reason:                       Running
    Status:                       False
    Type:                         Running
    Last Transition Time:         2022-06-28T17:40:53Z
    Reason:                       Failed
    Status:                       True
    Type:                         Failure
  Image:                          quay.io/ansible/awx:19.5.1
  Postgres Configuration Secret:  portal1-awx-postgres-configuration
  Secret Key Secret:              portal1-awx-secret-key
  Version:                        19.5.1
Events:                           <none>


Name:         portal2-awx
Namespace:    awx1
Labels:       app.kubernetes.io/component=awx
              app.kubernetes.io/managed-by=awx-operator
              app.kubernetes.io/name=portal2-awx
              app.kubernetes.io/operator-version=0.23.0
              app.kubernetes.io/part-of=portal2-awx
Annotations:  <none>
API Version:  awx.ansible.com/v1beta1
Kind:         AWX
Metadata:
  Creation Timestamp:  2022-06-28T08:37:40Z
  Generation:          1
  Managed Fields:
    API Version:  awx.ansible.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:      ansible-operator
    Operation:    Update
    Subresource:  status
    Time:         2022-06-28T08:37:40Z
    API Version:  awx.ansible.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:admin_user:
        f:create_preload_data:
        f:garbage_collect_secrets:
        f:image_pull_policy:
        f:loadbalancer_port:
        f:loadbalancer_protocol:
        f:no_log:
        f:node_selector:
        f:nodeport_port:
        f:postgres_storage_class:
        f:postgres_storage_requirements:
          .:
          f:requests:
            .:
            f:storage:
        f:projects_persistence:
        f:projects_storage_access_mode:
        f:projects_storage_size:
        f:replicas:
        f:route_tls_termination_mechanism:
        f:service_type:
        f:task_privileged:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-06-28T08:37:40Z
    API Version:  awx.ansible.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
          f:app.kubernetes.io/operator-version:
          f:app.kubernetes.io/part-of:
    Manager:         OpenAPI-Generator
    Operation:       Update
    Time:            2022-06-28T08:37:41Z
  Resource Version:  3842068
  UID:               f9d6d8ae-1fec-4ad4-91eb-1208b7433777
Spec:
  admin_user:               admin
  create_preload_data:      true
  garbage_collect_secrets:  false
  image_pull_policy:        IfNotPresent
  loadbalancer_port:        80
  loadbalancer_protocol:    http
  no_log:                   false
  node_selector:            node_type: "<staging>"

  nodeport_port:           <port>
  postgres_storage_class:  <class>
  postgres_storage_requirements:
    Requests:
      Storage:                      200Gi
  projects_persistence:             false
  projects_storage_access_mode:     ReadWriteMany
  projects_storage_size:            8Gi
  Replicas:                         1
  route_tls_termination_mechanism:  Edge
  service_type:                     nodeport
  task_privileged:                  false
Status:
  Conditions:
    Last Transition Time:  2022-06-28T17:29:23Z
    Reason:                Failed
    Status:                False
    Type:                  Failure
    Last Transition Time:  2022-06-28T17:46:03Z
    Reason:                Running
    Status:                True
    Type:                  Running
Events:                    <none>
```

Let me know if you need more information.

**Note**: After upgrade I tried deploying portal2 AWX resource but it did not work and no pods came up in the namespace

**Comment by kurokobo** [comment]
Is my understanding correct that you originally had `portal1`, `portal2`, and `portal3`, but they were already removed and you manually created two new ones, `portal1-awx` and `portal2-awx`?
Also, the currently running Operator is `0.23.0`, right?

**About `portal1-awx`:**

Can you show me the results of following commands?

- `kubectl -n <namespace> describe deployment portal1-awx`
- `kubectl -n <namespace> describe replicaset portal1-awx-6ddc488dc7`

**About `portal2-awx`:**

From the output you posted, `portal2-awx` has `no_log` set to `false`, so you should be able to track down the detailed cause in Operator's logs. Please check the log again.

**Comment by fosterseth** [comment]
some relevant PRs just landed in the last version of awx-operator that you may be interested in

you can now specify `no_log: False` in the spec so that you can view the full logs from the operator as it runs

https://github.com/ansible/awx-operator/pull/923

and you can set auto_upgrade to false, which disables bouncing the awx deployment whenever the operator is upgraded

https://github.com/ansible/awx-operator/pull/956

**Comment by akus062381** [comment]
Hi!

https://github.com/ansible/awx-operator/pull/923 is out in the latest release of operator.
https://github.com/ansible/awx-operator/pull/956 should be going out in a release sometime next week.

Thank you very much for your comments on the above issue. It means a lot to us that you have taken time to contribute.

At this time we are closing this issue. If you feel we closed it in error, you may contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
