### ISSUE TITLE
Bump outdated ansible-operator (v1.12) used in Dockerfile to more recent version

### ISSUE THREAD

**Issue by Raptus1** [ansible/tower-operator#975]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Currently the Dockerfile used to build the AWX-operator starts with:

FROM quay.io/operator-framework/ansible-operator:v1.12.0
ref: https://github.com/ansible/awx-operator/blob/devel/Dockerfile#L1

This should be bumped to a much more recent version of ansible-operator to get rid og many of the current 298 vulnerabilities.
![image](https://user-images.githubusercontent.com/26519394/176869403-c58d5f9a-5cfd-4125-9df1-a6cca33485c4.png)

### AWX Operator version

0.23.0

### AWX version

21.2.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.23.2

### Modifications

no

### Steps to reproduce

Use awx-operator directly from quay.io.

### Expected results

Using newer ansible-operator.

### Actual results

Using outdated ansible-operator.

### Additional information

You guys are amazing and deliver a fantastic product!

**Comment by akus062381** [comment]
> You guys are amazing and deliver a fantastic product!

Thank you for the love!

@rooftopcellist can you take a look and see if this might cause any problems downstream?

**Comment by shanemcd** [comment]
PR: https://github.com/ansible/awx-operator/pull/1001

**Comment by rooftopcellist** [comment]
I just merged [this PR](https://github.com/ansible/awx-operator/pull/1001) to upgrade the operator-sdk to v1.22.0 so that we can bump the ansible-operator base image and clear up most of these security scan vulnerabilities.

There will be a release later this week with these changes.  cc @Raptus1
