### ISSUE TITLE
Request help around resource limits for custom execution environments 

### ISSUE THREAD

**Issue by rakesh561** [ansible/tower-operator#985]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hi Team,  

I have question around resource limits and requests for custom execution environments.Recently I came across an issue where jobs are waiting in queue saying 3 cpus requested I did configure execution environment requests to be 256 but seems like it is only applicable for control plane execution environment if so how can I define resource limits for the custom execution environments if this option is not available wat would be the other way around to achieve this

**Comment by shanemcd** [comment]
Hello. The resource settings for the operator only affect the control plane pods. To customize the pods for jobs, you can modify the pod spec under Instance Groups -> edit view.

For more help using AWX you more have more luck reaching out on the mailing list or IRC: https://github.com/ansible/awx#get-involved
