### ISSUE TITLE
Document installation using an Ansible playbook

### ISSUE THREAD

**Issue by mhalano** [ansible/tower-operator#986]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

The README has documentation on how to install using Kubernetes's Kustomization and Helm Chart, but it would be a nice idea if document how to use an Ansible playbook, something like `ansible-playbook -i inventory install-awx.yml`.

**Comment by PaulVerhoeven1** [comment]
There is some documentation about this: https://github.com/ansible/awx-operator/blob/devel/docs/debugging.md

**Comment by mhalano** [comment]
I saw that, but it's a playbook to run the `installer` role used by awx-operator itself. My idea is how to implement the awx-operator using an Ansible playbook and the official installation methods, Kustomize or Helm Chart. Or create a third official way using an official Ansible playbook. My use case is I want to create an Ansible playbook to install awx-operator (and awx itself) in my Kubernetes cluster.

**Comment by jbradberry** [comment]
We'd love to see a PR for this.

**Comment by d-rupp** [comment]
We have a playbook that checks out the awx-operator git repository, creates a kustomization file from a template, build and deploys the kustomization to the your current cluster and then deploy AWX itself. 
It that what you are looking for?

**Comment by PaulVerhoeven1** [comment]
> We have a playbook that checks out the awx-operator git repository, creates a kustomization file from a template, build and deploys the kustomization to the your current cluster and then deploy AWX itself. It that what you are looking for?

I am interested in that!

**Comment by d-rupp** [comment]
I added an example file. Not sure if the location or anything else is correct, but hopefully it helps.
