### ISSUE TITLE
AWX Operator installation failure

### ISSUE THREAD

**Issue by simonmacpherson** [ansible/tower-operator#987]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

ImagePullBackOff status returned when trying to get image when deploying awx-operator. 

### AWX Operator version

Latest (0.25.0)

### AWX version

Latest

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

k3s

### Modifications

no

### Steps to reproduce

Following AWX on Single Node K3s on https://github.com/kurokobo/awx-on-k3s

sudo systemctl disable firewalld --now
sudo dnf install -y git make
curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
cd ~
git clone https://github.com/ansible/awx-operator.git
cd awx-operator
git checkout 0.25.0
export NAMESPACE=awx
make deploy

### Expected results

Running awx-operator 

i.e.
# kubectl get pods -n awx
NAME                                               READY   STATUS    RESTARTS   AGE
awx-operator-controller-manager-6cf48d4b84-f78qx   2/2     Running   0 

### Actual results

NAME                                               READY   STATUS             RESTARTS   AGE
awx-operator-controller-manager-6cf48d4b84-f78qx   1/2     ImagePullBackOff   0          12m

### Additional information

Server has access tp download image from remote public repository. 

Operating system version:

NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

Kernel version 3.10.0-1160.71.1.el7.x86_64

### Operator Logs

Output of kubectl describe pod awx-operator-controller-manager-6cf48d4b84-f78qx

Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  3m11s                default-scheduler  Successfully assigned awx/awx-operator-controller-manager-6cf48d4b84-f78qx to iob4377
  Normal   Pulling    3m11s                kubelet            Pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0"
  Normal   Pulled     3m6s                 kubelet            Successfully pulled image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0" in 4.506811249s
  Normal   Created    3m6s                 kubelet            Created container kube-rbac-proxy
  Normal   Started    3m6s                 kubelet            Started container kube-rbac-proxy
  Warning  Failed     2m52s                kubelet            Failed to pull image "quay.io/ansible/awx-operator:0.25.0": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/ansible/awx-operator:0.25.0": failed to extract layer sha256:476579af086aee78cb12d88b08fd6b61a80a3f055cae293ec2d15a37dbe7b3f9: failed to unmount /var/lib/rancher/k3s/agent/containerd/tmpmounts/containerd-mount3064893575: failed to unmount target /var/lib/rancher/k3s/agent/containerd/tmpmounts/containerd-mount3064893575: device or resource busy: unknown
  Warning  Failed     2m26s                kubelet            Failed to pull image "quay.io/ansible/awx-operator:0.25.0": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/ansible/awx-operator:0.25.0": failed to extract layer sha256:476579af086aee78cb12d88b08fd6b61a80a3f055cae293ec2d15a37dbe7b3f9: failed to unmount /var/lib/rancher/k3s/agent/containerd/tmpmounts/containerd-mount2319743196: failed to unmount target /var/lib/rancher/k3s/agent/containerd/tmpmounts/containerd-mount2319743196: device or resource busy: unknown
  Warning  Failed     104s                 kubelet            Failed to pull image "quay.io/ansible/awx-operator:0.25.0": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/ansible/awx-operator:0.25.0": failed to extract layer sha256:476579af086aee78cb12d88b08fd6b61a80a3f055cae293ec2d15a37dbe7b3f9: failed to unmount /var/lib/rancher/k3s/agent/containerd/tmpmounts/containerd-mount339070260: failed to unmount target /var/lib/rancher/k3s/agent/containerd/tmpmounts/containerd-mount339070260: device or resource busy: unknown
  Warning  Failed     78s (x4 over 2m52s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    63s (x4 over 3m6s)   kubelet            Pulling image "quay.io/ansible/awx-operator:0.25.0"
  Warning  Failed     49s                  kubelet            Failed to pull image "quay.io/ansible/awx-operator:0.25.0": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/ansible/awx-operator:0.25.0": failed to extract layer sha256:476579af086aee78cb12d88b08fd6b61a80a3f055cae293ec2d15a37dbe7b3f9: failed to unmount /var/lib/rancher/k3s/agent/containerd/tmpmounts/containerd-mount1721002862: failed to unmount target /var/lib/rancher/k3s/agent/containerd/tmpmounts/containerd-mount1721002862: device or resource busy: unknown
  Warning  Failed     49s (x4 over 2m52s)  kubelet            Error: ErrImagePull
  Normal   BackOff    38s (x5 over 2m52s)  kubelet            Back-off pulling image "quay.io/ansible/awx-operator:0.25.0"

**Comment by kurokobo** [comment]
The image `quay.io/ansible/awx-operator:0.25.0` is working well in my environment. I think this issue is not for AWX Operator, but this issue is caused by something in your environment.

A similar problem has been reported on containerd repo https://github.com/containerd/containerd/issues/5538: security tools such as McAfee or analysis tools such as SystemTap can prevent unmounting during pulling or extracting, so make sure they are not running.

If the issue persists, it is still better to ask in the K3s or containerd repositories, or [mailing list for AWX](https://github.com/ansible/awx-operator#get-involved) than to seek support here.

**Comment by jbradberry** [comment]
@kurokobo thank you for weighing in.

@simonmacpherson please reach out on the mailing list for further help.
