### ISSUE TITLE
Error creating pod: Pod (automation job

### ISSUE THREAD

**Issue by letnab** [ansible/tower-operator#995]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Error creating pod: Pod "automation-job-5483-cq9mn" is invalid: [spec.containers[0].resources.requests: Invalid value: "250m": must be less than or equal to cpu limit, spec.containers[0].resources.requests: Invalid value: "100Mi": must be less than or equal to memory limit]

### AWX Operator version

0.23.0

### AWX version

0.23.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

kubernetes/rancher

### Modifications

no

### Steps to reproduce

install awx operator

### Expected results

success or failed

### Actual results

success

**Comment by Zokormazo** [comment]
It seems that the `requests` in the podspec is higher than the allowed maximum `limit` for that pod, either on the same podspec template or on a project quota, could be a `LimitRange` in the project where the job is being launched.

You might get some more help to solve your configuration in our mailing list. See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
